### ISSUE TITLE
Any plans for improving the file thumbnail so you can get a preview or first page(cover) view on the folder without the need to enter it?

### ISSUE THREAD

**Issue by xerance** [tagspaces/tagspaces#1002]
Hello, got any plans on adding a folder preview thumbnail?
something like this
https://puu.sh/DXV8w/48033e9855.png

would be very useful and save a lot of time in a lot of cases; especially when organizing stuff like comics/magazines or webtoons, having a cover on the folder would speed up things a lot

**Comment by JJJu** [comment]
That would be the feature i desire the most.

**Comment by xerance** [comment]
ayy, its probably the only feature that holds me off from going fully into this system.

**Comment by uggrock** [comment]
This is already implemented and will be released soon as a PRO feature.

**Comment by xerance** [comment]
@uggrock good to hear!
are we talking about within a month or longer? bough pro but its really not useful for my purpose without this feature,

**Comment by xerance** [comment]
bump @uggrock saw that it got an update but i dont see the thumbnail preview anywhere?

**Comment by uggrock** [comment]
Yes, now it is possible to select a custom thumbnail for every file or folder manually in TagSpaces PRO.
