### ISSUE TITLE
Importing tags from 2.9 in 3.1.6 doesn't work

### ISSUE THREAD

**Issue by XaBerr** [tagspaces/tagspaces#1003]
**Describe the bug**
Importing tags from 2.9 in 3.1.6 generate a white screen and doesn't import nothing.

**To Reproduce**
1. Open the version 3.1.6
2. Go to import tags
3. Import this file after renamed ".json" [tsm[20190412-124640].txt](https://github.com/tagspaces/tagspaces/files/3460517/tsm.20190412-124640.txt)

**Desktop:**
 - OS: Windows 10
 - Version: 3.1.6

**Comment by andthenwhat** [comment]
This is also true for 3.1.6 tags, import seems to be generally broken.  In dev mode, I'm getting this console error:

ImportExportTagGroupsDialog.js:74 Uncaught TypeError: Cannot read property 'map' of null
    at ImportExportTagGroupsDialog._this.componentWillReceiveProps._flowRuntime2.default.annotate.nextProps [as componentWillReceiveProps] (ImportExportTagGroupsDialog.js:74)
    at callComponentWillReceiveProps (react-dom.development.js:11441)
    at updateClassInstance (react-dom.development.js:11651)
    at updateClassComponent (react-dom.development.js:14694)
    at beginWork (react-dom.development.js:15644)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)

**Comment by andthenwhat** [comment]
A little more info:

3.1.4 works fine for me

3.1.5 and beyond is broken.

**Comment by andthenwhat** [comment]
Here's the fix, I can't make it right now, @XaBerr can you make the fix?

/app/components/menus/TagLibraryMenu.js  lines 92 and 93 need to be swapped

This:
` if (jsonObj.tagGroups) {
          setIsImportExportTagGroupDialogOpened(true);
          setTagGroups(jsonObj.tagGroups);
        } else {
          // TODO connect showNotification
`
Needs to be this:
` if (jsonObj.tagGroups) {
          setTagGroups(jsonObj.tagGroups);
          setIsImportExportTagGroupDialogOpened(true);
        } else {
          // TODO connect showNotification
`

**Comment by XaBerr** [comment]
> Here's the fix, I can't make it right now, @XaBerr can you make the fix?
> 
> /app/components/menus/TagLibraryMenu.js lines 92 and 93 need to be swapped
> 
> This:
> 
> ```
>  if (jsonObj.tagGroups) {
>           setIsImportExportTagGroupDialogOpened(true);
>           setTagGroups(jsonObj.tagGroups);
>         } else {
>           // TODO connect showNotification
> ```
> 
> Needs to be this:
> 
> ```
> if (jsonObj.tagGroups) {
>           setTagGroups(jsonObj.tagGroups);
>           setIsImportExportTagGroupDialogOpened(true);
>         } else {
>           // TODO connect showNotification
> ```

Tested, pushed, marge request done!

**Comment by daLuiz** [comment]
I'm also having this problem with an export from 3.1.6. (pro version) while migrating to a new computer. Is there any workaround? by when can we expect the posted patch in a release?
Thanks!

**Comment by daLuiz** [comment]
It still crashes for me in 3.2.1 - is this patch included in the latest release?

**Comment by uggrock** [comment]
should have been fixed in 3.2.5
