### ISSUE TITLE
Tagspaces v3.1.4 Pro fails to check for new version

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1004]
As shown in the following screenshots, the option "Check for new version on startup" is selected, and when the manual check for updates is clicked, the already available v3.1.6 should be announced; however both methods fail their purpose.

KDE Neon 5.16 (Ubuntu 18.04)
Tagspaces Pro v3.1.4; deb version.

![Screenshot_20190803_015047](https://user-images.githubusercontent.com/22734449/62408456-4b540f00-b597-11e9-856e-117354f5c371.png)
![Screenshot_20190803_015131](https://user-images.githubusercontent.com/22734449/62408455-4abb7880-b597-11e9-91fc-7c9ecbe5c49c.png)

**Comment by uggrock** [comment]
Thanks for reporting this will be fixed for the next version.
