### ISSUE TITLE
Tagspaces v3.1.6 Pro's interface shows truncated dialogs.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1005]
As shown in the following videos, the "Settings" dialog is differently truncated at different windows' sizes, also the scrollbar is unable to reach the button end of the dialogs.

KDE Neon 5.16 (Ubuntu 18.04)

![Peek 2019-08-03 02-13](https://user-images.githubusercontent.com/22734449/62408615-70e21800-b599-11e9-928e-a0610a4e1af0.gif)
![Peek 2019-08-03 02-18](https://user-images.githubusercontent.com/22734449/62408614-70e21800-b599-11e9-924f-8fceb553ccd4.gif)

**Comment by uggrock** [comment]
Thanks for reporting, issue is fixed for the next release.
