### ISSUE TITLE
Feature suggestion - Hide file in file explorer

### ISSUE THREAD

**Issue by ppizarror** [tagspaces/tagspaces#1008]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an option to hide the selected file(s) as a context menu action. That would be super nice because I've lots of files that I don't want to see in the explorer.

**Describe alternatives you've considered**
You can add a list of hidden files as a .json in .ts folder. So
`if {file} in {hidden-files.json}: hide{file}`
Also this can be done with folders.

**Additional context**
![image](https://user-images.githubusercontent.com/12925256/62814056-513c7980-badc-11e9-85c0-d3caff2db9e2.png)

**Comment by uggrock** [comment]
Thanks for the suggestion, we are planing to have a kind blacklist for hiding files with wildcards.
