### ISSUE TITLE
Interface gets blank when tagging.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1009]
As shown in the following video, when tagging if I click on the empty field, the interface will blank.

Tagspaces v3.1.6 Pro
KDE Neon 5.16 (Ubuntu 18.04 LTS)

![Peek 2019-08-14 07-51](https://user-images.githubusercontent.com/22734449/63019185-9b20b900-be68-11e9-85bd-1b6aaa3c26ff.gif)

**Comment by uggrock** [comment]
fixed for the next release
