### ISSUE TITLE
v3.2.1 Pro DEB download link is wrong.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1015]
When I tried to download v3.2.1 Pro DEB, I've got v3.2.1 DEB Community version instead.
I already downloaded TAR.GZ and ZIP versions and the files are the right Pro versions.

![screen-](https://user-images.githubusercontent.com/22734449/63421919-69af6c80-c3d7-11e9-8fac-1757c7315318.png)

**Comment by uggrock** [comment]
Corrected, thanks for reporting!
