### ISSUE TITLE
v3.2.1 Pro - Drag and Drop files won't work.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1017]
Moving files by dragging them to the desired folder won't work.

Tagspaces v3.2.1 Pro
KDE Neon 5.16 (Ubuntu 18.04 LTS)

![Peek 2019-08-24 04-46](https://user-images.githubusercontent.com/22734449/63634867-52b48880-c62a-11e9-8d48-2902d6a04987.gif)

**Comment by uggrock** [comment]
thanks for reporting, fixed for the next version
