### ISSUE TITLE
TagSpaces Indexing crashes

### ISSUE THREAD

**Issue by John1247** [tagspaces/tagspaces#1018]
Installed updated version 27/8/2019 on Windows 10 on my desktop PC (please see attached). Tagspaces was slow and obviously directories required indexing. Dialogue showed several minutes later indicating indexing had crashed. Restarted PC and same condition. Deleted Tagspaces and reinstalled, no improvement.

updated Tagspaces runs perfectly on my Mac. Please advise suggestions as to fixing my Windows 10 version. Love the program!
![Windows 10](https://user-images.githubusercontent.com/54566073/63738285-a0e8b680-c8cc-11e9-98b6-a0e1b3baadd6.jpg)

**Comment by uggrock** [comment]
this is difficult to reproduce, perhaps you are trying to index to much files ....
