### ISSUE TITLE
Everything highlights during tag drag-and-drop

### ISSUE THREAD

**Issue by grwaldon** [tagspaces/tagspaces#1021]
**Describe the bug**
When dragging a tag onto a file, all tags and all files become highlighted, so it suddenly looks like you'll be applying all the tags to every file. The final behavior is correct (single tag only applied to the file it gets dropped on) but the UI is disconcerting and makes it hard to track where you're actually dropping the tag. 

**To Reproduce**
1. Open a location.
2. Open the tag manager.
3. Start to drag any tag over onto any file.

**Expected behavior**
Highlighting appears only on the file(s) that will receive the tag when dropped. 

**Screenshots**
#1 shows the screen before I click a tag (everything looks good). #2 shows it as I am dragging a tag (everything suddenly highlighted). 

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: n/a
 - Version: 3.2.1

![screenshot1](https://user-images.githubusercontent.com/55028338/64477460-a063e180-d150-11e9-8d4b-16389710fb05.png)
![screenshot2](https://user-images.githubusercontent.com/55028338/64477461-a063e180-d150-11e9-9efa-6826cbbe3ca9.png)

**Comment by uggrock** [comment]
fixed for the next release
