### ISSUE TITLE
Freezes when exiting app on Mac

### ISSUE THREAD

**Issue by kdpawson** [tagspaces/tagspaces#1023]
**Describe the bug**
Whenever I quit or exit the app on Mac Mojave 10.14.6 it freezes. Starting and running it works fine. In most cases this is okay as I just leave it running in the background.
Also running Tagspaces on Ubuntu and it works so much better, faster and opens/closes in a snap.

**To Reproduce**
1. Go to TagSpaces from the menu bar
2. Click on 'Exit'
3. Window minimises, however app is still running.
4. Select Apple Icon and click Force Quit and select TagSpaces
5. It will then exit

**Expected behavior**
Exit close gracefully and like any other application

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6

**Comment by uggrock** [comment]
this is fixed for version 3.2.7 or later
