### ISSUE TITLE
3.2.1 Pro / Drag Drop into Subfolder doesnt'work

### ISSUE THREAD

**Issue by Taloan** [tagspaces/tagspaces#1024]
See screenshot. 
Drag one or more files onto the subfolder and Dop it there. 
Nothing happens then...

Win10/64

![image](https://user-images.githubusercontent.com/55314384/64906270-a32c7c80-d6e4-11e9-8a9b-540465def814.png)

BR Talo

**Comment by gitdocke** [comment]
The developer already fixed.
---> https://github.com/tagspaces/tagspaces/issues/1017

**Comment by Taloan** [comment]
Thanks! Great work! :)

**Comment by Taloan** [comment]
Thanks! Great work! :)
