### ISSUE TITLE
Crashes when opening folder with large amount of images

### ISSUE THREAD

**Issue by smokeofc** [tagspaces/tagspaces#1025]
**Describe the bug**
When opening a folder containing a large amount of media,15174 images in my case, the application crawls to a stop and then in most cases crash

**To Reproduce**
1. Open folder with a large amount of images
2. See application crawl to a stop. It has a loading notify for a while, but the application is still a slug after 
3. ...
4. Profit / Crash

**Expected behavior**
Not crash I guess

**Screenshots**
![2019-09-18 15_59_56-TagSpaces Desktop](https://user-images.githubusercontent.com/13959015/65155338-6981ab80-da2d-11e9-91d0-bbe7f844423d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (1903)
 - Browser: N/A
 - Version: 3.2.1 Pro

**Additional context**

**Comment by EnvarionX** [comment]
I'm in a similar situation, I need Tagspaces to handle >30,000 images in one directory. But in testing the program for the first time, my computer crawls at just 3,300 images in one directory. :(

**Comment by uggrock** [comment]
Having 30000 files in one folder without a folder hierarchy is not so typical use case. We have made some optimization in this direction in our last beta version for the upcoming 3.5 release. You can try them from here: https://github.com/tagspaces/tagspaces/releases/tag/v3.5.1

**Comment by Intermediateish** [comment]
I'm having this exact same issue though with ~800 video files in a folder. I need these files within the same folder and I'm not interested in subfoldering it out. I can't even open the folder since within a minute it crashes.

**Comment by uggrock** [comment]
@Intermediateish which version of the app are you using ?

**Comment by uggrock** [comment]
In version 4.x we have introduced pagination to prevent such crashes -> closing
