### ISSUE TITLE
Can't tag folders (via file-name)

### ISSUE THREAD

**Issue by userwithquestion** [tagspaces/tagspaces#1029]
I like to add tags myself (without using TagSpaces-programm) by writing them into the name when saving/creating a file/folder.
For "normal" files this works, so:
filename "examplefileone [taga tagb]" shows up in TagSpaces-programm as "examplefileone" tagged with taga and tagb
vice versa
Tagging "examplefiletwo" with taga and tagb in Tag-Spaces-programm shows up in the explorer as "examplefiletwo [taga tagb]".
But for folders tagging the file when saving/creating/inside explorer (= outside TagSpaces-programm) doesn't seem to work:
filename "examplefolderone [taga tagb]" shows up in TagSpaces-programm as "examplefolderone [taga tagb]" without any tags attached, just the filename with brackets being displayed.
vice versa
Tagging "examplefoldertwo" with taga and tagb inside TagSpaces-programm works correctly inside the programm, but in the explorer the file still shows as "examplefoldertwo" without any brackets being displayed.

Is that intended behavior? (It seems a bit like sidecar-tagging, though i thought this is for pro-users only (but folder-tags seem to be persisted somehow, just not in the file name.))
If so can this be changed by switching to pro or will this be possible to change in future versions (of either community or pro)? 
(Changed so that folders can also be tagged directly when saving/creating by changing the filename and if currently sidecar-tagging is used also freely copied etc.)
(I would be very interested in this feature. I would be most interested in direct integration with windows explorer via addon, but would definitely also be willing to pay for this feature.)
(I just started using TagSpaces and don't want to spend much time tagging data spread far over hard-drive(/s) to then realize that it wouldn't persist anyway etc.)

 
OS: Windows 10
Version: Community 3.2.3

**Comment by uggrock** [comment]
Folder tagging was always achieved in TagSpaces with a sidecar file tsm.json, located in the .ts folder of the current folder. Until version 2 of the application it was a PRO feature, now in version 3 is part of the community release and available for everyone to use.
