### ISSUE TITLE
Screen goes blank trying to edit tag attached to file

### ISSUE THREAD

**Issue by barnj** [tagspaces/tagspaces#1030]
**Describe the bug**
I wanted to rearrange some of my tags, moving them from one tag category to another.  I moved them by dragging and droppint.  In some cases, I needed to change the background color and text.  Most of the edits in the tag panel worked.  A few did not.  So I moved to individual files that had the tag and tried to edit the tag there.  When I changed the colors and pressed OK, the entire screen went blank.
Because I was reporting this and I wanted to take picures, I restarted Tagspaces.  It is no longer going blank, but something else has occurred.  When I was trying to change the colors in the files' tags, before, I was getting a screen with the tag's name and the color strips for background and text.  Having restarted Tagspaces, the edit tag screen -both in the tag panel and the individual file tags show only the tag name, not the colors.    So it is not letting me change either the background color or the text color.  This is maddening.
And because the screen has changed, I can't duplicate what happened.  
This is on a debian based os.
Let me know if there is anything else I can tell you.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows 10, Linux, Ubuntu]
 - Browser - only needed if you use the web version [e.g. firefox, chrome]
 - Version [e.g. 3.1.1]

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy 8]
 - OS: [e.g. Android 7.0.1]
 - Version [e.g. 3.1.1]

**Additional context**

**Comment by uggrock** [comment]
could not be reproduced anymore -> closing
