### ISSUE TITLE
ODT preview doesn't work (free version)

### ISSUE THREAD

**Issue by grandgooroo** [tagspaces/tagspaces#1032]
Hello, ODT file preview is supposed to work, but it has never worked for me. Thx, laurent.

Windows 10 x64 Pro
![tgspace](https://user-images.githubusercontent.com/56718637/67080386-719c4a80-f195-11e9-8bcf-3329d9de8407.jpg)

**Comment by uggrock** [comment]
Hi,
in version 3 we have dropped the support of the ODT format in the free version. ODT was never supported in the PRO version.
cheers,
Ilian

**Comment by grandgooroo** [comment]
OK, thx.
