### ISSUE TITLE
Can not use keyboard navigation in "Tag operation on multiple files" lightbox

### ISSUE THREAD

**Issue by jcdev97** [tagspaces/tagspaces#1033]
**Describe the bug**
After I upgraded from 3.1.4 to 3.2.5, keyboard navigation in the "Tag operation on multiple files" lightbox no longer works. It seems the current focus is not set to the lightbox anymore.
Really enjoying 3.2.5 so far! Thanks.

**To Reproduce**
1. Select multiple files
2. Click 'Tag selected entries' button
3. Press tab key
4. Focus is not set

**Expected behavior**
Focus should be set to the  'Drop tags here' input

**Desktop (please complete the following information):**
 - macOs
 - 3.2.5

**Comment by uggrock** [comment]
fixed for the next release -> closing
