### ISSUE TITLE
Navigate to parent directory from mouse back button

### ISSUE THREAD

**Issue by oprichnik** [tagspaces/tagspaces#1034]
Adding the possibility to navigate to parent directory from mouse back button (like in browser) should be easy and usefull.

**Comment by uggrock** [comment]
which is the mouse back button? I am closing this issues since it is a feature request.

**Comment by oprichnik** [comment]
[Mouse back button](https://community.spotify.com/t5/image/serverpage/image-id/30952i0A69555A87543306?v=1.0)
