### ISSUE TITLE
v3.2.7 crashes when switching Desktop/Mobile modes.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1037]
In the Settings dialog, when switching mode from Desktop to Mobile, and vice versa, the program will crash.
Restarting Tagspaces will make to load it in the desired mode, but it will crash again when switched, as shown below.

![Peek 2019-10-31 03-07](https://user-images.githubusercontent.com/22734449/67926927-b1980000-fb8d-11e9-8ff2-77fd84e5da8c.gif)
![Peek 2019-10-31 03-10](https://user-images.githubusercontent.com/22734449/67926948-bceb2b80-fb8d-11e9-820c-410b86590931.gif)

-----------------
tagspaces-linux-x86_64-3.2.7.AppImage
KDE NEON 5.17 (Ubuntu 18.04 LTS)

**Comment by uggrock** [comment]
fixed for the next version -> closing
