### ISSUE TITLE
v3.2.7 - Icon to navigate to parent directory is missing.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1038]
Icon to navigate to parent directory is missing.
![3 2 6](https://user-images.githubusercontent.com/22734449/67938328-a3ee7480-fba5-11e9-980f-8ade3f5c8ec3.png)
![3 2 7](https://user-images.githubusercontent.com/22734449/67938332-a650ce80-fba5-11e9-9ca6-d1cd4d4b44b3.png)

**Comment by uggrock** [comment]
The back button is identical with the button in the screenshot, so it was removed for now ...
![Screenshot from 2019-10-31 11-16-57](https://user-images.githubusercontent.com/1249777/67938601-1bd19480-fbd0-11e9-9978-149ab25fa26b.png)

**Comment by gitdocke** [comment]
Understood.

**Comment by uggrock** [comment]
back button added again in the mobile version instead of the parent folder navigator -> closing
