### ISSUE TITLE
[1.8.5] Editing a tag whilst editing a note creates a copy of the note with the updated tag

### ISSUE THREAD

**Issue by yatesco** [tagspaces/tagspaces#104]
Create a new file
Edit it but don't save it
Edit the tag but click Cancel on the "All unsaved changes will be lost!  Do you want to continue?"
At this point the panel displaying the files shows the new tag
Saving the contents of the edit-in-progress recreates the file with the original tag

**Comment by uggrock** [comment]
not reproducible in v2.1.0
