### ISSUE TITLE
Use exif thumbnails instead of separately calculated thumbnails for jpg images

### ISSUE THREAD

**Issue by gizmomogwai** [tagspaces/tagspaces#1042]

**Comment by uggrock** [comment]
This is interesting idea, but I am not sure, if all jpg files with EXIF data, have a build thumbnail, so we can relay only on this. What advantages do you see in using these thumbnails, performance ?

**Comment by gizmomogwai** [comment]
No, not all jpeg have exif data, and those with do not always carry thumbnails. also the thumbnail size/resolution might not be what you want.
for me the two advantages would be
1. less meta-info-files (i try out tagspaces at the moment to organize my image collection
2. less work todo

drawbacks:
- performance might be a little better, if you always look for the thumbnails in the .ts folder, because you would have to fallback for other filetypes or jpgs without thumbnails anyways.
- inconsistent thumbnails in jpegs.

**Comment by uggrock** [comment]
We try to keep TagSpaces generic for using of all kind files and I think that for now the current solution for thumb generation is fine. So I will close the issue for now and mark it as feature request.
