### ISSUE TITLE
Tagspaces injects metadata revealing internal paths.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1043]
When using the command "Download", the copy of the file is injected with the path, or origin, from where it came from.
It might be useful in some cases, but, it is also a huge weakness and potential liability by exposing information not meant to be known.
I request an improvement which will allow to disable this feature.

![Screenshot_20191103_183541](https://user-images.githubusercontent.com/22734449/68094148-c0bbce00-fe6b-11e9-9332-202aef23af98.png)
![Screenshot_20191103_184245](https://user-images.githubusercontent.com/22734449/68094149-c7e2dc00-fe6b-11e9-91cb-a04a6b320a11.png)

**Comment by uggrock** [comment]
This information is not added by TagSpaces but by your file manager. I suppose Dolphin and also Mac Finder are keeping this information in order to warn you when you want to open a file from a malicious website.

**Comment by gitdocke** [comment]
You are right. 
When I move the file to a NTFS disk and then back to EXT4, the metadata is gone.
