### ISSUE TITLE
ViewerImage option menu freeze

### ISSUE THREAD

**Issue by mladensap** [tagspaces/tagspaces#1044]
**Describe the bug**
When open print dialog from option menu and choose 'cancel' or 'X' button, the viewerImage option menu freezes

**To Reproduce**
1. Open 'jpg' file
2. Click on 'Option'
3. Click on 'Print'
3. Click on 'Cancel' or 'X' button in print dialog

 - OS: Windows 10

 - Version 3.2.8

**Comment by uggrock** [comment]
Reproduced, thanks for reporting

**Comment by uggrock** [comment]
fixid in the recent versions -> closing
