### ISSUE TITLE
Cannot browse more than 999 files in list view v3.2.9

### ISSUE THREAD

**Issue by RobbieJGreen** [tagspaces/tagspaces#1045]
**Describe the bug**
Cannot browse more than 999 files in compact mode list view v3.2.9

**To Reproduce**
1. Open a location with more than 999 files (I have about 2500)
2. Switch to list view
3. Go to the end of the list (item 999)
4. The 1000th item displayed is the last file on the folder (missing all files from 1000 to 2500) and all tags on that range show up as if they belong to the last item.

**Expected behavior**
Properly display all my files

**Screenshots**
![image](https://user-images.githubusercontent.com/57510892/68440854-2916f200-0181-11ea-9a42-4c4d41279682.png)
OBS: Text edited for content

**Desktop (please complete the following information):**
 - OS: macOS
 - Version [e.g. 3.2.9]

**Comment by uggrock** [comment]
Due to potential performance issues, TagSpaces is limiting the listed files to 1000, this value is adjustable in the Settings.
![Screenshot from 2019-11-08 09-58-44](https://user-images.githubusercontent.com/1249777/68463288-99b82000-020e-11ea-9a30-a66e115d5e50.png)
