### ISSUE TITLE
Support for Finder tags

### ISSUE THREAD

**Issue by cpshanley** [tagspaces/tagspaces#1048]
As well as the tags assigned within TS, it would be nice to also see the tags assigned in Finder.

thx

**Comment by uggrock** [comment]
Currently the TagSpaces' tags are not compatible with the tags from Finder. Making this feature is for now not in the scope of the project. We try to keep TagSpaces as generic as possible.

**Comment by codebykat** [comment]
Too bad, I was searching for a tool which would interoperate with Finder tags. It wasn't clear from the website or the docs that it didn't do this, I had to download the app, try it, play with Settings, and search the Github to find out it only uses its own tagging system. The search continues, alas...
