### ISSUE TITLE
WIN7 :: Error 123: Filename, directory name (...) syntax is incorrect

### ISSUE THREAD

**Issue by Ra0EL** [tagspaces/tagspaces#105]
Hi,

- [x] Windows 7 Enterprise x64 SP1
- [x] TagSpaces 1.8.5

This error occurs when folder name is containing special characters, as illustrated on following screenshots \: 
 - _Original_ ( :toilet: :speech_balloon: ) names in Explorer \:
![tagspaces_ok](https://cloud.githubusercontent.com/assets/8389138/3849451/585c8b10-1e79-11e4-93fd-ff2e778c4c95.png)

 - the same, as read by TagSpaces \:
![tagspaces_err](https://cloud.githubusercontent.com/assets/8389138/3849450/585c0348-1e79-11e4-8e6e-79c538b43f4f.png)

I guess it should be easy to fix ( API or Unicode related, my 2 cents...).
Thx.

**Comment by uggrock** [comment]
TagSpaces support unicode characters in the file names.
