### ISSUE TITLE
PDF in folder causes dead end

### ISSUE THREAD

**Issue by StevenGrow** [tagspaces/tagspaces#1050]
**Description**
Opening a folder with a PDF file in it causes TagSpaces in a dead end situation. Not a freeze, but a situation that I can't get out of.

**Version**
TagSpaces: Mac v3.3.0
Mac OS: Catalina 10.15.1

**Step to reproduce**
1) Prepare by creating folder A with two subfolders B en C, both with some .jpg files in it
2) Open TagSpaces
3) Open the Location Manager and connect folder A to TagSpaces
4) Open B by double clicking on it -> everything works ok
5) Now copy a PDF file into folder B
6) Go back to the Location Manager and re-open B
7) Now TagSpaces enters a state with a full screen that looks like this:

<img width="1440" alt="TagSpace" src="https://user-images.githubusercontent.com/32998772/69453859-21507380-0d65-11ea-875c-8d5d5e9ee872.png">

I can still use the menu, but I'm not able to go back to the Location Manager.

8) Restart TagSpaces
9) Open the Location Manager and open folder C (without the PDF) -> everything works ok
10) Go back to the Location Manager and open folder B again -> same error
11) Restart TagSpaces
12) Move PDF from B to C and repeat from step 6 -> folder C now causes the problem and folder B shows ok

**Comment by StevenGrow** [comment]
Maybe linked to https://github.com/tagspaces/tagspaces/issues/957#issue-435474621 ?

**Comment by JOHNCESTA** [comment]
In settings there is a switch that mentions something about thumbnails. Turn it off. That's how I got this to stop.

**Comment by uggrock** [comment]
This is should not be anymore the case -> closing
