### ISSUE TITLE
Chrome Extension - Right-Click > Save image

### ISSUE THREAD

**Issue by vital-net** [tagspaces/tagspaces#1055]
Hello,

I can't find an easy way to save picture and add tags to it in the Chrome extension.
A right clic>Save image with TagSpaces would be an excellent idea.

Thank you

**Comment by uggrock** [comment]
Thanks for the idea! It makes definitely sense.

**Comment by uggrock** [comment]
Another idea could be to open the image in a new tab using the browser's context menu and then use the TagSpaces' browser extensions as usual.
