### ISSUE TITLE
Firefox Add-on  doesn't saves the file to the connected TagSpaces folder 

### ISSUE THREAD

**Issue by fabiobianchiwebdev** [tagspaces/tagspaces#1057]
**Describe the bug**
I'm on Linux Mint 19.3 and the TagSpaces Firefox add-on saves the files to the /Downloads folder, not the designed folder of TagSpaces.

**Expected behavior**
When I was using the Chromium extension, the saved files were saved directly to the connected TagSpaces folder.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 (based on Ubuntu 18.04)
 - Browser - Firefox 71.0

**Comment by uggrock** [comment]
Hi,
and thanks for reporting. 
Unfortunately there is now technical way to specify the download folder of the browser. The extension takes the generally predefined one, which is either the defautl download folder or some other folder you have configured in the browser.
greeting,
Ilian
