### ISSUE TITLE
Can't download pro version

### ISSUE THREAD

**Issue by findingorder** [tagspaces/tagspaces#1058]
I went to download TagSpaces Pro using the link I received when I purchased it. When I click the Access button, I get an error message that says "Access to this file has been removed.  Contact the merchant for access."  Could you please restore my access to TagSpaces Pro?  My order ID is 0015720850.
Thanks,
Phil

**Comment by uggrock** [comment]
Hi Phil,
you have purchased the PRO version almost two years ago, we provide updates for this version for one year after the purchase date and then the access to the download links is automatically revoked. If you want to use the latest version of the software please purchase a new license, if not feel free to use your last available version for as long as you want.
Greeting,
Ilian
