### ISSUE TITLE
v3.4-beta1 - Unable to connect to a location different than default.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1065]
I'm trying "tagspaces-linux-x86_64-3.4.0.AppImage" and the dialog to add a different location won't work. The new path isn't acknowledged.

![Peek 2020-01-18 21-56](https://user-images.githubusercontent.com/22734449/72673941-d7230000-3a3e-11ea-912c-e6a93bde6b5e.gif)

 -----
KDE Neon 5.17 (Ubuntu 18.04 LTS)

**Comment by uggrock** [comment]
Thanks for reporting this. Fixed for the next release.
