### ISSUE TITLE
v3.4-beta1 - Menu bar disappears.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1066]
When Tagspaces is launched this menu is visible, but when I have the dialog to browse to a X directory , the menu disappears.
There isn't a known setting to force such menu to show up again. Only after the restarting Tagspaces it will temporally fix this inconvenience .
![Screenshot_20200118_212433](https://user-images.githubusercontent.com/22734449/72674323-32ef8800-3a43-11ea-977b-111ddccd7a71.png)
![Screenshot_20200118_222650](https://user-images.githubusercontent.com/22734449/72674327-36830f00-3a43-11ea-85bc-4920024030ae.png)

---------

KDE Neon 5.17 (Ubuntu 18.04 LTS)

**Comment by uggrock** [comment]
Thanks for reporting, fixed for the next release!
