### ISSUE TITLE
Bug: Changes to folders require a reload

### ISSUE THREAD

**Issue by pixelbrackets** [tagspaces/tagspaces#1073]
**Describe the bug**
When I change options having an affect on the visual output of a folder, then the folder should refresh automatically.

**To Reproduce**
1. Go to some folder and change its background color
1. …or open the settings and show/hide hidden files and folders
3. Look at the currently opened folder
4. Expected behavior: The folder show the new settings right away
5. Actual behavior: The folder requires a manual refresh

**Additional context**
TagSpaces 3.3.2 Pro

**Comment by uggrock** [comment]
this is fixed in version 3.7 -> closing
