### ISSUE TITLE
Feature Idea: Remove tag via drag and drop

### ISSUE THREAD

**Issue by pixelbrackets** [tagspaces/tagspaces#1074]
It is possible to add tags to files via drag and drop. It is not possible the other way around, remove a tag via drag and drop.

**Workflow Idea**
- Open a folder with tagged files
- Drag a tag of one file - the files get a grey border and the tag groups get a grey background → New: A field with a grey background and a trash icon appears below the tag groups
- Drop the tag in this »trash zone« - the tag is removed from the file

**Describe alternatives you've considered**
- Right click the tag in the file and select "Remove tag"

**Additional context**
- TagSpaces 3.3.2
- This idea is not vital. just makes the drag and drop experience more consistent imho

**Comment by roxfanuk** [comment]
right click > remove tag

pretty easy already..

**Comment by uggrock** [comment]
closing since an easy solution for this action already exists
