### ISSUE TITLE
Search does not show the location of the files found

### ISSUE THREAD

**Issue by pixelbrackets** [tagspaces/tagspaces#1076]
**Describe the bug**
When I search for files by tags, the search result page shows the name, the tags, the size and the last modification date of each file found. However it does not show the path to the file. It is necessary to click on each file to show the path.

**To Reproduce**
1. Open a folder
2. Search for files by tags
3. Expected behaviour: See a list of files and show the path of the file as well
4. Actual behaviour: The list contains filenames only and no indicator where the file is stored at

**Additional context**
TagSpaces 3.3.2 Pro

**Comment by pixelbrackets** [comment]
~~Even when I click on a file and show the details (name, tags, description, preview) the directory is not shown. Especially irritating is the fact that the filepath above the search result list shows the “current” directory, which may not include any of the files found.~~ I replaced this passage, the path is visible in the details.

**Comment by uggrock** [comment]
Hi
many thanks for the feedback you have send us yesterday!
Regarding this issue, if you hover with the mouse over the file extension of a file in the search results you will see the path of the file. I will close the ticket for now.
Greetings,
Ilian
