### ISSUE TITLE
 v3.4-beta1 - Perfomance report - (NOT A BUG REPORT)

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1078]
Tagspaces' earlier versions had the drawback of a poor performance when the number of tags exceeded a thousand, but this 3.4 version shows a great improvement.
I did the following test:
Using v3.1.4 Pro I collected 2,476 tags in a dedicated Tag Group.
Then using v3.4 Beta-1, I begun to tag files fully using the autocomplete feature, there is still a lag, but minimal compared with older versions.
The improvement is welcomed. Thanks.

------------------

KDE Neon v5.17 (Ubuntu 18.04 LTS)

**Comment by gitdocke** [comment]
2463 tags now.

![Screenshot_20200122_222911](https://user-images.githubusercontent.com/22734449/72954614-fdaaa900-3d66-11ea-8685-96eaa0d395c7.png)

**Comment by uggrock** [comment]
Thanks for the positive feedback! You have a lot of tags...
