### ISSUE TITLE
v3.3.2 Pro - Interface crashes when editing Date tags' values.

### ISSUE THREAD

**Issue by nelway42** [tagspaces/tagspaces#1079]
I am using v3.3.2, and I am experiencing exactly the same behaviour as described in issue #1016. 
 Basically the interface goes blank when I uncheck the 'show time' checkmark, or try to edit a date tag.  

Just reposting since the other issue report is closed. 
[Issue 1016 link](https://github.com/tagspaces/tagspaces/issues/1016)

OS : Windows 7

**Comment by uggrock** [comment]
Can you please send us the exact name of the tag, which crashes the app.

**Comment by uggrock** [comment]
closing since activitiy since 24.01.
