### ISSUE TITLE
Drag and drop in OSX not working in latest release

### ISSUE THREAD

**Issue by Mc128k** [tagspaces/tagspaces#108]
When I try to drag and drop a file to a folder to move it, it doesn't do anything. I am trying to select the gray extension box.
![screenshot 2014-08-21 11 52 49](https://cloud.githubusercontent.com/assets/3678359/3994358/efbfdd46-2918-11e4-8c0f-ad975b0df402.png)

**Comment by uggrock** [comment]
Drag & drop functionality was fixed in version 1.9.x
