### ISSUE TITLE
v3.4 Beta-1 - Date tags reset to their original value when dragged. (bug regression)

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1081]
As shown in the video below, the values reset.
This is a regression of bug #993 
![Peek 2020-01-26 00-36](https://user-images.githubusercontent.com/22734449/73131301-b75b8100-3fd6-11ea-9c9b-66e660bb7ac6.gif)

---------------

Tagspaces v3.4 Beta-1 appimage.
KDE Neon 5.17 (Ubuntu 18.04 LTS)

**Comment by uggrock** [comment]
fixed in 3.7
