### ISSUE TITLE
v.3.3.2 program crashes instead of notifying for unsaved changes on html documents. 

### ISSUE THREAD

**Issue by NikosGre** [tagspaces/tagspaces#1087]
While editing an html file if you forget to press "save" button and try to open an other html file, the program crashes into a white screen where you need to exit the program altogether in order to get rid of.  

1. have some different html files on a folder and then open it with tagspaces v.3.3.2
2. double click on one of the html files so that you can edit it. 
3. click on another html file to open it without having saved the changes you made to first one.
4. You'll see a completely white screen. If you exit the program and run it again, any edits you made on the first will be unsaved of course. 
**Expected behavior**
Up until the most recent versions of the program if you accidentally tried to open another file without having saved changes on the current ones, you used to get a notification message and the program wouldn't let you open the new file.  

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04

**Comment by uggrock** [comment]
This is fixed in version 3.4.2
