### ISSUE TITLE
Note-editing crashes on 'Save'

### ISSUE THREAD

**Issue by aviceda** [tagspaces/tagspaces#1090]
Note crashes on 'Save'
Have just purchased TagSpacesPro v3.3.2 and cannot save a 'Note', do I need to add license number somewhere?

1. Go to 'Open Location....(Desktop)
2. Click on '+ (Create new Content)
3. Scroll down to 'Create Note'
4. Add some text
5. Click 'Save'
6. Screen goes blank, almost every time.

**Expected behavior**
Just save note as is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linuxmint 19.3 (both .deb and .appimage files)
 - Browser - Firefox
 - Version [3.3.2]

**Comment by uggrock** [comment]
Hi,
and thanks for reporting this issue. We are going to release a new version very soon and this issue should be fixed there. 
You do not have to enter the license number anywhere.
Greetings,
Ilian
