### ISSUE TITLE
Error While Renaming File error (local system)

### ISSUE THREAD

**Issue by LordUber** [tagspaces/tagspaces#1091]
Using v3.4.1 for the first time.

I right-clicked on  a word docx and tried to rename it - the system gave me an error and said it wasn't able to rename the file. Obviously the goal was to rename the file. 

To reproduce, right-click on a docx file and choose rename. No, the file was not open in Word. It was free and clear of any system hooks and I replicated the problem 4 times in 5 minutes.

I use a regularly updated version of windows 10.  Thanks.

**Comment by uggrock** [comment]
Does it happen only this document or for any given files / file type?

**Comment by LordUber** [comment]
After rebooting, the problem seems to have resolved itself. Renaming now works fine. Sorry to trouble you.

**Comment by LordUber** [comment]
Hi Illian,

Could you answer a quick question or send a link with an explanation?

When I open tagspaces I get a second app running that looks like a small
grey box. What is this app and how to I use it?

Thanks for your time, Mat

**Comment by uggrock** [comment]
Hi Mat,
the window is used to perform the indexing needed for the search and for the generation of the thumbnails. We have separated the processes in a separate window in order not to slow down the main app window.

Greetings,
Ilian

**Comment by LordUber** [comment]
Great Ilian, thank you. Perhaps you could build in an option that allows
the user to turn it off?

Cheers, Mathias
