### ISSUE TITLE
[pro] AWS S3 buckets files are not created properly on windows

### ISSUE THREAD

**Issue by magicmoose** [tagspaces/tagspaces#1092]
When saving files and tags in an s3 bucket they are not saved under the proper filenames/folders

**To Reproduce**
Setup an s3 bucket
1. Add a file into a folder
2. Add a tag to the file
3. The files and tag files are not saved under the proper names and therefore are not considered to be at the correct location. 

This only applies to the windows version. 
On Linux the same steps work properly
![tagspaces-s3](https://user-images.githubusercontent.com/543565/76134015-5d90a280-5fe9-11ea-9bd2-95bb6f8ffb60.PNG)

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 3.3.2

**Additional context**
It seems to use windows file paths instead of the linux style ones required by s3. 
For s3 buckets it should not use \ but /

**Comment by uggrock** [comment]
Thanks for reporting, we will investigate on this....

**Comment by iliansap** [comment]
this issue is fixed in the upcoming 3.5.2 version of TagSpaces, which is planed for the next week.

**Comment by uggrock** [comment]
this issue is fixed in the upcoming 3.5.2 version of TagSpaces, which is planed for the next week.
