### ISSUE TITLE
v3.4.2 won't allow to input tag with spaces

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1093]
As described in the release notes, the ability to use spaces in tags is back, but it won't work.
The space is allowed but any letter after it will disable the tagging functionality.

![canvas](https://user-images.githubusercontent.com/22734449/76205788-4f04df80-61d1-11ea-9d25-6b50e84985a3.png)
![Screenshot_20200309_063526](https://user-images.githubusercontent.com/22734449/76205808-55935700-61d1-11ea-9d85-cdd74c630997.png)
![Screenshot_20200309_062152](https://user-images.githubusercontent.com/22734449/76205815-5926de00-61d1-11ea-850b-c02aa02369fd.png)

-----------
Tagspaces v3.4.2 appimage
KDE Neon 5.18 (Ubuntu 18.04 LTS)

**Comment by uggrock** [comment]
The "allow spaces as separator for tags" is related to the tag creation dialog in the tag library. There you can now create multiple tags at once by separating them with spaces. e.G. tag1 tag2 tag3 ...
