### ISSUE TITLE
UI glitch

### ISSUE THREAD

**Issue by Ankk98** [tagspaces/tagspaces#1095]
**Describe the bug**
The text showing the directory overlaps on top of the text showing subdirectory. Has issues while clicking on them also.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a directory
2. Go to a subdirectory
3. open a file or note
4. Resize the partition
5. See error (Look at image)

**Expected behaviour**
It should be scrollable like the icons below it is.

**Screenshots**
![tagspaces-glitch](https://user-images.githubusercontent.com/24476799/76742818-b3a6d800-6797-11ea-8236-1176ddb724b6.png)

**Desktop Application:**
 - Operating System: Linux, Ubuntu 18.04
 - TagSpaces Version 3.4.2

**Additional context**
Expected behaviour can be different from what I have suggested above. But the existing UI looks very cluttered and also has a problem while clicking as both are overlapping.

**Comment by uggrock** [comment]
Thanks for reporting this! We will take a look.

**Comment by uggrock** [comment]
fixed for the next release
