### ISSUE TITLE
Not Saving Config On Close

### ISSUE THREAD

**Issue by Shwalamazula** [tagspaces/tagspaces#1096]
**Describe the bug**
When launching the program, you are taken thru initial setup (choose theme, set sidecar file, etc). Then you can setup directories and tags. Closing the program and re-launching it forces everything to reset. It is as if it is thinking it is my first time using the program every time. 

**To Reproduce**
1. Launch program
2. Click thru the initial setup
3. Close program
4. Launch program

**Expected behavior**
Setting or configuration choices should be saved on exit. 

**Screenshots**

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: 3.4.2

**Additional context**
I tried launching the program with admin privileges and the same thing happens.

**Comment by uggrock** [comment]
You probably have tried to start two instances of the application on the same time.

**Comment by MrConjurer** [comment]
I have the same problem, but i did not understand the solution?
