### ISSUE TITLE
Annoying behavior of saving Description (directories)

### ISSUE THREAD

**Issue by paulvoors** [tagspaces/tagspaces#1097]
**Describe the bug**
It is not a bug, but very annoying behavior. When you add some text to a description and then leave the description for adding an Tag (for instance). Then the description box is closed without saving the text. This very frustrating when you have added a lot of text. (Or text which was a lot of work).
Autosaving would be the best solution otherwise give a warning.

**To Reproduce**
1. Open de description-field
![Schermafdruk-2020-03-20-tagspaces](https://user-images.githubusercontent.com/27760989/77174156-e8c96800-6ac0-11ea-952d-4b99c014b9eb.png)
 (of a file or map) and ad some text
2. Click on the tag field above the description field and add a tag.
3. Look at the description field.
4. The box is closed and the text is gone...

**Expected behavior**
There should be a warning to save the text or it should be autosaved.

**Screenshots**
Screenshot of the menu with the 'bug'.

**Desktop Application:**
 - Operating System: Ubuntu
 - TagSpaces Version [3.4.2]

**Additional context**

**Comment by uggrock** [comment]
Thanks for reporting this, we will try to find a solution in the next versions.

**Comment by uggrock** [comment]
This is fixed in version 3.7.7 of the application -> closing
