### ISSUE TITLE
Не работает Hotkey в русской раскладке. 

### ISSUE THREAD

**Issue by AleksandraAl** [tagspaces/tagspaces#1098]
Добрый день. Tag 3.4.2 
Когда я нажимаю ctrl+t в английской раскладке, появляется окно "Работа с тегами для множества файлов". Когда я нажимаю тоже самое сочетание в русской раскладке, ничего не происходит. 

win 10 x 64.

**Comment by uggrock** [comment]
You can change the hot-keys in the settings with Cyrillic-characters.
