### ISSUE TITLE
Indexing taking too long

### ISSUE THREAD

**Issue by OriginalFlavor** [tagspaces/tagspaces#1100]
TagSpaces v3.4.2 Community Desktop Version in Windows 10.

When I open a location "Games" which has a location path of E:\Games, I get the following message at the bottom of the TagSpaces window:
`Indexing     CANCEL INDEXING`

I have let the indexing run overnight. The message does not go away.

There are ~300 subfolders within Games. I have not counted the files within the folders but there are a lot.

I only what to tag the 300 folders, not their contents. I do not want to index any file contents.

**Comment by uggrock** [comment]
In the PRO version there is an option in the location properties which will prevent the indexing of the location on opening it and try to load an pre-existing index instead. 
BTW: Can you please tell me how many files contains your Games folder, I am just curious.

**Comment by OriginalFlavor** [comment]
746,319 files
34,235 folders

**Comment by uggrock** [comment]
These are currently tough numbers for TagSpaces.... It is limited to index up to 200,000 files in a location.

**Comment by OriginalFlavor** [comment]
Is there a way to tag only folders and not contents?

**Comment by uggrock** [comment]
No, you can tag both files and folders. There is not way currently to disable tagging for files.
