### ISSUE TITLE
Selecting multiple files from keyboard does not work

### ISSUE THREAD

**Issue by gwpl** [tagspaces/tagspaces#1101]
**Describe the bug**
Selecting multiple files with mouse+keyboard works.
With just keybaords doesn't

**To Reproduce**
Try to select multiple files like you normally do, by holding shift or control and using arrows or simmilar ways -> nothing works.

**Expected behavior**
Being bale to select multiple files using just keyboard.

**Desktop Application:**
 - Operating System: Linux
 - TagSpaces Version: 3.4.2.

**Additional context**
Some users have (health) problems, making using pointing devices harder (mouses, touchpads).
Therefore they like to be able to perform all operations from keyboard.

**Comment by Radivarig** [comment]
I'm able to just use up/down arrows, but it does not move the row, instead it acts as left/right.

**Comment by ZebulonGlitch** [comment]
Arrow keys don't work at all for navigating files.  Still an issue, 

Linux Mint 21, Mate Desktop

**Comment by uggrock** [comment]
Selecting files with ctrl + click on files works as expected in 5.x -> closing
