### ISSUE TITLE
Tagging with use of sidecar files does not work for WEB version

### ISSUE THREAD

**Issue by Lifter-PL** [tagspaces/tagspaces#1102]
**Describe the bug**
For version 3.4.2 (also previous ones, i.e. 3.3.1) ran in Apache web server, when using sidecar files for tags, it is only possible to assign first tag to one file file in a directory. Attempting to add another tag for any other file in the same directory fails.

**To Reproduce**
1. Install Apache 2.4.43 server.
2. Configure webdav module in this server. Without any autorisation. With use of external tool, check if all operations (read/write/delete/rename file /create/rename/remove dir) are possible.
3. Install Tagspaces 3.4.2 and run the server. 
4. Login to localhost. Configure application to use sidecar files and to use webdav location.
5. Put at least one file into webdav location.
6. Assign one tag to file. It works (see first pic).
7. Assign second tag to file. It prints message 'Adding tags failed" (see second pic).
8. Tag assigned in point 7 is not visible.

**Expected behavior**
Tag in point 7 should also be added correctly and be visible.

**Screenshots**
Adding tag is succesfull - point 6.
![point6](https://user-images.githubusercontent.com/31290686/78471329-c1190780-7730-11ea-96a6-62e8316fefb2.jpg)
Adding tag fails - point 7.
![point7](https://user-images.githubusercontent.com/31290686/78471332-c413f800-7730-11ea-85f9-74ca30a87644.jpg)

**Desktop Application:**
 - Operating System: Windows 10
 - Browser - Firefox, newest one.
 - TagSpaces Version - 3.4.2

**Additional context**
It seems that during execution of point 6, directory '.ts' containing sidecar file is created correctly (sidecar file is present). But during point 7 sidecar file is not updated (when tag is added to already tagged file) nor new one added (if tag is added to other file in the same dir).

**Comment by uggrock** [comment]
We are not supporting the web version anymore, due to lack of resources, but we are open for PRs
