### ISSUE TITLE
Editing a file shows a blank page half of the time.

### ISSUE THREAD

**Issue by edgecase963** [tagspaces/tagspaces#1107]
On Linux (Ubuntu, 19.10), about  50% of the time I try to edit a file on my computer, Tagspaces will show a blank page. I have to navigate back to the folder and click "edit" again and repeat until it shows the actual contents of that file.

**Comment by uggrock** [comment]
We can not reproduce this issue with our current versions, which version of TagSpacea are you using ?

**Comment by edgecase963** [comment]
I have version 3.4.2 installed

**Comment by uggrock** [comment]
Can you please try to reproduce the issue on our new 3.5.2 version? We still could not reproduce the issue by us.

**Comment by edgecase963** [comment]
Looks like version 3.5.2 doesn't produce this issue. Thank you!
