### ISSUE TITLE
IOS app does not start at all

### ISSUE THREAD

**Issue by realabhay** [tagspaces/tagspaces#1108]
I downloaded the app and launched it multiple times but it does not move ahead of the logo/loading screen

![81675013-0F13-4AF8-BE5E-F366281F8664](https://user-images.githubusercontent.com/61345653/79117594-290ec400-7da9-11ea-9008-45c870222325.png)

**Comment by uggrock** [comment]
We have stopped the development of the iOS app two years ago and we not supporting it any more. If you want to have TagSpaces on iOS device you can use PWA version, which is part of TagSpaces Enterprise.
