### ISSUE TITLE
v3.5.2 Linux won't start

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1110]
I'm trying v3.5.2 "appimage" and "tar.gz" packages.
The distro is Netrunner 20.01 (Debian Stable 10.3 Buster)
*
The issue is as follows:
The Appimage package integrates well as shown in the below pic, however by clicking on its icon won't start.
![Screenshot_20200422_155110](https://user-images.githubusercontent.com/22734449/80027119-3ca8e180-84b1-11ea-99ec-c5dc96744390.png)
![Screenshot_20200422_151855](https://user-images.githubusercontent.com/22734449/80026030-7973d900-84af-11ea-9efc-da223ba01cbe.png)

So, I tried to use the terminal to see what was going on with the following error:
![Screenshot_20200422_152431](https://user-images.githubusercontent.com/22734449/80026151-a627f080-84af-11ea-8da9-7e5f4cef6071.png)

Then I tried with sudo which launched the "AppimageLauncher", so I clicked the "OK" button:
![Screenshot_20200422_152558](https://user-images.githubusercontent.com/22734449/80026368-0a4ab480-84b0-11ea-8072-59af689c69e6.png)
 
To get the following error:
![Screenshot_20200422_152733](https://user-images.githubusercontent.com/22734449/80026424-1df61b00-84b0-11ea-9912-d2933b754e0d.png)

Clicking "OK" again closes the error dialog and also the ongoing command in the Terminal, reporting "Segmentation fault":
![Screenshot_20200422_152828](https://user-images.githubusercontent.com/22734449/80026735-a07eda80-84b0-11ea-9bd7-699a2451aecc.png)

So, I tried the "tar.gz" version but it won't launch either, as shown below:
![Screenshot_20200422_155559](https://user-images.githubusercontent.com/22734449/80027939-61518900-84b2-11ea-9ee6-124a049d8cf3.png)
![Screenshot_20200422_155821](https://user-images.githubusercontent.com/22734449/80027955-66aed380-84b2-11ea-8447-9ead300ac45a.png)

**Comment by uggrock** [comment]
Thanks for reporting, I am running this version successful on ubuntu 19.10. Are you sure that the linux you are trying to run TagSpaces is 64bit ?

**Comment by gitdocke** [comment]
> Are you sure that the linux you are trying to run TagSpaces is 64bit ?
Positive.
![Screenshot_20200423_044754](https://user-images.githubusercontent.com/22734449/80079228-fd64aa00-851d-11ea-959a-3a73fde670ec.png)

**Comment by gitdocke** [comment]
I'm not a coder and I'm flying blind with this post.
But researching a bit about this bug took me to a perhaps relevant article about building packages in Debian, it mentions some issues between Stable and Testing flavors and tools addressing them coming soon to Ubuntu:
>Building Packages with Buildah in Debian
https://tauware.blogspot.com/2020/04/building-packages-with-buildah-in-debian.html

**Comment by uggrock** [comment]
@gitdocke do you still face this issue, have you tried the .deb package ?

**Comment by gitdocke** [comment]
I installed the .deb package and works without issue so far. I'll test it a bit tomorrow to see how it goes.
The catch of installing a .deb community version is that it will overwrite the Pro version, but I can reinstall it again, so no big deal.

![Screenshot_20200507_214833](https://user-images.githubusercontent.com/22734449/81362631-48022c80-90af-11ea-8107-72dbeee20ef9.png)
![Screenshot_20200507_220208](https://user-images.githubusercontent.com/22734449/81362650-54868500-90af-11ea-846c-3a31a5ebd635.png)

**Comment by uggrock** [comment]
Ok, know I understand why you need the appimage....
