### ISSUE TITLE
Collect Tags from Current Location is not working

### ISSUE THREAD

**Issue by mrkuramoto** [tagspaces/tagspaces#1111]
two problems I have tried to fix buying the pro version but unfortunately it doesn't work. 

1 - when I create a TAG using a file as a reference, the TAG library is not updated
2 - When using the feature "Collect Tags From Current Location" (this is why I decided o pay for the pro version) it doesn't work.

Please see the screen record I attached to this request.
How can I solve this?

Side note: If I edit the TAG, do nothing, than close the TAG, it is recognized by the library.

![Animation1](https://user-images.githubusercontent.com/64651477/80819290-15d26580-8bab-11ea-9fb5-5edce9cec80b.gif)

**Comment by uggrock** [comment]
Hello,
and thanks for reporting this issues. I was able to reproduce it and we will fix in the next Pro version.
Greetings,
Ilian

**Comment by uggrock** [comment]
fixed for the next release

**Comment by mrkuramoto** [comment]
Hi Llian, is there a forecast for the next release? I'm very anxious because if I could collect the TAGs created by another computer that syncs the files and the .ts folders though Dropbox, done! I would have TagSpaces working smoothly in both machines.

**Comment by uggrock** [comment]
Probably next week...
