### ISSUE TITLE
[Feature] Popup Dalogues, Directory Properties and Keyboard Traversal

### ISSUE THREAD

**Issue by Suika** [tagspaces/tagspaces#1117]
Oof, there a few of them. And this is a mix between bugs and features.
OS: WIndows 10
TS: v3.5.2 Pro

## Focus on opened Popups
**Is your feature request related to a problem? Please describe.**
For example, selecting a folder or file and hitting `Ctrl+t` will open a `Tag operation on multiple files` popup.
Once the popup is open, the focus of the curser is sill on the window behind it. So, if you hit enter or backspace, you will move through the folders while the popup is still open.
Tabbing or any type of other action won't let you focus on the popup, unles you click it with the mouse.

This is a problem with every popup that has not been clicked.
**Describe the solution you'd like**
An open popup should be in focus at all times and allow direct editing without the need to do anything with the mouse.
**Additional context**
Any type of keyboar interaction with popups is greatly decreased if the focus is not properly set.

![WhkLEhuAVV](https://user-images.githubusercontent.com/2320837/81312442-2fc1eb80-9076-11ea-80cd-c753932cae34.gif)

## Directory Properties
**Is your feature request related to a problem? Please describe.**
There is a function in tagspaces where if you click on a file it will be opened in editor or whatever is defined in the extension settings.
When the properties of a directory are opened and you change to a different folder, the properties that are open are still focused on the old folder.

Yet, if you click on a file after that, it will discard that view in favour of the file editor or whatever.
There is a lot of clicking involved if you want to 
**Describe the solution you'd like**
Chaning the focus of the folder aka. you click on another folder, while having the Directory Properties open, should also change the irectory Properties view to the new selected folder.

Possibly make a checkbox that allows TagSpaces to open `Directory Properties` automatically once a directory is slected. Like it's done with the file.
Possibly make a shortcut to open the `(File/Directory) Properties`, or just use the `ctrl+e` on folder to edit the properties, which would make more sense than adding an extra shorcut.
Example:
1. You have two folder `A` and `B` in a location, 
2. Open context menu of `A` and click `Directory Properties`, it will display the `Directory Properties` of `A`
3. Click on `B`, the `Directory Properties` should now show `Directory Properties` of `B`

**Additional context**
![cefj6RNojf](https://user-images.githubusercontent.com/2320837/81312688-71529680-9076-11ea-9c26-4ddb526516ce.gif)

## Keyboard Traversal through folder, tabbing and Directory Properties
**Is your feature request related to a problem? Please describe.**
I currently can't navigate through folders due to #1116, but here I want to point some QoS when it comes to the working with the interface.

Once you open `Directory Properties`, your focus is still on the folder that you selected. This is ok in itself. But if you wish to edit the `Directory Properties` you are forced to click the field first, before you can TAB yourself through the whole mask.

If you are anywhere in the UI and hit TAB, you automatically slect the Logo Button one the top left and then traverse through the whole thing. 
Once you arrive at the place you want, after countless tabbings, you can't enter the text, even if the focus is on the filed.
For some reason in this run, hitting enter didn't trigger save, but entered the folder, but after another test once clicked on the name field, entered the new name and then hit enter, it worked. 
**Describe the solution you'd like**
TABBING should start from the object focus. Possibly, if you have `Directory Properties` a TAB would move you to the first field of the `Directory Properties` and then procede to go down.
SHIFT TAB shoul go back, once you reach the Name property and hit SHIFT TAB again, it should move you to the folder tree or however you call the thing to the left of the properties where the files and folders reside.
**Additional context**
The moment you see me doing "nothing" over the name field, is when I try to enter something but it doesn't work.
![qWv1NF98Bh](https://user-images.githubusercontent.com/2320837/81313583-95fb3e00-9077-11ea-8aea-678f3216c0d0.gif)
![grafik](https://user-images.githubusercontent.com/2320837/81312073-b6c29400-9075-11ea-8885-a5b8496e7da7.png)

## Tags with spaces
**Is your feature request related to a problem? Please describe.**
Select multiple folder, hit `Ctrl+t`, enter `bad tag`, hit enter.
The tag is not created, only if the tag is a single entitiy like `bad_tag`, will it work.
**Describe the solution you'd like**
Tags with spaces. Generally whatever is entered and then if enter is hit, should be a tag.

**Comment by jmk2142** [comment]
Your observations and expected UX behaviors are spot on the money. Including https://github.com/tagspaces/tagspaces/issues/1116

Got to this issue via running into the Directory Properties behavior... I just started using this app and already I'm running into quirks that go against what you'd expect the behaviors ought to be. A little disheartening to see that this issue was posted May 2020 and we're in August 2021.

**Comment by Radivarig** [comment]
It's better to create a separate issue for each report. That way it's more specific and easier to reference.
