### ISSUE TITLE
Yarn Install Timeout for @material-ui/icons

### ISSUE THREAD

**Issue by jonathan-shahen** [tagspaces/tagspaces#1118]
**Describe the bug**
There seems to be a known bug with yarn timing out for material-ui-icons (https://github.com/mui-org/material-ui/issues/12432, https://github.com/yarnpkg/yarn/issues/4890#issuecomment-348479446).

**Suggested fix**
 * Change `yarn install` to `yarn install --network-timeout 1000000` 

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow README.md instructions (git  clone; git checkout develop; yarn install)

**Expected behavior**
For yarn to install everything without issue.

**Screenshots**
```
D:\Users\jonathan\Documents\Repos\tagspaces>yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.9.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Users\\jonathan\\Documents\\Repos\\tagspaces\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 3.5.2

**Comment by uggrock** [comment]
fixed with #1120 -> closing
