### ISSUE TITLE
Yarn Start Cannot Work from Fresh Repo

### ISSUE THREAD

**Issue by jonathan-shahen** [tagspaces/tagspaces#1119]
**Describe the bug**
If following the `README.md` file, it states you can call `yarn start` after calling `yarn install && yarn install-ext`, but the production code is not built so when you call `yarn start` it cannot find `app/main.prod.js`.

**Suggested Fix**
 * Change `yarn start` in the README.md to `yarn bs` (build and start)

**To Reproduce**
1. Follow the README.md from a fresh repo

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 3.5.2

**Comment by uggrock** [comment]
fixed with #1120
