### ISSUE TITLE
Tage Spaces Pro freezes with Gdrive folder on PC

### ISSUE THREAD

**Issue by fnorrmann** [tagspaces/tagspaces#1122]
Hi,

I recently upgraded to the latest Pro version.  When I connect to a lñocation that is a local GDRIVE folder, it starts indexing and eventually finishes, but in the end it freezes the app. The menu items are still available but I cannot do anything, I need to quit and restar the app.

When I restart the app and try to connect to this folder, I try to "cancel indexing" but it does not work, from that moment on the app freezes and I need to quit.

What to do??

**Comment by uggrock** [comment]
Hi,
If there is a problematic folder in your location, you can disable the automatic indexing on opening this location. This can be done in the location properties dialog, by enabling the following checkbox:
![image](https://user-images.githubusercontent.com/1249777/81494387-e0173600-92a8-11ea-9c5f-1ec1b20976e3.png)

**Comment by fnorrmann** [comment]
Thank you Lillian, I switched the "manual index creation" button as you
suggested, when I left the dialogue and went to another folder the same
happened: the app froze!  :(  This is very frustrating and unproductive for
us now!!!

*Frank Norrmann*
*Norcotek*
Phone +(5622) 745-1820 │Mobile +(5699) 225-0041 <+(5699)+225-0041>
frank@norcotek.cl  │ www.norcotek.cl │ www.isensor.cl

**Comment by fnorrmann** [comment]
Lillian, After restarting and trying again, the app no longer freezes, so
it seems that the problem is resolved. Just a question about the manual
index: what does that mean? Will I need to build that folder index
separately?

Regards,

*Frank Norrmann*
*Norcotek*
Phone +(5622) 745-1820 │Mobile +(5699) 225-0041 <+(5699)+225-0041>
frank@norcotek.cl  │ www.norcotek.cl │ www.isensor.cl
