### ISSUE TITLE
Custom Date Tag has no impact on file name

### ISSUE THREAD

**Issue by Nevga** [tagspaces/tagspaces#1124]
Tagspaces pro V 3.5.2 running on Linux Mint 19.3.

Usually, assigning a new tag to a file automatically changes the file name by adding the tag to the brackets. This does not seem to be the case with the custom date tag. Bug (my opinion) or feature?

**Comment by uggrock** [comment]
This is a bug, I was able to reproduce it. Thanks for reporting.

**Comment by uggrock** [comment]
fixed in the upcoming 3.5.3 version
