### ISSUE TITLE
Editor Save

### ISSUE THREAD

**Issue by Green0Photon** [tagspaces/tagspaces#113]
Traditionally in editors, one could save and still keep the document open.

The TagSpaces editor closes the editor and goes back into view mode after save. It also confirms the save.

Modern editors don't do this. They leave the editor open, and have a different close button.

My suggestion would be to have a separate save and close button, so I could save easily, and close when I'm done. Thus, I could hit Save every little while to prevent major loss if my computer crashes., just like in Word or Notepad++. Then, if I needed to preview, I could just close the editor.

**Comment by uggrock** [comment]
implemented
