### ISSUE TITLE
v3.5.3 - Drag and drop onto main parent directory won't work.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1130]
As shown in the video, I can drag and drop without problems, except into the main parent (DEMO FOR BUGS).
![Peek 2020-05-23 23-53](https://user-images.githubusercontent.com/22734449/82745347-22348300-9d51-11ea-9628-1ceda5022ba7.gif)

------
Tagspaces v3.5.3 community version
Linux Netrunner 20.01 64 bits (Debian Stable Buster)

**Comment by uggrock** [comment]
That was never implemented, but is something what I have missed a lot, so now it will be part of the next release.

**Comment by gitdocke** [comment]
I didn't know.
Thank you so much.
