### ISSUE TITLE
v3.5.3 video player has video disabled by default

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1131]
The video player comes with the setting "Video Output Enabled" disabled by default, which results in the player playing sound but no video.
Enabling video will reset the video to the beginning, in other words, to time index 0:00.
What is the usefulness of this setting is for everybody's guessing.

![Screenshot_20200524_070807](https://user-images.githubusercontent.com/22734449/82752861-0c45b300-9d8f-11ea-9330-40c5d6e586f2.png)
![Screenshot_20200524_070837](https://user-images.githubusercontent.com/22734449/82752864-110a6700-9d8f-11ea-9c68-564ee62fd7b3.png)
-----------------------
Tagspaces v3.5.3 community version
Linux Netrunner 20.01 64 bits - Debian Buster (stable)

**Comment by uggrock** [comment]
Thanks for reporting fixed for the next release.
