### ISSUE TITLE
v3.5.3 unable to delete tags in the search field.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1132]
As shown in the below video, the problem is specifically in the field "Must contain all of these tags". The field won't allow to delete a tag "IF" this tag is the last and only one remaining.
Other fields don't have this problem.
The only way to fix this behavior is to click on the Reset button.

![Peek 2020-05-24 07-54](https://user-images.githubusercontent.com/22734449/82753608-d9062280-9d94-11ea-9c7b-11542b9d35bd.gif)

--------------------------
Tagspaces v3.5.3 community version
Linux Netrunner 20.01 64 bits - Debian Buster (stable)

**Comment by uggrock** [comment]
fixed in 3.7.7
