### ISSUE TITLE
v3.5.3 - Renaming files messes the file name up.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1134]
When I try to rename a file, the file's name gets attached some internal code.
Also the renamed file is moved together with the thumbnail file and the .JSON to a folder created on the fly by Tagspaces.
As shown in the video below.

![Peek 2020-05-27 03-32](https://user-images.githubusercontent.com/22734449/82991121-384d7800-9fcb-11ea-8f80-7b7ff88a2f0a.gif)
![Screenshot_20200527_035401](https://user-images.githubusercontent.com/22734449/82993010-f5d96a80-9fcd-11ea-8a80-93514a312ce2.png)
![Screenshot_20200527_035444](https://user-images.githubusercontent.com/22734449/82993028-fbcf4b80-9fcd-11ea-9384-f106e91918c1.png)
![Screenshot_20200527_035513](https://user-images.githubusercontent.com/22734449/82993048-ff62d280-9fcd-11ea-934e-480318f950dc.png)

----------------------------------
Tagspaces v3.5.3 community
Linux Netrunner 20.01 - (Debian Buster, stable)

**Comment by uggrock** [comment]
Thanks for reporting, fixed for the next version.
