### ISSUE TITLE
Error: EBUSY: resource busy or locked, rename

### ISSUE THREAD

**Issue by jonathan-shahen** [tagspaces/tagspaces#1135]
**Describe the bug**
If watching a video in the preview window, and you try to add tags to that same video, you will not be able to because of the "Error: EBUSY: resource busy or locked, rename"

**To Reproduce**
Steps to reproduce the behaviour:
1. Double click on a Video in the file browser
2. While the video is Playing or Paused, try to add a tag to it
3. See error message popup "Error while renaming file ..."
4. See error message in console "app.ts:1361"

**Expected behavior**
Temporarily close the resource when that specific error occurs, try to rename again, and then open the resource again. The resource should be opened and playing if it was playing , and opened and paused if it was paused. Don't need to track the video file if that is too hard.

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 3.5.2 (develop branch, commit 17421d816796d65bf80af18d833b04f0735270ea)

**Comment by uggrock** [comment]
could not be reproduced -> closing
