### ISSUE TITLE
Generated Thumbnails are bigger than originals

### ISSUE THREAD

**Issue by Shrumpf** [tagspaces/tagspaces#1137]
**Is your feature request related to a problem? Please describe.**
Tagspaces is generating thumbnails wich are bigger than the original file and I think this is not very useful.

**Describe the solution you'd like**
Maybe it's possible to compare the filesize and just dont generate an extra one. And maybe use the original file format?

**Describe alternatives you've considered**
It would be super useless is the file just get copied to .ts folder, but I could live with that.

**Additional context**
I don't know why tagspace have to generate thumbnails at all, but at the moment It's a image manager without seeing what I tag, except I open/preview the file or I use much more space than it would need.

**Example:** I have a sprite of a cat. 32x32, 316 Bytes *.png. The Windows Explorer (and other Explorer) Thumbnail is 32x32, thats fine, bigger would look like sh*t. The Tagspaces thumbnail is 400x400, 7.6KB and *.jpg.

**Comment by gitdocke** [comment]
> I don't know why tagspace have to generate thumbnails at all, but at the moment It's a image manager without seeing what I tag, except I open/preview the file or I use much more space than it would need.

Simple solution. Disable thumbnails.
![Screenshot_20200531_204640](https://user-images.githubusercontent.com/22734449/83366989-3b0bec80-a380-11ea-8af6-a05c602df7dd.png)

**Comment by Shrumpf** [comment]
> 
> 
> > I don't know why tagspace have to generate thumbnails at all, but at the moment It's a image manager without seeing what I tag, except I open/preview the file or I use much more space than it would need.
> 
> Simple solution. Disable thumbnails.

That's simple, but no a solution. As I said, a image manager without preview thumbnails is pretty useless :/

**Comment by uggrock** [comment]
Thumbnails are actually for internal use in TagSpaces and are kind of temporal files, so their size is not really important for the app. I see from the user's perspective this is could an issue with the increased usage of hard drive space, but since this looks like an edge-case, we are not going to change this for now.
