### ISSUE TITLE
Remap keyboard shortcuts

### ISSUE THREAD

**Issue by csuka** [tagspaces/tagspaces#1141]
**Is your feature request related to a problem? Please describe.**
On Mac, when pressing COMMAND + SHIFT + N, Tagspaces opens a prompt to "Create new content".
However, I want to use this keyboard shortcut for Chrome to open a new incognito windows. But Tagspaces takes precedence.

**Describe the solution you'd like**
Either have an option to remap key combinations.

**Describe alternatives you've considered**
A possibility to remove the Tagspaces keyboard combo.

**Additional context**

**Comment by uggrock** [comment]
Hi, 
you can currently disable the global keyboard shortcut in the settings, tab key binding. I hope this helps. Making the global shortcuts configurable is a feature-request which we may implement in the future.
