### ISSUE TITLE
Flatpak package?

### ISSUE THREAD

**Issue by JaneSmith** [tagspaces/tagspaces#1142]
I'd like to see a Flatpak package for this app. It's a very interesting application and I was very disappointed to see that it is not available as a Flatpak, but only as an AppImage (and a plain archive).

Flatpak would be preferred for a number of reasons.

1. Firstly, it's the future of application packaging on Linux, and it's better (more consistent) when everything is using the same system. Most distros are supporting Flatpak out of the box, with support for it built into store apps such as GNOME Software. Some distros (e.g. Fedora Silverblue) are now using Flatpak as *the* native packaging format.

2. It allows the application to run on any distro, whereas AppImage does not necessarily - it's up to the packager to decide which distros to make the AppImage compatible with and up to the packager to test that compatibility. I wasn't able to find any information stating which Linux distros TagSpaces officially supports.

3. It has a built-in sandboxing and permissions system that provides more awareness and trust about the app. It's better for the user to know what the app has access to, instead of just giving it free rein over the system and access to all user data. (Being open source already helps with trust, but not everybody has the time to audit the source code themselves.) The sandboxing also helps to keep things neat by keeping the app's data files tucked away in their own directory (i.e. not polluting the home directory with ".ts" folders).

4. It allows easy updating of packages, as well as benefits such as being able to safely update while the app is running, not needing to reboot the system, installing multiple versions side-by-side, etc.

Thanks for reading.

**Comment by uggrock** [comment]
Thanks for the suggestion, it seems like a reasonable idea. But we do not have resources to handle one more package for the application. Although, If someone can provide the configuration for this we may integrate it in our build pipelines.
