### ISSUE TITLE
is the android development death? 

### ISSUE THREAD

**Issue by aisbergde** [tagspaces/tagspaces#1143]
**Describe the bug**

the current android version is 2.8.0 is not very compatible with android 10 permission system. Are there any plans to maintain the android version?

If not then it would be better to write this in the readme of the project. Instead of writing that tagspaces is available on android there could be the information:

An android app is available but it is not maintained and it is not compatible to Android 10 or higher. 

**To Reproduce**

1. Find the app in Play store and install
2. try to connect a new location, it is not possible
3. try to use SD card, this works, but it starts always in the root folder because it is not possible to define a subfolder as location

**Expected behavior**

a more clear statement about android

**Comment by uggrock** [comment]
Yes a new Android version is in active development, a beta of the product will be released in the next days here for testing purposes.
What are the issues with the permissions on Android 10, I just tested connecting locations with the 2.x version and it worked.

**Comment by aisbergde** [comment]
as I wrote it is not possible to select a folder when "connect new location". A location path can't be selected. The current path is "/", subfolders does not exist, browsing up is not possible.
This is a specific behavior which can be found in several apps and the reason are changed permissions in Android 10.

On the other hand the predefined locations are working, including the SD card. It is not a general permission issue but only in the "select directory".

In the current app I also can't find how to switch between tag store mode (Metadata in current file or separate files).

**Comment by uggrock** [comment]
Our latest Android version is available here: 
https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk

**Comment by aisbergde** [comment]
this beta version also doesn't work with folders as required:
Photos, Pictures, Downloads, Music and Movies - they are all working.
But the "SDCard" has issues:
sub folders are shown but first you need to wait very long for some thumbnail generating. If I try to select any folder then it is empty. All folders are empty. And when I try to back using the navigation button then I always get:
"unable to navigate, Parent folder not in the current location"
