### ISSUE TITLE
[android] it is hard to open a note in external editor

### ISSUE THREAD

**Issue by aisbergde** [tagspaces/tagspaces#1144]
**Describe the bug**
it is hard to open a note in external editor

**To Reproduce**
1. select "open file Natively"
2. now it takes very long to select the app I want to use to edit the file and this is not remebered
(would be fine to set an default external editor to open the file with one click)
the choice is also not remebered if I select "remember choice", but this could be related to the used android version
3. The note opens in the external editor (I am using Markor), but there is black on yellow warning. I try to translate the main content:
Attention, the app is allowed to write into this file, each change will be lost. There is no way to solve  the issue, Android permittes any access.
4. Try to change something and to save
5. check the result in tagspaces, the change has been saved. but this is because of the folder I use for notes. I use the Markor folder and Markor has access.

**Expected behavior**
the note should open with one click in the external editor, and there should not be warnings

**Screenshots**

**Desktop Application:**
 - Android 10, MIUI Global 11.0.8
 - TagSpaces Version 2.8.0

**Additional context**

**Comment by aisbergde** [comment]
maybe this information is helpful

```
intent:///sdcard/Documents/markor/notes/test_aaa_bbb.md#Intent;scheme=file;type=*/*;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: file:///sdcard/Documents/markor/notes/test_aaa_bbb.md 
MIME: */* 
URI: intent:///sdcard/Documents/markor/notes/test_aaa_bbb.md#Intent;scheme=file;type=*/*;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
```

it would also be better if the mime instead of */* would be the real data type, in this case markdown

**Comment by uggrock** [comment]
Please check our latest Android version, the file opening was improved there: https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk
