### ISSUE TITLE
Tag colour changing problem

### ISSUE THREAD

**Issue by daniellsh** [tagspaces/tagspaces#1145]
**Changing Colour with Tag directly created with document would fail**
This happens occationally. Sometimes I found the tag(s) that created with the document view mode fails to edit the colour. This happens with both the Mac and Win version of TagSpaces that I'm trying.

**To Reproduce**
1. Go to Location Manager
2. Click on the folder to select any document
3. Choose "Tag selected entries on the menu above the document
4. Create new tag and choose "Add Tags"
5. Go to Tag Library and select the new tag just created
6. Click Edit Tag with the 3 dots aside
7. Make changes (e.g. change the colour)
8. While the tag not only remain the same colour, but it also reproduced another same tag to replace any existing tag next to it.

**Screenshots**
I've recorded a GIF to better demonstrate my problem. Also I've made 2 separate tags in the Tag library as a reference near the end of video.

![CleanShot 2020-06-23 at 11 01 08 2](https://user-images.githubusercontent.com/67302979/85358612-bf4c2c80-b546-11ea-9820-1d73857219d5.gif)

**Desktop Application:**
 - Operating System: both macOS and Windows 10
 - TagSpaces Version 3.5.4

**Comment by uggrock** [comment]
Thanks for reporting we will take a look.

**Comment by uggrock** [comment]
closing since fixed for the next release.
