### ISSUE TITLE
smart tags how to use

### ISSUE THREAD

**Issue by JOHNCESTA** [tagspaces/tagspaces#1149]
I don't see the smart tags offered when I select to choose a tag?
How do I access the smart tags?
Thanks
John

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Application:**
 - Operating System: [e.g. macOS, Windows 10, Linux, Ubuntu]
 - Browser - only needed if you use the browser extensions for Firefox or Chrome
 - TagSpaces Version [e.g. 3.1.1]

**Additional context**

**Comment by JOHNCESTA** [comment]
I realized I had the mobile experimental switch on. It prevented the smart tags and others from being dragged to the files and folders.

**Comment by uggrock** [comment]
Ok, so I will close the issue...
