### ISSUE TITLE
ctrl shift f keybinding conflicts with basic functionality of google sheet/docs, how to change or simply disable?

### ISSUE THREAD

**Issue by SolveEverything** [tagspaces/tagspaces#1153]
ctrl shift f is already used as basic functionality of google sheet/docs, and this app is breaking it

**Comment by uggrock** [comment]
You can disable the global keyboard shortcuts in the settings, tab key bindings.

**Comment by SolveEverything** [comment]
does that disable hotkeys within the app?

if it does, that wont work

the question was how to change or disable specifically that hotkey?

**Comment by uggrock** [comment]
Currently the global  keyboard shortcuts are not configurable. With the checkbox from the attached screenshot you can disable the global keybinding including ctrl+shift+f. 
![image](https://user-images.githubusercontent.com/1249777/87150580-a4054f00-c2b2-11ea-9ef7-2e6fddbc5ea3.png)
