### ISSUE TITLE
Unsubscribe bug

### ISSUE THREAD

**Issue by ChrisRoald** [tagspaces/tagspaces#1155]
**Describe the bug**

tapping the unsubscribe link to github & logging in
gives me theHeader msg "you are unsubscribe from this group" 

But the tagSpace emails keep coming, and in everIncreasing numbers.?! 

Can someone look at the code for this, pls. 

I would, but don't understand computers very much, let alone why t's doesn't work on mine! 

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Application:**
 - Operating System: [e.g. macOS, Windows 10, Linux, Ubuntu]
 - Browser - only needed if you use the browser extensions for Firefox or Chrome
 - TagSpaces Version [e.g. 3.1.1]

**Additional context**

**Comment by uggrock** [comment]
You mean email from github about tagspaces, or other email ?
