### ISSUE TITLE
Bug in the trial version

### ISSUE THREAD

**Issue by jimclay75051** [tagspaces/tagspaces#1160]
I bought TagSpaces several days ago and really enjoy it. I did find a bug that effects the trail copy and so might cause some to think twice before buying. It did me. I noticed this because I have two Window 10 computers, a Surface Go and a desktop computer. I placed the trial copy on both and realized they behaved differently. 

When a new user first opens the application they are greeted with the opening help dialogs. These are the opening help dialogs that tells the newcomer what the app does. On my Surface Go I went through the dialogs, on my desktop I did not. 

This is where what I think is a bug comes in. Actually, a group of possible problems. On the desktop computer where I did not go through the dialogs, instead I clicked off the dialog to close it, ever time I closed the application the tags that I had created disappeared from the tags sidebar. The same for the folders that I set up in the folders sidebar. This happened over and over. I would restart the app and realized they were gone. I also discovered that when I added tags to a large number of files, hundreds or a thousand, the app would hang up; although I used file explore and found that the tags had been correctly added to all the filenames. Also, the trial keeps bringing up on each startup up the help dialogs and the user agreement. And because it was just a trial, I kept accepting the agreement but did not bother with the help dialog.

When I finally realized what was going on, I decided to click through the startup dialog, After doing that the above problems stop.

Again, once I clicked through the help screens, the problems stopped. 

Just want to make sure you know.

**Comment by uggrock** [comment]
Thanks for reporting this issue. It should not be the case in our last version anymore.
