### ISSUE TITLE
Incorrect tag is moved when dragging tags between tag groups

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#1166]
**Describe the bug**
When dragging and dropping tags between tag groups, often the incorrect tag is moved. 

**To Reproduce**
1. Make sure you have created a few tag groups
2. Create a bunch of tags within each group, say 10 per group
3. Try dragging random tags fom  one group to another. Also try dragging collected tags into your tag groups
4. Some tags move as expected, other don't and instead a tag other than the selected one moves. 

**Expected behavior**
Tag is dragged and dropped from one tag group to another

**Desktop Application:**
 - Operating System: Linux Mint 20
 - TagSpaces Version 3.5.4

**Additional context**
So far I have not understood any pattern as to why some tags move and others don't. My tags are mixed upper and lowercase for easier reading. Restarting TagSpaces doesn't help

**Comment by uggrock** [comment]
Can you please try to reproduce this issue in the last 3.6.1 release of the application?

**Comment by roxfanuk** [comment]
seems to be ok in 3.6.1
thanks!
