### ISSUE TITLE
v3.6.1 - Minor misspelling in English interface

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1167]
As shown in the screenshots, I believe it is "rich" instead of "rech".
Also a text file (TXT) doesn't allow formatting.

![Screenshot_20200804_022957](https://user-images.githubusercontent.com/22734449/89261346-e2fd9a80-d5fb-11ea-997f-d9812211c34e.png)
![Screenshot_20200804_023110](https://user-images.githubusercontent.com/22734449/89261360-eabd3f00-d5fb-11ea-9d90-6f130127932d.png)

**Comment by uggrock** [comment]
fixed -> thanks for reporting
