### ISSUE TITLE
Configuration guide to e.g. disable functionality?

### ISSUE THREAD

**Issue by tyteen4a03** [tagspaces/tagspaces#1168]
Hi - I'm looking to ship TagSpaces as a standalone application to some Linux desktops as a basic file manager. In order to not confuse my users I'm looking for ways to disable some features (e.g. tagging and link to TagSpaces Pro). Is it possible to do this in a configuration file? If so, is there a link to the guide for all configuration options available?

I'm shipping the AppImages version.

**Comment by uggrock** [comment]
Hi, this is what is currently supported: https://docs.tagspaces.org/dev/external-config
