### ISSUE TITLE
Make multiple file selection check box easier to see

### ISSUE THREAD

**Issue by duarteframos** [tagspaces/tagspaces#117]
It is currently hard to select several files, especially with thumbnails turned on.
The checkbox is small, and drawn only with an outline, which makes it becomes very hard to see if image thumbnails are on, vanishing or blurring into the details of the image thumbnail.
Also accidentally missing to click one unselects all previously selected files.
Perhaps additionally support shift + click or ctrl + click for multiple file selection? That'd be great

**Comment by dandv** [comment]
I've just installed TagSpaces, and within a minute of using it, I saw there's no Shift+click to select. This is a hugely important feature when it comes to managing large amounts of files.

**Comment by bsl8** [comment]
I've just installed TagSpaces, and I love the concept.  I too would love to have a Shift+click and Ctrl+clock option for adding tags to multiple files simultaneously.  If this gets added, I will make a donation of $20 to support further development of this software.  When can we expect to see this feature get added?
