### ISSUE TITLE
creates folder instead of renaming file when adding tag

### ISSUE THREAD

**Issue by sotto** [tagspaces/tagspaces#1174]
**Describe the bug**
tagspaces creates a directory instead of renaming the file

**To Reproduce**
1. go to the detailview of a pdf in tagspaces
2. in the detailview click on "Drop tags here", type 'test', hit [enter] to add test as a tag
3. in the folderlist click on "tag selected entries" 
4. Notice the file name under "select tags" doesn't include the tag "test" yet
5. type a new tag "bug" [enter], hit "add tags"
6. rightclick the file, to "open in filemanager"
7. find the file without tag "bug" and also find a new created empty folder with the name of the file

**Expected behavior**
rename the file correctly, don't create a folder

**Screenshots**

**Desktop Application:**
 - Operating System: windows 10
 - TagSpaces Desktop 3.5.4

setting: tags in filenames, not in sidecar-files

**Comment by uggrock** [comment]
could not be reproduced in version 3.10 -> closing
