### ISSUE TITLE
Can't apply more than one tag on Firefox

### ISSUE THREAD

**Issue by duarteframos** [tagspaces/tagspaces#118]
I am on Tagspaces 1.8.5 in Firefox 32 on Windows 64bits (both Windows 7 and XP) and I cannot apply more then one tag per selection.
Select several files > click tag of left panel > Tag Selected Files

Files are correctly tagged, but become unselected, making it impossible to easily repeat the operation on the same files.
Also the real bug here seems to be that those files can't easily be selected again, clicking the selection checkbox only works on previously unselected files (the ones not tagged in the previous operation). And if you progressively tag any further files after applying one tag they also become unselectable.
Drag and drop tagging also only works once per file, after adding the first tag to a certain file you have to refresh.

Only refreshing the folder fixes the issue

**Comment by uggrock** [comment]
the file browser is meanwhile disabled in the Firefox Addon, please use the desktop versions.
