### ISSUE TITLE
add folder/file ignore to prevent indexing

### ISSUE THREAD

**Issue by grodrigo** [tagspaces/tagspaces#1184]
I recently installed this software, but I couldn't find such feature that is relevant I think.
Probably is just my use case, but I have mixed content, the one that I like to get indexed and the one that not. I would like to have a system-wide and folder specific ignore with some rules, like happens with a .gitignore.
For example, my-super-secret-files, some always huge node_modules and vendor folders, folders that I don't care, etc.
I thought it's strange that is not present, but I couldn't find it and in the documentation it is not even mentioned, forgive me if I'm wrong.
Tanks in advance :)

**Comment by uggrock** [comment]
this is implemented for version 3.11 -> closing
