### ISSUE TITLE
v3.6.2 - Autocomplete feature displays multiple same tag

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#1188]
As shown in the screenshots below.
I suspect Tagspaces is showing tags created at different times by different Tag Groups and is reading the IDs instead of the tag's value (or name).
----
TagSpaces v3.6.2 community
Linux 64 bits

![Screenshot_20200918_060859](https://user-images.githubusercontent.com/22734449/93587660-39d6ed80-f978-11ea-82f2-8b735c8e8e60.png)
![Screenshot_20200918_061442](https://user-images.githubusercontent.com/22734449/93587678-3fccce80-f978-11ea-8ce3-0665bf325b96.png)
![Screenshot_20200918_061516](https://user-images.githubusercontent.com/22734449/93587687-44918280-f978-11ea-9b20-ee8dd105282a.png)

**Comment by uggrock** [comment]
fixed for the next release
