### ISSUE TITLE
Initialize all configurations at each startup in ver.3.6.2

### ISSUE THREAD

**Issue by El-Livia** [tagspaces/tagspaces#1190]
**Describe the bug**
After updating to ver.3.6.2 the TagSpaces initializes all configurations every time I start it, any changes I made would not be seen in the next time.

**To Reproduce**
1. Start TagSpaces
2. Make any changes
3. Close it and restart
4. See the welcome page and none of the changes remain

**Screenshots**
![TagSpaces screenshots](https://user-images.githubusercontent.com/32706845/93686360-4b3f0780-fae8-11ea-8c77-35779b100a68.png)

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces 3.6.2

**Additional context**
The feature of deleting files still causes errors and crashes.

**Comment by El-Livia** [comment]
I have tried many times to restart the TagSpaces and it always initialized itself.
But today I restart my computer and the issue is resolved. My configurations made before the crash (I'm sorry I forgot to write that this issue was happened after TagSpaces' crash when I tried to delete photos) are still there.

**Comment by sytolk** [comment]
@El-Livia this can happed if tagspaces for some reason cannot write data to disk (maybe out of disk space?). If you know how to repeat this feels free to reopen this issue.

**Comment by El-Livia** [comment]
> @El-Livia this can happed if tagspaces for some reason cannot write data to disk (maybe out of disk space?). If you know how to repeat this feels free to reopen this issue.

My disk has enough space and full authority for tagspaces. I think the issue was caused by the deleting error I have mentioned in this page ( https://github.com/tagspaces/tagspaces/issues/1180 ).
When I first open tagspaces, all functions work well, including deleting function. But if I try to perform the deleting action on  other files again, it will show errors and fail to delete. If I keep trying, tagspaces will crash. After I restart tagspaces, it has a probability to return to the initial state. It seems that restarting my computer may solve the initialization issue, but until now I still cannot use tagspaces to delete files. 

Is there anything such as log files I can provide to help analyze the deleting issue?
