### ISSUE TITLE
Extensions in v.2.8 Android ?

### ISSUE THREAD

**Issue by Katja295** [tagspaces/tagspaces#1191]
### _**Hallo,**_
erstmal vielen Dank für Ihr Programm, ich finde es super. In der Theorie, ich habe es erst vor kurzen entdeckt.

_**Meine Frage:**_
Momentan ist die Version 2.8 die aktuelle im Play Store.
Und zwar, in den Dokumenten über "Tagspaces" steht zum Thema "Extensions" das jede Extension in der neueren Version  integriert sei. Betrifft das die Android Version ? Muss ich unabhängig von meiner Frage noch irgendwas dazu installieren damit ich mit Ihren Programm super arbeiten kann ???

**Comment by uggrock** [comment]
Please try our latest Android version available here: https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk
The 2.8 is really very old and not worth using anymore.

**Comment by Katja295** [comment]
Vielen Dank !!!
