### ISSUE TITLE
not-selected files presented in deletion confirmation dialog

### ISSUE THREAD

**Issue by sotto** [tagspaces/tagspaces#1192]
**Describe the bug**
Files that where not selected in the main view, are presented in the delete confirmation dialog when pressing the delete icon after moving files.

**To Reproduce**
1. Go to an existing "location" in tagspaces
2. select one or more files in the folder, and 'move' them to another folder using the move or copy icon at the top of tagspaces
3. after moving, without selecting another file in the location first, hit the delete-icon.
4. See the moved files listed in the confirmationdialog

**Expected behavior**
maybe: alert "no file currently selected"

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 3.5.4

**Comment by uggrock** [comment]
Thanks for reporting. The issue was fixed in the current 3.6.2 version. If not please reopen the ticket.
