### ISSUE TITLE
There is a typo in the FAQ section of Tagspaces's official web site

### ISSUE THREAD

**Issue by matthklo** [tagspaces/tagspaces#1193]
**Describe the bug**
There is a typo in the FAQ section of this page (in English): [https://www.tagspaces.org/products/](https://www.tagspaces.org/products/)
There is a question goes: _"How do I know, when I new version is available?"_, which obviously need to be corrected to
_"How do I know, when_ **a** _new version is available?"_

**To Reproduce**
1. Open a web browser
2. Visiting the web page in English : https://www.tagspaces.org/products/
3. Scroll down to FAQ section
4. Observe the text of question "How do I know, when I new version is available?"

**Expected behavior**
The correct text should be "How do I know, when a new version is available?"

**Screenshots**
Not applicable.

**Desktop Application:**
Irrelevant.

**Additional context**
Forgive me if this kind of bug report should not post at here.

**Comment by uggrock** [comment]
Thanks for reporting, we have fixed the typo!
