### ISSUE TITLE
"Show in File Manager" does not works for internal directories (Sub-folders)

### ISSUE THREAD

**Issue by wasifgd** [tagspaces/tagspaces#1197]
**Description of Bug**
Function: "Show in File Manager" only works for main directories, root(main) folders of the directories inside of the location manager. Once you are in the main folder and go deeper into sub-folders and try to open the specific file location, clicking on "Show in File Manager" will not work, it does nothing while clicking.

**To Reproduce**
1. Go to 'location manager'
2. Click on 'any directory'
3. Go into 'any inside folder on selected directory' or click on the plus sign on any inside of the selected folder.
4. Right-click on the selected folder and click on "Show in File Manager"

**Expected behavior**
Function "Show in File Manager" should work for every directory, file, and folders not only for root directories.

**Screenshots**
https://www.youtube.com/watch?v=rQ_b1BMDL70

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Pro 3.6.2

**Additional context**
As per https://docs.tagspaces.org/ui/locations/ it should work for any directory, file, and folders
![image](https://user-images.githubusercontent.com/13394092/94411030-85b43e80-0191-11eb-978a-597ae62f0d1d.png)

**Comment by gitdocke** [comment]
In Linux, it works fine.
---
Tagspaces v3.6.2 community.
Debian 10
Dolphin is the file manager.

**Comment by uggrock** [comment]
could not be reproduced, please reopen if still valid in your setup
