### ISSUE TITLE
Failed to create data pipe due to MOJO_RESULT_RESOURCE_EXHAUSTED on large folders

### ISSUE THREAD

**Issue by mrpew** [tagspaces/tagspaces#1203]
**Describe the bug**
Tagspaces crashes with the following error (stderr):
````
(node:36207) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[35387:1002/182321.310973:FATAL:data_pipe.cc(12)] Failed to create data pipe due to MOJO_RESULT_RESOURCE_EXHAUSTED.
Trace/breakpoint trap (core dumped)
````

**To Reproduce**
1. In the location manager, open a location with a large amount of files (in my case mainly images, 8342 files in total)
2. The first time I tried, the app crashed (I suspect the same error, but I didnt start tagspaces in a terminal so I could not see it)
3. After starting tagspaces again, I could actually open the folder and the indexing worked fine, however no thumbnails were generated.
4. "Later", e.g. after restarting tagspaces, I am no longer able to open that location, It crashes with the above error message every time.

Checking htop while executing above steps, neither memory nor cpu limits are reached (or even close).

**Expected behavior**
The location gets displayed as expected.

~~**Screenshots**~~

**Desktop Application:**
 - Ubuntu 20.04.1 LTS
 - TagSpaces Version 3.6.2
- 32g RAM
- i7 6700k

**Comment by uggrock** [comment]
this appears to be a node issue -> closing
