### ISSUE TITLE
Must re-open the software to tags-searching for newly added tags files/folders 

### ISSUE THREAD

**Issue by Testing20134** [tagspaces/tagspaces#1206]
When i add new tag to a file or folder, i cant search for that file/folder immediately by using that new tag. Instead, i have to close the software and open it again, then i can search for that file/folder with that new tag. This occurred on both desktop and portable.

This isnt really a big problem but it gonna costs a lot of time if im working with a lots of files at once

 - Operating System: Win 10
 - TagSpaces Version 3.6.2

**Comment by uggrock** [comment]
this is fixed in 3.7.3 and later versions
