### ISSUE TITLE
Create new tag from file context menu

### ISSUE THREAD

**Issue by jeremymeyers** [tagspaces/tagspaces#1214]
**Is your feature request related to a problem? Please describe.**
I often have files for which i dont necessarily have a collection of tags in mind (say, a download directory with peoples names in the filename). Currently in order to tag these new people I would have to go into the tag library and add a tag and then drag it to the file.

**Describe the solution you'd like**
In the "Add Tags" popup, if i type a tag name that is not found within the tag library, the dropdown menu should say "+ Create & Apply New Tag Called "[input]" (which could then prompt for the tag group)

**Comment by uggrock** [comment]
This works already actually. You have to just hit enter after you finish the writing of the name of the new tag.
