### ISSUE TITLE
Page skipping after tagging files.

### ISSUE THREAD

**Issue by spikeli321** [tagspaces/tagspaces#1216]
I have 500+ tagged files in my folder and it was getting extremely laggy and unusable when I tried to drop new tag to the files without page limit.
So I set the page limit to 50 to make the app usable.
But the problem is, everytime I drop a new tag to a file, the location browser automatically navigates back to page 1. It's not really helpful and super frustrating. Is there a way to fix it?

**Desktop Application:**
 - Operating System: Windows 10.0.19041.572
 - TagSpaces Version v3.7.0 beta

**Comment by uggrock** [comment]
This appears to be a bug in the current beta version. Thanks for reporting it. 
@sytolk can you please take a look on this.

**Comment by sytolk** [comment]
fixed: https://github.com/tagspaces/tagspaces/pull/1218
