### ISSUE TITLE
Deleting tag in search window deletes all tags except the selected one

### ISSUE THREAD

**Issue by ceperman** [tagspaces/tagspaces#1234]
**Describe the bug**
In the Search window, if you delete a tag by clicking on the "X" in the tag, all tags EXCEPT the selected one gets deleted. The same behaviour is seen in all the tag selection lines ("Must contain all of these tags", "At least one of these tags" & "None of these tags". The tag selection seems to be the inverse.

**To Reproduce**
1. Go to 'Search'
2. Add tags to the selection lines (any)
3. Delete a tag by clicking on the "X"
4. Observe that that tag remains but all others are removed

**Expected behavior**
Just the selected tag should be removed

**Desktop Application:**
 - Operating System: Linux Mint Cinnamon 18.3
 - TagSpaces Version 3.7.4

**Additional context**
It occurs to me that the bug that says that the last tag in the line cannot be deleted would also be described by this bug's behaviiour.

**Comment by sytolk** [comment]
fixed here: https://github.com/tagspaces/tagspaces/pull/1233

**Comment by uggrock** [comment]
fix released in .3.7.5
