### ISSUE TITLE
Cannot rearrange file tags

### ISSUE THREAD

**Issue by ceperman** [tagspaces/tagspaces#1235]
**Describe the bug**
There seems to be no way to rearrange tags on files. I assume it's possible because drag/drop seems to be enabled for the tags - a tag can be dragged but dropping it within the list of tags is ineffective.

**To Reproduce**
1. Open the directory for a location. Files with their tags are shown
2. Drag a tag with MB1
3. Drop somewhere else within the tag list
4. Nothing happens

**Expected behavior**
Tags should be rearranged.

**Desktop Application:**
 - Operating System: Linux Mint Cinnamon 18.3
 - TagSpaces Version 3.7.4

**Comment by uggrock** [comment]
this is implemented in version 3.11.2 -> closing
