### ISSUE TITLE
Deleted file tag remains until directory is reloaded

### ISSUE THREAD

**Issue by ceperman** [tagspaces/tagspaces#1236]
**Describe the bug**
A deleted tag on a file appears not to be deleted. In fact it has been but it continues to show until the directory is reloaded. Also true for an edited tag.

**To Reproduce**
1. Open the directory for a location. Files with their tags are shown
2. Delete a tag using the tag menu
3. The tag remains
4. Reload the directory - the tag disappears

**Expected behavior**
The tag should disappear when it is deleted

**Desktop Application:**
 - Operating System: Linux Mint Cinnamon 18.3
 - TagSpaces Version 3.7.4

**Comment by uggrock** [comment]
Thanks for reporting, this is fixed in the upcoming 3.7.5 release.

**Comment by ceperman** [comment]
Thanks. I'm new to TagSpaces - great program!
