### ISSUE TITLE
Cannot copy S3 files with umlauten

### ISSUE THREAD

**Issue by SpiGAndromeda** [tagspaces/tagspaces#1237]
I tried to copy a bunch of files in an S3 bucket from one location to another. All files are working fine expect the ones with umlauten. TagSpaces simply shows an "Copying files failed" error.

**Desktop Application:**
 - Operating System: macOS 10.15.7
 - TagSpaces Version 3.6.2

**Comment by uggrock** [comment]
could not reproduce this in version 3.10.4 -> closing
