### ISSUE TITLE
White browser screen in the webdav version of the product

### ISSUE THREAD

**Issue by MrConjurer** [tagspaces/tagspaces#1238]
Hi,

i use the web Version from tagspaces with the Version 3.6.2 i only see a white screen in the broswer. 
For a small moment i see the tagspace site. 
With the Version 3.2.5 everthing work well.
I tested it with chrome, firefox and safari.
I use the Webserver Modul from QNAP.
If you need more information please give me a hint then i will give it to you.

Thanks.

**Comment by sytolk** [comment]
Can you try with [v.3.7.4](https://github.com/tagspaces/tagspaces/releases/tag/v3.7.4) and provide web browser console log. Thanks!

**Comment by MrConjurer** [comment]
I would be try it, but you see on the screenshot there is no web Version avalibale. 
![3 7 4](https://user-images.githubusercontent.com/2649574/98533373-2e6eb700-2283-11eb-8cbf-5ccc6790e780.JPG)

**Comment by uggrock** [comment]
We do not develop the webdav version of TagSpaces anymore. But we will accept PRs with fixes and the republish it once it is working again.

**Comment by MrConjurer** [comment]
Ok so it is better not to use the webdav Version because you do not get any updates anymore?

**Comment by uggrock** [comment]
We have limited resources for the further development of the project, so we want to focus more on the desktop and the mobile version of the product. If you need a web based we offer the Enterprise solution, but it works exclusively with AWS S3 compartible buckets for the storage and not webDAV.

**Comment by MrConjurer** [comment]
Ok then i use the windows version and you can close the ticket. To use the windows version also helps to solve the problem that i can not save settings.
