### ISSUE TITLE
search content status?

### ISSUE THREAD

**Issue by ghost** [tagspaces/tagspaces#124]
I understand that content search is not implemented:

"Searching and Finding
The search in the application is currently restricted to the file names only. Nevertheless there is a special query syntax allowing to narrow the search results."

"currently" suggest that that may change.  If it will, where on the version roadmap is that function?

WIth thousands of currently existing files in another app, unless I can search for context, then tag the results, TagSpaces -- a great concept & implementation, so far! -- is of litte help :-(

Thanks!

**Comment by saroele** [comment]
What is the status of this feature?  I would vote for a quick implemenation that would only search inside text files.

**Comment by basilesimon** [comment]
Hello @uggrock, 

This feature would be, in my opinion, extraordinary. 

Since, as far as I know, TagSpaces does not use a database, do you think a quick work-around could be based around simple bash tools such as a simple `grep -R searched-word /directory`?

Thanks

**Comment by johanneslotz** [comment]
I tried to implement the most simple way of doing this here: 461e1c7db5a08d1691970cf14b83dfca15dae5fd. This is the first thing I have written in JavaScript so bear with me if it is a bit clumsy. 

The new feature works as follows: If you add a space in front of the search term, All .txt and .md files are searched completely. I am aware that this will be terribly slow if the amount of data increases, but for me it does the trick for now. I would be happy to see this further improved. Let me know if you have some ideas.

![screenshot](https://cloud.githubusercontent.com/assets/7905525/8273490/aadee94a-1870-11e5-8874-737a4a1d4710.png)

**Comment by mpetri** [comment]
@johanneslotz looks cool. this could also work for PDF files if PDF.js is used to extract the text content.

**Comment by motiontwelve** [comment]
There aren't too many libraries out there that support viewing and indexing of most popular document formats such as docx, pdf, msg, xlsx, html, rtf, etc.   One that does this very well from my personal experience is Outside In from Oracle (previously Stellent).  The famous X1 search fully depends on this technology.  With such approach, one could specify which folders to include in the indexing and at what intervals to update the index.  However, I am not too sure how Oracle's licensing would work in this case.  I believe for personal and non commercial use the libraries are free of charge.

**Comment by uggrock** [comment]
we have a limited search in content support in the PRO version of the application, so I will close this issue.
