### ISSUE TITLE
Cannot collapse or remove the Smart Tags group

### ISSUE THREAD

**Issue by ceperman** [tagspaces/tagspaces#1241]
**Describe the bug**
Tag library page: I cannot collapse the Smart Tags group - clicking the "V" (down arrow) symbol does nothing. Other tag groups do collapse correctly.

**To Reproduce**
As above.

**Expected behavior**
The Smart Tags group should collapse.

**Desktop Application:**
 - Operating System: Linux Mint Cinnamon 18.3
 - TagSpaces Version 3.7.4

**Additional context**
I would actually like to remove or at least hide the Smart Tags group as I'm not using it, and although its context menu shows a "Remove tag group" option, this does nothing. I don't know if this is intentional or a bug. If intentional, then perhaps there could be a setting to have it not show.

**Comment by sytolk** [comment]
fixed here: https://github.com/tagspaces/tagspaces/pull/1246

**Comment by uggrock** [comment]
Collapsed is fixed for the next release. Smart tags could not be deleted because they are integrated part of the application.
