### ISSUE TITLE
Disable dialog question for tag deletion

### ISSUE THREAD

**Issue by GeorgeSTm** [tagspaces/tagspaces#1252]
Hi friends!

Is there an option to disable the dialog for confirming the deletion of a tag?
We work with lots of data and it is annoying to be asked every time...maybe put in Settings an option for this.
![image](https://user-images.githubusercontent.com/74489269/99182147-cfee8080-273b-11eb-80d1-3eaee48a8041.png)

If this is at this moment not a feature please make it one in the near future!
Thank you!

**Comment by sytolk** [comment]
Yes maybe we can add in this Dialog checkbox "Don't ask again". @uggrock ?

**Comment by uggrock** [comment]
you can use also the tagging dialog to remove tags from multiple files (e.g. from your search) at once. This way you have to confirm just once.

**Comment by uggrock** [comment]
removing of this dialog will make the deletion of tag too easy and since we do not have undo-functionality for this, it is not a good idea especially for novice users.
