### ISSUE TITLE
Unique Tag

### ISSUE THREAD

**Issue by GeorgeSTm** [tagspaces/tagspaces#1253]
Hi friends!
I am new to TagSpaces but in my opinion tags should be unique.
What I mean by that is: in the Tag Library it would be better to have a tag present only in one Group, I don't see the logic for a tag to be present in several Groups, or?

I work a lot with tags in our CRM system and they are fantastic, but the tags are unique and there is a tag management system in witch one could see all the tags in alphabetical order. I see that in TagSpaces in a specific Tag Group there is also this option available and this is good but there is no "global" place with all the tags listed alphabetically.

Please note this as a future feature.
Thank you!

**Comment by sytolk** [comment]
It's not a big deal to add new view of the Tag Library but what about Smart Tags? in this view you will see tag "George.Bush" near the "geo-location". Maybe it's better to leave Smart tags group separated delete all others tag groups and create only one that can be sorted alphabetically?

**Comment by GeorgeSTm** [comment]
Smart Tags are just fine as they are now.
Can you put a new group above the Smart Tags with all the Unique Tags sorted alphabetically?
![image](https://user-images.githubusercontent.com/74489269/99241257-48ba0f00-2806-11eb-908d-bd4249d25c58.png)

**Comment by sytolk** [comment]
I can confirm that "Move Up" button don't work for the smart tag group

![4DB70290-B763-42AA-BE31-01275DDF8B53](https://user-images.githubusercontent.com/1415463/99290758-652a6b80-2847-11eb-96c4-693c01691aec.jpg)

This can be fixed. Thanks!

**Comment by uggrock** [comment]
the menu on the smart tags tag group is disabled now -> closing
