### ISSUE TITLE
Displayed tags won't update until directory is reloaded

### ISSUE THREAD

**Issue by jellypox** [tagspaces/tagspaces#1259]
**Describe the bug**
After updating to 3.7.7 from 3.6.2, when adding a tag to multiple files at once, it will only be visible on one of the files, until the directory is reloaded.

**To Reproduce**
1. Click the "Toggle Select All" button in a directory containing multiple files.
2. Drag and drop a tag onto the selected files or add a tag using the "Tag selected entries" button.
3. Reload the directory or navigate to another directory and back.

**Expected behavior**
After step 2, the added tag will appear on every selected item; the directory will look the same after performing step 3.

**Actual behavior**
After step 2, the added tag appears only on the top item, and doesn't show up on any of the other files. After step 3, however, the tag appears on all the files it was added to.

**Desktop Application:**
 - Operating System: Windows 10 x64 Version 2004
 - TagSpaces Version 3.7.7

**Additional context**
I am running TagSpaces in portable mode, using a batch file containing the text  `start /B .\Tagspaces\tagspaces.exe --portable`.

Edit: I previously mentioned having upgraded using the .zip rather than the .exe, but have now confirmed this doesn't make a difference.

**Comment by uggrock** [comment]
can you please try to reproduce this issue in version 3.7.8 ?

**Comment by taubmann** [comment]
Same result in TagSpaces Pro Version 3.7.8, Operating System: Mac OS 10.14.6

**Comment by uggrock** [comment]
could not be reproduced in the current 3.10 -> closing
