### ISSUE TITLE
Is it possible to insert icons from the command line when using the PRO version of tagspaces?

### ISSUE THREAD

**Issue by rafaelmuynarsk** [tagspaces/tagspaces#1263]
Hi

I'm interested in buying the PRO version of TagSpaces to make use of the perspective views on it. I have one last doubt though, I see that I can put icons on the "change thumbnail" option, but is there any way of doing it programmatically on the PRO version? I mean, something like having a command line where I can use on my code just so I can do it automatically for my needs?

**Comment by sytolk** [comment]
If I understand you want to change TagSpace thumbnail on remote server? with command line like: 
tagspaces --thumbnailPath --targetFile

**Comment by uggrock** [comment]
you do not have to use TagSpaces for that, you have just to copy the thumbnails you generate somewhere else on the right place (.ts folder) with the right name (filename.docx -> filename.docx.jpg). This can be done with simple scripting.

**Comment by rafaelmuynarsk** [comment]
@uggrock That's nice it can be done with simple scripting... I asked about solving it with a tagspace command line because on nemo and nautilus we can easily automate the insertion of icons in files and folder with a command line. Having it on TagSpaces would make the code that I already portable to TagSpaces. 

I didn't manage to make it work as you described though. I put a file called Android.jpg inside the .ts folder and I didn't see it as a thumbnail on folders that are called "Android" inside TagSpaces. Is it a feature only available on the PRO version?

**Comment by uggrock** [comment]
It is a generally available feature. You have to name file Android.jpg.jpg it order to be recognized correctly. Can you share, which command you are using for setting the icons on nautilus ?

**Comment by rafaelmuynarsk** [comment]
Sure, the commands to set and unset the icons on nemo are the following:

```
file='/path/file'
image='/path/image'
gio set -t string "$file" metadata::custom-icon "file://$image"    # set icon on file or folder
gio set "$file" -t unset metadata::custom-icon                           # unset icon on file or folder
```

I've tried renaming the image to Android.jpg.jpg and it still didn't work. Just putting images inside the .ts folder is enough for them to show as icons inside TagSpaces? Is there any additional configuration I need to make?

**Comment by uggrock** [comment]
Thanks for the commands. Regarding the file rename, this how the thumbnails in all version work. There is no magic behind just correctly named files placed in the right .ts folder. We have also a script with which you can generate thumbs for image files, without the need of TagSpaces itself. You can take a look here: https://github.com/tagspaces/tagspaces/blob/develop/scripts/thumbgen.sh
