### ISSUE TITLE
Cant searching folders by tags in portable mode on a external hard drive!

### ISSUE THREAD

**Issue by Testing20134** [tagspaces/tagspaces#1277]
As the title said, i cant find my folder by using the tag i had attached to it when using portable mode on my external hard drive in search results.
In case you ask, run as admin will make the program run and use tsprofile from somewhere else, not from the tsprofile that currently in the same folders with it

However, when i deleted my old tsprofile and use it like a brand new, the search work perfectly.

 - Operating System: Windows 10 64-bit
 - TagSpaces Version 3.7.8

**Comment by Testing20134** [comment]
haizz, this is so frustrating to work with

**Comment by uggrock** [comment]
Are you starting the program with command line switch for the portable mode, as described here? https://docs.tagspaces.org/installation/#running-in-portable-mode

Linux/Mac
./tagspaces --portable & 
Windows
start /B tagspaces.exe --portable

**Comment by Testing20134** [comment]
Yes i did. 
Also, after some tests, i found out that the problem is because of my drive. The portable work fine with my internal drive but it is not working on an external one. 
Maybe my external has some restricted maybe? do you have any suggestion?

**Comment by uggrock** [comment]
hmm, I have no idea, the external drives on Windows a just regular drive with another letter in front d:, e: ... but we do not have a special handling for let's say c: drive. If it is a network drive this could be a right problem, but on external drive?!

**Comment by uggrock** [comment]
what happens if you are not in portable mode ? can you use this drive in TagSpaces ?

**Comment by Testing20134** [comment]
Suprisingly, the normal tagspaces was able to search folders in my external drive, but the portable one which located in the external is not

**Comment by Testing20134** [comment]
Look like this cant be solve then, arggg. Which other alternative should i use now

**Comment by Testing20134** [comment]
I just tested it with my other external drive and still, same result, you cant search for files in external drive when you use tagspaces located in the same external drive. So im pretty sure this is tagspaces problem, you guy might want to have a look into it.

**Comment by uggrock** [comment]
We have to take a look on this, I am afraid there is not quick fix for this issue.

**Comment by Testing20134** [comment]
> We have to take a look on this, I am afraid there is not quick fix for this issue.
