### ISSUE TITLE
mht / mhtml files not shown in hosted version (FF and Chrome)

### ISSUE THREAD

**Issue by tbleiker** [tagspaces/tagspaces#128]
mht / mhtml files are not shown in Firefox and Chrome with "viewerBrowser" (web version, 1.8.6 release), but they are in IE 11. I get the following behaviour:
* FF: viewerBrowser stays blank / white with the rotating Icon showing that the file is (should be) loading
* Chrome: the file gets downloaded
* IE: the file is shown

**Comment by tbleiker** [comment]
I have seen that you have added the new mht(ml) viewer. Does the viewer already work? Are there some other plugins needed? Nothing is shown in the webedition if I enable the new viewer and try to open a mht(ml) file.

**Comment by uggrock** [comment]
I just tested opening of mhtml files on demo.tagspaces.org and it works.

**Comment by tbleiker** [comment]
It works with the web edition from the releases! 

Until now, I just pulled the whole repository on my webserver and accessed tagspaces over the browser via the data folder.

I think that this issue can now be closed! Thx
