### ISSUE TITLE
Windows Executable contains malware

### ISSUE THREAD

**Issue by davosian** [tagspaces/tagspaces#1284]
**Describe the bug**
When downloading the Windows version (.exe), Windows Defender detects the Malware Win32/Presenoker.

**To Reproduce**
Download any of the recent Windows .exe releases (I checked back until 3.6.x).

**Expected behavior**
No malware

**Comment by uggrock** [comment]
This is probably a false positive notification. You can use this online tool for scanning exe files for viruses. https://www.virustotal.com/gui/

**Comment by davosian** [comment]
Well, Windows Defender installed on every current Windows system is complaining about Win32/Presenoker. Shouldn't we provide at least an explanation to our users what is causing this malware warning, why it needs to be there and why it is ok to proceed?

I for my part at least will not use nor trust software that contains questionable components - someone could have compromised the build system and therefore the builds are indeed malicious.
