### ISSUE TITLE
Reindex of location leads to crash

### ISSUE THREAD

**Issue by koan-tunes** [tagspaces/tagspaces#1295]
**Describe the bug**
Having quite a large location with quite some sub folders, when trying to re-index the whole application sometimes crashes. 

**To Reproduce**
1. Select a location
2. Click on the three dots (...) and select 'Refresh Location Index'
3. An info box with 'Indexing     CANCEL INDEXING' should appear.
4. Wait for some time. In case it cannot finish, switch to another location or simply click 'Refresh Location Index' again
5. Sometimes the application crashes with the following message box (see screenshot)

**Expected behavior**
Index should run without issues

**Screenshots**
![tagspaces-crash](https://user-images.githubusercontent.com/58424554/104295404-b4e08880-54c0-11eb-911f-08ae84dea966.PNG)

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: 3.7.8 Pro Version

**Additional context**
When doing it via the search tab, you could also choose 'Update all location indexes'. But there the problem is even worse, as after re-start, the application appears as a fresh installation, showing the configuration wizard. All locations and tags are gone in this case!

Hope this helps, cheers.

**Comment by uggrock** [comment]
Indexing issue was resolved in the newly released 4.0 version of TagSpaces. Here we have separated the indexing in a separate process, now it show work more smoothly.
