### ISSUE TITLE
Editing html notes on Android not working 

### ISSUE THREAD

**Issue by dsalomoni** [tagspaces/tagspaces#130]
Android 4.2.1,  I tried to create an html note, I was able to give the note a name, but then when I try to edit the note content I cannot :

I am shown the usual html buttons, I am apparently brought to the editing area, the keyboard opens (I am using SwiftKey), but whatever I type is not reflected in the editing area. 

I can go back to the TagSpaces file manager window, and nothing except html boilerplate has been written to the file (checked with an external file viewer). Is this a bug or am I missing something?

**Comment by uggrock** [comment]
not reproducible on 2.0.0
