### ISSUE TITLE
Suggestion - Disable auto-tag files that have [random letters]

### ISSUE THREAD

**Issue by Testing20134** [tagspaces/tagspaces#1302]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more like a preference. As i usually rename temporary folder with [folder 1...], of course i can use other like (,) but i dont know why i kinda prefer [,]

**Describe the solution you'd like**
A setting to turn off auto-tagging file that have [random...] as a part of their name like you can turn off sidecar.

**Comment by uggrock** [comment]
this is to specific and can not be implemented of now
