### ISSUE TITLE
Tags - Allow multiple selection with ctrl+click / assign right click to open menu as usual

### ISSUE THREAD

**Issue by nikdonikde** [tagspaces/tagspaces#1314]
Problem:
TagSpaces will become far more powerful when it presents a DECENT workflow for multiple tagging.
Quite often more than one tag needs to be applied on a file(s)

Suggestion:
Allow a selection of tags, just like files, by using a CTRL+click approach, and finally dragging onto file(s)
This means also disabling showing tag menu upon clicking, and instead moving this functionality upon right-click

Thank you for your consideration

**Comment by roxfanuk** [comment]
I think I'm right in saying that this was a feature in v 2
This would simplify the tagging process a lot

**Comment by uggrock** [comment]
you can tag multiple files in special dialog, where in a similar manner as described tag can be selected and applied -> closing
