### ISSUE TITLE
Tags removal on mutiple files

### ISSUE THREAD

**Issue by nikdonikde** [tagspaces/tagspaces#1316]
Problem:
User has many tags across many files he wishes to remove.
Presently, this has to be done one by one, which is INCREDIBLY tedious.

Alternatives Tried:
ctrl+t opens "tag operation on multiple files" pop up.
There is no way at first to remove tags on multiple files.
However there is an (intentional?) bug which does allow this but it is a hack.
If you select from the list of tags available the tag(s) you want to remove (essentially "adding them")
then you can hit "remove tags" and the tags will indeed be removed.

This is presently quite hacky and also suffers from the problem I mentioned in another suggestion that
the tags are flattened and not categorized, making it difficult to find the tags for removal

Suggestion:
There are many ways to go about this.
The best way would be to allow tags, in the files view, to have a little "x" in the corner. User could then go and click on
each very quickly. Finally, a button would appear somewhere (perhaps bottom of the panel) that would say "apply".
This would then remove the tags. There would also be a "cancel" button.

Ideally, the "tag operation on multiple files" pop up would also be enhanced to speed this process, if we have a lot of tags to remove across many files. The pop up, upon opening, would gather all the "common" tags across all selected files (with a note perhaps that only COMMON tags are displayed). and present them on the top. The user could then simply deselect those he wishes to keep. The ones remaining, user can click "remove tags".

Note that I am not 100% comfortable how this entire pop up for multiple files is designed. I find it confusing.
Even with my suggestion, although one can get used to it, it is still confusing. For instance, when the pop up opens,
as suggested, it presents COMMON tags that are present in all selected files. If I click remove, is it obvious that all the tags presented on the bar on top will be removed? Is it obvious that for me to KEEP certain tags I actually have to REMOVE them from the list 1st, then hit "remove tags' on the remainder? I find this confusing and counter productive. Yes it would work, but it's just not natural.

That is why I say that the op up on multiple files needs to be rethought I think, from ground up. It is a necessary tool, but it lacks a lot of finesse to make it a useful tool.

Thank you for your consideration

**Comment by roxfanuk** [comment]
You already can remove tags on multiple files at once.
It's not very intuitive but it works fine.

1. select all the files that contain the tag you want to remove
2. click on the tag icon from the upper toolbar
3. type the tag you want to remove into the text box and hit enter
4. In the toolbar at the bottom of the window "remove tags" is now active - click it
5. the tags will be removed from the files

**Comment by uggrock** [comment]
Closing the because the functionality is already existing, see comment from @roxfanuk .
