### ISSUE TITLE
Search by multiple tags - Allow selecting tags by categories

### ISSUE THREAD

**Issue by nikdonikde** [tagspaces/tagspaces#1317]
Problem:
User wants to search for files using multiple tags. If he opens the search tool, the tag drop down shows
yet again (like many parts of Tagspaces) a flattened, alphabetically ordered tags. The different tags from
different categories are mashed together. If you have a lot of tags, this is incredibly tedious to find the
tags you wish.

Alternatives Tried:
While in tag view, click on a tag and you are presented with the option to search for files that have this tag.
Although this is nice, this is a very simplistic scenario. It does not consider the more common scenario, where
user wishes to search using multiple tags.

TagSpaces is supposed to be useful, not tedious to use. Finding things and tagging things FAST should
always be part of design objective.

Suggestion:
As mentioned in my other suggestions, the drop downs should be redesigned to show tags by categories at least
(and can we dream? with checkboxes next to the selections in the drop down to do multiple selections, or, using ctrl+click).

As well, the tag view, that shows the nice colours and categories, should allow multiple selections of tags, via ctrl+click
and then choosing an option of "search for files that have these tags", which would then open up the search panel with the tags
prepopulated in the search field.

Thank you for your consideration

**Comment by uggrock** [comment]
in version 3.10.4 we have in the tag group context menu the entry: "Search for tags in this group" -> closing
