### ISSUE TITLE
Search returns only 5 results

### ISSUE THREAD

**Issue by jschmidt-gh** [tagspaces/tagspaces#1318]
**Describe the bug**
A search for "tax" in the Windows 10 TagSpaces application 3.8.4 (new install) shows only the first 5 results instead of showing all results.

**To Reproduce**
1. Create the following files (without [tax] in filename) at D:\docs\

Schmidt J Tax Return-2[tax].tax
Schmidt J Tax Return-final[tax].tax
2005 Schmidt J Tax Return[tax].tax
2006 Tax Return - Justin Schmidt[tax].tax
2007 Tax Return - Justin Schmidt[tax].tax
2008 Schmidt J Form 1040  Individual Tax Return[tax].tax2008
2010 Schmidt J Form 1040  Individual Tax Return[tax].tax2010
2011 Schmidt J Form 1040  Individual Tax Return[tax].tax2011
2012 Schmidt J Form 1040  Individual Tax Return[tax].tax2012
2013 Schmidt J Form 1040  Individual Tax Return-2[tax].tax2013
2013 Schmidt J Form 1040  Individual Tax Return[tax].tax2013
2014 Schmidt J Form 1040  Individual Tax Return[tax].tax2014
2015 Schmidt J Form 1040  Individual Tax Return[tax].tax2015
2016 Schmidt J Form 1040  Individual Tax Return[tax].tax2016
2017 Schmidt J Form 1040  Individual Tax Return[tax].tax2017
2018 Schmidt J Form 1040  Individual Tax Return[tax].tax2018
2019 Schmidt J Form 1040  Individual Tax Return[tax].tax2019

2. Add "tax" tag to these files

3. Go to Search screen in the app
4. Search target is "Location" and search box is empty
5. "Must contain all of these tags" field is "tax" tag
6. Select Search
7. All files are shown in results list
8. Now modify search box from blank to "tax" ("tax" tag can remain selected as well)
9. Only the first 5 files are shown in results list, even though in application Settings the max search results value is set to default 1000

**Expected behavior**
Results should show all files for search term "tax" (with or without tag "tax") because all filenames include the word "Tax".

Additional relevant information: Overall this app is awesome!

**Also noticed the following:**
Text search for a word, invoice, at the end of a long filename ("2001-02-03 university spring tuition payment request - 2001-01-02 books invoice[invoice].pdf") does not return the expected result but search by the tag invoice works perfectly.  Text search for "university," closer to the beginning of the long filename, also works.  Text search does not seem to work when searching for words near the end of long filenames.  Perhaps the long filenames are truncated in the search candidates list, or jmespath query is considering only the first few characters of each filename?

**Comment by Amasis** [comment]
This happens for me, too. And it is a show stopper for me using the app, as I even can't search for files I want to tag this way :-(

I investigated a bit further, it seems that it "cuts" the filename after 30 chars:
Searching for "test":
`123456789012345678901234567890test.txt`	-> PASS, [30 chars]<search target>.txt
`1234567890123456789012345678901test.txt` -> FAIL, [31 chars]<search target>.txt

Searching for "est":
`12345678901234567890123456789test.txt` -> PASS, [30 chars]<search target>.txt
`1234567890123456789012345678901test.txt` -> FAIL, [31 chars]<search target>.txt

**Comment by uggrock** [comment]
Thanks for reporting this, we will investigate the issue.

**Comment by uggrock** [comment]
We found the reason for this issue. It is the configuration of the library for fussy search we are using. Thanks again for the tip about the 30 chars. The fix should be part of our next release.

**Comment by uggrock** [comment]
fixed for the next release
