### ISSUE TITLE
Tagging - get focus

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#1320]
**Is your feature request related to a problem? Please describe.**
in versions pre v3 when tagging you could just start typing right away. Now I have to click in the tag entry box first

**Describe the solution you'd like**
right click - > add remove tag, or menu hit tag button
start typing your tag right away without having to click in the text box

**Comment by uggrock** [comment]
Very good we have to fix it. Thanks for reporting.

**Comment by uggrock** [comment]
fixed for the next release (3.9.2)
