### ISSUE TITLE
Can't pick internal Books folder on Likebook Mars

### ISSUE THREAD

**Issue by MarjaE2** [tagspaces/tagspaces#1324]
**Describe the bug**
TagSpaces Lite can't pick the internal /Books folder on the Likebook Mars with Android 8.1. Boyue's built-in reader can only read in /Books.

**To Reproduce**
1. "Choose Location." TagSpaces shows photos, pictures, downloads, etc., but not books.
2. "Connect New Location."
3. Tap the folder icon to the right. This triggers a lot of flashing.
4. Shows Current Path: / "No subfolders found"

**Expected behavior**
/Books should show up in step 4, if not step 1.

**Desktop Application:**
 - Operating System: Android 8.1.
 - TagSpaces Lite 2.8.0.

**Comment by uggrock** [comment]
Version 2.8.0 is very old and supported any more please use a recent version from https://github.com/tagspaces/tagspaces/releases/tag/v3.9.5
