### ISSUE TITLE
Too much flashing/animation

### ISSUE THREAD

**Issue by MarjaE2** [tagspaces/tagspaces#1325]
**Describe the bug**
TagSpaces Lite contains a lot of flashing/animation and triggers my migraines. I doubt I am the only person so affected.

This is on the Likebook Mars, and e-ink tablet. I use e-ink because conventional tables always trigger my migraines.

**To Reproduce**
1. Open TagSpaces. It flashes 3 times before reaching the main screen.
2. Click on "Choose Location." The menu flashes as it opens.
3. Click in "Connect New Location." The edges of the screen flash as the modal opens.
4. Click on the folder icon. The folder icon flashes, and then the edges flash again.

**Expected behavior**
To be frank, I don't expect apps to avoid flashing/animation, but they ought to.

**Desktop Application:**
 - Operating System: Android 8.1.
 - TagSpaces Lite 2.8.0.

**Comment by uggrock** [comment]
version 2.8 is not supported, please use a recent version like 3.9.5
