### ISSUE TITLE
Cannot move or delete files with characters in filenames

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#1327]
**Describe the bug**
If filenames contain certain characters you cannot move or delete them without renaming first

**To Reproduce**
1. make sure you have a file with non-standard characters - try using apostrophe or a period (somewhere other than the file extension) for example
2. try to delete the file or move the file
3. action will fail 

**Expected behavior**
Deletion or moving of any file should be possible, no matter what characters are in the filename
All characters supported by generally accepted filenaming conventions should be supported in TagSpaces

**Desktop Application:**
 - Linux Mint 20 Ulyana (Ubuntu 20.04)
 - TagSpaces Version 3.8.4

**Comment by uggrock** [comment]
could not be reproduced in the last version on Ubuntu -> closing
