### ISSUE TITLE
Double tags in search results

### ISSUE THREAD

**Issue by BramMiseur** [tagspaces/tagspaces#1354]
Dear support staff,

I just upgraded to Tagspaces Pro as I’m happy with your product. However, one issue I get is seeing double tags on all files when searching for files. I initially tagged some files without renaming after switching to renaming for tagging, however I also get this problem for files wich I have not tagged without renaming before. Moreover, before starting tagging with renaming, I removed all tags done without renaming. I added a screenshot to show these double tags in search results, one pair of the tags is just green without upper case while the other is the correct colors I assigned. This problem makes search results look disorganised, so thank you in advance for helping to find a solution.

Thanks in advance, 
Bram Miseur

**Screenshots**

![Capture 899](https://user-images.githubusercontent.com/80424838/110691642-af17d280-81e5-11eb-8edd-e0304adab3ff.JPG)

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version [e.g. 3.8.4]

**Comment by uggrock** [comment]
@BramMiseur thanks for reporting this, the solution for this issue will be part of the next release.
