### ISSUE TITLE
Open file with a custom application

### ISSUE THREAD

**Issue by scottrlarson** [tagspaces/tagspaces#1356]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently when I select a markdown file to open I have two choices:
1. Open file Natively
2. Open file (In TagSpaces)

I use a custom markdown editor to edit my markdown files and it would help me greatly to be able to open my files in a custom application instead of relying strictly on the native application (which I use only for my business authoring). I use different markdown editor based on the type of authoring I am involved in to separate my projects. It would be great if I can add custom applications to open files based on my needs. For instance, when I right click on a file I get the two options "open" and "open natively" It would be great to go into settings and add custom entries that would show up in the context menu of a file.

**Describe alternatives you've considered**
I have not consider any alternatives.

**Additional context**

**Comment by uggrock** [comment]
Hello, and thanks for this suggestion. You are not the first once requesting such feature, but unfortunatelly it is not easy possible to implement. For opening the files externally we relay on an Electron feature, which is so far not customizable.
