### ISSUE TITLE
AWS S3 Location Folder Limited to 1000 files

### ISSUE THREAD

**Issue by andrewfeliciano** [tagspaces/tagspaces#1366]
We recently started using Tag Spaces Pro 3.8.4  and are using an S3 bucket to store all of our documents. 

We noticed that Tag Spaces stopped displaying in the root folder any additional documents added to the S3 buckets after 998

I was able to create a couple of folders in the S3 buckets and limit the number of documents in those folders to under 1000 and we are able to see everything now. 

I looked a looked for a setting or something else that might be causing this, but am not finding anything. I believe saw in the documentation a practical limit of about 60,000, and hard limit of 200,000, which is far more than the 1000 document limit we seem to be seeing. 

Is there anything that I am missing?

**Comment by uggrock** [comment]
TagSpaces is currently pre-configured to show max. 1000 entries in a folder or from search results. You can increase this limit in Settings. At the very bottom there is a property called "Max Search Results". Please keep in mind that this could lead to performance issues. In general we recommend to split your files in sub folders, with let's says up to 1000 files. There is another limit build-in the app, the search index is limited to 200000 entries.
