### ISSUE TITLE
Turn off "preview" of video files

### ISSUE THREAD

**Issue by RevitArkitek** [tagspaces/tagspaces#1372]
v3.8.4
I'm not understanding the relevance of showing a preview of a video file which is just a bunch of random letters and squares.  There should be a way to turn it off.

**Comment by uggrock** [comment]
this is actually a feature, TagSpaces loads the first 10k bytes of every file, for which there is no build-in viewer, so the user can get a first impression about the file content. This is especially useful for text based files, but also for many zip-based files types.
