### ISSUE TITLE
[Android] intro screen scrolling/display bugs (on first launch)

### ISSUE THREAD

**Issue by jwmh** [tagspaces/tagspaces#1374]
Hi,
Thanks for building this, and for releasing it as open-source!!
I noticed a couple issues in the Android build (v3.9.5).

In the intro/readme
The second screen has a very nice layout / key / legend for showing newbies what each button does.
But...
A) I have a smartphone (not a tablet),so [each of] the intro screens won't fit 100% on my display.
B) 
but it scrolls (up+down, and left+right)

BUT:

#####

TL:DR;
On the first-launch intro screens:

The "SCROLL left" gesture is conflated with "SWIPE left".

So when i scroll right to see more of the screenshot/legend,
Then i scroll back left (and down),
instead it 'swipes' back to the previous (first) intro screen.

I am unable to pinch/zoom in/out.

To view all of the legend, i had to force quit, clear all app data, and relaunch it.

NB:
This only occurs if i release my finger after scrolling right.
If i don't release my finger, then i can still scroll back left again.
So i can't let go of the screen during scrolling right, or else i'll be unable to scroll back left.

#####
Why this trivial issue?
A:
Because first impressions count for a lot,
and
I really really want this Android app to take off!

**Comment by uggrock** [comment]
fixed for the next release
