### ISSUE TITLE
[Android] clicking Disagree in EULA... does nothing.

### ISSUE THREAD

**Issue by jwmh** [tagspaces/tagspaces#1375]
I am unable to disagree with the license; clicking "Quit/Goodbye" (i.e. disagree to the EULA).... has zero effect. (But "Agree" button works fine.)

Obviously trivial,
but adding it here for completeness' sake.

Android version downloaded today, directy from your website (apk).
App info says version 3.9.5

**Comment by uggrock** [comment]
actually this should close the app, or at least minimize it ...

**Comment by uggrock** [comment]
fixed for the next release
