### ISSUE TITLE
Tagspaces Pro 3.9.5 Shortcut key doesn't work

### ISSUE THREAD

**Issue by vdvin** [tagspaces/tagspaces#1376]
**Describe the bug**
Hello I am a user who is using the product very well. After using it, I liked it so much that I paid for the paid version,

but it is very difficult to use because the shortcut part does not work. It all needs to work with a mouse, so it takes a lot of time. Basically, it is possible to set a shortcut in the setting menu, but it cannot be changed,

and it does not work normally except for the ctrl+1, ctrl+2, ctrl+3 shortcut keys. I cannot also use F2, the shortcut for renaming. I don't know what the hell is wrong. Please help me.

Window10
Tagspaces Pro 3.9.5

**Comment by uggrock** [comment]
Hello and thanks for reporting this issue, this is appears to be a general issue and not specifically for the PRO version. We will take a look. Have those shortcuts worked for you in previous versions ?

**Comment by vdvin** [comment]
Thank you so much for the quick feedback. As of March 31st, I used the free version, but even then, SHORTCUT didn't work.
Afterwards, shortcut keys cannot be entered in the same way in the pro version.

There is no response even if I enter a key in the shortcut setting.

It is erased but cannot be re-entered.

If I type CTRL+Q, which is not in the hotkey setting, the program turns off immediately.

**Comment by uggrock** [comment]
CTRL+q is shortcut for exiting the app, and it is unfortunatelly not configurable....
if you want to redefined a key combination you have to type CTRL or CMD or SHIFT in the input field, not just pressing the keys.

**Comment by vdvin** [comment]
Even if you type the desired key to change the shortcut key, it is not applied. Sadly,
even if I change the hotkey that works for me to another hotkey, it still works with the original hotkey.

These are the only hotkeys that work.
CTRL+1, CTRL+2, CTRL+3, UP, DOWN, DEL, F1, F11, F10

**Comment by vdvin** [comment]
What I found out now is applied by rerunning the program after changing the shortcut key. 
However, Only these keys are apply (CTRL+1, CTRL+2, CTRL+3, UP, DOWN, DEL, F1, F11, F10)

**Comment by sytolk** [comment]
@vdvin yes I can repeat this issue thanks
