### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by sheafferusa** [tagspaces/tagspaces#138]
Any commercial license available ? ( so as to allow me to use/host the app without being bound to or forced to release the source code under AGPL??

**Comment by gautamsi** [comment]
Any plans to allow MIT License? Are you using any component which forces you to use AGPL? 

I like the perspective and want to implement it with my cross platform Email Client app

I guess I can use it with AGPL anyways, just asking.

**Comment by uggrock** [comment]
Almost all extensions for TagSpaces (viewers, editors and perspectives) are meanwhile extracted from the core and licensed under MIT license. The core is still AGPL and and such you can use it in your Email Client if its license is AGPL compatible.
