### ISSUE TITLE
not showing thumbnail of video files

### ISSUE THREAD

**Issue by MS-sound** [tagspaces/tagspaces#1381]
Thumbnails of video .MOV H.264 files are not shown in browser window. 
After adding extension mov  as media Files are played correctly in viever on right side, but still thumbnails are not shown.

[ Windows 10;  files: XAVC .mov;  TagSpaces Version 3.9.5]

**Comment by uggrock** [comment]
Thumbnails for .mov files are not supported in TagSpaces -> closing
