### ISSUE TITLE
Display difference between View and Edit mode

### ISSUE THREAD

**Issue by dacoul** [tagspaces/tagspaces#139]
Hi,

When you edit an HTML article (i don't test other format) styles are different than when you view it.

The most obvious difference is the font, but all bootstrap styles are lost in viewing mode.
![edit](https://cloud.githubusercontent.com/assets/6197074/4884091/84a8b3fe-6368-11e4-982e-1c2aedf7f0f1.png)
![view](https://cloud.githubusercontent.com/assets/6197074/4884097/91c5b262-6368-11e4-859a-9898b73da344.png)

It 's seem that the problem comes from the iframe in view mode. Css files are included in the page but not in iframe.

best regards
David

PS :  Thanks for your awesome work !

**Comment by uggrock** [comment]
fixed
