### ISSUE TITLE
BigSur/M1 : The app must be updated by the developper

### ISSUE THREAD

**Issue by polomatt** [tagspaces/tagspaces#1393]
**Describe the bug**
No way to open the app cause Apple cannot verify...
The app must be updated by the developper

**To Reproduce**
1. Download TagSpaces lite version
2. Let install the app
3. Launch the app

**Expected behavior**
Launching

**Screenshots**

**Desktop Application:**
 - Operating System: macOS Big Sur on Mac mini M1
 - TagSpaces Version: 3.9.8

**Additional context**

**Comment by sytolk** [comment]
You can try to Open System Preferences.
Go to Security & Privacy and select the General tab.
https://www.macworld.co.uk/cmsdata/features/3669596/how_to_open_mac_app_unidentified_developer_780.jpg

**Comment by polomatt** [comment]
Resolved.

Thank you for your help.

Best regards, Yves
