### ISSUE TITLE
Loads location meta data not working

### ISSUE THREAD

**Issue by seeb0h** [tagspaces/tagspaces#140]
I export tsm.json from Add-On for Firefox in Firefox Aurora like this (on windows)
>**MY_SPACE**
>>**.ts**
>>>tsm.json 

I check the Loads location meta data option in Extension for Chrome and Windows version.
I tried to reload tagspace in either cases, to set up again the MY_SPACE, but my tag groups are still not imported. 

Btw, I really like your project. Keep going!

**Comment by uggrock** [comment]
could not be reproduced...
