### ISSUE TITLE
Thumbnail generation consume too much resources

### ISSUE THREAD

**Issue by anarkopsykotik** [tagspaces/tagspaces#1401]
I added a pretty big folder containing a ton of webms (1000+), and the thumbnail generation consume huge amount of RAM, causing windows to prompt me of lacking memory and slowing all applications including tagspace, making them unresponsive.
At some point, it will crash and stop producing thumbnails, or only empty files
It would be good if you had the option :
- to pause/unpause the thumbnail generation
- to limit max ram use
- to limit simultaneous thumbnail generation
- to display how many thumbnail have been processed/are left to process
- to manually generate thumbnails for a folder/file
Will also note that if another application is also writing to disk (steam was downloading), tagspace will apparently take priority.

**Comment by Alecell** [comment]
I also have this issue, on my case isn't the a ram issue, but a processor issue. Maybe could the thumbnail generation run lazy loaded as we scroll the list.

**Comment by uggrock** [comment]
In the newly release version 4 of the app, we use a native library for generating thumbnail for images. Now this process works very smoothly and fast.
In TagSpaces, it was always possible to set thumbnails manually, you have just to place them in a appropriate place and rename them correspondingly. ( image.jpg -> .ts/image.jpg.jpg )
