### ISSUE TITLE
Changing key binding for "Add Tag" puts in a single character in tag window

### ISSUE THREAD

**Issue by noctif3r** [tagspaces/tagspaces#1419]
I've changed the key binding for "Add / Remove Tags" from "ctrl+t" to "t". This results in a single "t" character in the tag panel window, which you have to delete manually.

**To Reproduce**
1. Open TagSpace settings
2. Go to menu "key bindings"
3. Scroll down to "add / remove tags"
4. Delete "ctrl+t" and type in "t"
5. Close the window
6. Navigate to a location in your location manager and choose any image at the right panel
7. Stroke "t" on your keyboard
8. The tag operation window opens up with a single "t" character as tag.

**Expected behavior**
Tag operation window should open with an empty tag line and focus set on line.

**Desktop Application:**
 - Operating System: Windows 10 Pro
 - TagSpaces Version 3.9.8

**Comment by uggrock** [comment]
thanks for reporting this, but this actually the expected result, some users may want a single character for an action -> closing
