### ISSUE TITLE
Concurrent access is not implemented

### ISSUE THREAD

**Issue by seeb0h** [tagspaces/tagspaces#142]
Not sure if it is an issue or a suggestion.

The concurrent edition between several instances is poorly managed. 
Use case 1 : concurrent edition with desktop and mobile versions
Use case 2 : collaborative use of the space with multiple users

When you save a file, you're not warned if another user is in editing mode.
Neither when you save it.

A simple lock mecanism could be :
1. when a user edits a file : write a 'in-edition" tag 
2. forbid the file edition by another user when the tag is present
3. remove the tag when the file is saved

Collaborative work would be much safer

**Comment by uggrock** [comment]
Considered as enhancement request -> closing for now
