### ISSUE TITLE
Wouldn't it better to use one pair of brackets for every tag?

### ISSUE THREAD

**Issue by sherlocknieh** [tagspaces/tagspaces#1429]
Every time I try to add a tag containing 2 or more words, it just turns into multiple tags.

So, instead of putting all tags in one brackets, separated with space, (like: [tag1 tag2 tag3...] )

wouldn't it better to use one pair of brackets for every tag ? (like: [tag1][tag2][tag 3]...)

**Comment by uggrock** [comment]
This is a huge change because a lot of users have already renamed their files and changing of this logic will require a kind of migration. Beside that the length of the filename is have one character more per tag delimiter...
