### ISSUE TITLE
JFIF File Preview (Basically an Extension of JPG File Preview)

### ISSUE THREAD

**Issue by CarJem** [tagspaces/tagspaces#1442]
Despite the JFIF Format being almost identical to a JPG/JPEG, TagSpaces doesn't classify it as an image, even if I manually force it too.

If I rename my files to JPG/JPEG instead of JFIF TagSpaces offers a preview, what I purpose is basically just handling JFIF files like JPG/JPEG because of their similarity and compatibility. Just a small suggestion since JFIF is at its core JPG/JPEG.

**Comment by uggrock** [comment]
You can add JFIF/JIF file formats in the settings of the applications, so you will be able to open these files in TagSpaces. For creating thumbnails for this files we have to make changes in the app.

**Comment by CarJem** [comment]
Then why close this, JPEG is the same as JFIF

**Comment by uggrock** [comment]
if will be part of the next release

**Comment by CarJem** [comment]
Okay, cool stuff!
