### ISSUE TITLE
Android Update?

### ISSUE THREAD

**Issue by CarJem** [tagspaces/tagspaces#1448]

**Comment by CarJem** [comment]
Did someone forget to update the Android branch... I just paid for PRO hoping for an Android build....

**Comment by uggrock** [comment]
We do not have an official version of PRO version for Android yet. The free version will be updated in the coming days on Google Play. Nevertheless, we can provide you a preview of the PRO Android version, if you are interested.

**Comment by CarJem** [comment]
yes please... let me know how!!!
