### ISSUE TITLE
Warning fires every time opening a file natively

### ISSUE THREAD

**Issue by jgerac** [tagspaces/tagspaces#1454]
Latest 3.10.4 version now fires a warning every time you click to open a file natively.  Warning is understandable, but please provide an ability to suppress (e.g. "do not show this again" checkbox or option in the settings menu).

**Comment by sytolk** [comment]
What is your Operating System ?  Windows ?

**Comment by jgerac** [comment]
macOS 11.4 on Mac mini M1

**Comment by sytolk** [comment]
I can repeat this: 
![CC03E80C-FA2E-4104-A59C-991730D663E4](https://user-images.githubusercontent.com/1415463/123077952-2e42b680-d423-11eb-9aa2-999c0496a699.png)

**Comment by uggrock** [comment]
this was done for security reasons, having a checkbox for disabling could lead to issue by inexperienced users -> closing
