### ISSUE TITLE
[Android] F-Droid Repository

### ISSUE THREAD

**Issue by CarJem** [tagspaces/tagspaces#1455]
The Android Versions do not rely on Google Play Services... So Why Not make it accessible on the F-Droid Appstore as well? Especially for people who don't have access to the Google Play Store, plus it would also receive updates responsively and not have to go through the 1-2 week waiting period that happens with Google Play.
https://f-droid.org/

**Comment by uggrock** [comment]
We tried this some years ago, but back then F-droid was not accepting Cordova apps for some reason...

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@uggrock, hostage of a repository for your software, if it continues to be declined by the adminsitrators of the default repository is not difficult. Bitwarden and Collabora do it.

**Comment by CarJem** [comment]
I still really think that this should be reconsidered or at the very least put in some infrastructure built into the app that would allow us to automatically download updates from GitHub

**Comment by rokejulianlockhart** [comment]
@CarJem, wanna create a new issue? It might be triaged by someone that bothers to check their notifications.

**Comment by CarJem** [comment]
honestly I've given up on tagspaces and moved on to FileRun.... indexing is just to slow and the app is too clunky and not fit for mobile

**Comment by rokejulianlockhart** [comment]
https://tagspaces.discourse.group/t/86?u=rokejulianlockhart

**Comment by CarJem** [comment]
> honestly I've given up on tagspaces and moved on to FileRun.... indexing is just to slow and the app is too clunky and not fit for mobile

That said if the devs could change that... maybe I'd return.... but right now using it feels like a chore
