### ISSUE TITLE
PDF Preview on Linux doesn't show comment highlights on text

### ISSUE THREAD

**Issue by kuparikettu** [tagspaces/tagspaces#1473]
**Describe the bug**
PDF Preview on Linux (Ubuntu 18.04) doesn't show the yellow highlight on text that has a comment on it. Bringing the cursor over such text shows the comment window, but there is no highlight. In Firefox, which seems to have the same PDF viewer, the highlighted parts show up correctly.

**To Reproduce**
1. Open a PDF file with added comments / highlights
2. Go to a page where there should be yellow highlight on text
3. No highlight can be seen, but putting the cursor on the text shows that there is a "comment"

**Expected behavior**
The highlighted text should show up with highlight.

**Screenshots**
Expected behaviour (from Firefox)
![Kuvakaappaus - 2021-07-12 17-42-05](https://user-images.githubusercontent.com/59308117/125307425-b6d4b880-e338-11eb-82e2-5aee1596e555.png)

How it shows up in TagSpaces
![Kuvakaappaus - 2021-07-12 17-42-39](https://user-images.githubusercontent.com/59308117/125307462-bcca9980-e338-11eb-9282-09b594e03814.png)

**Desktop Application:**
 - Operating System: Ubuntu Linux 18.04
 - Browser - only needed if you use the browser extensions for Firefox or Chrome
 - TagSpaces Version 3.10.4

**Comment by uggrock** [comment]
Thanks for reporting this, it is fixed for the next release: https://github.com/tagspaces/viewerPDF/commit/22dbe2946ed48ca8bed898b0c26fd74b7f3043d0
