### ISSUE TITLE
Some videos not working

### ISSUE THREAD

**Issue by bobotto** [tagspaces/tagspaces#1484]
Some videos not loading, even though it has the same encoding/container as other videos that load fine
MP4, H264
All those videos work fine when using quicktime to open
Thank you

Sample problem videos attached

https://user-images.githubusercontent.com/16209990/126889473-17c600bf-9f28-48a6-84e8-8d147d671299.mp4
https://user-images.githubusercontent.com/16209990/126889482-6aece01a-78b5-4327-93da-7efd68725ab3.mp4

**Desktop Application:**
 - Operating System: MacOS 11.4
 - TagSpaces Version 3.11.2

**Comment by uggrock** [comment]
Thanks for reporting this. For playing videos we relay completely on the underlying browser capabilities. The attached browser can not be played in a Chrome browser, so unfortunately we can not do anything here.
