### ISSUE TITLE
Deleting file should refresh view automatically to show deletion took place

### ISSUE THREAD

**Issue by rancidfrog** [tagspaces/tagspaces#149]
When a file is deleted, it does not get removed from the list until you refresh view.
This can cause confusion, as you think the file is not deleted. Also, tagspaces allows you to keep deleting file even though it has already been deleted.

Solution: Refresh view -> removed file disappears

**Comment by binarybum** [comment]
This persists in v1.9.0 on Win8.1 64bit.

**Comment by uggrock** [comment]
fixed again for v1.9.2
