### ISSUE TITLE
Misspelled search button name

### ISSUE THREAD

**Issue by CR0CKER** [tagspaces/tagspaces#1490]
**Describe the bug**
The search button option for fuzzy search should be named "fuzzy", not "fussy". Very different meaning.

**To Reproduce**
1. Click search button in the sidebar
2. See search options

**Expected behavior**
The correct term for this button is "fuzzy" search.

**Screenshots**
![Screen Shot 2021-08-06 at 11 56 09 AM](https://user-images.githubusercontent.com/6056387/128449445-b95f536a-b66b-4abc-ae58-22a0e6d65bfb.jpeg)

**Desktop Application:**
 - TagSpaces Pro 3.10.4

**Comment by uggrock** [comment]
Thanks for reporting this is already fixed for the next release: https://github.com/tagspaces/tagspaces/commit/b28a9545958b70a9e68ce468f43381a0f09dfeab#diff-162a398d3f69f6a8d848771d7e1c9f02ef3a1cd86e5d854283e2fc897cd89821
