### ISSUE TITLE
Using it as a web app

### ISSUE THREAD

**Issue by ugintl** [tagspaces/tagspaces#1497]
Is it possible to use it as a web app? If yes, then how?

**Comment by sytolk** [comment]
Yes, look at this script: https://github.com/tagspaces/tagspaces/blob/develop/package.json#L68
It's possible to run tagspaces web in aws with amplify but I'm not sure if this is Pro feature only @uggrock

**Comment by uggrock** [comment]
The web version is a PRO package available as a separate product.
