### ISSUE TITLE
Tag creation fails on any file (but not folder) when using Sidecar files

### ISSUE THREAD

**Issue by EliEron** [tagspaces/tagspaces#1498]
**Describe the bug**
When attempting to add a tag to a file the message "Adding tags failed" appears. This appears to be caused by an error creating the ".ts" folder as manually creating it fixes the issue. But strangely enough if you add a tag to a folder TagSpaces does manage to create the ".ts" folder inside it correctly.

**To Reproduce**
1. Open any location
2. Add a tag to a file (not folder)

**Expected behavior**
TagSpaces should create the ".ts" folder automatically and apply the tags successfully.

**Screenshots**
Here is a video showing that tags cannot be adding unless you manually create a ".ts" folder:

https://user-images.githubusercontent.com/22575945/131080788-ad616ae9-f787-479a-be27-85c3b1b567c1.mp4

Here is a video showing that adding tags to a folder does work, and creates the ".ts" folder successfully:

https://user-images.githubusercontent.com/22575945/131081076-6e6b2b5d-1be9-4642-a896-c8c52a14bc40.mp4

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 3.10.4 PRO 

**Additional context**
This happens in any folder on my computer, and I am certain it's not an issue with file permissions or anything like that.

**Comment by uggrock** [comment]
closing since the issue was fixed in version 3.11.5
