### ISSUE TITLE
Session details (I.E. window size and position) do not persist.

### ISSUE THREAD

**Issue by rancidfrog** [tagspaces/tagspaces#150]
Details such as view (window size,maximized, etc.) are not saved when you restart application, making you change window info each time you load tagspaces.
~~Neither is Toggle File Details. Each time you restart you have to reClick Toggle View Details~~
[Toggle File view has been removed in latest version.]

Previous Session details should be restored.

Using: tagspaces-1.8.6-linux64.tar.gz

**Comment by rancidfrog** [comment]
The window size (full size) still does not persist in version 1.10.0
Downloading and soon updating to 1.10.3
Hoping to see state persistence in the future
Thank you for your time

**Comment by rancidfrog** [comment]
Still in latest version: tagspaces-1.11.0-linux64.tar.gz
Each time I open tagspaces I have to maximize it.

Is it possible to have the option to remember window size and position?

**Comment by rancidfrog** [comment]
Does it work or you choosing it not to be necessary?

**Comment by uggrock** [comment]
We consider this is an enhancement request and beside that is appears to be a nwjs (node-webkit) issue...
