### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by mhorr99** [tagspaces/tagspaces#1514]
I'm unable to search by tag in Tagspaces

1. Go to 'Search' (search icon in left bar)
2a. Type a tag name
2b. OR choose from the list of tags (in the field 'must contain all of these tags')
3. click 'Search'
4. 'No file or folder found'

Also, the 'show files with this tag' feature doesn't work:
1. Go to a file's properties
2. Under 'tags', I can see the file has multiple tags. Right click one of them
3. click 'Show files with this tag'
4. 'No file or folder found'

When viewing the folder (in list view) I can see there are many files with this tag, so they should show up in the search feature.

![image](https://user-images.githubusercontent.com/92452201/137161876-8f5c7ec2-9daf-4c13-b6dc-ff879bca4013.png)
![image](https://user-images.githubusercontent.com/92452201/137161971-1b4216a7-87ad-438b-8452-fe30f43381f1.png)

 - Operating System: Windows 10
 - TagSpaces Version 3.11.9

**Comment by uggrock** [comment]
Thanks for reporting this. I am not able to reproduce this issue. Have you tried to restart the program and search again?

**Comment by mhorr99** [comment]
Yes I have, but that doesn't help.
I now discovered that Tagspace works just fine in folders on my first ssd, but the issue only occurs on my second ssd. Any ideas on why that could be a problem and how to work around?

**Comment by sytolk** [comment]
@mhorr99 can you check in searchable dir DOCUMENTEN/MHORRFILMS/.ts/tsi.json if this file exist and its content?

**Comment by mhorr99** [comment]
> You can check the reason why tsi.json is not created

how do I check that?

**Comment by sytolk** [comment]
I see that there is missing dir separator (/) between Documenten and Mhorrfilms. This is the reason that files not found. Its appear like a bug in Tagspaces we will try to reproduce it.. @mladensap.  
Thanks @mhorr99

**Comment by mhorr99** [comment]
thanks for your help and for responding so fast!

**Comment by sytolk** [comment]
@mhorr99 gennerally I cannot repeat this issue but in this screenshot: https://user-images.githubusercontent.com/92452201/137161876-8f5c7ec2-9daf-4c13-b6dc-ff879bca4013.png I see in file properties path like D:\\\Documenten\Mhordfilms\..
Can you check if your location path is D:\\Documenten ? 
![Screenshot_46](https://user-images.githubusercontent.com/1415463/138082245-dd27d34f-6f74-4988-9769-0f13c846c8b8.png)
and if it is change it to D:\Documenten and try to repeat this issue
