### ISSUE TITLE
Cannot edit pdf files on macOS.  In settings PDF Viewer is set but the macOS preview editor is not provided as an option to edit the file. 

### ISSUE THREAD

**Issue by Shama202** [tagspaces/tagspaces#1517]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Application:**
 - Operating System: [e.g. macOS, Windows 10, Linux, Ubuntu]
 - Browser - only needed if you use the browser extensions for Firefox or Chrome
 - TagSpaces Version [e.g. 3.1.1]

**Additional context**

**Comment by uggrock** [comment]
TagSpaces do not support annotations in PDF files. But you can add description and tags to PDF files or actually any kind of files. The app do not support changing the content of PDF files.
