### ISSUE TITLE
manually import tags

### ISSUE THREAD

**Issue by disaster123** [tagspaces/tagspaces#152]
tagspaces has now a export tags option in the webgui. But where is the import function ;-) I really would like to import tags without marking them as imported and beeing able to edit them gain.

**Comment by sunjam** [comment]
Didn't work for me either on Win7 64-bit 1.10.1 client.

**Comment by binarybum** [comment]
Import function is in the experimental section in settings.  It sounds as though the tag groups are specific to the location and a copy of the json file needs to be in a subfolder ".ts" at each location.  Despite, that I still could not get it to work on windows.  Anyone figure this out?  A walkthrough would be helpful

**Comment by uggrock** [comment]
Issue was fixes in pre release 1.10.2. Can somebody try it out and confirm?

**Comment by binarybum** [comment]
Yes.  Starting to work.  Here are the problems though:  1st, I've pinpointed the menu duplication issue I emailed you about to simply exporting the JSON file - for posterity I've created a new issue ( #193 ) to specifically reflect this.

  2) To get importing to work I have to delete the date / timestamp tag that is automatically assigned during export. It would be simpler / preferable not to have to do this, also if the code allowed recognition of the newest timestamp, old json files could be kept around to allow backtracking by simply deleting the newest json file in the .ts folder.

3)  It will not let me move up or down the imported tag groups.

4) Either a merge of groups with the same title or simply overwriting all of the existing groups with the imported groups would be preferable to the current behavior of adding imported groups to the end and then requiring the user to delete duplicate groups.

Thanks!

**Comment by binarybum** [comment]
Noticed another issue:

5)  With imported tags if you try to move one tag to another group via drag/drop the tag simply disappears.  

I also found another problem with moving tags around to different groups - see new issue #196

**Comment by fxshpac** [comment]
Notice a behavior with latest .3 version. When I choose a location which has tsm.json file it loads the tags from the file just fine. But when I switch to a different location which doesn't have such file, the tags imported stay there. I was thinking the imported tags from the first location should be removed in this case they are not.

**Comment by binarybum** [comment]
Yes, fxshpac highlights a good point - it looks like the way tag database syncing is built is to have each location have it's own json database file, but this isn't always executing that way and the process is a little cumbersome (I have to create .ts folder, rename json file, "manually" export, turn on importing).  Ideally a turnkey solution where I just turn on or off an option to "sync tag groups with locations" with all the rest being transparent would be best I think.

**Comment by uggrock** [comment]
the import function is implemented, for more details see this article: https://www.tagspaces.org/documentation/sharing-tags/
