### ISSUE TITLE
Can't order alphabetically title subfolders after last upgrade

### ISSUE THREAD

**Issue by MauDarktable** [tagspaces/tagspaces#1521]
![2021-10-25 22_09_35-Window](https://user-images.githubusercontent.com/77062442/138763454-439896ab-7e9a-4a37-bd30-f6743acfd36b.png)
Dear support,
there is a bug into order function. I have hundreds of subfolder with names like "[2021-10-24] Sending bug report"... After last upgrade TagSpaces appear to "ignore" the part of subfolder name that stay between "[]".

![2021-10-25 22_06_57-Window](https://user-images.githubusercontent.com/77062442/138763160-6c1ffa3b-437e-41c0-9418-c20afdd76e6e.png)
For example, I have this "title" order:
[2021-06-05] Aaaa
[2021-02-14] Bbbbb
[2021-03-17] Cccc

Before the last upgrade the right order was:
[2021-02-14] Bbbbb
[2021-03-17] Cccc
[2021-06-05] Aaaa

I urgently need a solution because it's very difficult find everything.
Thanks.
Have a nice day.

**Comment by uggrock** [comment]
fixed in version 4.0.4

**Comment by MauDarktable** [comment]
Hi uggrock, sorry but it seem not be fixed:

![image](https://user-images.githubusercontent.com/77062442/141659523-b0fcc0af-a217-4987-851c-6bf6b5ab3d2a.png)

This is an example of my subfolders sorted by name. As you can see I've updated to 4.0.6 version.

Thanks for you support.

**Comment by uggrock** [comment]
@MauDarktable you were right, the provided fix was only partial. Now for version 4.0.8 it should be finally fixed.
