### ISSUE TITLE
do not reload editor on adding / removing tags

### ISSUE THREAD

**Issue by disaster123** [tagspaces/tagspaces#153]
I'm tagging a lot of PDF files. And this is nasty while going through the PDF and adding tags it realoads the whole PDF on every tag add or remove.

**Comment by disaster123** [comment]
closed means fixed or won't fix?

**Comment by uggrock** [comment]
The issue is considered as an enhancement, which can not be fixed for now. In the upcoming PRO version, you can add the tags in sidecar file, so the file will not have to be reloaded on tagging.
