### ISSUE TITLE
Unable to search by tags in case of sidecar file

### ISSUE THREAD

**Issue by sealferov88** [tagspaces/tagspaces#1530]
Dear, tagspaces team
Description:
I'm unable to search by tag or use 'show files with this tag' files that tagged by **sidecar** file. **For renamed files all works correctly.**
For created catalogue tsi.json created and filled, but tags property always empty, except renamed files. 
Option to show files with dot is enable.
Reindexing catalogue wasn't make things works correct
There is no any error in dev tools

 - Operating System: Windows 10
 - TagSpaces Version 4.0.3

**Comment by uggrock** [comment]
Thanks for reporting this, we were able to reproduce the issue on Windows. A fix will be provided in the next release, coming very soon.
