### ISSUE TITLE
Tags can't be ordered anymore

### ISSUE THREAD

**Issue by Quixus** [tagspaces/tagspaces#1547]
**Describe the bug**
As the title says the tags remain in the order they were added and cannot be moved around with drag and drop as in 3.11.9.

**To Reproduce**
Add tags to a file, click and hold one tag, move the tag in front of another tag, release the mouse button.

The tag is now shoved back to where it was.

**Expected behavior**
The tag should now be where it dropped

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: 4.0.6

**Comment by uggrock** [comment]
The features was causing issue in some edge case so we decided to put it behind a flag in the settings of the app. You can activate it by clicking on this checkbox:

![Screenshot from 2021-11-14 14-19-37](https://user-images.githubusercontent.com/1249777/141682790-e9bed04d-dc74-49ce-aacb-a642de5dbd44.png)

**Comment by sennewood** [comment]
I activated it, but the issue is still as described.

**Comment by Quixus** [comment]
It works for me after reactivating the feature. Thanks

It seems the issue isn't resolved for @sennewood though.

**Comment by sennewood** [comment]
I'm using the "sidecar file" if that helps.
