### ISSUE TITLE
error Command "install-ext" not found.

### ISSUE THREAD

**Issue by meiry** [tagspaces/tagspaces#1558]
when trying compile and install the app in windows 10 , im getting this error 
```
$ yarn install-ext --verbos
yarn run v1.22.17
error Command "install-ext" not found.
```

**Comment by sytolk** [comment]
Why you a running yarn install-ext ? (It it replaced with install-ext-node) to install extensions.

**Comment by meiry** [comment]
This is what is writing in the instructions

**Comment by uggrock** [comment]
Thanks for reporting this! I just updated the instruction in the readme file.
