### ISSUE TITLE
Little Issues with shorcuts

### ISSUE THREAD

**Issue by Biniou180** [tagspaces/tagspaces#157]
Hi Uggrock, first of all thanks for your hard work on tagspaces, i use it everyday at my office to take notes! ;-)

I've spotted some problems with it tough, nothing critical, but if i can help to enhance this tool... :-)

FYI, I have been able to test the following behaviors on windows standalone version, and firefox addon (windows/linux)

* When editing HTML files, there is a mistake in shortcut attribution: i've seen the popup help when hovering on buttons, which says ctrl+shift+7 for ordered list and ctrl+shift+8 for unordered list. However it is in fact the contrary.
Could you please correct either the help popup or the shortcuts?

* For indenting and outdenting, the shortcuts are Ctrl+[ and Ctrl+]. However it seems to not work at all.
Is there a way to make it work?

* Ctrl+S shortcut works well when editing md files (for example), but does not work when editing HTML files: on windows standalone client, nothing happens, on firefox addon, firefox himself tries to save the file.

**Comment by paflopes** [comment]
+1

**Comment by scith** [comment]
Hi, I can't make the "indent/outdent" shortcuts work either... I have an AZERY keyboard so the [ and ] keys are not very accessible either.
Is there a way to customize these shortcuts?
Thanks

**Comment by uggrock** [comment]
could not be reproduced in v2.1.0
