### ISSUE TITLE
Does TagSpaces support Windows7?

### ISSUE THREAD

**Issue by Femtometer** [tagspaces/tagspaces#1570]
**Describe the bug**
Crash when run on windows7 SP1 x64.

**To Reproduce**
1.  Double click to run, latest version.

**Expected behavior**
Crashed.

**Comment by uggrock** [comment]
We are not testing TagSpaces anymore on Windows 7 and officially we support Windows 10 and above. So probably the underlying Electron has issues with Windows 7.

**Comment by Femtometer** [comment]
Fine. I'll stay in 3.xx.x version, it works fine.
