### ISSUE TITLE
TagSpaces 4.0.9 crash on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by MacTerrassa** [tagspaces/tagspaces#1575]
**Describe the bug**

Update to 4.0.9, and when trying to open it with a double click, the window opens in the center, begins to expand to the entire space and hangs, leaving an error message.

**To Reproduce**
1. Install new version in applications folder
2. Double click
3. The window in the center of the screen opens, begins to expand.
4. The program closes.
5. An error message appears.
**Expected behavior**
Obviously open the program :-)

**Screenshots**

**Desktop Application:**

-Mac OS X 10.11.6
-TagSpaces 4.0.9

Attached the console error message in txt format.
[TagSpaces.txt](https://github.com/tagspaces/tagspaces/files/7651848/TagSpaces.txt)

**Comment by uggrock** [comment]
Hello,
macOS 10.11.6 is pretty old, I thing it was released back in 2015, I suppose that Electron which is the platform we use underneath TagSpaces is having issues with this version of the operating system. Unfortunately here is not much what we can do.
