### ISSUE TITLE
Problem with selecting HTML content in firefox addon

### ISSUE THREAD

**Issue by Biniou180** [tagspaces/tagspaces#158]
Hi Uggrock,

In firefox addon (windows or Linux), when editing HTML files, it is impossible to select content: when trying to click on the text, or selecting part of it, nothing happens.
Also, up and down keys does not behave correctly: when pushing "down", the cursor gets to the very end of the file, and "up" go to the beginning. (impossible to get to the next line)

For information, this problem does not appear on the standalone windows version. I've also tried on other file types (MD files particularly), and i do not encounter this issue.

Could you please see if this issue can be corrected?

Thanks a lot!

**Comment by uggrock** [comment]
the file browser is meanwhile disabled in the Firefox Addon please use the desktop versions.
