### ISSUE TITLE
"Collect Tags From Current Location" says "avalible in the PRO version" even though I have Pro

### ISSUE THREAD

**Issue by Kuchenaxt** [tagspaces/tagspaces#1580]
64bit desktop version of TagSpaces v4.1.2 on Ubuntu 20.04.

In the Tag Library, clicking on Collected Tags -> Collect Tags From Current Location I get "This functionality is available in the PRO version"

I have the Pro version.

**Comment by uggrock** [comment]
Thanks for reporting! I was able to reproduce the issue, it will be fixed very soon in the upcoming 4.1.3 version.

**Comment by uggrock** [comment]
v4.1.3 released with the fix.
