### ISSUE TITLE
Thumbnail filename is not renamed when main file name is changed

### ISSUE THREAD

**Issue by manolitto** [tagspaces/tagspaces#1581]
When you change the name of a (pdf) file, the corresponding json file in the hidden .ts folder is immediately getting renamed as well, but the filename of the generated thumbnail stays the same. This is not a serious problem and not directly visible because the old thumbnail seems to be cached by Electron. And when you leave the folder and re-enter it, a new thumbnail (with the correct filename) is automatically generated.
HOWEVER, the old thumbnail file is never getting deleted and when you often rename files, over time the filesystem will be polluted by many unused image files...

1. Add a PDF file to a Tagspaces Location
2. In Tagspaces go to the PDF file's parent folder
3. Inspect the hidden .ts folder in Finder or Explorer
4. Identify the thumbnail file (same filename as the PDF with an additional .jpg extension)
5. Rename the PDF file in Tagspaces
6. Watch the thumbnail filename not being changed
7. In Tagspaces got to another folder and go back to the PDF's parent folder
8. In Finder/Explorer watch a new thumbnail being created and the old one stay

**Expected behavior**
- The thumbnail file shall be renamed when the main file's name changes (similar to the json sidecar file)

**Desktop Application:**
 - macOS 12.1
 - TagSpaces Version 4.1.2

**Comment by uggrock** [comment]
Thanks for reporting this, we were able to reproduce the issue. We will try to provide a fix for the next version.

**Comment by uggrock** [comment]
Fixed in v4.1.3
