### ISSUE TITLE
Huge memory usage and freeze when generating thumbnails.

### ISSUE THREAD

**Issue by math-artist** [tagspaces/tagspaces#1584]
Trying to use Tagspaces on Windows 10.

I tried Tagspaces for the first time 1 month ago, then updated to 4.1.2, same issue.
I added a folder with over 1000 videos. The thumbnail generation makes the app crash. It uses all my ram (32 Go), then freeze. Only about 3% of the videos have thumbnails after more than 30 minutes of freeze. I decided to uncheck that feature because after 3-4 retry, it still freezes and makes Tagspaces unresponsive.

Then, I have many files not displaying their name, only the auto-generated tags. And files that only display a small portion of their name.  I figured out that this is because I have many files with [] characters in their names. Is there a way to disable the auto tagging from the filename? I already checked the option to use json instead of file renaming.

Thanks.

**Comment by uggrock** [comment]
This is due to the current implementation, there is no easy solution for the issue, so I will close it for now.
