### ISSUE TITLE
Tag Groups contain Folder Names

### ISSUE THREAD

**Issue by stevepane** [tagspaces/tagspaces#1588]
Hi all,

when creating new tag groups in TagSpaces (4.1.2 and 4.1.3) the folder name is added to the tag group.
This is new to me and I do not know how to turn that off.
Besides that it doesn't really make sense since the tags are not folder specific.

Any idea what to do to turn this off or is this a bug?

Kind regards

Stefan

**Comment by uggrock** [comment]
Hi,

this feature can be deactivated by turning off the switch from the following screenshot.
![Screenshot from 2022-01-11 09-35-08](https://user-images.githubusercontent.com/1249777/148913086-f1aa2f97-b470-4ffa-bfcc-3675d90ba762.png)

Greetings,
Ilian

**Comment by stevepane** [comment]
Perfect, thanks!

**Comment by stevepane** [comment]
Hmmm, no matter in which position that switch is - location is added. Annoying....

**Comment by stevepane** [comment]
If the switch is on, you can at least edit it and select another source where it is saved (and by this remove the location information).  But it shouldn't be added in the first place if it is off.

**Comment by uggrock** [comment]
I was finally able to reproduce your issue yesterday, it is now fixed in version 4.2.1
