### ISSUE TITLE
Prepopulate tags from an external processing pipeline

### ISSUE THREAD

**Issue by jbeezley** [tagspaces/tagspaces#1595]
I have a few processing pipelines (OCR, natural language tagging, etc.) that I want to run a large corpus of documents.  My primary interest in tagspaces is as a convenient interface for non-technical users to go through these results and fix them up as necessary.

I noticed that the sidecar files produced by tagspaces are documented and would be fairly easy to reproduce in my pipelines.  I'm curious if that is an intended use case?  Are there any roadblocks for such an approach?

**Comment by uggrock** [comment]
Sure, there are no restrictions in creating sidecar files with external tools and pipelines.
