### ISSUE TITLE
collect Tags From Current Location should be a core feature

### ISSUE THREAD

**Issue by aisbergde** [tagspaces/tagspaces#1598]
**Is your feature request related to a problem? Please describe.**
It is not possible to use the free version in any useful way if it is not possible to collect tags from the current location. The idea was to use any tool for the same files on PC and on Android and to store tags in filenames and to just sync files between PC and smartphone. So it looks like the idea of the app does exactly this. But the free version can't be used for this goal, because it doesn't collect tags.

**Describe the solution you'd like**
I would like to see the collect tags feature in the free versions.

**Describe alternatives you've considered**
A have no idea how to use the ftee app if it doesn't use existing tags. Just need to know existing tags and search them using a file manager? This has no advantages.

**Additional context**

**Comment by uggrock** [comment]
Thanks for this suggestion, we will discuss it. There is good chance that we will release it soon in the lite version. But it is not true that the app is unusable without this feature. You can always export your tag library from the desktop version and import in the app: https://docs.tagspaces.org/tutorials/sharing-tags

**Comment by aisbergde** [comment]
thank you for explaining. I did not know, because I only tested the mobile version.

**Comment by aisbergde** [comment]
I tried the desktop version. But it has the same limitation and can't collect tags. If I can't collect tags, then I can't export a list. 

It would be fine to keep this issue open until it is solved. I can't imagine any scenario of a tagspaces usage if it is not possible to collect tags. It is fine with all other limits, I only try to find any way to use tags on a smartphone.

**Comment by uggrock** [comment]
The feature will be part of the next free version.
