### ISSUE TITLE
Newly created txt file which name contains national chars is saved in file system with broken chars

### ISSUE THREAD

**Issue by tokubi** [tagspaces/tagspaces#16]
Tested on Windows 7 Pro EN, Firefox 25, Chrome 30.0.1599.101m

![screenshot 2013-11-13 09 55 39](https://f.cloud.github.com/assets/5927123/1529910/7d812e74-4c41-11e3-9832-deb0ba3d4060.png)

**Comment by uggrock** [comment]
issue not relevant anymore
