### ISSUE TITLE
Zoom in does not work

### ISSUE THREAD

**Issue by yevgenia-andrevna** [tagspaces/tagspaces#1600]
**Describe the bug**
Zoom in does not work (while zoom out does). When i press ctrl+ nothing happens. 
Changing the short cut does not help.

**Expected behavior**
For the interface to zoom in

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces v.4.2.0

**Comment by uggrock** [comment]
Thanks for reporting this! The actual shortcut for zoom-in is ctrl/cmd+shift+plus. I have corrected this for the next release.
