### ISSUE TITLE
tagspaces-win-x64-4.2.0.exe 's signature is invalid for sometime already.

### ISSUE THREAD

**Issue by ccchan234** [tagspaces/tagspaces#1601]
**Describe the bug**

tagspaces-win-x64-4.2.0.exe 's signature is invalid for sometime already.

**To Reproduce**
1. Go to tagspaces-win-x64-4.2.0.exe
2. Right click
3. check digital signature

![image](https://user-images.githubusercontent.com/37549409/151952425-50f8313b-fed9-4e56-82c5-be0884605f8b.png)

**Expected behavior**

I expect a valid signature

**Screenshots**

see above

**Desktop Application:**
 - Operating System: [e.g. macOS, Windows 10, Linux, Ubuntu]
 - Browser - only needed if you use the browser extensions for Firefox or Chrome
 - TagSpaces Version [e.g. 3.1.1]

**Additional context**

**Comment by uggrock** [comment]
Thanks for pointing this out, we will fix it for the next major release 4.3.x

**Comment by uggrock** [comment]
Signing of the Windows installer is fixed in the latest 5.0.5 version.
