### ISSUE TITLE
Folders can't be moved to an other location

### ISSUE THREAD

**Issue by Salamimonster** [tagspaces/tagspaces#1608]
**It is not possible to move a folder from one location to an other.**
Neither by drag&drop nor by the context menu (nornor by CTRL+C / CTRL+V 😂).

**Reproduce:**
1. Create at least two locations in the location manager
2. Add a folder to location1
3. Drag&Drop the folder from the list view of location1 to location2
4. realise, that the world is a shadily valley with blank signs leading the way.

Windows10 pro
TagSpaces 4.2.1

**Comment by uggrock** [comment]
Moving folders was never implemented in TagSpaces, so I will handle this as a feature request.

**Comment by Salamimonster** [comment]
Dear Ilian, 
this feature is important to me. Every day I stumble about folders that I had to move to other locations. If possible, please include this into one of the next releases. If I can support you by testin, please let me know.

André
