### ISSUE TITLE
symbolic link and tag

### ISSUE THREAD

**Issue by dzmitry-lahoda** [tagspaces/tagspaces#1612]
I have read that tool uses rename of files to tag. Sometimes that is not an option. For example, I use files shared from the external mount file system or shared via p2p solution or overall just shared. 

I want to be able to one button click to create a link and tag a link. 

For now link is separate process https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html  .

**Comment by uggrock** [comment]
if you do not want the files to be renamed, you can try using the so called sidecars for saving the tagging information. This option can be activated in the settings of the app.

**Comment by dzmitry-lahoda** [comment]
i just proposed 3rd option which like sidecar but allows other tolling based on file name work well. links exists on all main file systems and well supported.

**Comment by dzmitry-lahoda** [comment]
sidecars create noise when i navigate from console and need additional handling drom other tools. while links is native way to build semantic file system. exactmy as chromium bmarks work with plugins.

**Comment by uggrock** [comment]
Now I got this. Integrating a 3rd option for tagging requires a big refactoring which we are currently not able to invest. We are open for PRs though.
