### ISSUE TITLE
Color of tag on file does not get updated when the group color is updated

### ISSUE THREAD

**Issue by Quixus** [tagspaces/tagspaces#1617]
**Describe the bug**
When you add a new tag to a file, add it to a tag group and then edit the tag group to make all tags in the group the same color, the tag in the list gets updated but not the tag on the file. This worked in 4.2.1. The only way to get the tag in the right color onto the file is to remove the "old" tag from the file and add the updated one from the list.

**To Reproduce**
1. Add a new tag to a file.
2. Move the tag from Collected tags to a category which has a different tag color.
3. Edit the tag group so that all tags in the group have the same color.
4. Look at the file. its tag has not changed color

**Expected behavior**
When the tag color in the group has changed all instances on files should also change.

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: 4.3.1

**Comment by Quixus** [comment]
Then issue persists in 4.4.3

**Comment by sytolk** [comment]
@Quixus in TagSpaces if you add tag from some tagGroup this will copy tag color in .ts/file_name.json and there is not dependency from which tagGroup is this color (you can move tag in another TagGroup too). 
Maybe the right fix for this issue will be additinal functionallity in TagSpaces - batch update of tags color by Tag name. After change the TagGroup color you can get the message like: "Do you want to update the colors of the used tags from this TagGroup?" @uggrock

**Comment by Quixus** [comment]
@sytolk Why was that changed? It worked in 4.2.1 (and probably in versions before that).

**Comment by sytolk** [comment]
_3. Edit the tag group so that all tags in the group have the same color._
![Screenshot_61](https://user-images.githubusercontent.com/1415463/171559426-4f57c241-d3e2-4bbf-b235-427083e44458.png)
You cant change the whole tag group color. This settings will change the default taggroup color only - for the new created tags. 
Can I have screenshot of the same TagGroup edit dialog from 4.2.1 version ?

**Comment by uggrock** [comment]
The "apply color changes to all tags on the groups" checkbox works as expected and changes the color of all tags in the group -> closing

**Comment by PaperOrb** [comment]
@uggrock still having this issue on the deb package version of  5.7.4 lite using popOS 22.04. 

Steps to reproduce: Go to tag library > click 3 dots on tag group > edit tag group > change default tag background > apply color changes to all tags in tag group > hit "OK"

**Comment by sytolk** [comment]
@PaperOrb look at my comment: https://github.com/tagspaces/tagspaces/issues/1617#issuecomment-1144443930 if you want batch update of tags color on the filesystem this is an other issue. Default tag group color is the color of the tag group only but this not change color of already placed tags on the filesystem.

**Comment by PaperOrb** [comment]
> @PaperOrb look at my comment: [#1617 (comment)](https://github.com/tagspaces/tagspaces/issues/1617#issuecomment-1144443930) if you want batch update of tags color on the filesystem this is an other issue. Default tag group color is the color of the tag group only but this not change color of already placed tags on the filesystem.

Thanks, I'll reopen #2049 as a feature request. This behavior is so bizarre though that I genuinely thought it was a bug.
