### ISSUE TITLE
Add option to disable drag'n'drop tag reordering in tag library

### ISSUE THREAD

**Issue by usernamesaredumb2** [tagspaces/tagspaces#1619]
Please add an option to disable reordering of tags within the tag library frame on the left side. Whenever (well, 90% of the time) I try to assign a tag to a file by dragging it from the tag library to the file name, the GUI starts to almost freeze and the tag swaps position with EVERY tag in the same tag group in the tag library frame on the mouse path to the main window. It's ultra-annoying and renders TagSpaces almost unusable. I want to sort the tag groups every now and then (alphabetically) and then just KEEP all tags in their position. Besides slowing the whole tagging process down, my tag order gets mixed up with every tagging step and I have to permanently reorder the tag groups.

**Comment by carstenschroeder** [comment]
Yes please. It's so annoying that the tag order is changed when I drag and drop tags on files!

**Comment by MK481** [comment]
@usernamesaredumb2 I 100% agree with you. For now I'm using this solution: 
1) Select the files you want to attach a tag to. 
2) Right-Klick the tag you want to attach. 
3) Choose 'Apply Tag'.

I find that a pretty usable workaround for the time being.
(It seems there is an option for this issue in 4.3.1, but it dosen't do anything for now?)

**Comment by uggrock** [comment]
disabling the reorder of the tags in a tag group is fixed for the next version.
