### ISSUE TITLE
TagSpaces no longer remembers perspective

### ISSUE THREAD

**Issue by usernamesaredumb2** [tagspaces/tagspaces#1621]
Up to 4.2.1, I used the list perspective per default.
As of 4.3.1, TagSpaces always defaults to grid perspective after restart.
The list setting should be remembered after restart.

**Comment by SecSimon** [comment]
I can confirm this bug on Linux, deb package, v4.3.1.

**Comment by uggrock** [comment]
in version 4.3 we split the default grid perspective into grid and list perspectives. The advantage of this decision is that now you can select for every folder the desired perspective in the properties of the folder:

![image](https://user-images.githubusercontent.com/1249777/159645253-0862c1ae-534f-4d64-a11b-2d42d95aaf71.png)

And you have separate settings for these two perspectives.

We may think about adding a setting for selecting the default perspective in the future.

**Comment by SecSimon** [comment]
Setting the default perspective requires the PRO version. 

Does that mean that I ALWAYS need to change the perspective each time I open TagSpace as long as I keep the free version?

**Comment by uggrock** [comment]
We are going to provide a way to select the default perspective in free version soon.

**Comment by jeron1** [comment]
That would be great. I've been using list perspective, so this change has resulted in extra clicking.
