### ISSUE TITLE
Key shortcut for indent not working

### ISSUE THREAD

**Issue by SecSimon** [tagspaces/tagspaces#1622]
I noticed a few month ago that some shortcuts in the HTML editor, namely Indent and Outdent, are not working anymore. Other shortcuts such as bold or underline work as expected. 

Btw: Striketrough (CTRL+SHIFT+S) additionally saves and closes the file. I would expect a strikethrough without saving and closing.

- Linux Mint, deb package
- TagSpaces Version v4.3.1, but noticed a few minor versions ago

**Comment by uggrock** [comment]
This can not be fixed because the library used for the HTML editor is not updated anymore... -> closing
