### ISSUE TITLE
Menu bar and Tray menu

### ISSUE THREAD

**Issue by Pierosparviero** [tagspaces/tagspaces#1623]
I'm learning how to use Tag Spaces following the "Getting Started" tutorial. 
First problem: I don't see either the Main Menu bar (File, Edit, View, Help), nor the little Icon that should trigger the Tray Menu.
I'm working with Windows 11 and a standalone Tagspaces.

Thank you.

**Comment by sytolk** [comment]
On Windows press the Alt key to show the Main Menu

**Comment by Pierosparviero** [comment]
Thank You.

**Comment by uggrock** [comment]
solution found -> closing this issue.
