### ISSUE TITLE
Turn off animations

### ISSUE THREAD

**Issue by Salamimonster** [tagspaces/tagspaces#1625]
I do some additional scripting for our beloved TagSpaces.
But animations like unfolding menues (e.g. when clicking on the tree dots for options at a location) are making that difficult. I have to wait, till they are fully opened.
**It would be great, if one can disable animations (by .ini or option).**

Best regards,
André

**Comment by uggrock** [comment]
This is really a huge change and we do not have currently resources for this change. 
What are you trying to automate with scripting in the app?

**Comment by Salamimonster** [comment]
> What are you trying to automate with scripting in the app?

Mainly things that stream line the usability for my needs. For example:

Press `CapsLock` to open the AddTags dialog
Press `CapsLock` while in AddTags dialog opens a calendar popup to add dates as tags for automatic resubmission
Press `CTRL+ENTER` to save added tags
Automatically confirm the delete dialog ("do you realy want to delete?")
`Keyboard` shortcuts to specific locations
`Doubble left click` to open a file externally
`F5` to refresh listings
... and so on.

I do this with autohotkey. Waiting for animations is kinda ugly, but beside that, it works quite well.
