### ISSUE TITLE
Open natively on double click

### ISSUE THREAD

**Issue by Quixus** [tagspaces/tagspaces#1627]
**Is your feature request related to a problem? Please describe.**
To open a file natively (i.e. with the application that usually opens it) you have to right click on the file and then select open natively.
The single click opening option has the issue that you likely open the file when all you want to do is select it.

**Describe the solution you'd like**
Instead of opening a file in tagspaces a double click should open it in the usual application. Preferably make this behavior optional.

**Comment by uggrock** [comment]
Thanks for this suggestion. If you just want to select a file without opening it externally, you can hold the CTRL key.

**Comment by Salamimonster** [comment]
@Quixus you are not the only one, that would prever that double click behaviour. See this issue: https://github.com/tagspaces/tagspaces/issues/1602

**Comment by uggrock** [comment]
We have experimentally added in the list perspective a handler which open the current file natively on double click.
