### ISSUE TITLE
'Last modified' date bug

### ISSUE THREAD

**Issue by MK481** [tagspaces/tagspaces#1628]
Hello Everyone,
I discovered a bug regarding the 'Last modified' information when editing an existing tag in the Tag Library (Right-Klick Tag -> Edit Tag). I'm pretty sure the displayed modification date is not shown as 'Year-Month-Day' (as I would have expected) but as 'Year-**Minute**-Day'. I attached an example screenshot of this in the appendix.

To Reproduce:
1. Create a new tag.
2. Check the 'Last modified' date of that tag (Right-Klick Tag -> Edit Tag).
I just created a tag with the current date and time information in its name. The 'Last modified' information again mixes date and time into one. A screenshot is attached.

I run Tag Spaces on a Windows 10 Pro, x64, 20H2 system as a desktop application. The problem was present in Tag Spaces Version 4.2.1 and remains present in 4.3.1.

I hope this report is new, helpful and accurate. This is my first time posting anything on GitHub. Feedback is highly welcome. (I'm not a native English speaker by the way.)
![Example](https://user-images.githubusercontent.com/102470636/160284154-1961cb11-4c0e-4f9c-a0c7-468270bfeddd.jpg)
![Reproduction](https://user-images.githubusercontent.com/102470636/160284166-dfe3b74d-5e10-439e-9eeb-24484f09691f.jpg)

**Comment by uggrock** [comment]
Thanks for reporting this. The issue is fixed for the next version. Your bug-report is perfect!
