### ISSUE TITLE
TagSpaces vs SyncThing - The problem with Square Brackets

### ISSUE THREAD

**Issue by Salamimonster** [tagspaces/tagspaces#1633]
SyncThing uses square brackets to define syncronisation [ignore patterns](https://docs.syncthing.net/users/ignoring.html#:~:text=Square%20brackets%20(%5B%5D)%20denote%20a%20character%20range%3A%20%5Ba%2Dz%5D%20matches%20any%20lower%20case%20character.).
Because TagSpaces saves tags also in square backets, there is no way to set up a synchronisation filter based on tags.

**It would be realy great, if one could choose a different separator than square brackets in TagSpaces.**

**Comment by uggrock** [comment]
I think this issue should be addressed to SyncThing, in my opinion they should provide a way to escape the [ and ] in their ignore pattern. 
Supporting alternative tag separators is not easy possible to integrate and will lead to confusion by the users who already use the brackets if they switch to the new separators (migration issues/requests...).

**Comment by Salamimonster** [comment]
> Supporting alternative tag separators is not easy possible to integrate and will lead to confusion by the users who already use the brackets if they switch to the new separators (migration issues/requests...).

If the tag separator was configurable, existig users don´t have to use an other one than the default separator = no confusion for users that are used to use square brackets.
