### ISSUE TITLE
Was folderviz perspective removed in v4.3.2

### ISSUE THREAD

**Issue by karlduderstadt** [tagspaces/tagspaces#1634]
First of all, this for making this awesome software. I just purchased a copy of the newest version and overall it is working really well. I find it very helpful for organising my files. I just have this question about a missing feature. I was really excited to try the folderviz perspective. I think this would be a great way to look globally at a small collection of files, but I can't find the option in the menus.

**Describe the bug**
The documentation says there is an experimental folderviz perspective but I can't find it in the menu.

**To Reproduce**
Check the menu.

**Expected behavior**
I expected to fine folderviz perspective because it was in the docs.

**Desktop Application:**
 - Operating System: macOS
 - TagSpaces Version 4.3.2

**Comment by uggrock** [comment]
Hi, and thanks for your feedback. Unfortunately we do not offer FolderViz perspective anymore. This was a feature in version 2 of TagSpaces, which was removed in version 3 (2-3 years ago)...
