### ISSUE TITLE
Keeps defaulting to start up

### ISSUE THREAD

**Issue by OnFormLimited** [tagspaces/tagspaces#1635]
Version 4.3.2

Started it this morning. It forgot all my settings and started up from scratch. 

Chose location and reconfigured all settings.

Keeps doing it.

Help!

**Comment by uggrock** [comment]
You can try to restart your computer and then start TagSpaces again. Such issues happens if a previous TagSpaces process was not stopped properly.

Greetings!

**Comment by OnFormLimited** [comment]
Hi

My fault entirely.

I had another desktop running with tagspaces   in.

Obviously whatever file TS uses to startup was locked by that instance.

Must remember that.

Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
