### ISSUE TITLE
Web Clipper 'Create Bookmark' option creates .txt file in Firefox

### ISSUE THREAD

**Issue by SamBuckman** [tagspaces/tagspaces#1637]
**Describe the bug**
When I try to download a .url file with the 'Create Bookmark' option, the extension .txt gets added to it automatically, which makes it more annoying to use.

**To Reproduce**
1. Go to TagSpaces extension button
2. Click on 'Create Bookmark'
3. Click on 'Save'
4. Observe downloaded file
5. See error

**Expected behavior**
For the downloaded file to have a .url extension.

**Screenshots**
![Screenshot 2022-04-15 182814](https://user-images.githubusercontent.com/67415020/163544349-a1efbe40-48c3-42b8-9200-efd65699f886.png)

![Screenshot 2022-04-15 183019](https://user-images.githubusercontent.com/67415020/163544371-681c030f-d48d-41ce-8fe2-18fc004d2f4c.png)

**Desktop Application:**
 - Operating System: Windows 10
 - Browser - Firefox (also tried Chrome, problem does not occur)
 - TagSpaces Web Clipper Version 3.1.9

**Additional context**
I'm pretty confident that this is a problem on the Firefox end and expect there's nothing you can do; but I thought it was worth making you aware of it, and that I might be wrong.

**Comment by uggrock** [comment]
Issue moved to the correct repository: https://github.com/tagspaces/browser-extensions/issues/39
