### ISSUE TITLE
Support for Todo.txt

### ISSUE THREAD

**Issue by UserThre3** [tagspaces/tagspaces#1640]
**Is your feature request related to a problem? Please describe.**

Todo.txt is a file-based task management system, with widespread support on many devices. It works well with all sort of file syncing tools. A file based task management system seems like a good match for TagSpaces.

I currently use different todo.txt managers on different platforms and would like to use it through TagSpaces and get a unified interface.

**Describe the solution you'd like**

As TagSpaces have a file editor, you already have the most basic support for Todo.txt, but it's not very well suited for actively working with the task file. 

I'd like to get a way to use todo.txt-files from within TagSpaces, either as an integral part of TagSpaces (preset file, click an interface button, show dedicated sidepanel for task managements) or on a file basis (open the todo.txt file to show task management sidepanel).

Alternatively go to low-tech way, support basic functions like syntax highlighting, sort functions, archiving completed tasks etc. like how Markor supports task management straight in a text editor.

**Describe alternatives you've considered**

I'm currently using several third party apps across platforms.

**Comment by uggrock** [comment]
Thanks for this suggestion, it a classical example of what can be done with extension in TagSpaces. So if somebody is willing to create such extension we are going to support him/her and once ready integrate the extension in the app.
