### ISSUE TITLE
Option for tags block

### ISSUE THREAD

**Issue by MauDarktable** [tagspaces/tagspaces#1641]
Dear support,
in the lasts versions of TagSpaces I noted this issue.
When I'm drag & dropping tags on photos (from left pane to right photo preview) TagSpaces changes the sort of my tags.
It's very very annoying, it forces me to constantly rearrange tags in order to find them again.
If this is a new feature I suggest to add on option that allow to block the tags sort in order to preventing the accidental drag & drop resort.
Thanks and best regards.

**Comment by uggrock** [comment]
This feature can be disabled now in the setting of the app -> closing
