### ISSUE TITLE
Version 4.3.1 does not open when launched from a Box folder

### ISSUE THREAD

**Issue by paulohuggler** [tagspaces/tagspaces#1645]
Until version 3.11.9, I used to move the tagspaces zip file (used for external drives) unzipped to a folder on Box and I executed it without problems. Since this version, all the following others do not run in this mode. I opened an issue on Dec 13 2021 about this subject (version 4.0.6), but it was closed since I did not continue the conversation. Sorry for that!

I run tagspaces from a folder from Box using Box Drive, so it is simple to run the tagspaces.cmd from the folder.

We have now version 4.3.1 and today I have done the same test - unzipped the file and tested in my workstation (running fine), used in a pen drive (running fine), and then move the folder to Box. I have updated the "tsprofile" with the actual directories and tags I use. I got the same problem - tagspaces does not run from a Box folder. I have collected some information about this issue (I did not collect for the issue on Dec - not had the idea of making some kind of trace) that I am attaching to this issue. For me, as tagspaces run from a pen drive, it could run from a Box folder where my user has read/write access, as has in the pen drive.

I changed the /B at the tagspaces.cmd to /w to keep the screen open to catch the information as a trace.

I am attaching the files:
1) tagspaces431ErrorLaunchingFromBoxFolder.jpg - cmd screen with the execution of the command to launch tagspaces and all error messages
2) tagspaces431NetstatPorts.jpg - as an error says that port 49352 was already in use, I run the netstats command to see the used ports
3) tagspaces431DirContents.jpg - the contents of the directory where an error says that it failed to open a file. All files in this folder has the date/time of the run, so it is possible to write to the Box folder.

Thanks in advance for any support
![tagspaces431DirContents](https://user-images.githubusercontent.com/32499376/167051556-d117b8a2-24ca-43bd-ac61-8966d067e0c6.jpg)
![tagspaces431NetstatPorts](https://user-images.githubusercontent.com/32499376/167051558-c5c38545-cbca-49f8-8496-0553749a6827.jpg)
![tagspaces431ErrorLaunchingFromBoxFolder](https://user-images.githubusercontent.com/32499376/167051562-21cc1a24-eefc-4f9d-8159-976ec9895e3c.jpg)
.

**Comment by uggrock** [comment]
Thanks for reporting this issue again, but we really can't do anything here. This is an electron problem which is not able to run for some reason from a Box folder. The issue has something to do with the syncing functionality of Box. Have you tried to put TagSpaces as a Zip file in the Box folder and unzip the program outside of the Box-folder on any computer you need it?

**Comment by paulohuggler** [comment]
Thanks for your reply. Yes, I have unzipped the zip file on a computer and it runs ok. The main idea was to put in Box a folder with TagSpaces to be shared with all participants in a project, allowing them to use the product to search and open the files in other folders in the project, in Box. So, we could have a very good solution to search and open the documents of the project. I planned to put TagSpaces in a Box folder to have there the tags and the map of directories available for access. 
If each participant has TagSpaces on his/her own computer, this information could not be shared and I need to distribute the files each time I add a tag or create a new directory with files in Box.

Do you know about any other cloud solution (such as Box) where Electron could run without problems? I think some previous Electron versions worked in some different manner since TagSpaces 3.11.9 still works fine in a Box folder.

Thanks for your support and diagnosis. And your attention...

**Comment by uggrock** [comment]
Our 3.x versions of TagSpaces are still available on GitHub, if you are a PRO customer I can provide you 3.11.9 as a PRO version.
