### ISSUE TITLE
.ts folders no longer marked as hidden on Windows

### ISSUE THREAD

**Issue by EliEron** [tagspaces/tagspaces#1646]
**Describe the bug**
The .ts folder created when tagging files/folders is supposed to be hidden by default, but in recent versions of Tag Spaces it is not marked with the hidden attribute.

This bug was introduced in TagSpaces version 4.1.1

**To Reproduce**
1. Tag a file/folder that has not been tagged before
2. Look at the properties of the .ts folder that was created

**Expected behavior**
The folder should be marked as hidden.

**Screenshots**
Tagging a file in 4.0.9:

https://user-images.githubusercontent.com/22575945/167240653-2f6cb05b-cc73-4ede-85e8-2ceb00d9eb1e.mp4

Tagging a file in 4.3.1:

https://user-images.githubusercontent.com/22575945/167240658-31faabfa-aa75-4f3c-bfc9-e49a5847124f.mp4

As can be seen the .ts folder is not visible after tagging a file in 4.0.9, but is visible when tagged in the most recent release.

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: 4.3.1

**Comment by uggrock** [comment]
Fixed in 4.4.1
