### ISSUE TITLE
Persist sort order of list / tag grouping

### ISSUE THREAD

**Issue by mrbiber** [tagspaces/tagspaces#165]
After closing and opening the application, the sort order of a list view is lost. It would be great if that could persist across sessions. The same holds for the groupingby tag of the grid view.

**Comment by mrbiber** [comment]
There is now a $50 bounty for this.

**Comment by mrbiber** [comment]
I just tried out the latest git and the issue does not seem to be fixed.

To reproduce either

- add a new folder with default list view
- sort by date
- close app
- reopen app
- sort order is lost

or

- add a new folder with default grid view
- group by day
- close app
- reopen app
- grouping is lost

**Comment by claell** [comment]
I am sorry to hear this. It works for me with github version and Node Webkit on Ubuntu.

But: I only added support for saving to list view. Nevertheless, the first usecase should work for you.

**Comment by mrbiber** [comment]
Yes, I did follow these exact instructions, also under Ubuntu, using the Github version.

I can verify that state persists when changing between directories. But when I close the app and re-start it, the sort order of the list-view is reset to sort by name, ascending.

**Comment by mrbiber** [comment]
Anyway, the bug should be understood to also cover the grid view. I imagine that the solution would be similar there.

**Comment by claell** [comment]
I will try a new installation as well as a Virtual PC with Ubuntu.

The solution for grid view is alot different afaik, but I can try to do it as well.

**Comment by claell** [comment]
Just tried a new installation, but it still works. I am using 64bit. Are you using 32 bit?

**Comment by mrbiber** [comment]
Sorry for the hassle. No, I am also on 64 bit. I'll try it over the weekend on a different computer, maybe it's some weird feature of my setup.

**Comment by claell** [comment]
No problem. Might be really be caused by your setup. I guess that @uggrock tested my pull request.

Regarding to the group view, found out that the grouping is switched with this function:

´´´ExtUI.prototype.switchGrouping = function(grouping) {
        this.currentGrouping = grouping;
        //TSCORE.startTime = new Date().getTime(); 
        this.reInit();
    };´´´

Unfortunately I do not know, how to store this new grouping so it can be read out and set again after a restart.

**Comment by mrbiber** [comment]
Hi, can confirm this now fixed on 10.1 (now, the previous folder isn't automatically opened on start anymore, but that's a different issue...). Thanks for your work! 

I'll open a new issue for the grid perspective. Of course, any contribution there would be immensely helpful.

**Comment by claell** [comment]
Ok, glad that it works for you now. For me the previous folder is opened automatically at start, afaik.

Will see, what I can do for grid, but maybe @uggrock will find time to help as he knows better how to do JS.
