### ISSUE TITLE
Data Loss when removing tags

### ISSUE THREAD

**Issue by sparevermicelli** [tagspaces/tagspaces#1656]
**Describe the bug**

When opening a folder containing files with the same name, distinguished only by a hash stored in brackets (example below), the hashes are turned into tags (this I understand is working as intended - related issue https://github.com/tagspaces/tagspaces/issues/683).

Example files:
file [xqa907a].txt
file [ald24aja].txt
file [sdhv7a2].txt
file [523kasjs].txt

When I delete the tags, 3 files from the example would be deleted and I would be left with a singe file.txt. No warning, no confirmation. It's even more confusing because I am using .ts to store tags. 

**To Reproduce**
1. Have files similar to example above
2. Select all files -> Right click -> Add /Remove Tags
3. Select "Clean all tags"
4. lose files....

**Expected behavior**
A warning that it would result in a data loss would be nice.
maybe - if using .ts to store tags, ignore the brackets altogether (?)

**Desktop Application:**
 - Operating System: Linux Mint
 - TagSpaces Version 4.4.3

**Comment by uggrock** [comment]
Thanks for reporting this, we will try to reproduce it.

**Comment by uggrock** [comment]
Fixed for the next release -> closing
