### ISSUE TITLE
Persist selection of tag navigator

### ISSUE THREAD

**Issue by mrbiber** [tagspaces/tagspaces#166]
When starting the application, my default folder always is displayed with the "Location Navigator" on the left. If I choose the "Tag Navigator", close and restart the application, I have to choose it again. It would be great if the choice could persist across sessions.

**Comment by binarybum** [comment]
+1

**Comment by binarybum** [comment]
Why closed?  Don't agree this is preferred behavior?

**Comment by uggrock** [comment]
I have closed this issue, because I consider it as enhancement request. We are trying to use github for bug tracking ...
