### ISSUE TITLE
The built-in text editor to seems disrupt the file format

### ISSUE THREAD

**Issue by aityan1016** [tagspaces/tagspaces#1667]
**Describe the bug**
I used the text editor of TagSpaces to edit my FASTA format,  a file type for analyzing gene or protein sequences, and its format is pretty strict. Then, the analyzing application(MEGA 11) cannot read the file which was edited with the text editor of TagSpaces. Did the text editor save the extra contents in my file?

**To Reproduce**
1. Edit my FASTA file on TagSpaces Desktop with the text editor.
2. Save the modified file.
3. Open the file which was just edited with the analyzing application(MEGA 11).
4. The analyzing application(MEGA 11) shows the error message.

If I edit the file with Windows Notepad, The analyzing application(MEGA 11) can read the file successfully.

p.s. There is the same situation when editing the file with the HTML editor.

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: Tagspaces Lite v.4.4.3

**Comment by uggrock** [comment]
Not reproducible in 5.x -> closing
