### ISSUE TITLE
Key bindings problem

### ISSUE THREAD

**Issue by mullenkamp** [tagspaces/tagspaces#167]
Hi,
I seem to have a problem with the key bindings when editing documents. When I open a document, I use the key binding to edit the file. Then if I want to do any other modification through a key binding (e.g. save or close) I must have the mouse near the top of the page and not within the editable area for the key binding to work. This kinda defeats the purpose of a key binding if you need to move the mouse to the correct position anyway. 
I'm using Ubuntu 12.04.

Thanks for all the work and support! 

P.S.: more available key binding actions would be nice too.

**Comment by waynew** [comment]
I've got the same issue - Mac OSX.

How do you install this plugin?

**Comment by uggrock** [comment]
issue should be fixed in > v3 -> closing
