### ISSUE TITLE
Image thumbnails are not being generated from latest MP4 files

### ISSUE THREAD

**Issue by OnFormLimited** [tagspaces/tagspaces#1670]
**Describe the bug**
Latest MP4 video files from new Mavic 3 Cine are not showing image thumbnails. Interestingly neither do they play in Tagspaces either. Only difference between these and other MP4  files is that they are 60fps

**To Reproduce**
1. Go to folder
2. Click on reloaddirectory
3. "Loading or generating thumbnails" stays on screen

**Expected behavior**
Expect to see thumbnail

**Desktop Application:** 
 - Operating System: Windows 11
 - TagSpaces Version 4.4.3

**Comment by uggrock** [comment]
Thanks for reporting this. TagSpaces uses Electron for playing videos and generating thumbnail. Electron is based on Chrome, so can you please try to open this specific video in a recent Chrome browser. If it does not play we can't do anything, if it plays then updating to a newer version of Electron will probably fix this issue.

**Comment by OnFormLimited** [comment]
The DJI Mavic 3 Cine MP4 files do not seem to play in Chrome. However, the DJI Pocket MP4’s do – but they also do not get generated as thumbnails within Tagspaces (perhaps because the DJI Mavic MP4 causes the issue which affects all other files in that space?)

How do I update Electron??

Regards

Steve

**Comment by uggrock** [comment]
If the current Chrome could not play the file then upgrading the version of Electron will not fix the issue. To your question, we are updating the version of Electron almost in every major release.

**Comment by uggrock** [comment]
Thumbs are generated from MP4 in the latest version 5.1. It can always happen that electron/chrome can not open a certain mp4 because of many reasons... -> closing
