### ISSUE TITLE
Linux UI Bug after you use Mapique perspective

### ISSUE THREAD

**Issue by meutrei** [tagspaces/tagspaces#1672]
**To Reproduce**
1. Go inside any folder
2. Right click and select Mapique Perspective (hard to exit for a new user)
3. Exit from Mapique Perspective 
4. Error: All icons and some text menus turn black (from white). If the user uses a dark theme, like me, everything gets complicated.
**Screenshot:**
![Screenshot from 2022-06-15 16-18-18](https://user-images.githubusercontent.com/8816415/173851085-1db05ca3-19aa-457d-9b30-84feaa15a9e7.png)

**Expected behavior**
On Dark theme all icons and text are white before you visit the menu Mapique Perspective. Icons and menu to remain white on Dark theme.

**Desktop Application:**
 - Operating System: Linux Mint 20.3 Cinnamon
 - TagSpaces Version:  tagspaces-pro-linux-amd64.deb (**PRO**)
 
**Additional context**
**Other little bugs:**
1. You are in a folder with some files.
2. Right click any file > select from menu 'Open parent folder' > Nothing happen! 
3. Right click any folder > select from menu 'Use as Thumbnail for current folder' > Thumbnail creation failed!

**2 questions:** 
1. When you click a file > Show file preview. After on right side at top if you click the "Info icon" You can add description of file, add tags, etc.
Is there an option > when you click on a file, to automatically open the Info file too (menu of the right side Info icon) at the same time with 'File Preview'? I think this is the expected behavior. In your video demo, this is what it looks like to me. Now it's crazy: click on File > Show 'File Preview' > After that you have to click on the Info icon at the top (right side) to be able to see or add your details. Not so helpful!
2. On Dark theme can I change from somewhere the Pink color? (It drives me crazy). To change Pink color to Orange or something else.

**Comment by uggrock** [comment]
The main issue can not be reproduced anymore in version 5.0.1. Regarding the second question, once you have opened the file properties they stay opened also for the next opened file.
We will provide a way to change the pink color soon...
