### ISSUE TITLE
Settings requiring restart crash and are not changed on restart

### ISSUE THREAD

**Issue by beofhelp** [tagspaces/tagspaces#1675]
**Describe the bug**
Choosing "Dark Theme" or "Use available Stock Icons" and then then selecting "OK" causes the program to close. Upon reopening the program the setting is not updated.

**To Reproduce**
1. Go to Preferences
2. Click on "Dark Theme" checkbox
3. Click on "OK" button

**Expected behavior**
If the program does exit, it should reopen in dark-mode. Otherwise hitting the "OK" button should not close the program but darkmode should be enabled after the program is restarted.

**Desktop Application:**
 - Operating System: Windows 11
 - TagSpaces Version 1.1.1+dev

**Additional context**
This is on the portable version of the program.

**Comment by uggrock** [comment]
Could not be reproduced.
