### ISSUE TITLE
Feature request: Import from Evernote

### ISSUE THREAD

**Issue by biocyberman** [tagspaces/tagspaces#168]
I am very excited to find out TagSpaces. As a Evernote premium user, I am looking for a way to import all of my Evernote contents to TagSpaces. I will spend my Evernote subscription for TagSpaces if I can make smooth transition to TagSpaces. As far as I understand, this is just a matter of exporting Evernote to HTML and store them in a TagSpace location. But if there is a better way, I would like to know. 

Thank you.

**Comment by uggrock** [comment]
I wrote an article on the TagSpaces blog describing a way to export content from your Evernote. http://www.tagspaces.org/export-your-evernote-as-local-files/

**Comment by uggrock** [comment]
A dedicated Evernote import will be probably not offered soon in TagSpaces.

**Comment by wiwwo** [comment]
Hi there!
Months ago, Evernote changed it's free subscription plan, and i'm pretty p#@d off.
Luckily, Evernote guys developed ENEX file format, and it is 1) pretty simple yet powerful, 2) open source
https://blog.evernote.com/tech/2013/08/08/evernote-export-format-enex/
( google cache backup if EN guys read this post and delete the original article https://webcache.googleusercontent.com/search?q=cache:u6u950lXC7YJ:https://blog.evernote.com/tech/2013/08/08/evernote-export-format-enex/+&cd=1&hl=en&ct=clnk ).
I won't mind paying for tagSpace extra feature of importing this -again- easy and open ENEX file format...
Sure you don't want to reconsider this request and re-open it? :-)
