### ISSUE TITLE
Image wasn't created for some files

### ISSUE THREAD

**Issue by seal0818** [tagspaces/tagspaces#1680]
Description.
For some video files thumbnails didn't created.
Also this video when i try to play doesn't contains any image but audio is presented.

Reproducing with some video files.
File extension - mp4
4k resolution. File size more than 6gb. But for some of them it's work fine.
Folder contains more than 10 files with size from 4-12 gb with mp4 type.

Desktop Application:
 - Operating System: Windows 10
 - TagSpaces Version 4.4.3 common version. using only local pc

Some context:
1 - when moving problem file at clear folder - issue still reproduced
2 - when played only audio presented
3 - function generateVideoThumbnail has right fileURL, but video.onseeked and video.onloadedmetadata never called
4 - at generateThumbnailPromise dataURL didn't contains image date so i get "Invalid dataURL"
5 - file name and folder path not contains any special symbols. only numbers, "-" and english letters with different letter case. example "0 - Some text"
6 - sometimes it happend with not 4k resolution files
7 - found only one difference between files - fps. via file properties for files that works fine it's equals 59.9, for issued files it's equals 60
8 - when checking folder via windows explorer - images presented for all files. All of them works fine via classic player
9 - rename file not working

**Comment by uggrock** [comment]
The generation of the thumbnails for mp4 depends on the underlying Electron/Chromium framework. There is not much what we can do here beside updating from time to time the Electron framework, which we have done in October for version 5.0.
