### ISSUE TITLE
Selecting reorders file entries in list view

### ISSUE THREAD

**Issue by SonephetR2** [tagspaces/tagspaces#1694]
**Describe the bug**
In 'List Perspective' (but not 'Grid Perspective'), the list of files is fully reordered (re-randomised) when selecting any file, which means you have to scroll down to find the file you just clicked on. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Set view to 'List Perspective'
2. Set sorting method to 'Random'
3. Click on any file in the list on display in the main panel

**Expected behaviour**
When clicking on a file name, I am expecting everything to stay put, and not have any rerendering/randomisation until I navigate to another folder.

**Desktop Application:**
 - Operating System: Linux Mint 20.3 Cinnamon
 - TagSpaces v4.5.2

**Additional context**
This possibly ties in with issue #862.

**Comment by rlach** [comment]
Starting with v5.2.2 pro it happens also in Grid Perspective. Doing anything in Grid Perspective when set to random will reorder the items:
* left clicking on any item
* right clicking on any item
* right clicking anywhere else
* resizing the tagspaces window

This used to work properly in Grid Perspective up until 5.0.x versions at the very least.

I've skipped some versions so this bug might have been introduced in earlier version between 5.0.x and 5.2.2. I don't remember exactly which I had before update.

**Comment by tagspaces-amp** [comment]
Fix will be provided in the upcoming 5.2.3 release.

**Comment by uggrock** [comment]
5.2.3 released -> closing
