### ISSUE TITLE
Add the option to deactivate side-pane preview in settings

### ISSUE THREAD

**Issue by SonephetR2** [tagspaces/tagspaces#1695]
TagSpaces tends to freeze or slow down when selecting heavy files such as videos. There tends to be a noticeable lag even for smaller files, as the program loads PDF files for instance, whatever their size.

Being able to deactivate previews would probably make for a much more seamless experience. Settings could allow users to deactivate previews based on file size ("Only for files smaller than […] MB" – leaving it up to the users to enter their preferred value), all previews, or perhaps even based on both file size and type.

**Comment by skaldarnar** [comment]
I'm trying to organize STL files with TagSpaces and it regularly crashes when working with models over 100MB. 

Would be great to be able to disable the preview either for specific file types, depending on the file size or altogether.

**Comment by sytolk** [comment]
@skaldarnar can you try to set in Settings for STL file extension TextEditor or delete this file type 

![7E56543D-783E-4A73-82F9-99F78730BBCA](https://github.com/tagspaces/tagspaces/assets/1415463/8895bc7b-89ef-4611-be27-667de210dddc)

To disable preview for STL file type it's possible to add to the list of viewers void option that will not try to open STL file type. If this works for you?
