### ISSUE TITLE
Bug:  video files not playing from the search page 

### ISSUE THREAD

**Issue by Netmedia1** [tagspaces/tagspaces#1699]
**Describe the bug**
 Video files are not  playing from a search  results page

**To reproduces**
1. Search for files. 
2. Click on any found video file 
3. Video player gets opened but  the video is not  playing 

- Android 9 on Samsung Galaxy S8
 - TagSpaces Version 4.4.3

**Comment by aisbergde** [comment]
same issue on all my android devices (smartphones, tablets, different Android versions)

**Comment by uggrock** [comment]
This is fixed in version 5.0.x of the application.
