### ISSUE TITLE
Yarn instructions outdated, code will not run

### ISSUE THREAD

**Issue by makingglitches** [tagspaces/tagspaces#1710]
It looks like the development team updated the build engine because of module incompatibilities with yarn
The instructions to bootstrap and run the code are out of date.

**Comment by sytolk** [comment]
Yes we migrate from yarn to npm in the resent version of tagspaces. Documentation needs to be [changed](https://github.com/tagspaces/tagspaces#how-to-run-tagspaces-from-the-source-code)

**Comment by uggrock** [comment]
Documentation is update for using npm instead of yarn.
