### ISSUE TITLE
How do I migrate the tags including colours from an old machine to a new machine

### ISSUE THREAD

**Issue by Dude77777** [tagspaces/tagspaces#1715]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dude77777** [comment]
As above - how would I go about that?

**Comment by uggrock** [comment]
Please refer to our documentation, regarding how to export and import tags and tags groups:
https://docs.tagspaces.org/tutorials/sharing-tags#exporting-the-existing-tag-groups
