### ISSUE TITLE
Hide files by extension or regex

### ISSUE THREAD

**Issue by rlach** [tagspaces/tagspaces#1716]
**Is your feature request related to a problem? Please describe.**
For most of the files I work with using tagspaces the related software creates additional 3 files with the same name, but different extension. This leads to the folder view being flooded with files I don't need to see. This makes the application less and less useful as I use it.

**Describe the solution you'd like**
In settings allow configuring extensions to always filter out of view. If I put `.bak` filter out all files with this extension.
Alternatively allow to configure regexes that I want filtered out, in that case `.*\.bak` would filter out files like this. I think both method at once would be the best option, since less technical users could just define extensions, while advanced users could define regexes, which would allow them to hide more than just extensions.

There should be a new checkmark near the top of the folder view to show hidden files, as I think some users might want to see those files from time to time.

**Describe alternatives you've considered**
Alternatively I thought the UI could automatically "merge" files with exact same filename, but different extension and show them as one item on the grid. This should be a per-folder option then, or at the very least it shouldn't be default behavior. When clicking on the "merged" files you could have tagspaces expand it, to show all files inside, and then user could click on one of the files. The user could also configure that clicking on "merged files" instead asks which of the files to open, and you can set it to automatically open the extension you want if it exist in the "merge". When renaming/tagging the "merge" all the files in the "merge" should be renamed in sync.

The problem with this solution is it would require a lot of UI and UX work to have it be right, and it would probably be niche. So the effort seems not worth it. If done bad it could be confusing for the users, and as such the filtering option could be better.

**Additional context**

**Comment by uggrock** [comment]
We have a functionality in the upcoming 5.0 version, where you will be able to define ignore list with wildcard for every location. -> closing
