### ISSUE TITLE
"The desired path could not be opened" using external storage

### ISSUE THREAD

**Issue by francis-io** [tagspaces/tagspaces#172]
Hello,

When trying to browse to a location I'm getting the error "The desired path could not be opened". The only common thing I can see is it resides on external storage. Internal storage seems to be fine. I can see the external location using a file browser without issue.

Ver 1.9.0

**Comment by scubamut** [comment]
I have the same problem using the chrome extension when I "launch application"

**Comment by rancidfrog** [comment]
Similar to #440 ?
Using default file picker and having correct permissions seem to work for other apps

**Comment by uggrock** [comment]
Duplicate to #440
