### ISSUE TITLE
 search time

### ISSUE THREAD

**Issue by HDInfautre** [tagspaces/tagspaces#1722]
Hi 
/*for about 2 months, I wrote by mail to ilian@ ideas@ ...
I didn't get any answer. I copy/paste my questions and suggestions now */

I now use tagspace from time to time to search for information. I search for a word in the content because it is the easiest. I find the time very long. As for the web, less than 4 s would be bearable but I have the impression that it does not advance and I stop. Even if I search by clicking in the location manager "show files with this tag" it is also long and does not work.
I am running ubuntu 22.04 and tagspace pro 4.4.3. The data is on an external hard drive, but I don't have problems with any other application.
I have maybe a hundred articles (html format) but not thousands!
So tagspace is not used to manage my content:
2022
- event A
-- photo1, photo2 ...
I would find it relevant to put a link in this html article of this directory with either a visualization or a switch in parallel? 
Regards

**Comment by HDInfautre** [comment]
Hello
After several months, I come back because I bought a much more powerful computer.
The search time is very long unless you are looking for a tag in the current location.
I am on ubuntu 22.10 with the latest version of tafgspaces
I never search globally. 

There are not that many updates in my documents. Would it be possible to have a faster search, perhaps by storing an index in a database?

In any case, it limits enormously the use of your software (even if the rest is interesting).
I hope you can find a solution soon.
regards

**Comment by HDInfautre** [comment]
HI
Would you be so kind as to answer me.
It was the case before by email, but now I've been waiting for months and it's a big worry for me and I have to make decisions. 
Is it just a problem with Ubuntu?
How can I make the search as good as some searches on linux file managers?
I don't know if this helps with:
https://github.com/cboxdoerfer/fsearch
https://apps.kde.org/fr/kfind/
https://github.com/DoTheEvo/ANGRYsearch
https://docfetcher.sourceforge.net/fr/index.html

**Comment by uggrock** [comment]
Hi,
have you tried to create the index for the location with our command line tool? How big is your index actually after the indexing the hundred html files? 
This is the documentation for the command line tool: https://docs.tagspaces.org/dev/command-line-tools
Greetings

**Comment by HDInfautre** [comment]
Hello
Thank you for your reply. 

To answer you
1/ Can you tell me how to find the size of the index?
2/ I couldn't install the recommended command line mode. Do you have another tutorial or program for Ubuntu 22.10?

In relation to my message, I have upgraded to v5.2 appimage (note that it is a portable version!).  
I also put images on my latest setup.

I see an improvement on some queries, but not on my most common needs. I am sending an image to make myself clearer.

I abandon the idea of searching all the files on my entire data disk!

I concentrate on searching the notes I have taken with tagspaces.
For example, I search in the [Informat. Com.] directory, which has a few sub-folders with my HTML note files.
In another directory [HD] there may be an extra sub-folder and a few more HTML files in the last child directory (but nothing extraordinary!)

My searches are basically 1 tag and/or a keyword in the title. If I have to give up a rough search or a search in the content, I'm willing to give it up to continue testing your application.
I often wait more than 30s to 40s, sometimes even blocking the application :-(

3/ Can you tell me how to improve the search in the expected time order of one to two seconds?

Regards

![Capture d’écran du 2023-02-17 16-35-43](https://user-images.githubusercontent.com/6817936/219702093-2df97779-1eba-4179-833e-dbc31823cf1c.png)
![Capture d’écran du 2023-02-17 16-52-04](https://user-images.githubusercontent.com/6817936/219702103-b84296a2-1f68-4b50-8727-42c016a086d9.png)
![Capture d’écran du 2023-02-17 16-52-09](https://user-images.githubusercontent.com/6817936/219702107-c8b0ca4d-1a79-4683-a141-2ca0330e6a93.png)
![Capture d’écran du 2023-02-17 16-52-47](https://user-images.githubusercontent.com/6817936/219702118-86f4a953-c9f3-4688-9d09-f19251f0a2fe.png)
![Capture d’écran du 2023-02-17 16-56-04](https://user-images.githubusercontent.com/6817936/219702493-529d5b97-80c6-4da2-97b0-47e253246aee.png)

**Comment by HDInfautre** [comment]
Hello
I still can't use this application that I'm attracted to, since I bought it.
I think I have given enough information for you to be able to reproduce the problem and give me the beginning of an answer or solution :-)
Thank you, I need your support

**Comment by sytolk** [comment]
@HDInfautre you can create new Location with your `Informat. Com.` directory path and look at `./Informat. Com./.ts/tsi.json` file - this file will be created  after first search in this location. You can attach here tsi.json file for debugging.

**Comment by HDInfautre** [comment]
HI @sytolk 
Thank you for your reply.
I am not sure I understood and made the suggestion correctly.
I have created a new location, but I can't find a json file. See images
Is there another way to send a debug file after a search?
![Capture d’écran du 2023-03-01 10-26-43](https://user-images.githubusercontent.com/6817936/222099444-57270388-29a1-4cb5-96e0-933ecd2bc7a4.png)
![Capture d’écran du 2023-03-01 10-27-40](https://user-images.githubusercontent.com/6817936/222099454-7d743371-fc58-4006-a382-879788756c86.png)

**Comment by sytolk** [comment]
![6F447528-B0BB-4C60-A62C-2EF6B5438BC9](https://user-images.githubusercontent.com/1415463/222104900-b0090bda-7aa7-4f36-a3cd-c8a99453dc9e.png)
`.ts` folder is hidden to view it content its need to enable show hidden files option in Tagspaces General Settings

**Comment by HDInfautre** [comment]
Well, I'm not sure we understood each other.
Under ubuntu, I have already activated the visibility of hidden files.
The problem is after your request was created, where it was created in a strange and inaccessible place.
I still send you my json file to the base of my notes even though the creation is older.
[tsi (copie).json.TXT](https://github.com/tagspaces/tagspaces/files/10859661/tsi.copie.json.TXT)

**Comment by sytolk** [comment]
If you create new Location from subfolder like `/home/user/Documents/Informat. Com.` you tsi.json in this location will be smaller that the root Location `/home/user/Documents`. But this `tsi.json` is 400Kb only. What is the Location path to this tsi.json ? and are you sure that you have performance issues with search in this Location?

**Comment by HDInfautre** [comment]
Hi 
Yes it is small, because I have taken into account a location only with my notes tagspaces and not other files in my data.
See the location on the image.
Yes, it's way too long for normal use.
You don't say anything about my configuration. I have to assume it is correct!
On your side, have you tested on my environment. It is possible that it comes from my use in appImage with the recommendation to make it a portable application on my ubuntu 22.10.

![Capture d’écran du 2023-03-01 12-23-38](https://user-images.githubusercontent.com/6817936/222126032-521aee92-3f88-4d7b-ac6f-c74c4b5c6291.png)

**Comment by uggrock** [comment]
We are developing TagSpaces also on Ubuntu and there are no issues with the appimages. Have you tried the .deb version, just to be sure the problem is not depending on the portable version? 
@sytolk Maybe the dots in the location path are causing the issue? Can you try to test with such path?

**Comment by HDInfautre** [comment]
Hi again
Searching with the deb version works well :-)
Searching ~ 1s instead of over a minute on the portable appImage version.
(I tried the latest appImage version (the one I told you about was 5.2.4) and I get an EOF error message when I run the search. I don't have time to test this anymore because I've already lost a lot of time.

I hope you will find a solution for the portable version of appImage.
I hope you can find a solution for the portable version of appImage, because as I mentioned, I have the impression that other portable applications work with an appImage.config folder instead. 

I'm glad it's working better (I'm waiting to retest everything); I'm still disappointed that I haven't been taken seriously in the last year :-(

**Comment by tagspaces-amp** [comment]
the PRO version of 5.3.2 was released today and should be available from your links.

**Comment by HDInfautre** [comment]
hello
It's been several times that I try to install the new deb version on the old one.
I clicked on Download tagspaces-pro-linux-amd64.deb (90.16MB) then I opened tagspaces-pro-linux-amd64.deb with the ubuntu application installer

1/ When I run it, I still have the old version, even if strangely I can't find my locations that I had before on the right side :-(!
Please help me to solve this problem?

2/ Can you also tell me if you have solved the problem with the appImage version that I prefer with the portable side of my removable disk

![Capture d’écran du 2023-04-13 23-34-05](https://user-images.githubusercontent.com/6817936/231888837-0870d001-e17f-4660-b0b8-af571e67d603.png)
![Capture d’écran du 2023-04-13 23-35-19](https://user-images.githubusercontent.com/6817936/231888841-8f753e61-e306-4a34-b94c-9ace2e31027a.png)

**Comment by sytolk** [comment]
what is the output of `which tagspaces` in console?

**Comment by HDInfautre** [comment]
Hi
`~$ which tagspaces
/usr/bin/tagspaces
`

**Comment by uggrock** [comment]
The installed app have a different place for storing the location data from the portable version. Maybe this is the reason why you are not seeing your locations. 
Have you tried to install the deb-version of the application with the dpkg -i tagspaces....deb command?

**Comment by HDInfautre** [comment]
HI

I stopped using appimage when I saw the search time! 
(did you improve the search function on appimage? because in the long run, this is what I want to use)

The currently installed version must be in .deb (although I can't see the location)
Usually, I download the .deb file then I right click to use the application installer. 

It seems to be ok (see screen)
![Capture d’écran du 2023-04-17 13-40-26](https://user-images.githubusercontent.com/6817936/232474811-45f5a1cd-9863-4e7e-9787-50fc15992f7c.png)
[I tried without success 
dpkg -i tagspaces-pro-linux-amd64.deb
dpkg: erreur: l'opération demandée requiert les privilèges du superutilisateur
]
When I open tagspace, it's not the right one
![Capture d’écran du 2023-04-17 13-40-26](https://user-images.githubusercontent.com/6817936/232474937-672ab68a-8e98-4763-8b40-4f0565588280.png)

Regards

**Comment by uggrock** [comment]
Please call the dpkg with sudo in front. There is no difference between the appimage and deb releases, beside the fact that appimage can be started without installation. For the portable mode you can start the app with the -p parameter. This will create a tsprofile folder in the folder where you have started the app, not where it is located. The tsprofile folder contains the location data your tag library and other settings.

**Comment by HDInfautre** [comment]
Thank you for your quick answer. Indeed it worked :-) (strange I don't remember the failure with the Ubuntu application installer)
Ok I'll try again with the appImage, but again, it's strange, because I saw a clear difference!

What you tell me "For the portable mode you can start the app with the -p parameter" seems very interesting if it has the same advantages of creating a portable version, by not storing anything on the machine in other Linux directories!

So I wonder about the advantages/disadvantages compared to the 
appImage version. If you have a detail, tutorial, I will be very interested

regards

**Comment by HDInfautre** [comment]
Hello
I really see a difference in search time with appimage :(
I couldn't launch in portable mode.
Can you tell me the more precise command? or the configuration point?

`tagspaces-pro-linux-x86_64 -p`

**Comment by tagspaces-amp** [comment]
You have use the zip or tar.gz package, unzip it and run the tagspaces(.exe) with -p parameter.

**Comment by HDInfautre** [comment]
Hi
Uh a little above I said I did:
dpkg -i tagspaces-pro-linux-amd64.deb 
It's a ".deb" executable for Linux, I'm not on windows.
Can you tell me more precisely what I have to do to have a portable version? or to make appimage work well?
Thanks

**Comment by uggrock** [comment]
After installing the with dpkg command, the tagspaces executable will be available from your terminal. So you have to navigate to the folder (e.g. usb stick) where you want to have the configuration for the portable tagspaces. Now you can start the app with tagspaces -p . That's all, the app will create a tsprofile folder in the current folder, which contains all the configuration for the portable instance.
