### ISSUE TITLE
links

### ISSUE THREAD

**Issue by HDInfautre** [tagspaces/tagspaces#1723]
Hi
2/ a link between note and photo directory
I make a note about a hike. I took pictures that are physically in a subdirectory of my pictures
2b/ link to a note
In a similar way, allow a link between notes of different categories, preferably symmetrically?

**Comment by uggrock** [comment]
It is already possible to create links in the description of files and folders to other files, folders or locations, using the so called link for internal sharing available in the properties of every file and folder. Links can be places also in the content of regular markdown files. 

![image](https://user-images.githubusercontent.com/1249777/194714189-f68ca2e0-739c-45bc-be6d-ffb4a0f9c30d.png)
