### ISSUE TITLE
subfolders

### ISSUE THREAD

**Issue by HDInfautre** [tagspaces/tagspaces#1724]
Hi,
 in the location manager, have the possibility to see the subfolders in 1 click (with arrow ">", "v") like we see in the file manager (especially the one with the ">" arrow)

**Comment by sytolk** [comment]
You can try to click on Location Icon:
![F36E550F-FB0E-48E9-BB34-34E7A9750FFC](https://user-images.githubusercontent.com/1415463/189900936-380baf6a-47dd-40c4-8a2c-ede4e1f25918.png)

**Comment by uggrock** [comment]
Closing, since this is already implemented.
