### ISSUE TITLE
Android app: cannot open file natively from search results

### ISSUE THREAD

**Issue by ceperman** [tagspaces/tagspaces#1731]
Description:
I use settings to set "single click opens file natively". This works fine in a normal file list. However, if you tap on a file in the result list from tag search, nothing happens. You can't open it from the context menu either, in fact you can't open the file at all from the context menu.

1. Select setting "Single click opens file natively"
2. Switch off "Show warning on opening files externally"
3. Tap a tag and choose "Show files with this Tag"
4. Tap one of the files in the resulting list
5. Nothing happens

If you don't switch off "Show warning on opening files externally" then the warning message is displayed but the file still does not open.

Expected behavior
The file should open using a native app. In the desktop version (Linux Mint) it works fine.

Environment
Issue occurs in both Android 7 & 11.

**Comment by aisbergde** [comment]
same issue here. In the normal file list I can open file (see the content or edit)
When any filter is applied, nothing can be done. If the preview opens, then it is empty.

**Comment by aisbergde** [comment]
in the not filtered list I can only open the internal viewer and editor. Nothing happens, when I try in a file explorer (open in file manager), and I can't "open the file natively": I get some apps to select from, there is also a more, but when I press there, I don't get a selection of more apps, but some app openes randomly(?)

BTW, it is very unintuitive to select or unselect files, if the default option for a "one tap" is to open the file. I did not yet found a way to unselect files. And files will be also selected, when tapping them.

So it is more intuitive to use the option "Single click only selects the file". But then the default for a double tap is to open the file external. There should be a way to configure the default for double tap to open in the preview.

It looks like the app is developed for the desktop and not so good adapted for mobile usage. This makes it unintuitive to start to use the app.

**Comment by uggrock** [comment]
Hi @sytolk , can you please take a look on this.

**Comment by contributor** [comment]
Still cannot open natively in 8 days ago release v5.0.6 (Nov, 16)

**Comment by sytolk** [comment]
Sorry but cannot repeat this issue with v5.0.6 for Android. 
![viber_image_2022-11-24_14-31-04-488](https://user-images.githubusercontent.com/1415463/203785456-3deee741-e871-4d47-b884-5532254eecab.jpg)
Can I have screenshot from your device?

**Comment by ceperman** [comment]
Same for me, still does not open natively in 5.0.6 from results list.

**Comment by sytolk** [comment]
@ceperman "Same" means that you have the same Confirm dialog and if you click OK next you dont have native app associated to open the file with selected extension? Or maybe if you click on the search results there is no Confirm dialog and file is open internally in tagspaces - there is settings for this case.

**Comment by ceperman** [comment]
I mean that the problem remains as in my original problem report. The file opens correctly in the unfiltered view but not in the filtered list.

**Comment by sytolk** [comment]
@ceperman interesting The problem with filtered result was the path to the file like `/sdcard/Download/Canon_70D.jpg` from the screenshot.  Can you give me you path to file from search results? (maybe it's have extra dir separators?). And can you try to remove tsi.json located in .ts folder of the searchable location maybe it's contain index data from previous tagspaces version

**Comment by ceperman** [comment]
Path for unfiltered: "/sdcard/Recipes/beef stroganov.odt" - works
Path for filtered: "/sdcard/Recipes/s/beef stroganov.odt" - does not work

Removed tsi.json - no effect

Hope this helps.

**Comment by sytolk** [comment]
`/sdcard/Recipes/s/beef stroganov.odt` The question is where is comming `/s` after Recipes -> maybe you have special characters in Recipes ?

**Comment by ceperman** [comment]
`/s` only appears in the filtered path so I assume it is generated by the filtering mechanism - it's nothing to do with me. And there are no special characters in the file name. The file name cannot a problem _per se_ because the file opens just fine in the unfiltered view.

I looked into the file system while the filtered view was active, and there is no folder /sdcard/Recipes/s/ so not surprising that the file does not open. The only sub-folder is the `.ts` folder - perhaps it is trying to refer to this (although it does not contain the file `beef stroganov.odt`).

**Comment by contributor** [comment]
>Can I have screenshot from your device?
@sytolk Here is the screenshot, you can also see file path on it:
![image](https://user-images.githubusercontent.com/598873/204161372-255c3525-6df8-4fe2-a1bb-e9eb2ed700ca.png)

More details:
- the same file opens ok from browse mode
- the file doesn't open from search mode. If open confirmation is off in settings - it just ticks the checkbox. If open confirmation is on - it shows confirmation, but after tapping ok, it again - just tick the checkbox and that's it.

My settings are: single click opens file externally

**Comment by sytolk** [comment]
Very strange.. I will try to repeat this issue. Thanks for the screenshot!

**Comment by sytolk** [comment]
This issue happened with new added location from "Connect a location" dialog
