### ISSUE TITLE
Problem using tag to Autocad file about changing the filename

### ISSUE THREAD

**Issue by fansaihong** [tagspaces/tagspaces#175]
Dear All, 
Thank you for inventing this software.
I like this file manage system very much.

but I have some problems as below:

Q1
I am a Autocad file (.dwg) user. I have many link between the file, for example, in A.dwg file will have some xref files B.dwg, C.dwg inside A.dwg. but this tagspaces system is changing the filename for the tag, so every time after i make some tags on B.dwg and C.dwg, when i open A.dwg, I need to relocate the xref B.dwg and C.dwg.

I have many autocad files. if I use this tagspaces system to manage the files, then I will need to go inside every file to relocate the xref location. would you have some way to solve this problems? 
thank you very much.

Just for some ideas, instead of changing the filename, could we create a hidden-file(table) in every folder. and this table record all the file information including the tag in this folder. and every time just to go to check/revise/store that table for database?

Q2
when I try to tag some files, could the system auto put up some hints tag (which I have create before) when I just type a character. for example, I have create tags: [tree] [timber] [wood] [top]. so, want I type t, then the system will auto Appear [tree], [timber], [top] for me to choose? just like the evernote did. Or should I have some better way to do that?

Thank you very much for your effort to doing so.
best regards,
Hong

**Comment by uggrock** [comment]
The PRO version of TS will support adding tags to sidecar files, which will solve your issue.
