### ISSUE TITLE
Target Path for Move or Copy File does not update

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#176]
Not sure how to reproduce, but sometimes the Target path field stops responding to navigation through the folder icon next to it.  The folder location can be selected but the target path field simply fails to update.  The target path can still be entered manually.  Rebooting the program resolves this temporarily.  
  This is on Win8.1 Pro 64bit. v.1.9.0.

Thanks.

**Comment by binarybum** [comment]
Looks like this occurs whenever attempting to move a file to the same directory as the file before it.  The selected directory stays selected in the folder dialog box but selecting it does not update the target path field - this is reproducible.

**Comment by uggrock** [comment]
fixed for the next release
