### ISSUE TITLE
Thumbnail Display Often Fails

### ISSUE THREAD

**Issue by ArsVendy** [tagspaces/tagspaces#1769]
Thumbnail displays often fail on my Windows 11 installation. I am a free tier user on version 5.0.4. This has been replicated on both network hosted and locally hosted files, deleting the .ts sidecar folder and letting the thumbnails regenerate does not seem to impact the issue. Folders will sometimes appear normal with the expected thumbnails, but upon other program launches the thumbnails will break.

**Comment by sytolk** [comment]
Hi, what you mean _"but upon other program launches the thumbnails will break."_ 
You have two instances of tagspaces? Can you provide the steps to repeat this issue?

**Comment by ArsVendy** [comment]
Apologies, I was looking at the documentation space here when I submitted this issue so I didn't see the full issues list. It looks like others are seeing the same problem going back to the 4.x versions - issues 1736, 1670 look similar, and there was at least one more that I browsed to but cannot locate. I will check through the similar ones for any steps that might help.

**Comment by ArsVendy** [comment]
This is actually two issues in one, after some reading and checking. Issue #1702 is replicated on my system running 5.0.3 on Windows 11 - files that do successfully generate thumbnails stop displaying them when a sidecar JSON file is added.

The second issue looks to be files with special characters have issues with thumbnails being generated/displayed - I had several in my test directory with a "#" in the filename, removing them allowed the functionality to work as normal. Until I tagged the file, of course.

Thanks for your time and attention on this! Looking forward to a solution, this bug is holding me back from going PRO.
