### ISSUE TITLE
delete files issues: multiple delete, delete without confirm for delete file

### ISSUE THREAD

**Issue by vatslav** [tagspaces/tagspaces#177]
Add a button to delete selected files
Add to configure or request field allows you to operate without checking

**Comment by uggrock** [comment]
Your first point will be probably implemented soon.
The second one is a little dangerous ....

**Comment by lezzlee** [comment]
also please delete to the Recycle Bin on Windows if not set otherwise, thanks
(additional option from the referenced #203)

**Comment by uggrock** [comment]
Deletion of many files is already implemented.
Deletion to recylce bin is implemented in PRO version, which will be released soon.
