### ISSUE TITLE
Feature Request: Support for Previewing .wmv Files

### ISSUE THREAD

**Issue by joshuactk** [tagspaces/tagspaces#1775]
**Is your feature request related to a problem? Please describe.**

Previewing .wmv files in Tagspaces results in this output:
![image](https://user-images.githubusercontent.com/6805544/199223425-d0b5b373-33e2-4dfb-a633-6d0cfa081b40.png)

**Describe the solution you'd like**
Ideally, previewing .wmv files will result in video playback like how it works with .mp4 now.

**Additional context**
Enabling previews of .wmv files will help video file management.

**Comment by uggrock** [comment]
For playing media files, TagSpaces uses the underlying Electron/Chromium infrastructure. So if you can play a given file format in Chrome there is a good a chance that it will work in TagSpaces. Files in WMV format are currently unfortunately not playable in the Chrome browser.
