### ISSUE TITLE
hotkey ctrl+1,ctrl+2 does not work

### ISSUE THREAD

**Issue by ZeChengME** [tagspaces/tagspaces#1777]
![image](https://user-images.githubusercontent.com/74135001/199530986-241be79a-6767-41d5-bc1a-c17892e0d1f3.png)

revision TagSpaces Lite v5.05
Sorry I mean ctrl+1 ctrl+3 does not work. ctrl+2 works fine.

**Comment by uggrock** [comment]
Thanks for reporting this, it will be fixed for the next major release.
