### ISSUE TITLE
Filerename after tagging

### ISSUE THREAD

**Issue by jochenhalwachs** [tagspaces/tagspaces#178]
I think that could be only a bug (especially if using scripts inside the documentation). Better way to do this is to use some exif tags for tags.

Files are renamed to filename[tag,......].extension

Lg, Jochen

**Comment by uggrock** [comment]
This is one of the core ideas behind TagSpaces. The only way to achieve a cross platform and cross document tagging for now is by saving the tags in the file name. Take a look on the comment from fsiefken on  Hacker news https://news.ycombinator.com/item?id=8739045 .
EXIF is mainly supported in JPGs...
