### ISSUE TITLE
Can not Preview Tga File 

### ISSUE THREAD

**Issue by xplpsj** [tagspaces/tagspaces#1785]
Can not Preview Tga File  now

**Comment by uggrock** [comment]
yes, tga files are not supported in TagSpaces.
If somebody decides to implement such feature this library can be used: https://github.com/schmittl/tgajs
The right place for the implementation would be here: https://github.com/tagspaces/tagspaces-extensions/blob/main/image-viewer/main.js

**Comment by uggrock** [comment]
Previewing TGA files will be possible in version 5.2 of TagSpaces.

**Comment by xplpsj** [comment]
Now in the 5.2 I can see the TGA files in Preview but the thumbnail can not show yet.
&nbsp;


追风の光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tagspaces/tagspaces] Can not Preview Tga File  (Issue #1785)





 
Previewing TGA files will be possible in version 5.2 of TagSpaces.

**Comment by tagspaces-amp** [comment]
The generation of thumbnails for TGA files is part of the PRO version.
