### ISSUE TITLE
Folder rename from inside a folder, results in stale name in Location Manager

### ISSUE THREAD

**Issue by ZebulonGlitch** [tagspaces/tagspaces#1788]
**Describe the bug**
Folder rename by clicking the folder name in the main window from inside a folder, results in stale name in side bar heirarchy.  The folder name is not updated on the left, a hook is missing.  Clicking the stale name, predictably results in a grumpy message.

**To Reproduce**
 Go into a folder, and click the folder name to edit it. Left foler list won't update.

**Expected behavior**
Renaming folders renames them

**Screenshots**
n/a 

**Desktop Application:**
TagSpaces v5.0.5 from appimage
Linux Mint latest (Vanessa21 < Ubuntu Jammy) with Mate Desktop, fully up to date with Linux kernel 5.15.0-xx

**Additional context**
n/a

**Comment by ZebulonGlitch** [comment]
Clarified location of stale folder name in subject.

**Comment by uggrock** [comment]
This issue could be solved only partially, because the folder of the location can be renamed also outside of the app.
