### ISSUE TITLE
Bug: White screen crash / hang if canceling a tag edit with escape key

### ISSUE THREAD

**Issue by ZebulonGlitch** [tagspaces/tagspaces#1790]
**Describe the bug**
A white screen of doom if you press the escape key in the wrong place.

**To Reproduce**
Click a file. Click a tag and select edit. Change your mind and hit the escape key to exit.  Entire app window goes white and unresponsive. Only way to recover is restarting the app.  NOTE:  Clicking "cancel" works fine, app keeps working.  

**Expected behavior**
Escape should not crash the app.  Something in this release is really messed up with keybindings under Linux. There are quite a few open bugs related to keyboard input, Arrow keys are also broken for file navigation in this release, they just don't work.  Backspace and enter will let you go up and down file hierarchy but you can't use arrows to move around.  Seems like a sign of a broader boo-boo.

**Screenshots**
not necessary, it's super simple and reproducible.

**Desktop Application:**
TagSpaces v5.0.5 from appimage
Linux Mint latest (Vanessa21 < Ubuntu Jammy) with Mate Desktop, fully up to date with Linux kernel 5.15.0-xx

**Additional context**
I provided in "expected behavior" above.

**Comment by uggrock** [comment]
Thanks for reporting this, I was able to reproduce it. We will fix it for the upcoming 5.1 version.

**Comment by ZebulonGlitch** [comment]
Awesome!  :D  Many thanks!!  Every time I forget and hit escape I do a face palm. Heh

**Comment by uggrock** [comment]
Fixed in 5.0.6 and 5.1.x
