### ISSUE TITLE
When deleting a file, incorrect warning given.  Files are moved to trash, not deleted forever.

### ISSUE THREAD

**Issue by ZebulonGlitch** [tagspaces/tagspaces#1794]
**Describe the bug**
Info string incorrect when confirm/cancel dialog pops up on delete file action.

**To Reproduce**
1. Delete a file

**Expected behavior**
It should tell the truth, as it is far less alarming.  When I first started using the app I was totally freaked out that it would delete files forever.  After a bit of testing I realized it was using the recycle bin.

**Screenshots**
n/a

**Desktop Application:**
Tagspaces 5.0.5 - Linux Mint 21, Mate Desktop

**Comment by sytolk** [comment]
@ZebulonGlitch it's have option for this. Look at the bottom of General Settings:
![A8326655-9738-4E27-9E3E-5ACDF6DE1988](https://user-images.githubusercontent.com/1415463/202152758-98f998d8-7e3a-4e18-8985-53255b2f317a.png)
If this option is enabled the delete message can be "The selected entries will be moved in trash bin" @uggrock ?

**Comment by uggrock** [comment]
TagSpaces is a basic file manager, so I think the user expect that it can delete files. We have a generic text for the deletion because for example on S3 buckets there is no trash bin, and the files are deleted directly.

**Comment by uggrock** [comment]
I will extend the text in the message to: "Move deleted files or folders to trash bin if available" and add some additional information.

**Comment by ZebulonGlitch** [comment]
For info I'm very happy it by default moved the files to trash instead of deleting permanently!  :D  It was only a scary message.  I didn't know about that option - makes sense now.  Yes if you can make it so the warning goes away if you're sending files to trash, that would be great. We can always go get them back from the trash if we make a mistake. :+1:
