### ISSUE TITLE
MacOS version 5.1.1 beta or stable release?

### ISSUE THREAD

**Issue by suschizu** [tagspaces/tagspaces#1809]
The GitHub site says 5.1.1 is a beta version but the website (https://www.tagspaces.org/downloads/#) already claims that 5.1.1 the latest stable version:

_The current stable version of TagSpaces is 5.1.1 released on 2022.11.29._ 

Could you please clarify this? Thanks!

**Comment by tagspaces-amp** [comment]
You can consider version 5.1.1 of the Lite version available here on Github as stable. We will release v5.1.2 very soon, containing some improvements and a PRO release.

**Comment by suschizu** [comment]
great thanks for the information!
