### ISSUE TITLE
Android App: keyboard obstructs text when typing

### ISSUE THREAD

**Issue by snakth** [tagspaces/tagspaces#181]
There is impossible to slide down the page when keyboard is shown.
Keyboard literally hide half of the page making impossible to see what you are typing.

**Comment by uggrock** [comment]
Can you please send us a screenshot of the issue and tell us which version of Android you are using.

**Comment by snakth** [comment]
Here is the Screenshot http://goo.gl/mkr8E5

Sony Xperia z2
Android 4.4.4

**Comment by uggrock** [comment]
This issue appears to be not reproducible in recent version of TagSpaces
