### ISSUE TITLE
Perspective Setting "Show Folder Description" not working

### ISSUE THREAD

**Issue by thefoofighter** [tagspaces/tagspaces#1816]
**Describe the bug**
Perspective Setting "Show Folder Description"

**To Reproduce**
1. Open a Location 
2. Navigate to or create folders with descriptions
3. View folders in Grid View
4. Under Perspective Settings "Show Folder Description" seems to have no affect
5. Description is always visible over the thumb,

**Expected behavior**
Description should toggle on off. This was working, Not sure why it stopped.  

**Screenshots**

**Desktop Application:**
 - Operating System: Windows 10 64Bit & OSX 10.14.6
 - TagSpaces Version 5.1.2 both Pro and Free versions exhibit the issue.

**Additional context**
The toggle for the tags works as I would expect, it shrinks the tags to a small numbered total.

**Comment by uggrock** [comment]
Thanks for reporting this, hiding description for files in the grid perspective is a great suggestion, in order to make the grid look more clear. But it was never implemented so far, as much as I can remember... We will consider this is as feature request and have added it already to our backlog.

**Comment by thefoofighterRW** [comment]
Great Thank you!
