### ISSUE TITLE
Right Click -> Show in File Manager doesn't work while filtering by tags

### ISSUE THREAD

**Issue by Ryuggha** [tagspaces/tagspaces#1824]
When I enter TagSpaces and use navigate through files, everything works just fine. But when I search for tags, find the file I want the path of, and try to open it in my File Manager, it doesn't work.

**To Reproduce**
1. Search for some tag
2. Right click on some file (a .jpg on my case)
3. Click Show in File Manager
-> File Manager should open up, but it doesn't

**Desktop Application:**
 - Operating System: Windows 11
 - TagSpaces Version 5.1.3 (But this bug has been for two or three versions already)

**Comment by uggrock** [comment]
Fxied in 5.2.3 -> closing
