### ISSUE TITLE
A few observations and changes to consider.

### ISSUE THREAD

**Issue by nomonkeynodeal** [tagspaces/tagspaces#1825]
I really love the concept here. I was using Tabbles, which is a pain to deal with. Today I added a few hundred files and several dozen tags to Tagspaces and it's a big improvement.

1) First observation: when I click a video it opens in a little box on side. I'm expecting to double click the file and for it to open in MPV. I'm going to suggest that an internal player should be kind of an ancillary feature, unless this software is intended to be MPV or VideoLAN with tags. I'd leave the video playing to the default media player (at least by default).

2) I'm having this really annoying problem where when I have the option to open the external player selected, every time I click a file it pops up a message box first warning me that I am about to open a file. Perhaps this is because all my files are on a network. I know all about opening files and I don't feel that I need to be warned about it.

3) I don't know if I'm missing something, but it doesn't make sense to me that the only way to search multiple tags at once is to type them in! It seems like that is the most basic functionality. It would make so much sense just to click a tag to search. The way I see this working is you click tag1 and "+tag1" appears in the search box, click tag2 and the search box becomes "+tag1 +tag2". Then maybe if you right click the tag you get the popup menu.

That's it for now. Thanks for this project!

**Comment by uggrock** [comment]
Thanks for your suggestion! Here me feedback:
1. You can always right click on a file and open it externally. Redefining the double click to do this, could be confusing for many user.
2. You can disable the warning in the settings:
![image](https://user-images.githubusercontent.com/1249777/211487883-ea465ee4-c22e-4c2c-bf0a-ad0db4d81194.png)
3. You can click on every tag and select show file with this tag. 
![image](https://user-images.githubusercontent.com/1249777/211488422-ad38b743-6a93-4bf3-b7b5-d36fd9c2a202.png)

**Comment by nomonkeynodeal** [comment]
>     1. You can always right click on a file and open it externally. Redefining the double click to do this, could be confusing for many user.

Right clicking and going through a menu is a very different experience. I am opening hundreds of files. An option could be added for this functionality. It's how every file browser works.

>     2. You can disable the warning in the settings:

Thanks! I didn't see that option!


>     3. You can click on every tag and select show file with this tag.

I'm afraid you misunderstand me. I want to be able to combine multiple tags in the search bar with a click.
