### ISSUE TITLE
Update 5.1.3 don't want to be installed

### ISSUE THREAD

**Issue by inCarbon** [tagspaces/tagspaces#1827]
I've download from Play store : v4
Then I download v5.1 apk, but at the end of the install, the app say " can't install the update" 

If I desinstall and then reinstall the update, do I lost all my tags and stuffs ?

**Desktop Application:**
 - Operating system android

**Comment by tagspaces-amp** [comment]
If you uninstall the app you will loose the tag library and your locations. The files will remain tagged. If you need your tag library you can export and import it again in the new app installation.

**Comment by inCarbon** [comment]
So I need to pay the pro version ?..

**Comment by inCarbon** [comment]
It doesnt let me export the Tags, only import tags and create tag group is here

**Comment by uggrock** [comment]
Yeah, you are right, I just checked the code, the export functionality is disabled on Android because the saving function we use from the FileSaver library do not work on Cordova which we use for the Android app.
