### ISSUE TITLE
Create a new location is not working

### ISSUE THREAD

**Issue by inCarbon** [tagspaces/tagspaces#1831]
When I had a new location, on the root of internal storage on android, the location appear but no document is in there ! 
Weirdly, it show into the location "SD Card" (and I don't even have an SD card!....)

**To Reproduce**
1. Go to Connect a location
2. Click on Location Path's icon on the right
3. Click the folder on the root of internal storage
4. No document in the newly added location 

Android last version and tagspace 5.3.1 somthing like this

**Additional context**

**Comment by inCarbon** [comment]
? Youve just respond and close the case ? And what about the location dont working ? What can i do ???
Even i make a location in the screenshot folder it does not appear please HELP

**Comment by inCarbon** [comment]
Even tho i put my file into Internalstorage/document/myfolder it still dont work at all !..

**Comment by uggrock** [comment]
This appears to be a specific issue for your phone and/or operating system. If you tell me the operating system of your phone I can try to investigate there. The issue is closed because the location creation is working on our test devices.

**Comment by sytolk** [comment]
@inCarbon if you paste here screenshot with your Location details it will be very helpful

**Comment by inCarbon** [comment]
Ok its on s10+ i will do a video and post here no problem

**Comment by inCarbon** [comment]
https://youtu.be/OqWlKgH5cJI

**Comment by inCarbon** [comment]
I want to add that i waited a bit, like some days but nothing is in the folder within the app

**Comment by sytolk** [comment]
It appers the problem is with directory chooser and the space between Vivre Avec 
![F27DD714-2ED2-4A67-A7C3-B0C9D46D34BF](https://user-images.githubusercontent.com/1415463/211873039-feadf9bc-1f17-4ce6-b9ec-6dd40c4815b4.png)
@inCarbon can you try to manually change the path from escaped `sdcard/Vivre%20Avec` to `sdcard/Vivre Avec` and check the files again ?

**Comment by inCarbon** [comment]
YES it worked ! Thank you a lot !
So it seems thats the space is the problem here 🤔
