### ISSUE TITLE
each time I open tagspace, all locations are lost

### ISSUE THREAD

**Issue by gio710** [tagspaces/tagspaces#1832]
**Describe the bug**
each time I open tagspace, all locations are lost.

**To Reproduce**
1. i go to add a location
2. i use the app
3. when I quit and open it again, the previous locations are not recorded and I have to set them up again in odrer to use the app
**Expected behavior**
Having my locations kept from one session to another

**Screenshots**
none

**Desktop Application:**
 - Operating System: win 10 , latest
 - TagSpaces Version [5.1.3]

**Additional context**
nothing

**Comment by uggrock** [comment]
You are having a instance of TagSpaces running in background. As soon as you close/kill it you will get your locations back. If you do not know how to kill process, restarting your PC will do the trick.

**Comment by gio710** [comment]
great, thanks
