### ISSUE TITLE
modal dialog boxes do not all support keyboard-specifically delete file

### ISSUE THREAD

**Issue by gio710** [tagspaces/tagspaces#1837]
**Describe the bug**
when i select a file and tap "del" on keyboard, a modal dialog box opens. When I tap "tab" 3x to get to yes, it works, but when on "yes" and tap "enter", delete is not performed as if "enter" was not supported

**To Reproduce**
1. select a file
2. tap "del" on keyboard
3. tap 3x "tab"
4. tap "enter"

**Expected behavior**
file deletion after 4.-

**Screenshots**
NA

**Desktop Application:**
 - Operating System: : win 10 latest
 - TagSpaces Version [5.1.3]

**Comment by sytolk** [comment]
This can be easy changed if we set autoFocus on "Yes" button in delete file dialog. But file will be deleted if I accidentally press on Delete and next button Enter (distance between two buttons is small) @uggrock ?

**Comment by sytolk** [comment]
Maybe this can be set in Dialog https://mui.com/base/react-focus-trap/ @uggrock ?

**Comment by lorenz-bienek** [comment]
To be honest having to do step 3, pressing 3x tab already feels wrong to me. I should be able to confirm by pressing Enter right away. Also, I would expect a setting to disable the confirmation dialog, since the files go to the trash anyway. My other file managers do not ask me to confirm the initial deletion.

**Comment by uggrock** [comment]
Issue is fixed for the next release. The number of the needed tabs is reduced. As a quick fix for now, you can remap the "open entry" key binding from ENTER to ALT+ENTER for example.
