### ISSUE TITLE
No showing jpg files on Mac OS

### ISSUE THREAD

**Issue by thyagoquintas** [tagspaces/tagspaces#184]
Hi Dear, I try to tag some of my images, but I'm having trouble to do that.
First I try using a 64bits and 32bits app, but all of that I have the same issues, maybe something liked to the security.

I just try to show images (jpg files) on the view but any of my files are working, just a black screen.

Thanks for the support and I would like to say that your idea of this software is awesome!!

Cheers!

**Comment by uggrock** [comment]
This is very strange. Can you put a screenshot and tell which version you are using.

**Comment by uggrock** [comment]
Do you still have this issue?
