### ISSUE TITLE
Type Error on your webpage

### ISSUE THREAD

**Issue by pcinternetit** [tagspaces/tagspaces#1848]
Type Error on your "Installing TagSpaces" webpage: https://docs.tagspaces.org/installation/

- SEE/Find the following sentence: This folder is located in the from where the application is started and not in the home user folder on current operating systems.

- I suggest: This folder is located where the application is started and not in the home user folder on current operating systems.

- "in the from" The aforementioned word are the type error and needs to be deleted.

**Comment by uggrock** [comment]
Hi @pcinternetit ,
and thanks for pointing out this error. I just corrected it. 
Greetings!
