### ISSUE TITLE
Tags completely broken after update (colors lost, numbers interpreted as date tags)

### ISSUE THREAD

**Issue by usernamesaredumb2** [tagspaces/tagspaces#1857]
After upgrading from 5.0.5 to 5.2.3 on Linux, all tags in the file list show up in default green color, while the colors in the left tag overview frame are still correct. Also, tags consisting only of numbers are interpreted as date tags showing a calendar icon and a nonsensical tooltip for January 1970.
Returning to 5.0.5 is not possible, all tags in the tag overview are now gone when opening that version.

Do you actually... test before release?

**Comment by tagspaces-amp** [comment]
Of course we are testing, but we unfortunately could not cover all features... So thank you for reporting this, we will provide a fix for the color of the tags in the filename soon. Can you give me an example of a tag containing number which is represented as a date ?

**Comment by bnp1234** [comment]
The color of the tag has become the same since the update.
first Export the tag library and reinstall it to version 5.1.4 or earlier
And if you import the tag library, the color comes back.

**Comment by bnp1234** [comment]
I am a Windows 10 user, and the color of the tag has become the same since the update.
Export the tag library first, then reinstall it to version 5.1.4 or earlier
And when I import the tag library, the color came back.

**Comment by tagspaces-amp** [comment]
The issue with the tag colors is fixed in 5.2.4.
