### ISSUE TITLE
Crash when importing mhtm

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#186]
[Screen cap before crash](http://i.imgur.com/emKYvgR.jpg)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	tagspaces.exe
  Application Version:	0.0.0.0
  Application Timestamp:	549a5309
  Fault Module Name:	tagspaces.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	549a5309
  Exception Code:	80000003
  Exception Offset:	00000000001068d8
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	ed42
  Additional Information 2:	ed4297e225bfe821f88ee57e435f0198
  Additional Information 3:	b4ec
  Additional Information 4:	b4ec8bfcdd96981c674d2a0bea4384f6

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

''This happened when I attempted to export all of my 110mb of Evernote data as a single mht, which I saved into my default tagspaces directory (there is no import option), clicked around so it would show up in the directory (no refresh button), and once it appeared "MHT files are disabled due to security restrictions."  Doesn't seem to be a way to enable them.  Tagspaces halted, went grey and crashed with the above report.

System - Tagspaces 1.10.1 on Windows 7 64-bit client.
Multiple attempts with the same result.  Thanks.

**Comment by sunjam** [comment]
Problem persists in each revision, including 1.10.3, as Tagspaces locks up completely while attempting to preview mhtm file type

**Comment by uggrock** [comment]
Sometimes if the files is too big, it can take time to preview the file. And trying to preview an 110mb Evernote export will also not work, you will definitely go in some out of memory case....

Can you open this file directly in Chrome without TagSpaces?
