### ISSUE TITLE
Tagspaces mangles most filetypes in Xubuntu 14.04 (version 1.10.1)

### ISSUE THREAD

**Issue by matthewmoppett** [tagspaces/tagspaces#187]
When I import documents into Tagspaces, their contents typically become unreadable. For example:

Filetype: | Opened in Tagspaces: | Opened natively:
----------- | ------------------------------ | ----------------------
pdf | Pages are blank | Pages are blank
docx | Displays gibberish | LibreOffice can't open file: "General input/output error"                              
doc | Readable but no formatting; interspersed with gibberish | LibreOffice displays only gibberish
jpg | Image is blank | Image Viewer can't open file: "Error interpreting JPEG image file: (Not a JPEG file:                                                starts with 0xc3 0xbf)"

All of these files are OK when opened from their original locations (i.e. before being copied by Tagspaces into my Tagspaces directory).

**Comment by uggrock** [comment]
Reproduced, Thank you for reporting

**Comment by uggrock** [comment]
Fixed in 1.10.3
