### ISSUE TITLE
html editor - menus not working since 5.2.0 on Debian and Android

### ISSUE THREAD

**Issue by marfuscha** [tagspaces/tagspaces#1873]
Debian 11 with GNOME desktop. Also same bug appers with the Android version.
Installed the *.deb file of Tagspaces.

What is meant by HTML Editor: when i created notes via Tagspaces as html file. Open the file and select "edit" in Tagspaces.
What is meant by editor menu: when in HTML editing mode in Tagspaces - dropdown menus appear by clicking on them, to select header-levels, insert excel-like table and so on. These dropdown-menus are not working. Klicking on them - nothing happens.

Bug
Since version 5.2.0 - the HTML-file editor has a black background.
At the same time (and version) - the editor menus are not working. No drop-down lists are visible when clicking on them (all of them are not working in "editing" mode).
Installed 5.1.4 --> everything works fine. Backto 5.2.x (tested all versions above 5.2.x) - not working anymore.
Editor-Background is also black (before the background was white).

I have the Pro version also - same bug (Pro and github versions affected).
Initially i thought this was an issue with one version of Tagspaces - but everyone after 5.2.0 is affected and the issue seems not to be reported yet.
Android version also affected. Tested on LineageOS 20. HTML-Editor worked fine - but from apk version 5.2.0 - editor menus not working (no dropdown lists). Same issue as with Debian.

And i want also to thank the Tagspaces team for this wonderful piece of SW - which helps me a lot in my daily work to create and tag notes. Thank you very much.

**Comment by uggrock** [comment]
Thanks for reporting this. The fix will be available in the next version (5.3.x)
