### ISSUE TITLE
Inappropriate changes in top horizontal menu bar with Perspective switch

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#188]
Hope I'm not abusing issues but this behavior seems so strange to me I think it qualifies as a bug.  When switching perspectives the options available in the graphical top horizontal menu bar change and not appropriately so.  These should remain largely the same with perhaps very few exceptions.  Ie. in Gridview why might I not want to select the include subfolders option? or in list view it would certainly be nice to be able to select the options in the "group by" menu.  Please keep this menu bar as constant as possible throughout perspective view changes. Thank you.

**Comment by uggrock** [comment]
not relevant anymore
