### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by makhacker** [tagspaces/tagspaces#189]
The pdf file cannot be opened in the internal viewer (PDF.js) after adding a tag. The following message is being displayed:

PDF.js v1.0.1040 (build: 997096f)
Message: Cannot read property 'length' of null

Regards,

Robert Dimitrovski

**Comment by uggrock** [comment]
PDF.js or TagSpaces has issues with opening of some PDF files. Are you sure that the problem occurs after tagging?

**Comment by makhacker** [comment]
Yes, I reproduced the fault several times. Also, when I removed the tags it
worked again.

Regards,

Robert
Am 20.01.2015 22:32 schrieb "Ilian" <notifications@github.com>:

**Comment by uggrock** [comment]
pdf.js library was updated, problem should be fixed
