### ISSUE TITLE
Tag spaces v5.2.5 creates sidecar file even if renaming is the method selected

### ISSUE THREAD

**Issue by Elowmes** [tagspaces/tagspaces#1891]
**Describe the bug**
Tagspaces is creating a sidecar file instead of renaming the file
when I manually rename the file tagspaces doesn't recognize the tag

expected it to rename files. My automated organization file system is based around the ease of using the renaming method to add tags to indicate where the file should be.

 - Windows 11 
 - TagSpaces Version 5.2.5

**Comment by sytolk** [comment]
@Elowmes can you check if you have enabled Rename file option here 
![D3E432CB-E993-4272-B9E2-49CF8978733C](https://user-images.githubusercontent.com/1415463/225679798-ad373f45-816d-4ad0-acd1-1b49e3f6e481.png)
and what is the content of sidecar file?

**Comment by Elowmes** [comment]
Contents of the sidecar file are a .json file named tsi and jpeg files if there are pictures in the folder Best regards,E  Low From: StanimirSent: Thursday, March 16, 2023 12:02 PMTo: tagspaces/tagspacesCc: Elowmes; MentionSubject: Re: [tagspaces/tagspaces] Tag spaces v5.2.5 creates sidecar file even if renaming is the method selected (Issue ***@***.*** can you check if you have enabled Rename file option hereand what is the content of sidecar file?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Elowmes** [comment]
content of the sidecar file is .json file and any Jpegs that are in the folder it is attatched to

**Comment by uggrock** [comment]
Sidecar files are used not only for tagging but also for saving the file description.
