### ISSUE TITLE
Inability to "Toggle Select All Files" on search results

### ISSUE THREAD

**Issue by lorenz-bienek** [tagspaces/tagspaces#1895]
**Describe the bug**
My understanding of tags is that after performing a search there is a new view of the data and you would be able to continue working with this view in the way we have learned to do inside a folder.

When I search for something, I am not able to apply the "Toggle Select All Files" to the search result. Instead, it is applied to the folder I was previously in. For me, this is unexpected and has no value. It also prevents me from working quickly. Currently, I have to manually select each search result before I can do anything with it.

**To Reproduce**
1. Search for something,
2. Click on "Toggle Select All Files".
3. Only files that are at the root of the folder you were in when you searched will be selected.

**Expected behavior**
The search results and nothing else will be selected.

**Desktop Application:**
 - Operating System: Linux (Debian package)
 - TagSpaces Version 5.2.5

**Comment by lorenz-bienek** [comment]
It is only happening in the List Perspective. The Grid Perspective seems to work correctly.

**Comment by uggrock** [comment]
not reproducible anymore -> closing
