### ISSUE TITLE
Tagspaces Chrome Extension does not store Files but "downloads them" (Linux)

### ISSUE THREAD

**Issue by tante** [tagspaces/tagspaces#190]
I have the current Tagspaces Chrome Extension (1.10.1) installed on Chrome on Linux (Version 40.0.2214.85 beta (64-bit)). 

Whenever I try to clip something into my tagspace, The file gets "downloaded" (into my Downloads folder) instead of saved to the tagspace. The extension has the required permissions.

**Comment by uggrock** [comment]
You have to enable chrome to ask you where to save the downloaded files. Here is a small howto malektips.com/google-chrome-prompt-download-file.html
This behavior should be changed in the upcoming releases, so a save as dialog will come regardless of you chrome settings.

**Comment by tante** [comment]
So, the Extension will always have to ask me to save things in the proper location? Ok, that might kind of work.

Have you looked at the Native Messaging API of Chrome (https://developer.chrome.com/extensions/messaging#native-messaging) ? Might allow tagspaces to send a message to the desktop client (or a helper program) to write things to the correct path.

**Comment by uggrock** [comment]
This could be possible solution for the issue, but is for me feature request...
