### ISSUE TITLE
Problematic filename characters

### ISSUE THREAD

**Issue by tiemay** [tagspaces/tagspaces#191]
At least with PNG, JPEG, and GIF filetypes, if one of the following `+ # % &` are in a file's name, whether it be from a tag, or just in the file's regular name, the image preview or thumbnail won't display the image. However some other filetypes are ok with these symbols, including: TXT, MD and HTML.

Renaming a file with with `/` in tagspaces is (understandably) problematic, though a more elegant way to fail would be nice. Right now placing the `/` at the beginning, middle-ish, and end of the filename produces various results. 

Tested on TagSpaces 1.10.1, Kubuntu 14.04

**Comment by uggrock** [comment]
not reproducible in 2.1.0
