### ISSUE TITLE
Search results are not updating correctly, v5.3.3 on Windows

### ISSUE THREAD

**Issue by MK481** [tagspaces/tagspaces#1912]
**Describe the bug**
After searching with a few tags (two in my specific case) if you modify the search by changing the last tag the result sometimes stays the same even if it actually should change for the new tag combination. I suspect that this occurs when the first and second search produce the same amount of search results. In my case the first and second search both delivered two results. The results should be different (and they are if you start an entire new search) but they are not updated in a continued search.

**To Reproduce**
I haven't tried this, but it should reproduce the problem
1. You need four tagable items and three tags.
2. Tag two items with the tags 1 and 2.
3. Tag the other two items with 1 and 3.
4. Now search for the tag combination 1 and 2.
5. You should get the two items that are tagged accordingly.
6. Change the search to the tags 1 and 3 and search again.
7. Normally the result should get updated, but if this behaves like my problem, it'll stay the same.

**Expected behavior**
A modified search should deliver the same results as an entirely new search for the same tags.

**Desktop Application:**
 - Operating System: Windows 10 Home 64 bit
 - TagSpaces v5.3.3

**Additional context**
I modified my search multiple times in a row. As I mentioned if the number of results doesn't change the search results in general won't change.

**Comment by uggrock** [comment]
Fixed in 5.3.4 -> closing
