### ISSUE TITLE
Cannot see Preview videos on MacOs

### ISSUE THREAD

**Issue by maurymarcano** [tagspaces/tagspaces#192]
Hi! I downloaded 32bit and 64bit version and video previews doesn't work. Can you help me with this?
Thanks u!

**Comment by tiemay** [comment]
Which video format are you trying to play? (MP4, MOV, AVI .etc) Can you play a WEBM file?

It looks like some video formats are not yet supported for playing in TagSpaces native app (windows, mac, linux). WEBM works for me as expected, but the unsupported MP4 does not. However MP4 does play for me with the TagSpaces firefox add-on, which looks to be using firefox's support for MP4 (though the right edge of the video is off the screen...).

You can view a list of file type support [here](http://www.tagspaces.org/supported-file-formats/)

**Comment by tiemay** [comment]
By the way, [this](https://www.youtube.com/watch?v=akjVaF09mSY) looks like a decent way to determine if you're running on 32bit or 64bit hardware/operating system on a mac. 32bit programs should work either way, but 64bit programs would run better; however 64bit software cannot run on 32bit hardware. To understand the speed difference between 32 and 64 bit, think of it like this: would you rather drive on a two lane highway, or a four lane highway?

**Comment by uggrock** [comment]
Due licensing concert playing of pattented format is not supported. In order to enable them you have to follow this tutorial: https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.
