### ISSUE TITLE
Error in the Perspectiv titles

### ISSUE THREAD

**Issue by MK481** [tagspaces/tagspaces#1927]
**Describe the bug**
Just a minor thing, but I guess the 'false' at the end of the first four Perspective titles isn't intended?

![grafik](https://github.com/tagspaces/tagspaces/assets/102470636/c54bcef8-11ee-4e7f-8197-682bda377b2c)
![grafik](https://github.com/tagspaces/tagspaces/assets/102470636/79164ed8-2bc3-4bdb-997b-e1e5c6aa23fa)

**Desktop Application:**
 - Operating System: Windows 10 Home
 - TagSpaces Version 5.3.5

**Comment by sytolk** [comment]
Will be fixed in the next release thanks!
