### ISSUE TITLE
View and Help menu duplication with JSON export

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#193]
Win8.1 64bit  TagSpaces 1.10.1 and 1.10.2:

 Goto View / Settings / Export JSON file.

This duplicates the view help menu titles in the uppermost titlebar and also duplicates entries within the respective menus - Please see attached pictures for examples.  Each time this behavior is repeated the duplication occurs again.

![untitled picture2](https://cloud.githubusercontent.com/assets/10375234/5912459/906dd4ba-a591-11e4-9611-fb872ca4988f.png)

**Comment by claell** [comment]
Experienced something similar after switching language, I think.

**Comment by uggrock** [comment]
It is reproducible after language switching, should be fixed.

**Comment by uggrock** [comment]
Fixed for the next release.
