### ISSUE TITLE
TagSpaces, Move/Copy dialog is incorrect.

### ISSUE THREAD

**Issue by LloydRB** [tagspaces/tagspaces#1944]
**Describe the bug**
Starting with Build 5.3.2 for macOS, the Move Copy Files dialog box has changed to Move Copy Entries and the Target Path field and Folder icon are no longer displayed. Instead, a drop down list is displayed allowing only selections of Photos, Videos, etc. I am unable to navigate to the destination folder like I was able before in 5.2.5 and earlier. The New Subfolder button works, but I don't need it. Navigate to parent folder button does nothing.

**To Reproduce**
1. Go to a folder with a photo.
2. Right Click on the photo and select Move/Copy File(s).
3. The Move Copy Entries dialog is displayed with no field for entering the Target Path. 

**Expected behavior**
I expected to have a text field for entering the Target Path and a folder icon to navigate to the desired folder.

**Screenshots**
Correct Move/Copy in 5.2.5
![Screen Shot Correct Copy Move 5 2 5](https://github.com/tagspaces/tagspaces/assets/138179482/4867437a-8a58-4a17-9e95-ff66d3c01ec5)
Incorrect Move/Copy in 5.3.2
![Screen Shot Incorrect Copy Move 5 3 2](https://github.com/tagspaces/tagspaces/assets/138179482/388b8d56-c240-4149-a4a8-fa75f49035e5)

**Desktop Application:**
 - Operating System: macOS
 - Browser - N/A
 - TagSpaces Version 5.3.2 and later to the current release of June 2023.

**Additional context**

**Comment by uggrock** [comment]
Hi and thanks for reporting this issue! Can you please try to reproduce it in our latest release https://github.com/tagspaces/tagspaces/releases/tag/v5.4.0 ?

**Comment by LloydRB** [comment]
Hi Ilian,

Actually, it fails in the current stable version of TagSpaces is *5.4.1*
released on *2023.06.30*. When my v5.3.x version failed, I downloaded
v5.4.1 hoping it would have a fix. It did not. I also did not see the
problem reported in Issues, so I presumed I was the first to find it. I had
to download and install about 5 different versions before I could pin it
down to a particular version where it was introduced. Not sure if it is
macOS specific. I try to keep up with new releases, however, I just did not
need to use Move/Copy until yesterday.

Thanks for your message and help.

LloydRB

**Comment by sytolk** [comment]
@LloydRB I don]t have this issue with the latest release I'm testing on Mac OS with v5.4.1 it's have default target path selected from the current folder initially:
![B65EA3CF-C169-49B0-B7AA-267BCAAD0BC7](https://github.com/tagspaces/tagspaces/assets/1415463/d37b96b5-b715-4c12-a852-958aa70f6ab4)
Navigate to parent folder button works for me and you can navigate to root dir 
![A7175443-BCD6-47FC-9F27-962452F08902](https://github.com/tagspaces/tagspaces/assets/1415463/3a502dbd-90d9-4c91-8bf2-abab8ac2fc2d)

**Comment by LloydRB** [comment]
Hi Sytolk,
I downloaded 5.4.1 and it worked. In other releases I tried pressing Navigate to Parent Folder and nothing happened. I thought I got the same results with 5.4.1, too. Thanks for your help. I will Close with comment, resolved.
LloydRB

**Comment by LloydRB** [comment]
I downloaded version 5.4.1 and pressing Navigate to Parent Folder correctly displayed the subfolders. The issue is resolved.
