### ISSUE TITLE
Contrast/Night View Button bugs

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#195]
[Imgur](http://i.imgur.com/3u6L3Ov.jpg)
See example of what happens with each click.  Font size, colors continue to change between white, black, blue, etc.

Present in both Windows 64-bit 1.10.1 and current 1.10.2  pre-release client.

**Comment by uggrock** [comment]
These are different predefined css themes with different font sizes and colors .... so this is for now the desired behavior.

**Comment by sunjam** [comment]
Hmm, it confuses me to have to click the button several times before it will restore the default sized font and coloring.  Could there be a simpler way to switch between themes?

**Comment by sunjam** [comment]
Also realized that whatever css theme you select is reset to the default upon closing Tagspaces.

**Comment by uggrock** [comment]
last point is corrected and will be released soon.
