### ISSUE TITLE
Android 13 - html Editor - Pro Version - not saving (saving goes endless)

### ISSUE THREAD

**Issue by marfuscha** [tagspaces/tagspaces#1955]
OneNote 6T - Android 13 Custom Rom (Lineage OS 20).
Tagspaces Pro 5.4.2: not working  --> Non-Pro version is 100% working (saving feature) - tested 5.4.3
Tagspaces Pro worked really well until 5.3.x (i didnt use the saving feature for a longer time).

But i notified last days (after update the Pro version to 5.4.2) - that i cant save HTML Editor files when editing.
Saving button - after pressed - does not safe but the "saving" picture is running endless (circle moving).

So - no saving of HTML files with editor possible. Only Pro version is affected.

**Comment by tagspaces-amp** [comment]
this is fixed in the upcoming 5.4.4 release, thanks for reporting the issue!
