### ISSUE TITLE
Tagging of search results in a folder isn't working correctly

### ISSUE THREAD

**Issue by MK481** [tagspaces/tagspaces#1956]
**Describe the bug**
When searching within a specific folder, if you select results using 'shift' to tag them afterwards, you'll tag more files than the selected ones. It seems that you're tagging all files from the original folder between the ones you selected pressing 'shift'.

Update: You can see a difference in the number of the visable selected files and the number shown by the program.

**To Reproduce**
1. Go to a folder.
2. Start a folderwide search that returns some files from the folder, but also leaves out some files in between them.
3. Use 'shift' and klick on the first and last search result to select all of them.
4. Assign them a new tag, that no file in the folder has yet.
5. Reset the search to go back to the original folder. 
6. Reload the view.
7. Now there'll be some files with the newly given tag that weren't part of the search results you tagged.

**Expected behavior**
When you tag a selection of search result files you only should tag these specific files.

**Desktop Application:**
 - Operating System: Windows 10 Home, 64 bit
 - TagSpaces Version 5.4.3

**Additional context**
working with:
- Grid perspective
- single click selects only

**Comment by sytolk** [comment]
Can't repeat this with the fix provided for Shift key: https://github.com/tagspaces/tagspaces/pull/1958

**Comment by uggrock** [comment]
fixed in v5.4.4
