### ISSUE TITLE
Missing video thumbnails for search results

### ISSUE THREAD

**Issue by Kurufinwe21** [tagspaces/tagspaces#1965]
This is with TagSpaces Pro v. 5.4.4 on Windows 11 (but it's been happening for several versions).

I have a location with a bunch of MP4 files, displayed using the Grid perspective. Thumbnails are shown for those files.

However, when doing a search (by tag, name, etc.), the results are displayed with empty thumbnails. This makes parsing the results harder than it should be.

I'm pretty sure it used to work at some point, but that was several versions ago.

**Comment by sytolk** [comment]
@Kurufinwe21 can you check this with the lates version: [5.4.6](MZP2DFZXVMPWRF7YJIS4G3WKSITMGETI45FLKCPQ6TOUGR2L2PEKTYZYB4)

**Comment by Kurufinwe21** [comment]
You're right, the bug seems to be fixed in v 5.4.6, at least the free version.

Unfortunately, my link for the pro version still downloads v 5.4.4. Hopefully that'll fix itself within a few days.
