### ISSUE TITLE
"Save Selected" on Chrome extension does nothing.

### ISSUE THREAD

**Issue by Lanyard** [tagspaces/tagspaces#197]
On a fresh install of TagSpaces, with "allow access to file URLs" checked, selecting part of a webpage, clicking the tagspaces extension button, and clicking "Save Selected" does nothing. The "Save whole page" and "Screenshot" buttons work just fine, though.

**Comment by uggrock** [comment]
This feature is working for me on Linux, can you tell which OS you are using?

**Comment by uggrock** [comment]
please reopen if you have more details about this issue.
