### ISSUE TITLE
Unable to Install on Android 13 via Google Playstore

### ISSUE THREAD

**Issue by sumbria** [tagspaces/tagspaces#1971]
**Describe the Bug**
Unable to install on Android 13 via Google Playstore.

**To Replicate**
Go to Google Playstore
Search for TagSpaces
Playstore message displayed: "This app isn't available for your device because it was made for an older version of Android."

**Mobile Device**
- Samsung Galaxy Z-Fold 4

**Comment by tagspaces-amp** [comment]
The Android app of TagSpaces in the Google Playstore is not supported anymore. Please use the direct download link from the release page on github to get the current APK: https://github.com/tagspaces/tagspaces/releases/tag/v5.4.6

**Comment by tagspaces-amp** [comment]
https://github.com/tagspaces/tagspaces/releases/download/v5.4.6/tagspaces-android-5.4.6.apk
