### ISSUE TITLE
Can't Build App from Source Code

### ISSUE THREAD

**Issue by BlueSpiders99** [tagspaces/tagspaces#1976]
**Describe the bug**
I'm trying to set up the source code for editing, but the build process ('npm run build') compiles with 84 errors and 7 warnings. The majority of the errors are along the lines of:

> [1] ERROR in ./app/services/utils-io.ts 25:0-63
> [1] Module not found: Error: Can't resolve '@tagspaces/tagspaces-common/utils-io' in 'C:\tagspaces\app\services'
> [1]  @ ./app/reducers/app.ts
> [1]  @ ./app/containers/Root.tsx 30:0-56 55:23-41
> [1]  @ ./app/index.tsx
> [1]
> [1] ERROR in ./app/services/utils-io.ts 31:0-85
> [1] Module not found: Error: Can't resolve '@tagspaces/tagspaces-common/misc' in 'C:\tagspaces\app\services'
> [1]  @ ./app/reducers/app.ts
> [1]  @ ./app/containers/Root.tsx 30:0-56 55:23-41
> [1]  @ ./app/index.tsx
> [1]
> [1] ERROR in ./app/services/utils-io.ts 32:0-405
> [1] Module not found: Error: Can't resolve '@tagspaces/tagspaces-common/paths' in 'C:\tagspaces\app\services'
> [1]  @ ./app/reducers/app.ts
> [1]  @ ./app/containers/Root.tsx 30:0-56 55:23-41
> [1]  @ ./app/index.tsx

which I take to mean "something something tagspaces-common is missing", or thereabouts. Do you have any idea how I can fix this?

Running the app ('npm run start') produces a window with the tagspaces logo that does not do anything else. It also produces the following terminal output:

> 
> PS C:\tagspaces> npm run start
> 
> > tagspaces@0.0.0 start
> > cross-env NODE_ENV=production electron ./app/
> 
> 
> pm2.start Exception: Error: Invalid package C:\tagspaces\node_modules\electron\dist\resources\app.asar
>     at createError (node:electron/js2c/asar_bundle:2:1561)
>     at readFileSync (node:electron/js2c/asar_bundle:2:9254)
>     at d.append (C:\tagspaces\app\webpack:\tagspaces\node_modules\properties-reader\src\properties-reader.js:100:17)
>     at new d (C:\tagspaces\app\webpack:\tagspaces\node_modules\properties-reader\src\properties-reader.js:16:9)
>     at propertiesReader (C:\tagspaces\app\webpack:\tagspaces\node_modules\properties-reader\src\properties-reader-factory.js:6:11)
>     at startWS (C:\tagspaces\app\webpack:\tagspaces\app\main.dev.ts:422:24)
>     at Module.call (C:\tagspaces\app\webpack:\tagspaces\app\main.dev.ts:552:1)
>     at __webpack_require__ (C:\tagspaces\app\webpack:\tagspaces\webpack\bootstrap:19:32)
>     at C:\tagspaces\app\webpack:\tagspaces\webpack\startup:4:27
>     at Object.<anonymous> (C:\tagspaces\app\main.prod.js:1:719709)

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version: I'm using the master branch from git

**Comment by sytolk** [comment]
@BlueSpiders99 you can run 'npm run dev' script instead. It will run 'npm run prepare-node' internally this script will install [tagspaces-common ](https://github.com/tagspaces/tagspaces-common) for you platform.

**Comment by BlueSpiders99** [comment]
Well, progress, but I'm still not getting a functional app. The console is producing dozens of variations on this:

> ERROR in ./app/reducers/app.ts 27:0-337
> Module not found: Error: Can't resolve '@tagspaces/tagspaces-common/paths' in 'C:\tagspaces\app\reducers'
>  @ ./app/containers/Root.tsx 30:0-56 55:23-41
>  @ ./app/index.tsx 28:0-37 41:94-98
> 
> ERROR in ./app/reducers/io-actions.ts 25:0-84
> Module not found: Error: Can't resolve '@tagspaces/tagspaces-common/utils-io' in 'C:\tagspaces\app\reducers'
>  @ ./app/containers/MainPage.tsx 51:0-47 672:20-44
>  @ ./app/containers/Root.tsx 32:0-34 38:96-104
>  @ ./app/index.tsx 28:0-37 41:94-98
> 
> ERROR in ./app/reducers/io-actions.ts 26:0-213
> Module not found: Error: Can't resolve '@tagspaces/tagspaces-common/paths' in 'C:\tagspaces\app\reducers'
>  @ ./app/containers/MainPage.tsx 51:0-47 672:20-44
>  @ ./app/containers/Root.tsx 32:0-34 38:96-104
>  @ ./app/index.tsx 28:0-37 41:94-98

It's just saying over and over again that it can't resolve '@tagspaces/tagspaces-common/XXXXXX' in 'C:\tagspaces\app\YYYYYY'. The window that launches is a gray box with the Tagspaces logo on it. The menu items (File, Edit, View, Help, and their children) don't do anything either.

Apologies if there's something basic I'm missing; I'm afraid I'm entirely new to Javascript. All I want is to add "open in Firefox" to context menus, but it's being a real pain in the butt to even get started.

Thank you so much for taking the time to help.

**Comment by sytolk** [comment]
What is your `npm --version` and `node --version`.
Are you sure that have run `npm install` before you try to run `npm run prepare-node` ?

**Comment by sytolk** [comment]
can you downgrade npm and node to versions:
```
sytolk@Stanimirs-Mac-mini Public % npm --version       
8.5.5
sytolk@Stanimirs-Mac-mini Public % node --version
v16.15.0
```
beter use [nvm](https://github.com/coreybutler/nvm-windows/releases)

**Comment by BlueSpiders99** [comment]
I _am_ using nvm, I think? nvm -version returns 'running version 1.1.11'. I'm not exactly clear what the lines between nvm, npm, and node are, but I'm pretty sure I have all three of them.

Downgrading has successfully avoided the error message from 'npm install'! Unfortunately, 'npm run prepare-node' and 'npm run dev' still produce the same errors that they did up [here](https://github.com/tagspaces/tagspaces/issues/1976#issuecomment-1704382511).

**Comment by sytolk** [comment]
maybe after downgrade npm/node you need to remove `node_modules` folder `package-lock.json` and try again 
`npm install` and `npm run prepare-node`

**Comment by BlueSpiders99** [comment]
I tried completely deleting the tagspaces folder, uninstalling npm / node / nvm, and starting over from scratch (using those versions you posted). It works now, though it does take a while for the app to load. No idea why.

Thanks so much for all your help. Now I just have to figure out how to, y'know, write Javascript. :P
