### ISSUE TITLE
Can't view PDF files

### ISSUE THREAD

**Issue by aloomens** [tagspaces/tagspaces#198]
I just found TagSpaces and installed 1.10.1. I really like it so far. 

One thing I have noticed is that I am not able to view and PDF files. It shows the same error for all of them:

"PDF.js v1.0.712 (build: 6969ed4)
Message: Cannot read property 'length' of null"

I can view these files just fine in Acrobat Viewer.

**Comment by sunjam** [comment]
What version of tagspaces are you using and on what client?  I'm able to access PDF files just fine on the latest 1.10.3 release with Win 7 64-bit

**Comment by aloomens** [comment]
I was using 1.10.1 on Windows 7 64-bit. I just updated to 1.10.3 also on
Windows 7, 64-bit, and have the same issue. When I try to view a PDF it
says an error occurred while loading the PDF. When I click on "More
Information", it shows:

"PDF.js v1.0.712 (build: 6969ed4)
Message: Cannot read property 'length' of null"

On Sat, Jan 31, 2015 at 2:47 PM, sunjam <notifications@github.com> wrote:

> What version of tagspaces are you using and on what client? I'm able to
> access PDF files just fine on the latest 1.10.3 release with Win 7 64-bit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tagspaces/tagspaces/issues/198#issuecomment-72335882>.
>



-- 
Al Oomens
Wheaton, IL.
aloomens@gmail.com

**Comment by aloomens** [comment]
I have just found some PDFs that I can view in TagSpaces. Although about 80% of the PDF files that I have, I get the error shown above. All the PDF files open just fine in Acrobat Viewer. Would there be the same issue in the Android version?

**Comment by uggrock** [comment]
The PDF library (pdf.js) will be updated in the next release, but this is not a warranty that you can open all you PDF files. Please keep in mind, that here we are using only a JavaScript lib for the rendering and not something powerful and enterprise ready like Adobe Acrobat Reader.

**Comment by aloomens** [comment]
Greetings. I just discovered that the PDF files that I could not view in TagSpaces, I am able to view just fine in TagSpaces Light 1.11.3. I still get an error on the same files using the Windows 64 version of TagSpaces. Is there something I can do to get this working with the Windows version?
