### ISSUE TITLE
HTML editor: Formatting turns off and on again after line CR

### ISSUE THREAD

**Issue by pellenys** [tagspaces/tagspaces#200]
1) Edit a file in the HTML editor, press Ctrl-U and type a few words. They will be underlined 
2) Press return - underlined toolbar button is still 'on', as expected
3) Press Ctrl-U to switch off underline
4) Press return - underline unexpectedly turns back on again. 

Win8.1, x64

**Comment by uggrock** [comment]
This is a summernote issue, I could reproduce it on their demo website, please open issue there. 

p.s. summernote (https://github.com/HackerWins/summernote) is the lib we are using in the HTML editor.
