### ISSUE TITLE
File softing order inconsistent

### ISSUE THREAD

**Issue by BlueSpiders99** [tagspaces/tagspaces#2022]
**Describe the bug**
When I sort my files, the order is often inconsistent or blatantly wrong. For instance, I might sort by title descending and see 'b' before all of the 'a' files are done. Paging through the results, it seems that the folder has been divided into 'blocks' and files have been sorted only _within_ their block.

For example, I generated 1800 files: 0_0 through 0_49, and similarly for every other digit and letter (1_0 through 1_49, ..., 9_0 through 9_49, a_0 through a_49, ... , z_0 through z_49). Each file was an image of about 3 megabytes (using 4-byte text files did not produce the error). I sorted randomly, then by title descending. It was clearly visible that not all files had made it into the search - there were only four out of the 50 files starting with '0_' at the beginning, followed by three of the '1_'s and six of the '2_'s. This continued for 350 or so files at which point the pattern started over again (this time with nine of the missing '0_' files).

Sorting algorithms are not my strong suit, but this feels like an incomplete sort, producing a kind of 'sawtooth' effect. Perhaps the program ended its sorting early for some reason. Since it didn't work with text files, perhaps it ran out of room somehow?

**To Reproduce**
1. Generate easily-ordered files
2. Sort randomly
3. Sort alphabetically
4. Observe that files are missing from the order

**Expected behavior**
An alphabetical sort should put _all_ files in alphabetical order.

**Screenshots**

**Desktop Application:**
 - Operating System: Windows 10
 - TagSpaces Version 5.4.7

**Comment by sytolk** [comment]
@BlueSpiders99 I can't repead this issue. This is the sorting context provider https://github.com/tagspaces/tagspaces/blob/0fe6b0f1a4f36ec53c471c8e7ef2af9b8285c165/src/renderer/perspectives/grid-perspective/hooks/SortedDirContextProvider.tsx#L117 sorting is performed before pagination.
This is the sorting function: https://github.com/tagspaces/tagspaces-common/blob/5ebaecc580ed65891535b0d9e5a7cb894bf0df84/packages/common/misc.js#L572
It's have unit tests for sorting too: https://github.com/tagspaces/tagspaces-common/blob/a4fd5768ca0319b5e8b86a3068525a90933ae4e4/__tests__/common/unit/misc.test.js#L133

It will be very helpful if you can provide script that generate files with names to repeat this issue. (Or unit test).
This is our shell script for teststing: https://github.com/tagspaces/tagspaces/blob/develop/tests/create-1000files-nothumbs.sh

**Comment by BlueSpiders99** [comment]
5.7.1 did not work, unfortunately.

Here's the Python I used to generate the files. Put a Python file with this code in a folder containing an image and a directory titled "alphabet folder" and it'll do the rest.

```
folderpath = "alphabet folder"

liststring = string.digits + string.ascii_lowercase

for i in range(50):
    for a in list(liststring):
        filename = f"{a}_{i}.png"
        new_file_path = os.path.join(folderpath, filename)
        if not os.path.isfile(new_file_path):
            imagepath = "dey3mffo06b61.png"  # replace with image name
            shutil.copy(imagepath, folderpath)
            os.rename(os.path.join(folderpath, "dey3mffo06b61.png"), new_file_path)
```
