### ISSUE TITLE
Dragging tag from file to group fails and tag graphic gets stuck where dropped

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#204]
Win8.1 64bit, 1.10.3:  Not sure, but think this behavior is new in one of the last two releases.

To reproduce - assign tags to a file, drag a tag from file to try to copy it into  a tag group.

Witnessed behavior - tag graphic sticks where it was dropped until app restarted.  Tag does not successfully copy to the group.  See images attached here.
![capture2](https://cloud.githubusercontent.com/assets/10375234/6014694/48af9e2a-ab26-11e4-9173-855fbc74ea2c.JPG)

![capture1](https://cloud.githubusercontent.com/assets/10375234/6014693/4360c9b2-ab26-11e4-87da-831981a9a703.JPG)

**Comment by uggrock** [comment]
not reproducible in version 2.1.0
