### ISSUE TITLE
Feature request: inform user that file deletion is PRO-only feature

### ISSUE THREAD

**Issue by PaperOrb** [tagspaces/tagspaces#2058]
update: My mistake, I just realized I had 4 files with very slight edits and similar names.

Right click file > click delete does not move the file to the trash bin, it only hides the file from displaying inside tagspaces. I thought this was a bug at first until I realized it's a PRO-only feature as stated here: https://github.com/tagspaces/tagspaces/issues/177#issuecomment-176185644

Please change the "delete" button on lite versions to say "hide", or add a one-time modal stating that proper file deletion requires upgrading to pro.

**Desktop Application:**
 - PopOS 22.04
 - TagSpaces 5.7.5 lite debian package

**Comment by sytolk** [comment]
@PaperOrb delete to trash works for me on Windows with free version of Tagspaces 5.7.5. Can you check if files are deleted in your file maneger and can you confirm that you have enabled move to trash in settings
![Screenshot 2024-02-20 100603](https://github.com/tagspaces/tagspaces/assets/1415463/99fa517e-18ff-4aae-ba0d-358dcbe54f63)

**Comment by PaperOrb** [comment]
Thanks guys, I put an update in the OP stating it was my mistake though. What happened was I deleted a file, but then saw it was still in the folder on the file system As it turned out, it was just a very similarly named file, and the original file was indeed deleted correctly.
