### ISSUE TITLE
Tags should not be hidden behind checkbox in grid mode

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#206]
Win8.1, 64bit, 1.10.3:  Tags should not overlap with the checkbox in grid mode - this is especially problematic with small tags and I imagine would be an even bigger problem on a touch display.
 
Please see attached pic for example:
![capture3](https://cloud.githubusercontent.com/assets/10375234/6014787/3f298bc0-ab28-11e4-8766-0d01304c2af7.JPG)

It is very difficult to select options for this small tag.  Furthermore selecting the tag to get options can simultaneously select the checkbox depending where clicked.  Also misleading in that it looks like arrow next to tag text should be trigger for menu but it is actually upper third of tag that is trigger zone.  

Suggest just not allowing tags and this checkbox to overlap.

**Comment by uggrock** [comment]
fixed in version 2.x
