### ISSUE TITLE
Question:  What if my files already have a [ in the name?

### ISSUE THREAD

**Issue by margoba** [tagspaces/tagspaces#207]
This is not really an issue, but I could find no other place to ask a question.  I have a lot of files that use a single open bracket in their name.  An example would be version2 [filename.txt

Can I make your program work, or do I have to rename all my files?

Thanks,
-barry

**Comment by uggrock** [comment]
Hi Barry,

i think that there is no way, that TagSpaces recognizes your files. It is better to rename them. You can use some batch renaming utility.

cheers,
Ilian

**Comment by margoba** [comment]
Just as a suggestion, you might consider for a future version, making the delineator characters "[" and "]" configurable.

 

I will investigate renaming my files, but I do have a few thousand of them.  :- (

 

Thanks for the info,

-barry

 

--

Barry F Margolius - bfm@pobox.com
