### ISSUE TITLE
Android - Sort by Date is Broken

### ISSUE THREAD

**Issue by locuturus** [tagspaces/tagspaces#2082]
**Describe the bug**
Sorting by date is broken on Android. A few files will change positions compared to sorting by name but this appears random to me. Ascending and descending seems to have little effect on the outcome either.

**To Reproduce**
1. Go to a local folder
2. Change sort to "Date Modified"
3. Observe that the expected sort does not occur. Files do sort differently than by name but they are clearly not by date. 

**Expected behavior**

**Screenshots**

**Desktop Application:**
 - Operating System:  Android 14
 - TagSpaces Version:  5.7.12

**Additional context**

**Comment by sytolk** [comment]
There is problem with order by size too in Android

**Comment by locuturus** [comment]
Hello, maybe it didn't make it into 5.7.13 but order by date is still broken. However order by size appears to be working.

**Comment by sytolk** [comment]
@locuturus the fix is included in TagSpaces v5.7.13.  Will check order by date..

**Comment by locuturus** [comment]
Hello again. I updated to 5.8.4 and checked file sorting. __Both sort by Size and sort by Date Modified are still broken.__ 

The issue with sort by Date Modified is easy to see — the result appears the same as sort by Name — but sort by Size can seem to work unless you look closer. The first ```n``` files will sort by size as expected, but this starts over at ```n+1``` and sorts by size for another ```m``` files and it may start over there too at ```n+m+1```. At least in my screenshots folder this sequence of sorting repeats stops somewhere in page 2 and all remaining files sort by size as expected.

![markup_image_1000651045](https://github.com/tagspaces/tagspaces/assets/19397973/f3c2c7b3-9ccb-4bcc-b01c-f2c227f4a374)

**Comment by locuturus** [comment]
@uggrock Sorting is working for me now. Thanks!
