### ISSUE TITLE
Android - Indexing Location Fails

### ISSUE THREAD

**Issue by locuturus** [tagspaces/tagspaces#2083]
**Describe the bug**
Indexing a local folder either never starts or never completes.

**To Reproduce**
1. Go to location manager and index a location. In my case this is always a local folder on my Android.
2. Observe the lack of progress indication (UX improvement idea maybe?) so keep the screen on and wait 20 minutes just to be sure.
3. Try to collect tags from the location, observe a message saying that the location needs to be indexed first. This implies the indexing failed.
4. Repeat for good measure, but it never works.

**Expected behavior**
I expect to be able to collect tags from the location, or do anything else that depends on having a fresh index.

**Screenshots**

**Desktop Application:**
 - Operating System:  Android 14
 - TagSpaces Version:  5.7.12

**Additional context**
If you think it's helpful I can collect logs but as there is no application crash I'm not sure what to filter for.

**Comment by sytolk** [comment]
In the next relese will be fixed. Thanks for issue!

**Comment by nyrell** [comment]
I'm running tagspaces v5.8.6 on android and experience the same problem as above. That or the indexing is extremely slow (as I let it try to index overnight). There is also no progressbar, so it is impossible to see if it is actually doing anything. My folder is a local folder on the SD card.
