### ISSUE TITLE
Selecting Target Path in Move or Copy Files Dialog via folder icon sometimes results in "\" as target path

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#211]
1.10.3 - Windows8.1, 64bit:  Sometimes using the black folder icon in the move or copy files dialog to select a folder destination and then hitting ok in the file browser popup will result in the Target path being listed simply as " \ " in the move or copy dialog.  

I think it may be a speed thing  - If I am very fast about navigating the folder tree and clicking ok, this seems more prone to occurring (note though, that I do see the correct folder name listed in the bottom element of the file-tree popup before clicking ok).

**Comment by binarybum** [comment]
as update - persists 1.11.0

**Comment by uggrock** [comment]
This should be fixed now.
