### ISSUE TITLE
Tagging a webdav'ed file break the sync

### ISSUE THREAD

**Issue by erixtekila** [tagspaces/tagspaces#212]
Hi,

While trying to use own cloud 8 and tagspaces webdav edition, I got an error when adding a new tag to a sync'ed file.
The issue seems to come from the fact that the name changed.

**Comment by uggrock** [comment]
TagSpaces was tested with owncloud 6 and 7. Issue will be investigated soon with owncloud 8

**Comment by grefel** [comment]
Is this bug fixed? Is there a plan to support future owncloud releases?

Thanks!

**Comment by uggrock** [comment]
This issue is still untested from us. But this is also the only report that it does not work with owncloud 8. Theoretically we don't have to support owncloud directly, we just plug into the webdav interface of owncloud, which is another open soure PHP based library.

**Comment by grefel** [comment]
ok, i will test it with oc8 and report.
