### ISSUE TITLE
Tag search results do not contain folders

### ISSUE THREAD

**Issue by aleksg17** [tagspaces/tagspaces#2148]
**Describe the bug**
When trying to search for a tag only files on being returned. Since Tagspaces Allows adding tags to folders they should also be visible in search results for the given tag. In fact the search results would read "No file or **folder** found".

**To Reproduce**
1. Tag any sub folder with a new tag (for example "other")
2. Go to the parent folder
3. Search for the tag (for example "|other")
4. See "No file or folder found" message

**Expected behavior**
I expect the tag folder to be listed in the search results

**Screenshots**
N/A

**Desktop Application:**
 - Operating System: Windows 11
 - TagSpaces Version [e.g. 5.9.2]

**Additional context**
N/A

**Comment by sytolk** [comment]
fixed in https://github.com/tagspaces/tagspaces/releases/tag/v5.10.1
