### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by snakth** [tagspaces/tagspaces#218]
Autosave option would be very convenient while working with large files.

**Comment by JamieNg** [comment]
Yes, It's an must-have feature or at least, tagspaces should ask when close the programe if any change haven't saved yet . I wrote and forgot to press save, then the next time I open my work, It drives me crazy.

**Comment by kmf** [comment]
+1

**Comment by sunjam** [comment]
+1

Also, asked for this within the "Request a Feature" for Tagspaces if that helps.
https://tagspaces.uservoice.com/forums/213931-general/suggestions/6977684-add-option-to-auto-save
