### ISSUE TITLE
tagspaces-web: read from / write to local storage

### ISSUE THREAD

**Issue by jniggemann** [tagspaces/tagspaces#219]
I really like tagspaces and would like to use the local FS as a backend.
That way, tagspaces would make a a sort of self-hosted web-notebook...

**Comment by tbleiker** [comment]
This already works! You just have to setup webdav (see [this blog post](http://www.tagspaces.org/webdav-edition/)) on your server. Works like a charm here. 

For webdav you can use [owncloud](www.owncloud.org), [pydio](www.pyd.io) or just a webdav server like [sabre/dav](http://sabre.io/).

My setup: Among other folders, I sync two note folders (private and work) with [syncthing](http://syncthing.net/). All folders are accessable with pydio (webdav enabled) and the hosted tagspaces access the note folders via webdav.

**Comment by jniggemann** [comment]
>You just have to setup webdav
webDAV isn't a local backend and unnecessarily adds additional attack surface to the system as a whole.

Installing a separate webdav service like owncloud, sabreDEV or the like also means:
* additional administrative work to be done (needing to keep the DAV service up to date)
* additional bugs and security issues
* additional complexity while toubleshooting

That's why I'd like local storage as a backend after all :-)

**Comment by tbleiker** [comment]
Good point! But the same holds for each new feature in tagspaces which Ilian has to maintain... ;)
* additional administrative work to be done
* additional bugs and security issues
* additional complexity while toubleshooting

Btw, if you manage to setup tagspaces on your server, you will certainly manage to set up sabreDAV! And there are lots of Apps to sync with webDAV. As soon as local storage is implemented, another (or the same ;)) voice asks for sync... :)

**Comment by jniggemann** [comment]
Correct, that's also true.
I didn't yet look at the code, is the backend modular enough so we could develop "backend plugins" that could be developed seperately?

**Comment by steph-ben** [comment]
I would really like to have the local storage available for tagspaces-web as well.

I'm already synchronizing my directories with BTSync (or Dropbox or Syncthing), and I don't really understand why I should use another in-the-middle software to sync with tagspaces ...

Thanks a lot !

**Comment by jniggemann** [comment]
Care to explain why you closed this without comment?

**Comment by uggrock** [comment]
Yesterday I forgot to classify this issue as enhancement request, sorry for that....
