### ISSUE TITLE
Media player doesn't work

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#221]
Unable to playback video (mp4) and audio files (mp3) on Win 7 1.10.3 64-bit.  Audio icon shows up as muted and refuses to unmute within tagspaces.  Files opened fine natively.

http://imgur.com/G1xurk1

edit: Updated to latest Github release 1.10.5 and problem persists.

**Comment by sunjam** [comment]
Okay, after some research I found [this past issue](https://github.com/nwjs/nw.js/issues/216) on nw.js explaining the ffmpegsumo.dll has to be built a certain way.  I also see that proprietary codecs (mp3, etc.) [require some additional configuration](https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.) when building the dll.  
  Using today's Github build of nw.js got **working Wav playback.**  There was no success when attempting proprietary m4a, mp3, mp4.  I also checked they were set to correctly open by viewerBrowser.

**Comment by alexweissman** [comment]
I've had luck with the version of `ffmpegsumo.dll` provided here: https://github.com/nwjs/nw.js/issues/2898#issuecomment-69145619
