### ISSUE TITLE
Problems when copying documents from OneNote

### ISSUE THREAD

**Issue by wonea** [tagspaces/tagspaces#226]
I've been moving documents across from OneNote by copying them across. Copying and pasting them across, however I've noticed the image references are stored in the temp folder. This makes no sense, because I want to sync my notes between multiple computers. Shouldn't the image pasted into a document be stored locally?

![2015-03-31 10_37_05-c__users_gareth brown_documents_tagspaces_tech_embedding a repository within ano](https://cloud.githubusercontent.com/assets/557192/6916183/ff4e961c-d791-11e4-885f-4416cdbcb8fa.png)

**Comment by uggrock** [comment]
The references to the images are stored from OneNote in the temp folder. This is how the mht format is opened in Internet Explorer/OneNote. But in fact TagSpaces is trying on saving to convert all the external images to dataurls. This way they are stored in the html file itself, without external reference.

**Comment by wonea** [comment]
Thanks, I was just hoping to dump OneNote and move everything across. Perhaps I'll save the images locally to a tagspace, then re-added the images. Just a fair bit of work.
