### ISSUE TITLE
New panel resize feature doesn't scale properly

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#230]
http://i.imgur.com/mgzVez2.png

Panel resize works (Thank you!), but:

1. The folder panel gets cluttered and unusable when shrunk
2. Restarting Tagspaces will lose any resizing of the panels beyond the default.

I'm really excited to see all menus be configurable in the GUI!

**Comment by sunjam** [comment]
I've begun experimenting with nw.js and I've found that by default it does not scale properly either.  I played around with other nw.js apps and [Light Table](https://github.com/LightTable/LightTable) scales beautifully.

**Comment by uggrock** [comment]
In the current pre-release 1.12.2 the UI was redesigned with material design paradigmas and panel resize functionality is not supported anymore.
