### ISSUE TITLE
Android: Swiftkey "flow"

### ISSUE THREAD

**Issue by thirdnote3** [tagspaces/tagspaces#232]
Create or edit a HTML/ Text/ Markdown... file on TagSpaces for Android

the function "flow" on Swiftkey, Google Keyboard and AOSP Keyboard is not working in the editor and the whole Tagspaces app (inclusive search).

Are anybody here with the same problem and can fix it?

**Comment by uggrock** [comment]
This is an issue with the cordova packaging...

**Comment by uggrock** [comment]
not reproducible in v2.x
