### ISSUE TITLE
Issue accessing folders

### ISSUE THREAD

**Issue by J316** [tagspaces/tagspaces#235]
If I set root folder or sdcard folder as one of the locations, I can open the files in them, but I cannot open the subfolders, and I get the message that path cannot be opened. But it works fine when I try to open the subfolders of the download folder for example (a subfolder of sdcard folder).

**Comment by iskaldvind** [comment]
I have this bug too (tagspaces 1.10.3, win7x64). Tagspace was unable to get subfolders of root dir on my usb (3.0) hdd and by the still light of led indicator I suggest it wasn't even trying to read it, but starting from the next level (root dir's subfolder) if set as location everyting works fine there.

**Comment by uggrock** [comment]
could not be reproduced
