### ISSUE TITLE
pdf-xchange and Tagspaces conflict

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#236]
![Example from imgur](http://i.imgur.com/lf0gZ8e.jpg)
Tagspaces is running PDF files natively off my Windows 7 machine using pdf-xchange.  Not sure why the PDF reader on my local machine is used as opposed to the built-in reader by default, but PDF documents are overlaying on top of Tagspaces.
![2nd Example from imgur](http://i.imgur.com/af4xahL.jpg)

**Comment by uggrock** [comment]
is this in Firefox ?

**Comment by sunjam** [comment]
This is in the source-built Tagspaces client on Windows 7, and I'm not using the Firefox add-on.

**Comment by uggrock** [comment]
this seems for me as a PDF-xchange issue. Something with its PDF recognition system goes to far ....
