### ISSUE TITLE
avi files cause "Save as" window to pop up and white blank screen

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#242]
Same result with different avi videos on latest build.  Tried renaming/saving the videos to **test.avi** with same result.  avi extension set under filetypes to viewerBrowser.
![example of bug](http://i.imgur.com/qFvLOnd.png)

**Comment by uggrock** [comment]
Opening of AVI files works actually only in the Firefox AddOn, but only if you have installed media player plugin... I will disable it for all platforms.
