### ISSUE TITLE
Configuration changes not persistent after closing Tagspaces

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#244]
avi extension is still listed under filetypes and no persistent changes can be made that won't revert back to it existing after restarting Tagspaces.

Likewise, setting options such as "Don't check for updates on start" will revert as well.  It would also be nice if toggles such as showing thumbnails would stay persistent within restarts.

Thanks so much for your hard work!

**Comment by sunjam** [comment]
I got the "Don't check for updates on start" to change after setting it to *false* in both **js/settings.default** and **default.settings.tmpl**.  Not much experience with Javascript so I'm learning as I go, but after changing both of these (doing just one didn't work) it still showed as *true* within a restarted Tagspaces.  I selected false from the GUI, restarted Tagspaces and the change is persistent.

**Comment by sunjam** [comment]
I've begun using 1.11.4 (from Git) on Linux 64-bit and changes are not persistent upon system reboot.  Tagspaces will show the 'first run' splash screen after a system reboot and ask to choose a primary location

**Comment by Hans-Maulwurf** [comment]
All changes get lost when closing tagspaces. (On Linux) it works fine if run as root. So seems like a permission problem? where does tagsapces store the settings?

**Comment by uggrock** [comment]
On ubuntu the settings are here: /home/yourusername/.config/TagSpaces

**Comment by Hans-Maulwurf** [comment]
I'm on arch and use tagspaces from source, so i start it with nw /opt/tagspaces/data/node-webkit/ but there is no tagspaces folder in my .config folder or anywhere else ??

**Comment by uggrock** [comment]
In such case, you use the settings of the nwjs, which are probably in /home/yourusername/.config/nwjs or some temp folder...

**Comment by Hans-Maulwurf** [comment]
when i start it, there is such an output

[24372:1209/120114:ERROR:process_singleton_posix.cc(307)] Failed to create ../../nwjsdata/SingletonLock: Datei oder Verzeichnis nicht gefunden
[24372:1209/120114:ERROR:connection.cc(1060)] Web sqlite error 14, errno -2: unable to open database file, sql: -- sqlite3_open()
[24372:1209/120114:ERROR:web_data_service_backend.cc(54)] Cannot initialize the web database: 1
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[24372:1209/120114:WARNING:nw_form_database_service.cc(21)] initializing autocomplete database failed

no matter if sudo or without

**Comment by uggrock** [comment]
Open  /opt/tagspaces/data/node-webkit/package.json and remove   "chromium-args" : "--data-path='../../nwjsdata/'" and the comma at the end of the previous line and try to start TS again.

**Comment by Hans-Maulwurf** [comment]
thanks, solved :) great

**Comment by uggrock** [comment]
your kind of starting the application is meant actually for devs ...
