### ISSUE TITLE
Cant open app on OS X

### ISSUE THREAD

**Issue by sebi96** [tagspaces/tagspaces#248]
It doesnt even open. Get the message: Can't open TagSpace  from Os X. Both 32 and 64 bit

**Comment by sunjam** [comment]
Are you building from source or using an Os X release?

**Comment by sebi96** [comment]
I used the the official builds.

Tested with 1.10.1, 1.10.3 and now with 1.11.0 (and everytime both, 32 and 64 bit)... 

Using Yosemite (OS 10.10)... 

![bildschirmfoto 2015-04-17 um 12 03 44](https://cloud.githubusercontent.com/assets/2863264/7200086/d802dbb6-e4f9-11e4-8aea-b5273aa4069c.png)

**Comment by sebi96** [comment]
PS: When trying to open with terminal I get

LSOpenURLsWithRole() failed with error -10810 for the file /Users/.../Downloads/TagSpaces.app.

**Comment by sunjam** [comment]
Tagspaces depends on [nw.js (node-webkit)](https://github.com/nwjs/nw.js) and I see two mentions of this error and how to resolve your *[terminal error](https://github.com/nwjs/nw.js/issues/1303)* and *[Permission Denied](https://github.com/nwjs/nw.js/issues/604)*.  

Might relate to how tagspaces was packaged and you can see if it has executable privileges by running **ls -l** on the directory of tagspaces.

**Comment by sebi96** [comment]
+x with chmod I already tried without success...

But the apps is seen as a folder, so I had to try chmod with -R (recursive)... now it works

--

But I tried it with the terminal unzip and another unziper, with both I need to do it... I wonder if it is just with me so?

**Comment by uggrock** [comment]
please see #220 for a suggestion how to solve this issue
