### ISSUE TITLE
Github request - Gitter for Tagspaces repository

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#250]
uggrock, Would it be okay to have a public Gitter page linked to the Tagspaces repository?  Public rooms are free and it would allow Github users to talk about the repository outside of posting issues/wiki pages.  Just a thought, but I understand if this doesn't interest you.

**Comment by uggrock** [comment]
Chatroom created: https://gitter.im/tagspaces/tagspaces
