### ISSUE TITLE
subfolders don't move with the main file?

### ISSUE THREAD

**Issue by rosecat** [tagspaces/tagspaces#254]
When moving a note (file) from one main folder to another, it seems that corresponding subfolders– containing ancillary files for exported html–don't follow to the new subfolders and remain in the initial main folder. Do they have to be moved by hand? Or are they no longer needed once a note has been opened and saved in initial main folder?

**Comment by uggrock** [comment]
Yes, subfolder create with saved html files should be moved manually.
