### ISSUE TITLE
audio files

### ISSUE THREAD

**Issue by rosecat** [tagspaces/tagspaces#255]
Is there a means to insert an audio file? I have several exported html files with subfolders contaning audio files. In display view the audio files don't even show on the note. In edit view, there is only a placeholder picture which is not clickable to listen to the audio file.

**Comment by sunjam** [comment]
Do your encoded audio files playback?  I've only been able to have .wav work correctly on Windows.

**Comment by uggrock** [comment]
the native version of TagSpaces could not play mp3 and other licensed formats due to licensing restrictions. On Android/Firefox/Chrome versions of TagSpaces such files can be played.
