### ISSUE TITLE
Parent folder contents not displayed in left pane after selecting sub-folder

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#259]
It is confusing when clicking through multiple sub-folders:  If I re-select the parent it'll collapse any sub-folders I've opened with no option to continue displaying the contents.  Not sure if this is intentional or not.

I tried adding an additional location, but that new location is entirely separate for any folders I was previously viewing and must be selected from the drop down menu under "Your Locations" and cannot be combined with other locations.

This makes for a lot of menu diving and guess work as the number of folders increases.

**Comment by uggrock** [comment]
Currently this is the designed behavior, but this is one of reasons, we are planing to implement a tree folder view. Clicking on the black folder icons, will show/hide the subfolders. Clicking on a "white" folder will navigate to it, and will regenerate the folder path, which will close the previous path.
