### ISSUE TITLE
Selection/cursor doesn't follow navigation through images

### ISSUE THREAD

**Issue by dandv** [tagspaces/tagspaces#263]
Open a folder with images. Double click one of the images in the list. Press the up or down arrows.

The next image will be displayed, but the selection is gone.

![selection cursor doesn t follow up down navigation](https://cloud.githubusercontent.com/assets/33569/7366111/c5f1a3ae-ed4a-11e4-8c28-f5e354e46f50.gif)

**Comment by uggrock** [comment]
this is clearly a bug, thank you for reporting

**Comment by uggrock** [comment]
fixed in v2.6
