### ISSUE TITLE
Enhancement - disable or customize automatic editorText $date$time tag

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#272]
I'd like to be able to customize or completely disable automatic tagging that happens when creating a file.  I've toyed with hosting a Git repository(folder) of md pages edited in Tagspaces and I don't want tags included as part of the file name upon creation.  For now it makes more sense for me to use an editor outside of Tagspaces and editorText.

**Comment by uggrock** [comment]
This functionality was redesigned in version 3.0. Now the name of the file can be adjusted before its creation.
