### ISSUE TITLE
Empty file name ".txt" won't be recognized

### ISSUE THREAD

**Issue by BasEbeling** [tagspaces/tagspaces#273]
Files without a file name won't be recognized. My text file was originally something like [this is a test].txt.
I removed the tags in TagSpaces. At a certain moment the file was gone from the list, yet is still existed in my file explorer.

**Comment by uggrock** [comment]
Dot is front of a file name means on some operating systems that the file is hidden. But in the settings of TagSpaces there is an options which allows you to show such files.

**Comment by BasEbeling** [comment]
I couldn't find where to do this. The blog is not really search friendly (and I rarely search blogs, so maybe it's me), and there is no manual as far as I can see. Maybe I can make a manual or a wiki or something?
