### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by tomekwi** [tagspaces/tagspaces#284]
Hi,

I’ve just tested out the app and it looks absolutely great! I’ve just noticed that it doesn’t handle symbolic links.

As soon as I open a folder which has a symlink inside, a preloader pops up and wouldn’t go away. Symlink files are listed as subfolders. When I click any of these “subfolders”, an alert appears saying “The desired path could not be opened.”

Unfortunately it makes the app unusable for me – I manage my files with git-annex which uses symlinks extensively.

I’m using Fedora 22 x64. I’ve posted [the same suggestion on uservoice](https://tagspaces.uservoice.com/forums/213931-general/suggestions/8389716-support-symlinks).

**Comment by uggrock** [comment]
I personally use TagSpaces on a 64bit Ubuntu and symlinks works there without issues. Some times TagSpaces has problems with folder names containing non utf8 characters, can you please make sure that this is not the case by you?

**Comment by tomekwi** [comment]
Yeah, that might be the case. Probably each of my files I tried TagSpaces on had at leas an en dash (“–”) in its name. I’ll try renaming that to “-” as soon as I have access to that machine.

I really hope that would only be temporary though.

**Comment by nestukh** [comment]
Hi, I'm having this problem too!

Symlinking folders works good, but not for single files. 
Same symptoms, but I'm not using non-utf8 chars in file names or paths. 

I've tried the official 1.12.0 build and the 1.12.13 release, not working in both cases.
I'm on Debian Jessie 8.2 amd64.
