### ISSUE TITLE
selection with shift and ctrl key combinations

### ISSUE THREAD

**Issue by noerdi** [tagspaces/tagspaces#294]
I just started to use tagspaces today to organize my pictures and it works nice! But very soon I was searching for a way to add a tag to a big selection of files that I can filter easily, like a specific date. Having a range of files it seems I have to select each single one, since shift + select does not seem to be implemented.

After searching through options and descriptions I was looking into the open issues and I found #117, which also contained "implementing of the shift and ctrl key combinations, which will be implemented soon". Since there where some other folks wishing for this feature and issue #117 was created with a different topic I figured it would not hurt to create a separate issue for this. I dont't mean to push, I just hope to see it in a future version and until then I am greatful to use this nice open source tool the way it is ;-)

**Comment by uggrock** [comment]
This request will be considered soon...
