### ISSUE TITLE
Edit html-files on windows7 with Firefox-plug-in 1.11.0 - The address isn't valid

### ISSUE THREAD

**Issue by shgfeld** [tagspaces/tagspaces#305]
I use the recent Firefox-plug-in 1.11.0 on a windows7 machine. When trying to edit a html-file, I receive the error-message ...

    The address isn't valid
    The URL is not valid and cannot be loaded.
    Web addresses are usually written like    http://www.example.com/
    Make sure that you're using forward slashes (i.e. /).

I suppose, this error is related to the location path which uses \ in windows. Is there a solution to avoid this error?

Stefan

**Comment by uggrock** [comment]
The file browser is meanwhile disabled in the Firefox addon, please use the desktop version of the application.
