### ISSUE TITLE
tagspaces-web: not sharing tags among computers

### ISSUE THREAD

**Issue by roninsilencio** [tagspaces/tagspaces#306]
I'm currently using tagspaces version 1.11.0 over owncloud. 
Both owncloud and tagspaces are installed in the same server. I would like to be able to connect towards the server from computer A, create some tags and use them in a file. Then I connect to tagspaces from a different computer B. I use the same user (admin) and password. I have to configure the same "location path" in order to see the shared files. I cannot see the tags I have already created from computer B.

How can I use the same tag set from a different computer? Is that a bug?

**Comment by binarybum** [comment]
Maybe not a bug, I don't think it is setup to work that way, but agree would be really nice to have a simple way to sync tag library across computers.  Everyone has a cloud drive - would be nice to be able to just pick a folder that is sync'd with cloud drive for storage of the tag library.

**Comment by mpetri** [comment]
@binarybum would be nice if there was an option so metadata was stored inside the tracked folder so that could be synced via any method (e.g. Dropbox or bittorrent sync).

**Comment by uggrock** [comment]
there is an options described at the end of this blog article http://www.tagspaces.org/whats-new-in-1.8.5/
