### ISSUE TITLE
memory eater when managing a folder with lots of pictures

### ISSUE THREAD

**Issue by Felix-ZJU** [tagspaces/tagspaces#309]
I am very grateful that you (or should i say your team) developed the TagSpaces. For me it's the first file manager that support tags on files, meanwhile the interface is very friendly.

However when i tried to tag photos of an album, which is a directory containing 1000+ photos, and i clicked the button "Toggle Thumbnails", the TagSpaces just stuck, and the memory occupation just soars, ending up eating all my free memory space and i can do nothing but to kill the process. I guess the software is loading all photo data into the memory, which clearly is unnecessary.

**Comment by riazarbi** [comment]
To add my 2c to the above comment, I'm finding that tagspaces eats so much memory as to become unusable. 

My configuration:
I use a Windows 7 machine with 8gb of RAM.
I have tagspaces looking at a single folder, which has ~8500 PDFs, with a total file size of ~7.94Gb. 
When open, tagspaces is using about 1.5Gb of RAM and very little CPU.
When in use, performing tagging operations for instance, RAM usage can climb as high as 2.5Gb.

This does not crash/freeze the app, but it means that I can't leave it open in the background while performing other intensive computing tasks - an essential feature of a file browser/manager.

**Comment by qzo** [comment]
I just discovered TagSpaces and decided to use it on my directory with notes - hundreds of small text files. I found out that when I delete (move) a file from the directory or put a new file to the directory (using Total Commander), TagSpaces' memory use increases significantly (~ 20 MiB) and that memory is not freed. So after a while doing this the memory usage increased to about 2.5 GiB. And it took quite a lot of CPU time too. (When I restarted TagSpaces, everything was ok again.)

**Comment by uggrock** [comment]
I just tested this on a folder with 1000 files and was able to reproduce it. Actually every reload of this folder increases the memory irreversibly. If you change the content externally on the current opened folder in TagSpaces, it automatically reloads it content... This is clearly an issue.

**Comment by uggrock** [comment]
Due to this issue, the loading of images for displaying thumbnails is now disabled in TagSpaces. In the PRO version, we will have a real thumbnail generation, so this will be hopefully not an issue anymore.
