### ISSUE TITLE
Search in subfolders is not working with webdav/owncloud

### ISSUE THREAD

**Issue by primozcankar** [tagspaces/tagspaces#310]
When I try to search for tags in sub folders with: ?+tag no results are returned. If I go into the sub folder directly and do a search for ?+tag the tag is also not found. Only if I search in the directory with +tag the file is then found. 
Version: 1.11.0 
Used in conjunction with ownCloud

**Comment by uggrock** [comment]
The webdav.js library we are using does not implement currently deep saerch, so for now we are stuck without search in the subfolders.

**Comment by uggrock** [comment]
Alternatively a direct connection to the owncloud's search should be possible, but this solution will be vendor specific...

**Comment by khartahk** [comment]
So do the native apps then support recursive search? For example if I use android app and search through the phones internal storage will this work? Or If I use the Linux app? Because I can get arround this and set owCloud to download folders I need to my phone and my computer.

**Comment by uggrock** [comment]
The apps for windows, linux, osx, android, ios and firefox support searching in subfolders. The chrome extension and the webdav version does not support this feature.

**Comment by khartahk** [comment]
Thanks for the info. Just tried it on Arch and it works great - was hoping it would work with tags even if I don't type the entire tag name but non the less it's working
Just one more question - I know this is offtopic but is there a keyboard shortcut like  ctrl+f to activate the search bar?

**Comment by uggrock** [comment]
Ctrl+f for showing search input box is already implemented and will be released with the next version 1.12.1

**Comment by jdeblese** [comment]
I'm exploring using tagspaces as a web-based file manager on a NAS and am running into this problem as well. I'd rather not put everything in the same directory, so not being able to search subfolders is a dealbreaker.

Are you looking at any alternative libraries that have support for deep searches?

**Comment by uggrock** [comment]
In the current pre-release 2.0.5 of the application, search in subfolders was implemented for the webdav platform and the chrome extension.
@jdeblese you can try it https://github.com/tagspaces/tagspaces/releases/tag/v2.0.5
