### ISSUE TITLE
Missing Debian Package?

### ISSUE THREAD

**Issue by craigmaloney** [tagspaces/tagspaces#311]
Noticing the Debian package is no longer present on the downloads page. Curious if this is an oversight or by design. Having a Debian package made it easy to keep my machines in sync with the latest release.

Thanks!

**Comment by uggrock** [comment]
The removal of the Debian package was on purpose. We are working on a "PRO" version of TagSpaces which will include again installers for various platforms, including a Debian package.

**Comment by craigmaloney** [comment]
Ah, OK. Will revisit when the "pro" package is released. Thanks!

**Comment by uggrock** [comment]
The deb package for a non PRO versions is available again.

**Comment by craigmaloney** [comment]
Just downloaded and installed it. Thank you so much!
