### ISSUE TITLE
Selected file losing focus after tagging.

### ISSUE THREAD

**Issue by 5urpher** [tagspaces/tagspaces#312]
In the latest Windows Desktop version (1.12.0), when you tag a file or files the focus gets lost. So you have to reselect the file if you want to add further tags.

Also if you are using search and including subfolders, after you tag a file you will only see files from the current folder.

**Comment by binarybum** [comment]
Agree, this is a change in 1.12 that is very frustrating.  Worked in earlier versions and is especially time consuming when attempting tagging multiple files with multiple tags at once.

**Comment by uggrock** [comment]
could not be reproduced in 2.1.0

**Comment by Salamimonster** [comment]
In 4.2.1 the behaviour still persists. 
See it here https://www.youtube.com/watch?v=OGM7Jt_FlOk
After tagging the focus is lost.

**Comment by Salamimonster** [comment]
Since no one responds, I recreated this issue. See it [here](https://github.com/tagspaces/tagspaces/issues/1629).
