### ISSUE TITLE
Launching in portable mode forgets primary directory and configs

### ISSUE THREAD

**Issue by Di3mex** [tagspaces/tagspaces#314]
Launching tagspace via the tagspaces.cmd script:
User is greeted with start screen every time and locations and configs are forgotten.
I can't find any wiki article or help on the command line options of tagspaces either. 
Launching tagspaces through the .exe works as expected

**Comment by uggrock** [comment]
This is some kind of a bug in the command line handling. You can get working portable mode under windows by adding this line of code in package.nw/package.json file after the line "nodejs": true,.

    "chromium-args": "--data-path=profile"

**Comment by uggrock** [comment]
Please refer to this blog article for running in portable mode: http://www.tagspaces.org/tagspaces-2.0-released/#portablemode
