### ISSUE TITLE
MHTML Pages Are Blank in Version 1.12

### ISSUE THREAD

**Issue by tharrisone** [tagspaces/tagspaces#316]
[10165:0814/141431:INFO:CONSOLE(8)] "Uncaught Error: Script error for: ext/viewerMHTML/extension.js
http://requirejs.org/docs/errors.html#scripterror", source: file:///home/klepto/Downloads/tagspaces-linux/package.nw/libs/requirejs/require.js (8)

I'm on Fedora 22 btw and it has worked fine before the update

**Comment by uggrock** [comment]
Hi, 

thank you for the reported issue. We are actually testing mainly on Ubuntu Linux, and there we can not reproduce the issue. Can you provide some more information about this issue?

**Comment by tharrisone** [comment]
When I view a page in Tagspaces that is an mhtml file it shows nothing, just a white page.. It doesn't even show the security notice or an option to open it as a new window.

**Comment by palica** [comment]
I have the same behaviour with standalone app (blank page when trying to load mht file), but the page shows just fine using firefox extension. Gentoo Linux.

**Comment by uggrock** [comment]
not reproducible in 2.1.0
