### ISSUE TITLE
JPGs do not show preview in "grid" mode

### ISSUE THREAD

**Issue by I3ordo** [tagspaces/tagspaces#317]
Hello,

I am planning to use this with 3d files. I have converted the library to have jpg+max file next to it. What i want to achieve is search for "tagged" jpg files and use the max files for operation.

Currently, neither 32 bit nor 64 bit versions, show the contents of the JPG files. Also

The thumbnails would be too small to view, can you add a thumbnail size slider in the future?

Also, i can not drag and select or shift/ctrl select multiple files in grid mode, very few tag programs do let that... dunnno whats the deal...

**Comment by uggrock** [comment]
creating and displaying thumbnails will be part of a PRO version, which will be released soon.
