### ISSUE TITLE
Freezing while deleting search of subdirectories 

### ISSUE THREAD

**Issue by CrawlinChaos** [tagspaces/tagspaces#318]
If you search the subdirectories of a location and then try to manually clear the search instead of clicking on the clear function (the little eraser next to it), it will cause TagSpaces to freeze. For example, if I did a search for "?cheese" and then cleared it by pressing the DELETE key, it would freeze. More specifically, it freezes as soon as you delete the "?" from the search phrase. Also, in case it helps, when the program freezes and you try to force it to quit, it doesn't show up as NOT RESPONDING.

**Comment by uggrock** [comment]
not reproducible in 2.1.0
