### ISSUE TITLE
HiDpi Issues

### ISSUE THREAD

**Issue by valmar** [tagspaces/tagspaces#319]
When running on a laptop with super-hi resolution (for example the Lenovo Yoga 2 Pro, with 3200x1800, tagspaces does not adapt to HiDpi and looks tiny.

If it can help, the Developer Console outputs the following warnings:

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi)

index.html:1

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)

index.html:1

Trying to change the 'dpi' string to 'dppx' in the css files as suggested does not solve the problem...

  Valerio

**Comment by uggrock** [comment]
can you add a screenshot please

**Comment by valmar** [comment]
Dear uggrock, tanks for looking into this. I since sold the Yoga Pro and got myself an asus zenbook. The display of the Zenbook is also hidpi and has the same problem as you can see from the screenshot:

![screenshot from 2016-01-28 17-18-14](https://cloud.githubusercontent.com/assets/558469/12650621/c26bc5b2-c5e3-11e5-9d8f-d9d3eec7a05a.png)

As you can see I am running Ubuntu on the laptop. The settings manager scales perfectly but tagspaces does not...

Thank you again

**Comment by john-landgrave** [comment]
Yeah, I've got a 4k monitor and would love to use TagSpaces but I'm encountering this same issue. I use several other Electron apps which have handled the situation fine, and would really love to use your all's great product as well!

**Comment by uggrock** [comment]
Can somebody try to reproduce this issue with version 2.1.4. We believe it is fixed there.

**Comment by valmar** [comment]
@uggrock , sorry for the delay. I tested it, and it seems solved! Thank you so much!
