### ISSUE TITLE
v1.12.0 (x64 and x32) failing to launch in osx mavericks

### ISSUE THREAD

**Issue by chuzzant** [tagspaces/tagspaces#322]
Hi,

I am running osx mavericks .. on a macbook book pro 

I just downloaded TagSpaces version 1.12.0 (x64) and unzipped it .. but when I attempt to launch it by clicking the unpacked app nothing happens (no errors are displayed .. just nothing) .. 

I have poked around the logs and nothing is displayed .. the app just silently fails to run.  I then tried the x32 and I get exactly the same result.

Finally, I resorted to the command line:
`open /Applications/TagSpaces.app/`

and I get .. same result even with sudo, so its not a permissions issue .. 
`LSOpenURLsWithRole() failed with error -10810 for the file /Applications/TagSpaces.app.`

Any ideas what could be going on here ?

**Comment by chuzzant** [comment]
As an update, and based on past experience with similar issues (that are sometimes due to the exec bit not being set on a file), I peered into the contents of the app .. and then did:
` chmod +x /Applications/TagSpaces.app/Contents/MacOS/nwjs`

Subsequently, running the app via `open /Applications/TagSpaces.app/` actually pops up a window that immediately gets closed .. and this time no errors are displayed

So, it's possible that the exec bits need to be set also on whatever other binary gets called by nwjs ..

**Comment by uggrock** [comment]
did you have a chance to try the recent 2.0 release ?

**Comment by chuzzant** [comment]
Thanks for responding .. I have just downloaded the 2.0.1 version, and this one does run fine on osx mavericks ..  Thanks to the project team for sorting it out .. 

So, this issue is indeed resolved for me, and makes tagspaces viable (once again) for my needs ..
