### ISSUE TITLE
Markdown editing (v1.12.0 Firefox)

### ISSUE THREAD

**Issue by ugm6hr** [tagspaces/tagspaces#323]
The TagSpaces supported file types page ( http://www.tagspaces.org/supported-file-formats/ ) suggest the editorHTML extension should edit MD files (in concert with viewerMD).

However, the default is editorText. Changing to editorHTML causes an error:

>Error parsing HTML document
>Probably a body tag was not found in the document. Document will be closed.

**Comment by uggrock** [comment]
The information on the website is wrong and will be corrected soon. The correct editor for MD files in editorText.
