### ISSUE TITLE
Unable to Print PDF on Windows

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#325]
1.12.0, Windows 8.1, 64bit:

When selecting print from pdf viewer, printer shows up correctly, but hitting print does nothing, dialog disappears, no error, just doesn't print or make it to print queue.  Opening same file in native viewer and selecting same printer works fine.

**Comment by mladensap** [comment]
Тhe same problem occurs with me. 
1.12.1, Windows 10, 64bit

**Comment by uggrock** [comment]
appears as a nwjs issue

**Comment by uggrock** [comment]
fixed in version 2.1.4 based on Electron.
