### ISSUE TITLE
Support for +tags and @contexts

### ISSUE THREAD

**Issue by addisonamiri** [tagspaces/tagspaces#327]
I think it would be really cool to add support for defining tags by a space delimited list of tags beginning with `+` at the end of a filename (`note +tag1 +tag2.md`). If there were also support for contexts beginning with an `@`. I think it would complete a gtg workflow. Both `+` and `@` could be treated as tags though. The user would know the difference by the beginning character. I know this goes against the tag container idea that the application currently uses but I think it would be extremely useful.

Currently setting the tag delimiter to space gets halfway there. There would need to be the ability to set the tag container delimiters to nothing. The hardest part seems to be the prefix for the tag container. It would have to be `<Space>+ | <Space>@` but the leading `+` or `@` should be included in the first tag. Keep in mind once a word starts with a `+` or `@` the rest of the words in the filename could just be treated as tags so there doesn't need to be complex parsing. Just enough to recognize the first instance while including it in the first tag.

I understand if this would break the workflow this project is trying to achieve. If that's the case then this can be ignored but I think it would be a very useful feature as many apps already treat these delimiters these ways and it would help this fit into a gtg workflow.

**Comment by uggrock** [comment]
This is interesting suggestion, but is not conform with the current implementation...
