### ISSUE TITLE
Deleting the digit 1

### ISSUE THREAD

**Issue by awilkinson118** [tagspaces/tagspaces#328]
I use TagSpace on a MacBook Pro.  Version: 1.12.0 BuildID: 1.12.0.20150727225118

Every now and then, when I save a file (in HTML form), the program goes through the contents of file and deletes some, but not all, "1" digits.  Here is an example that happened today.

1) What is the conversion price in the event of a Qualified Financing?  Please confirm that the Fully Diluted Share Number is 7,600,000.  Please confirm that the conversion price in the event of a Qualified Financing would be 12,000,000/7,600,000 shares or 1.5789.

became

1) What is the conversion price in the event of a Qualified Financing?  Please confirm that the Fully Diluted Share Number is 7,600,000.  Please confirm that the conversion price in the event of a Qualified Financing would be 2,000,000/7,600,000 shares or .5789.

Please help.

**Comment by uggrock** [comment]
This is a very strange issue, which we are not able to reproduce on linux and windows, and since the osx version has the same implementation, I suppose that the reason for your issue is not in TagSpaces. Does this happen only on HTML files or you can reproduce it with TXT or MD files?

**Comment by awilkinson118** [comment]
Dear TagSpace Support:

I will start keeping my notes with MD files and see if the problem reproduces.  If it does not happen for several weeks then we will know it is an HTML issue and that may be a clue to the problem.
Thank you.

Best Regards,

Anthony


Anthony Wilkinson, Co-Owner/Manager

Wilkinson Law LLC


Tel: (732) 410-7595 (direct line)

Email: awilkinson@coffylaw.com


****************************************************************************************************
This e-mail is sent by a law firm and may contain information that is privileged or confidential. If you are not the intended recipient, please delete the e-mail and any attachments and notify us immediately.
****************************************************************************************************
