### ISSUE TITLE
iOS: How to use Google Drive provider?

### ISSUE THREAD

**Issue by jpease** [tagspaces/tagspaces#329]
How would you use Google Drive alone, or Google Drive + Boxcryptor, with the iOS app?

The only obvious option when setting up a Location is the "NoCloud" option provided.

**Comment by uggrock** [comment]
Hi,

currently there is no way to sync files out of the TagSpaces ios app. Apple currently does not allow external apps to change files in a given app, so for the support of such a sync the google drive api/sdk should be integrated in TagSpaces which is not a small task. One way to manage your files out of the TagSpaces app is to connect your iphone with iTunes and use the integrated file browsing there. There are also some 3rd party tools with which you can browse files on your not jailbroken iphone.  

kind regards
