### ISSUE TITLE
Powerful internal file viewer with indexed search keyword highlighting

### ISSUE THREAD

**Issue by motiontwelve** [tagspaces/tagspaces#330]
Hello,

IMO this would make TagSpaces really stand out from the rest and make it a truly portable package.  
A good example is the Outside In viewer library from Oracle (previously Stellent) but I am not sure how their licensing works.  Maybe making it as an optional addin that has to be downloaded separately by the end user would be the right approach.  Also, by taking this path, the same internal file viewer could be used by a search indexer to collect text and allow for keyword search highlighting.  For instance, couple apps that benefit from this technology are X1 Search and the uLister plugin (source code available) for Total Commander.
Please let me know what you think.

Regards,

MotionTwelve

**Comment by uggrock** [comment]
Hi MotionTwelve,

this is exactly our long term direction we are going with TagSpaces. So stay tuned for feature releases.

kind regards
