### ISSUE TITLE
Compartibility of Firefox add-on with Pale Moon

### ISSUE THREAD

**Issue by 2e8** [tagspaces/tagspaces#334]
Pale Moon is Firefox fork. It doesn't use new Firefox API.
I've found that TagSpaces 1.8.6 works correct on Pale Moon
Version 1.12.0 (minVersion changed to 24.0) works from menu only. There is no button. Web Clipper starts from button only. So, is not accessible.
Version 1.12.5 (minVersion changed to 24.0) doesn't work at all. It starts but only background is loaded.
I've tried to fix it, but it looks to difficult for me. Unfortunately I don't know js at all and I'm not familiar with Firefox API.

Is it possible to support also Pale Moon? At least for web clipper.

**Comment by uggrock** [comment]
this goes beyond our possibilities to maintain so many platform. If you find a solution for this issue, please open a pull request.
