### ISSUE TITLE
Tags stay persistent in Windows (8, 64bit) independent from the tagspaces application (exe).

### ISSUE THREAD

**Issue by develD** [tagspaces/tagspaces#335]
Hello, I have problems using tagspaces. Maybe you could be so kind to help me out by answering my questions or give me a helpful advice? Thanks in advance!

Tagspaces can be download as a zip file for windows: tagspaces-1.12.0-win64.
I had a usecase and created tags with tagspaces. Then I had another usecase and didn't want to mix the tags of the old usecase with the new usecase.

Initial solution I was looking for was to have the tags bound to the folder or to the usecase/project or to a defined profile I can switch, because with just 30 tags the layout is becoming quite unclear. -> maybe another issue to solve!

Then I thought it would be a simple solution just to copy the whole application to another directory and then just start a new instance. But by openening the new instance the old tags appeared.
Then I thought, ok - somehow the tags are saved within the application. So I downloaded another brandnew version - this time the 32bit version - and reopened it with the same problem: my old tags appeared - in a completly different executable tagspaces.exe!

QUESTION 1: How can I run different instances of tagspaces with different tags inside at the same time, where the different instances are still saving their tags until the next opening?

So here my QUESTION 2: Where are the tags stored?

To get around this, my REQUEST 1: Something like a Profile- / Usecase- / Project-Manager inside tagspaces for tag management is needed to separate the tags from different usecases!

And my REQUEST 2: A clear (fullscreen) view and a functionality to organize the tags (within ONE usecase) is needed to keep things sorted and clear - like a tagcloud with sorting functionality (alphabetic, groups, most used, ...) and such stuff!

Thanks for taking your time!

**Comment by uggrock** [comment]
Hi,
TagSpaces is saving the tags and the taggroups in your windows user folder. So no matter how many different version you download, it will always go to c:\Users\yourname\.... an so on, except you run tagspaces in a portable mode. This can be done in the current beta version 1.12.5(a new stable version will follow soon) by starting the tagspacesp.cmd file. In this file you can specify where the so called 'data-path' folder will point. For you use case you can have many copies of this file file with different content one called tagspaces_UC1.cmd with the content 'start /B tagspaces.exe --data-path=usecase1' and second called tagspaces_UC2.cmd containing 'start /B tagspaces.exe --data-path=usecase2'.

But nevertheless tagspaces is currently saving the tagging information in the names of the files, so if you have one file used in UC1 and UC2 its name will contain tags from both usecases.

One more thing in the last version you can close a tag group which you don't so will not take valuable  screen space. Ones closed a taggroups will stay closed even if you restart tagspaces.

kind regards,
ilian
