### ISSUE TITLE
having a "$1" in a rich text files causes errors

### ISSUE THREAD

**Issue by kbrannen** [tagspaces/tagspaces#337]
It seems that when you have a "rich text file" that has "$1" in the text, that something in the system won't save it correctly and that gets left out (my first guess it that it's the editor). I first discovered this in a much larger file where when I saved after an edit, it actually duplicated a copy of the entire file in at the spot were "$1" was. This leads me to believe there is some regular expression handling going on that isn't quoted correctly or is written incorrectly.

For an example, create a rich text files with this text:

---

sub format_dollar
{
    my $val = shift;
    if (length($val) > 3)
    {
        $val = reverse($val);
        $val =~ s/(\d{3}(?=\d))/$1,/g;  #offending line
        $val = reverse($val);
    }
    return '$' . $val;
}

---

Save file. If you look at the editor screen which should still be up, the text looks good. Open up a terminal and go look at the file, e.g. with vim, you'll notice that the "offending line" (or line 7) now looks like:          $val =~ s/(\d{3}(?=\d))/,/g;  #offending line
Telling tagspaces to view the file natively also shows the error in the new browser window.

Leave the file by going to another file and coming back causes a refresh and now you can see that the "$1" is missing in the viewer.

I wanted to document this since I just found it. This is in the latest linux 64bit binary download designated 1.12.0.

Kevin

**Comment by uggrock** [comment]
could not be reproduced in v3
