### ISSUE TITLE
PDF error openning

### ISSUE THREAD

**Issue by Rtlite51** [tagspaces/tagspaces#338]
Your thoughts.
PDF.js v1.1.366 (build: 9e9df56)
Message: Cannot read property 'length' of null

**Comment by uggrock** [comment]
PDF.js have some issues with opening of some PDFs ... Can you try to open this pdf in a recent version of Firefox (it also uses PDF.js) ?

**Comment by Rtlite51** [comment]
Should it be my understanding that this program does not work with "Chrome"?

**Comment by uggrock** [comment]
In Chrome, TagSpaces works as a file browser only, because it is not possibly there to manipulate files on your hard drive. Other main feature in Chrome is the build in web clipper, which can be used to save  locally web pages or parts of them.

**Comment by Rtlite51** [comment]
Thank you for your time. Regards, Ray
