### ISSUE TITLE
Feature request: add vim support for editorText

### ISSUE THREAD

**Issue by lotabout** [tagspaces/tagspaces#339]
Hi,

I myself use vim a lot in my daily life. Recently I started to use tagspaces for managing files and really loves it. However I miss the vim bindings so much.

1. I know that I can `open file natively` to open the file in vim.
2. I checked that editorText use codemirror as the editor which already support vim key bindings.

So, could you please add vim support to editorText? 

1. I've already integrate the vim key bindings with editorText locally.
2. But I hope there will be an option to turn it on and off. (Which I still don't know how to code).

I would be glad to submit a Pull Request if you plan to add this feature. Thanks for your time.

**Comment by uggrock** [comment]
We are accepting in general pull request, but before creating one, please consider our contributors policies http://www.tagspaces.org/contribute/ 

The current text editor is very basic, and does not have an UI for settings, so I thing this should be implemented first, before adding features like vim support.

**Comment by lotabout** [comment]
Thanks for your reply.

I also notice that  the text editor did not update for more than 1 year, is there any plan to upgrade it(codemirror)?  Cause the vim support is much better in newer version.

**Comment by uggrock** [comment]
The codemirror version will be updated in the master branch soon.

**Comment by uggrock** [comment]
CodeMirror is updated to https://github.com/codemirror/CodeMirror/releases/tag/5.8.0 in the master.

**Comment by 5TDg9** [comment]
hopefully issue #373 will go away with this, too.
