### ISSUE TITLE
The Android app description page needs a statement about open source code.

### ISSUE THREAD

**Issue by gnotaras** [tagspaces/tagspaces#340]
Hi,

The Android app is one of my favorite note taking tools, but there is one thing that has been puzzling me. Does it contain only open source code or a mixture of open & closed source code? This is not very clear on the description page on Google Play and I think a clear statement is required about this.

If the android app on Google Play also contains proprietary code, it would be nice to create an additional download (with the same price of course) with a clear statement that it is based exclusively on open source code. Some of us consider open source code a necessary feature for an application.

Thank you in advance.

George

**Comment by uggrock** [comment]
You will find a clear statement in the about page of the Android app from Google Play. A pure open source version of the app is available here https://github.com/tagspaces/tagspaces-android-lite . The www folder is not really up to date, but you can replace it with the data folder from this repository.

**Comment by gnotaras** [comment]
Hi Ilian,

> in the about page of the Android app from Google Play

Oh I see. That's great! Actually more than what I had wished for. I hadn't noticed it earlier, so sorry for bothering you about this. You see, the amounts of functionality in the PRO version make such a page a necessity and I'm happy the info is outlined there in detail.

However, I would strongly suggest to also release the fully open source lite version as a paid app on Google Play as well.

Kind Regards,
George
