### ISSUE TITLE
External local images with relative path are not shown in HTML viewer and editor (Win7-64)

### ISSUE THREAD

**Issue by 2e8** [tagspaces/tagspaces#342]
External local images with relative path are not shown in HTML viewer and editor under Win7-64.

I have found how to fix it for viewer:
change `$(this).attr("src", "file://" + fileDirectory + isWin ? "\\" : "/" + currentSrc);`
to `$(this).attr("src", "file://" + fileDirectory + "/" + currentSrc);`
in `setContent` of `main.js`.
I don't understand what is `isWin ? "\\" :`, but it doesn't work and is not needed. `/` works good for windows.

Unfortunately I have not found how to fix it for editor. There is no `fileDirectory` information in editor scripts to use it.

**Comment by uggrock** [comment]
We will try to fix this for the next release.

**Comment by uggrock** [comment]
There is a fix for this issue in the pre-release 2.0.3. Can please try it out?
