### ISSUE TITLE
Clicking on the text pane loses focus from the text area.

### ISSUE THREAD

**Issue by craigmaloney** [tagspaces/tagspaces#343]
When creating a note under Ubuntu Unity the only place I can click on in the "text pane" is the text area (the narrow band of text). Anywhere else loses focus and can cause me to think that I'm typing in the text area.

Would like to be able to click anywhere in this pane and still retain focus.

Thanks!

**Comment by uggrock** [comment]
Good usability point! We will try to find a solution for this...

**Comment by uggrock** [comment]
could not be reproduced in v3.x
