### ISSUE TITLE
file name length, spaces in file names, 

### ISSUE THREAD

**Issue by bennypr0fane** [tagspaces/tagspaces#345]
Hello,
I find what Tagspaces wants to do really exiciting, as none of the other tagging solutions I know of even try to tackle the portability problem. Doing that with file names has been done before, but not as cross-platform, not as good-looking and professional (Oyepa file tagger).
The filenames approach raises some issues for me though:
1. **The names become very long**. As stated elsewhere, filename lenght, and even path length is limited in certain environments, which puts a restraint on the cross-platformness and/or number and exhaustiveness of tags.
Questions:
- What are the **limits** to observe under windows, Linux, MacOS, and in their respective most widely used file systems? How about on a webserver?
- Apart from technical limitations, aren't long long filenames just **very very clunky** to handle? I figure that as long as Tagspaces is used instead of a filemanager, everything's fine, but it may become a big hassle managing those tagged files in situations when we are forced to use a regular file manager that doesn't assist us in that way.
2. How is the **sequence of tags** in a file name governed? If two filenames contain the same two tags, will these tags always be stored in the same order? Or is it possible to have a situation like this from Tagspaces: "Jane novels 18thcent femaleauthor.txt" and "Joe 18thcent femaleauthor novels.txt"? Again, this is probably more of a concern when handling tagged files with applications other than Tagspaces.
3. **Folders** become almost obsolete, right?
Do you think it is best to use very few or no subfolders at all in a repository of files managed with Tagspaces? The file paths are shorter, and a folder structure seems pointless anyway if everything is well-tagged. Or do you still prefer to retain a "tree-like", hierarchical folder structure, because it remains useful some another way (which one?)?
4. The standard format that Tagspaces uses for **filenames contains spaces**. At home I only use GNU/Linux-systems, so I wonder, can we make Tagspaces leave those out or replace them with something else? Of course Linux can deal with the spaces, but I guess anyone who has ever worked with files in the Linux/Unix command line tries to avoid filenames with spaces - even some GUI applications under Linux dislike them...

**Comment by bennypr0fane** [comment]
Should I maybe split this issue up into five separate ones? Maybe no one is replying because it's too much for one thread?

**Comment by kbrannen** [comment]
I'll try to answer some of these...

* The limits are obviously based on the OS. In general, you probably only get about 254 characters max. Yes this can become a real limitation. The "pro" version will generally fix this by pulling the tag names out of the filename, AFAIK.
* Yes, long file names are clunky to handle. :) Of course, once you're using tagspaces, you should find that you can use it for looking at and modifying the files (at least most of the time) and so you don't have to type in the long filenames manually. If you have to work on them manually, use a shell that has filename completion. ;)
* No, folders aren't obsolete. Folders are a way to sub-divide what you have. If you want, think if like a notebook. The top-level folders are like separate notebooks (I have them for "technical", "work", "personal", etc.) Each of those has sub-folders for major sections or categories. I keep making new folders if I need to sub-divide further for however deep I need to go. Eventually, I reach the files for that category/sub-division. That works for me, it might not work for you. Also consider, that all OS's have limits on the number of "items" in a folder. Also, if you have too many items in a folder it can become unwieldy.
* I'm not 100% sure, but I believe you can remove the spaces in filenames by changing the separator char and other config changes. But as you say, the software and the OS can deal with them just fine.

HTH,
Kevin
