### ISSUE TITLE
File tag with Windows 10

### ISSUE THREAD

**Issue by rajeshcr** [tagspaces/tagspaces#346]
My file name is changing based on the tag added. Is this the behaviour ? I recommend to add tag as metadata . Tool should not change my filename

**Comment by uggrock** [comment]
Yes, it is, this is key feature of the tool, please read issue #345

**Comment by nrolland** [comment]
I would not call it a 'feature'. that's just one (very odd) way of storing metadata...

**Comment by uggrock** [comment]
This is one versatile way for storing metadata, which works on every platforms. But I don't want to start a discussion here, please see more information here https://tagspaces.uservoice.com/forums/213931-general/suggestions/5789542-save-tag-data-and-metadata-in-a-separate-file 

You are not alone with your opinion...

**Comment by nrolland** [comment]
If by "versatile" you mean "works nowhere" then yes... 

In unix "everything is a file", it's a pretty much setlled discussion. 
That means messing up with filename, is messing with all of unix.

**Comment by nrolland** [comment]
So, judging form your uservoice, they are overwhelmingly telling you the same thing, "do not mess up with filename". That seem to be the single thing that they have been saying for more than 2 years....

If you dont trust the common knowledge that "everything is a file" is a thing, why would not listen to all your users telling you this one thing for such a long time... ?

That just seems totally wrong, squared. 

Seems like there's another unstated reason to stick to filenames that escape the normal common outsider perception.
