### ISSUE TITLE
title stays empty when creating plain txt file

### ISSUE THREAD

**Issue by hyperglow** [tagspaces/tagspaces#347]
Hey there,

I can not give a newly created note a title. Sometimes the word empty is not shown,  so I can not type in the title there and sometimes the title I type in is not saved. The same with editing older txt files. Also sometimes changing a txt files creates a duplicate of the file instead of changing it....

I am using Android 5.0.
Any ideas on this?

**Comment by hyperglow** [comment]
Tagspaces Pro Version 2.0.20151024114933 is used...

**Comment by uggrock** [comment]
Should be fixed for the next release.

**Comment by uggrock** [comment]
related #363
