### ISSUE TITLE
No thumbnails in grid view

### ISSUE THREAD

**Issue by Flimm** [tagspaces/tagspaces#348]
There are no thumbnails when viewing files in the grid view:

![Screenshot](https://cloud.githubusercontent.com/assets/355454/11267085/7f91e24c-8ea9-11e5-9b52-d4dee54d129b.png)

This is confusing, because it seems like previous versions of TagSpaces did seem to support thumbnails (according to the video in [this LifeHacker article](http://lifehacker.com/tagspaces-is-a-cross-platform-tag-oriented-file-manage-1564189159)). However, I can't find any reference to removing this functionality in the change log.

**Comment by uggrock** [comment]
The initial implementation of the thumbnails was loading the original image, which was leading to  performance issues as in #83. So for now it is disabled, but starting from version 2.0.3, TagSpaces will load thumbs located in a hidden .ts folder. So if you have a file with this path "yourfolder/image1[sunset].jpg", the app will try to find a file "yourfolder/.ts/image1[sunset].jpg.png and load it as a thumbnail for it. The PRO version of TagSpaces will generate the thumbnails in the .ts folder automatically for many file types.

**Comment by exic** [comment]
Hi, I've seen "Script for generation of image thumbnails added" in the 2.1.0 "what's new". How can I use it? I didn't find anything "thumbnail" related in the 2.1.1 deb.

**Comment by uggrock** [comment]
The script is located here: https://github.com/tagspaces/tagspaces/blob/master/data/web/thumbgen.sh and was created for the webdav edition of TagSpaces, but it can be used also with the normal version of the tool. As a prerequisite you will need Imagemagick and Linux. It will just create recursively thumbnails in the .ts folders as described in my previous comment.
