### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by MarkRobbins** [tagspaces/tagspaces#349]
You really need to put something on your site that says this software will change filenames -- and what is up with that anyhow? I am sure you have your reasons, but can't you put the tags in an *.ini file or something in the directory instead?

This issue is a real heartbreaker for me. I like what you are doing but you cant have filenames that change on a whim of tags. Are you mad?

Other entities rely on those filenames -- unless I am missing something, you are really constricting the use case for this software.

**Comment by binarybum** [comment]
This behavior is expected, it's how the app works by design - it's all over the website.  Check FAQ: 
http://www.tagspaces.org/documentation/faq.html
