### ISSUE TITLE
Request: Hypothes.is integration for PDF, plain text and markdown?

### ISSUE THREAD

**Issue by almereyda** [tagspaces/tagspaces#351]
It is very simple to inject @hypothesis into an application, like https://github.com/hypothesis/pdf.js-hypothes.is. It works especially nice with HTML and PDFs. As you are already using PDF.js, I think the step wouldn't be too far to offer it, too.

If considering offline use, of course a complete, login-free Hypothes.is backend fork would be disreable. Or them allowing localStorage/SessionStorage.

Thanks for the first file tagging interface I like. Would like to like it more, though ;)

**Comment by uggrock** [comment]
Thanks for pointing us this interesting project, but since your request is not an issue, I will close it for now.
