### ISSUE TITLE
markdown link to local image does not work 

### ISSUE THREAD

**Issue by cocomice** [tagspaces/tagspaces#352]
I am using TagSpace to organize all my markdown notes so far. Until last release the link image with markdown syntax (e.g., `![](path/to/image) ` works perfectly and I can easily preview the notes in tagspace. However, the with the latest release (v2.0.1) the linked is broken and can not be previewed. Any solution for it ?

**Comment by uggrock** [comment]
This issue is fixed in https://github.com/tagspaces/tagspaces/releases/tag/v2.0.4 . Please try it out...

**Comment by cocomice** [comment]
perfect, it works again ! Thank you for the prompt reply ~
