### ISSUE TITLE
Can't sync tagspaces with dropbox

### ISSUE THREAD

**Issue by eug2** [tagspaces/tagspaces#353]
I am using tagspaces on laptop with no issues. I have synced a file on dropbox (containing doc files) with Android tablet using dropsync. File on tablet is stored on internal storage. Tagspaces finds the folder on tablet but it perceives it as empty. Does anyone know what to do?

**Comment by uggrock** [comment]
This appears to be android/cordova issue, we currently could not do anything to fix it.
