### ISSUE TITLE
Locations not persisted

### ISSUE THREAD

**Issue by j6s** [tagspaces/tagspaces#354]
I have recently updated from a 1.x Version to the current version 2.0.1-1. All of my locations were removed, so I had to add them again. Thats not a problem as things like that can happen.

The problem here is that tagspaces is not saving my locations, so everytime I open tagspaces now I get 2 things:

1. The intro / tutorial is displayed everytime
2. My Locations are not added - I have to add them again

I think it is needless to say that this is a major annoyance. As I have not found a similar ticket I suspect that this might be a error that only effects my installation. Maybe you can provide information about how to debug an error like this.

Additional information:
`Linux jo-desktop 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

running tagspaces 2.0.1-1 installed through the AUR inside of cinnamon (although that should not be a problem).

nw.js version is 0.11.13-pre (but it is the same with 0.10.5), node version is 5.1.0 (But is the same with 0.12.2)

Edit: I updated all of the things around tagspaces because I thought maybe outdated versions were the issue, but the problem is still there. I did also try to clean the configuration variable in localstorage - but that also does nothing

**Comment by uggrock** [comment]
The AUR package is not maintained by us, so it is not officially supported, please see issue #244 for a possible solution.

**Comment by j6s** [comment]
Thank you for the pointer - removing "chromium-args" from package.json solved the problem
