### ISSUE TITLE
Double Click no longer adds tags to selected file

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#355]
Double clicking a tag used to add it to the selected file. This behavior is lost and there is no assigned function for double clicking on a tag - please restore this functionality thank you.

**Comment by binarybum** [comment]
Persists in 2.1.0 - Please reopen - I have new data on this.  Double clicking does sometimes work but it has to be in a very specific pixel location on the tag (usually left upper corner), majority of pixel map for tag does not work for double clicking.

**Comment by uggrock** [comment]
double click could not add tags to a file, because the single click open the tag menu.
