### ISSUE TITLE
Sync tags and tag groups across computers

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#356]
Feature Request: allow easy method for syncing tag groups/tags across systems using third party clouds just like files are sync'd.  
 Suggestion would be to allow selection of a separate folder for saving tag data and user could select already cloud sync'd folder. 
 Are there significant limitations preventing this behavior?

**Comment by uggrock** [comment]
Please see this article for information about this topic: https://www.tagspaces.org/documentation/sharing-tags/
