### ISSUE TITLE
tagspaces 2.0.4 xlsx "open file Natively" not working with linux version

### ISSUE THREAD

**Issue by ssinfod** [tagspaces/tagspaces#357]
Hello, I'm trying to open a XLSX (excel) document from the tagspaces file browser.
I'm using Ubuntu 14.04 and tagspaces 2.0.4. 
I would like the file to open in OpenOffice or directly inside tagspaces preview pane.

Right now, the "OpenFile" button only display Binary Data in the preview pane.
or It displays "Loading /home/folder/file.xlsx..." and stays like that forever. (if I use EditorODF in the settings)

Also, nothing happens if I choose "Open File Natively" in the right click menu.

I tried different "Settings" for the XLSX extension in the "Settings" section but nothing seems to work.
In fact, I only see 6 options in the "Settings" which are: "Choose file editor", "editorHTML", "editorText", "editorODF", "editorJSON", "editorNext".  

How can I add others options in this list ?
Is there a way to use a specific program (ex: OpenOffice) to open a specific file extension ?

How can I open xlsx file from tagspace 2.0.4 with Ubuntu 14.04 ?

**Comment by uggrock** [comment]
I was not able to reproduce this issue on Ubuntu, does it happen only with XLSX files? If yes, perhaps the opening of such files on your Linux is not configured correctly...
BTW editorODF is not able to open XLSX files, so currently it is not possible to open XLSX files in TagSpaces.

**Comment by ssinfod** [comment]
With my Ubuntu 14.04, the problem also occurs with .doc/.docx file.
I see binary data in the preview pane. Otherwise it opens the file browser (nautilus) if the settings are configured to "Choose file editor".

In short, I would like LibreOffice to open the file when I double click it in TagSpaces.
It this possible to do this with TagSpaces ? (Considering that my linux is configured correctly to open .doc/.docx/.xls/.xlsx file with LibreOffice)

What are the correct "Settings" to use for Microsoft Office file ? (.doc,.docx,.xls,xlsx.etc..)
For now, I only see 6 options in the "Settings" which are: "Choose file editor", "editorHTML", "editorText", "editorODF", "editorJSON", "editorNext".

Is there a way to use a specific program (ex: LibreOffice) to open a specific file extension ?
Thanks
ssinfod

**Comment by uggrock** [comment]
For microsoft files I will suggest to stay on the default viewer (not specifying anything) and then using the "Open Natively" button. This functionality is currently working on version 2.1.0
