### ISSUE TITLE
Renaming file on network share failed in OSX

### ISSUE THREAD

**Issue by vPriVate** [tagspaces/tagspaces#358]
Hi!
I'm using the OSX-version (latest) and trying to add tags to files on my network share. This doesn't work, a file can't be renamed by TagSpaces (Error: Renaming <filename> failed). R/W-access to this network-volume should be set up correctly, I can add or rename files in Finder to this folder manually.
With local folders it works fine. What else is needed to connect to files on a netwok share?

**Comment by vPriVate** [comment]
Let's specify the problem. These are my steps:

1. Download and install latest version (2.0.4) for Mac
2. Adding a network share (volume on my NAS, tested via AFP, SMB and WebDAV)
3. All documents within the share are available. I can open them, I even can create new files or delete existing files successfully!
4. But I can't get it working to edit a filename or add a tag.

There is a warning in the developer tools when I open my location:
```Listing directory: /Volumes/<volume_name>/.ts failed Error: ENOENT: no such file or directory, scandir '/Volumes/<volume_name>/.ts'```
Maybe it has something to do with this issue.
There is no log-entry when a file can't be renamed :(
Any ideas? Thanks for your help!

**Comment by Meralman** [comment]
Same problem here.  Totally different setup.
Windows 7 
12 gb i7 
No joy on tags.

**Comment by mgabb** [comment]
Same here. Mac OS X Yosemite, latest TagSpaces (2.0.4). Tested on shares mounted via AFP, SMB and NFS.

**Comment by lewis-whittaker-robots** [comment]
Hi all,
We are having the same problem using the tagging system, Has anyone found a way to fix this yet?

Mac OS X Yosemite, latest TagSpaces (2.0.4). Tested on shares mounted via AFP Nasbox. 

It works fine on local host when on shard documents I can see and add files but can not re-wright the names of files so can not apply tags.

**Comment by asbachb** [comment]
I dived a little into the code. Following error message is thrown:

Error: ENOTSUP: operation not supported on socket, link '/Volumes/documents/2006/tagged/A' -> '/Volumes/documents/2006/tagged/B.pdf' at Error (native)

**Comment by asbachb** [comment]
I just get a little deeper into the code. 

  ```
function doRename () {
    if (clobber) {
      fs.rename(source, dest, function (err) {
        if (!err) return callback()

        if (err.code === 'ENOTEMPTY' || err.code === 'EEXIST') {
          rimraf(dest, function (err) {
            if (err) return callback(err)
            options.clobber = false // just clobbered it, no need to do it again
            mv(source, dest, options, callback)
          })
          return
        }

        // weird Windows shit
        if (err.code === 'EPERM') {
          setTimeout(function () {
            rimraf(dest, function (err) {
              if (err) return callback(err)
              options.clobber = false
              mv(source, dest, options, callback)
            })
          }, 200)
          return
        }

        if (err.code !== 'EXDEV') return callback(err)
        moveAcrossDevice(source, dest, clobber, limit, callback)
      })
    } else {
      fs.link(source, dest, function (err) {
        if (err) {
          if (err.code === 'EXDEV' || err.code === 'EISDIR' || err.code === 'EPERM') {
            moveAcrossDevice(source, dest, clobber, limit, callback)
            return
          }
          callback(err)
          return
        }
        fs.unlink(source, callback)
      })
    }
  }
```
So the linking is not supported at least on AFP shares. For example when you set clobber to true and fs.rename is invoked everything works just fine.

@uggrock Do you think this can be fixed within the application or do wee need to report this upstream?

**Comment by asbachb** [comment]
My fix was merged in develop branch. Perhaps some one could double check if it fixes your problem and post your system / network share type combination.

**Comment by uggrock** [comment]
The fix from @asbachb is part of the prerelease [2.2.4](https://github.com/tagspaces/tagspaces/releases/tag/v2.2.4)
