### ISSUE TITLE
Icon Menu Bar Missing in File Viewer

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#364]
Version 1.12 had icons readily laid out across the top of the viewer in a menu bar for quick access. Now an extra step is required by clicking on the green circle.  Please restore option to bring back this top toolbar for faster navigation.

**Comment by uggrock** [comment]
this is the current design of the perspectives, if you wish you can create one of your own. All perspectives all now in seperate repos, so they can be easily forked.
