### ISSUE TITLE
Using extended attributes?

### ISSUE THREAD

**Issue by vsilv** [tagspaces/tagspaces#365]
Dear Ilian,
I see problems when I want to tag files of source code, since renaming is not in order here. You probably know that many file systems support extended attributes (refs [here](https://en.wikipedia.org/wiki/Extended_file_attributes) and [here](http://www.lesbonscomptes.com/pages/tagfs.html)) and I am aware that they are kinda problematic for NTFS, but apart from this, what do you think about using this possibility? I assume that you probably have better to do than to implement this option, so I would like to ask you to estimate the amount of implementing this, since I do not have the oversight over your project. I would be willing to open a new fork or branch for this purpose because I am really interested in bringing this into existence.

Let us for generality assume that for now I am only interested in ext4.

**Comment by retorquere** [comment]
Ntfs could in principle use parallel streams; they're sort of second files that live under the same filename, and they survive renames. The problem is that it won't survive being copied to other filesystems or cloud sync

**Comment by uggrock** [comment]
Extended attributes were consider in the beginning of the project, but were rejected due the fact that they are not really cross platform, and are broken in synced folders...
