### ISSUE TITLE
V2.4 - cannot read PDF

### ISSUE THREAD

**Issue by dantveita** [tagspaces/tagspaces#366]
This is happening on my PDF's:

```PDF.js v1.1.366 (build: 9e9df56)  
Message: Cannot read property 'length' of null```

Ive seen this issue in earlier version - but thought maybe this would get fixed soon..?

**Comment by uggrock** [comment]
PDF.js has sometimes issues with opening some PDF files. We have updated the PDF.js library to the latest one for our next release, but this is not a warranty that your PDF file will be opened....
