### ISSUE TITLE
Duplicate WebDAV URL causing 400/404  - http://tagspaces/http://tagspaces/webdav

### ISSUE THREAD

**Issue by jhalsey1** [tagspaces/tagspaces#368]
I am running tagspaces using IIS, I realise this is probably unsupported but it would be great if there was a simple fix.
Whilst the interface works fine, and I can browse the webdav share, whenever I try to open/tag or perform any operation on a file it fails.
This is the log from chrome, it would appear it is trying to open each file with the wrong url:
![image](https://cloud.githubusercontent.com/assets/16433349/11999687/dc824a54-aabb-11e5-9947-60c96c9c533e.png)
If I navigate to the correct URL the webdav seems to be working fine otherwise.

Thanks for any help

**Comment by jrtolle** [comment]
If you have URL rewrite installed on IIS, you can use this rewrite rule to work around this issue.  I also included the staticContent section because I added those as well on the tagspaces folder on my install to allow those files to be loaded properly (since they were blocked by my settings).

	<?xml version="1.0" encoding="UTF-8"?>
	<configuration>
		<system.webServer>
			<staticContent>
				<mimeMap fileExtension=".json" mimeType="text/json" />
				<mimeMap fileExtension=".woff2" mimeType="font/x-woff2" />
			</staticContent>
		<rewrite>
				<rules>
					<rule name="TagSpaces_Fix" patternSyntax="Wildcard" stopProcessing="true">
						<match url="https:/tagspaces/*" />
						<action type="Redirect" url="https://tagspaces/{R:1}" logRewrittenUrl="false" />
					</rule>
				</rules>
			</rewrite>
		</system.webServer>
	</configuration>

**Comment by jhalsey1** [comment]
Great, I did actually try creating a URL rewrite but I didn't know enough about IIS to get it right! Anyway I setup a apache version and had no problems but if I ever use IIS again I will try it

**Comment by uggrock** [comment]
The webdav edition was never tested on IIS, was it possible to run with the proposed rewrite?
