### ISSUE TITLE
PDF preview not working - downloads file instead

### ISSUE THREAD

**Issue by jhalsey1** [tagspaces/tagspaces#369]
I am running 2.04 for web, however whenever I click on a pdf it tries to download instead of previewing it. Other files such as .ODF and images seem to work fine. I tied different browsers but that does not seem to be the problem. I did also try version 1.81 but it was still the same.

![image](https://cloud.githubusercontent.com/assets/16433349/12006646/17192dd8-abd7-11e5-899a-1a0c6d7530a9.png)

Thanks for any help

**Comment by jhalsey1** [comment]
EDIT: Sorry I now realise that for some reason the web install defaults to the wrong viewer in settings. Perhaps it should be changed to match the client?

**Comment by uggrock** [comment]
Thank you for issue, we will correct the default pdf viewer for the next release of TagSpaces.
