### ISSUE TITLE
HTML editor lacks "back" button while supporting link navigation -- repurpose previous/next buttons

### ISSUE THREAD

**Issue by brevilo** [tagspaces/tagspaces#37]
The HTML editor allows to navigate (follow) links present in the document. However, in 1.7.8 there's no way to get back to the original document once you followed a link. You may only reopen the document again - certainly possible but pretty inconvenient.

Proposal: use the "previous" and "next" buttons right above the HTML editor for that purpose. Along the same lines you could (and should) even reconsider what their purpose should be. Right now they navigate between files *in the current folder* (ordered list). Wouldn't it be better if they could be used to navigate the *history of recently opened files* instead? We could factor this second part into its own issue if you want...

Cheers

**Comment by uggrock** [comment]
implemented

**Comment by brevilo** [comment]
thanks :+1:
