### ISSUE TITLE
plays some webm videos but not others

### ISSUE THREAD

**Issue by jim1001** [tagspaces/tagspaces#370]
Thank you for sharing TagSpaces.

I can play some webm videos inside TagSpaces but not others. Any idea why? 

ps:  I know they are all valid files as they play fine in another video player.  
pps: using TagSpaces 2.0.1 on Windows 7 Pro SP1

Best wishes,
Jim

**Comment by uggrock** [comment]
The Windows, Linux and OSX versions of TagSpaces are based [nw.js](https://github.com/nwjs/nw.js/), which does not include support for commercially licensed decoders e.g. for mp3 or mp4. But as much as I know there is a support for webm files. Can you send us a webm file which does not play, for further investigation.

**Comment by jim1001** [comment]
Hi Ilian,

I found this one wouldn’t play in TagSpaces (Win64 v2.0.1):

https://drive.google.com/file/d/0B4ubkI1JMkLQejhZa1ltS3laSjQ/view?usp=sharing

Best wishes,
Jim
====

**Comment by uggrock** [comment]
This file appears to be corrupt somehow, I could not play it in Chrome and Firefox. Firefox says it is corrupt. So for now I will consider this issue as not related to TagSpaces/nwjs issue. 
I can play the video with my native video player on Ubuntu...

**Comment by jim1001** [comment]
OK Ilian – it plays fine in Google Photos on Chrome & IE. Also plays fine in VLC media player on my Win64 machine

Best wishes,
Jim
====

**Comment by uggrock** [comment]
Try to open it directly in Chrome or Firefox with drag&drop. Google is probably decoding the video on their servers and then stream it somehow to the browser...
