### ISSUE TITLE
Remove location (smb share)

### ISSUE THREAD

**Issue by Meralman** [tagspaces/tagspaces#371]
First off, I'm no programmer, but an avid power user.  Second, this is a brilliant concept and I want to help. 

Windows 7 (fully updated)
12gb i7

"remove location" crashes tagspaces (every time so far) for a mapped smb share in the last two cases they were mapped to y:\ and y:\pictures from my windows 10 file server.  Also crashes when not mapped.  Simply \server\pictures removal will crash it.

Ideas or suggestions as workarounds are super appreciated.
- Meral Mathews

**Comment by uggrock** [comment]
this issue is solved for version 2.7
