### ISSUE TITLE
Tags not appear in collected tags after renaming

### ISSUE THREAD

**Issue by 5TDg9** [tagspaces/tagspaces#372]
I want reopen issue #258 since it is still not properly fixed in realese 2.0.4 (windows).

After editing (renaming) a tag in the list view the tag libary doesn't get updated.
The new tag name doens't appear under collected tags.
Tags that are renamed manually in file explorer don't appear in tag library, too.

It's clear, that tagspaces won't be able to rename all the files in directories and subdirectories, but at least under collected tags they should be showing off.

**Comment by uggrock** [comment]
implemented in the next release

**Comment by uggrock** [comment]
fix in 2.1.0
