### ISSUE TITLE
Line breaks deleted after editing plain text files

### ISSUE THREAD

**Issue by 5TDg9** [tagspaces/tagspaces#373]
Using last stable TagSpaces 2.0.4 - BuildID: 2.0.4.20151120205535 (Windows 8.1).
When i edit a txt-File after pressing the save button all line breaks are gone.
Surprisingly the preview in TagSpaces still looks fine, but when i open the file in another text editor everything is written in one single line and the linebreaks where deleted.

**Comment by mladensap** [comment]
We could reproduce your issue. It will be fixed soon. Thanks for reporting.

**Comment by uggrock** [comment]
could not be reproduced in v3.x
