### ISSUE TITLE
"Open containing folder" opens wrong directory after search

### ISSUE THREAD

**Issue by 5TDg9** [tagspaces/tagspaces#374]
TagSpaces 2.0.4 - BuildID: 2.0.4.20151120205535 (Windows 8.1)

After a search for a file the function "open containing folder" in the list field doesn't work as it should.
When i search for a file in subdirectories (with parameter ?...) and then want to open the file in containing folder, tagspaces opens file explorer in the parent folder not in the folder where the file is contained.

**Comment by uggrock** [comment]
Thanks for reporting, the issue will be fixed in the next official release

**Comment by uggrock** [comment]
fixed in 2.1.0
