### ISSUE TITLE
"Connect a Location" on an iPad 

### ISSUE THREAD

**Issue by jim1001** [tagspaces/tagspaces#375]
I'm trying to "Connect a Location"  on an iPad running iOS 9.2, however I don't know what to type in the Location Path as I'm unsure of the iOS folder/directory structure. I've tried a few file managers / browsers but all just show folders without listing their full path. 

For example when I connect the iPad to a PC I can see a path <My iPad>\Internal Storage\DCIM\100APPLE. But how do I specify this location in "Connect a Location"?

Any help welcome!

Thanks,
Jim

**Comment by uggrock** [comment]
Hi Jim,

connecting external folder is not possible on iOS, due to security restriction in the operating system. You can connect only the local folder of the TagSpaces app or you can create there subfolders and connect them as separate locations.

regards,
Ilian

**Comment by jim1001** [comment]
Ilian,

Thank you for this information. Using iTunes I was able to put some files into the TagSpaces local folder & connect to that.

If I have future questions is it OK to email “contact at tagspaces.org” directly or would you like me to always go through github?

Best wishes,
Jim
====

**Comment by uggrock** [comment]
Hi Jim,

We prefer to use github for managing issues and bugs. For general questions you can contact us via the email you mentioned.

Ilian
