### ISSUE TITLE
Firefox addon disabled because unsigned

### ISSUE THREAD

**Issue by basilesimon** [tagspaces/tagspaces#376]
Hello there, 

The Firefox add-on v.1.12.0 is automatically disabled in FF 43.0, [as it isn't signed](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct).

It would be great not to ask the users to tamper with `xpinstall.signatures.required`.

Thank you!

**Comment by uggrock** [comment]
We currently do not have enough resources to support the development and test of the Firefox addon. Volunteers or any external help welcome...

**Comment by basilesimon** [comment]
What resources would you need for this, @uggrock?
If Tagspaces decides not to pursue the signing of its add-on, then the whole thing won't be available for people to download, as it won't be on the addons.mozilla.org portal.

**Comment by uggrock** [comment]
In my previous comment I was just saying that we need help with the support for Firefox. It is not only signing where somebody can help.... And all that you are saying is correct, we just don't have the time currently for setting up the signing process.

**Comment by basilesimon** [comment]
I absolutely understand, @uggrock. What I meant was asking about the resources you would need to do that - maybe I can help, or maybe I know some people who can.
Let me know!

**Comment by retog** [comment]
@basilesimon I'm curious, did you get it to run after tampering with `xpinstall.signatures.required` ? I couldn't install it but apart from presenting the dialog it doesn't seem to be do anything, at least I didn't find any file it created. I couldn’t find a way to set the local tagspaces folder (https://github.com/tagspaces/tagspaces/blob/master/README.md#run-the-firefox-extension describes how to do it when using the SDK).

**Comment by jgriessen** [comment]
I'm interested in firefox also, so I will read some on signatures.  I was able to get the addon to install, (I think it was  temporary method  [ xpinstall.signatures.required] that will die in a few weeks).  The use case I like is finding material on the web and sorting it into firefox's bookmarks tree.  I want to add using tagspaces to that method.

What would it take to add a step to the file saving that the browser addon does -- I'd like to save the selected part of the web page with the file manager dialog, then go into edit mode on that file.  I'd also like the original URL available in a variable so I could script the adding of it to the edited file as attribution and link to full article.  The editor is pretty good as is.  What if it was like on Medium.com?  Is any of that medium code FLOSS?  Probably...

Anyone else interested in such a use case?

**Comment by uggrock** [comment]
Fixed with this release https://github.com/tagspaces/tagspaces/releases/tag/v2.2.5
