### ISSUE TITLE
Android App: Slow PDF Viewer

### ISSUE THREAD

**Issue by GerardMT** [tagspaces/tagspaces#377]
On Android, the PDF Viewer is really slow. It scrolls pages fast, but the content follows the page with lag. It makes impossible to navigate correctly.

**Comment by uggrock** [comment]
we are using an extenal javascript based pdf rendering (pdf.js), which can perform poorly on old android devices.... The good news is that pdf.js is constantly improving and we are updating it on a regular bases.
