### ISSUE TITLE
Feature request: display file icons

### ISSUE THREAD

**Issue by RenaudParis** [tagspaces/tagspaces#378]
The UI is a bit austere for the moment. It could be great to remove the "DOCX", "PDF" labels and replace them with file icons.

If nw.js would offer a way to use system icons directly it would be perfect, however I doubt it.

In any way, icons for the most common file types would be easy to implement, and great for UX :)

**Comment by uggrock** [comment]
We have added in v2.5.0 different colors for different file extensions.
