### ISSUE TITLE
Long names for tag groups, breaks tag group operations button

### ISSUE THREAD

**Issue by jhalsey1** [tagspaces/tagspaces#379]
I am using tagspaces 2.04 and 2.05 web version, with google chrome.

It would seem that when a tag group is given a name too long, the options button is no longer accessible. The only solution is too either reset or manually shorten the name in the browser storage.

![image](https://cloud.githubusercontent.com/assets/16433349/12374441/6000bc6a-bc93-11e5-934e-837e8c69ecbc.png)

**Comment by uggrock** [comment]
Issue was fixed for the next release. Thanks for reporting!
