### ISSUE TITLE
Sync the tag groups with .ts/tsm.json

### ISSUE THREAD

**Issue by LinxiFan** [tagspaces/tagspaces#380]
I have tagspace installed on both Win and Mac, which are synced by dropbox. 

The "load location meta data" option is not working as I expect: ideally, it should load from `.ts/tsm.json` every time the app starts and refresh the tag listing. Any tag changes should be written back to `.ts/tsm.json` when the app exits. In this way, my Mac and Win tag groups will be synced seamless by dropbox. 

Or am I missing anything?

**Comment by JimJarvis** [comment]
And is there any way to import `tsm.json` by hand? I can't even find any reasonable way to migrate the tags from mac to windows manually. Thanks!

**Comment by deptmoon** [comment]
Hi team, I am having this same issue. When navigating on my PC through a dropbox directory the metadata tags are displayed on the files correctly - they are just not added to the tag library...

**Comment by uggrock** [comment]
Please see this article for more information: https://www.tagspaces.org/documentation/sharing-tags/
