### ISSUE TITLE
Adding Tags, wrong color

### ISSUE THREAD

**Issue by Berndinox** [tagspaces/tagspaces#382]
When adding an Tag to an File, all Tags are green, regardless of wich color is specified for the tag. 
After Adding the Tag, in the Fileslist, the Tag appears in the color as expected:

All Tags here are green
![image](https://cloud.githubusercontent.com/assets/1122698/12554576/7d36ec5a-c37d-11e5-9d5c-5e77ef2ae6f7.png)

After Adding color is right:
![image](https://cloud.githubusercontent.com/assets/1122698/12554582/8855000e-c37d-11e5-9afc-a749ef8a5d3b.png)

**Comment by uggrock** [comment]
fixed in 2.1.0
