### ISSUE TITLE
Google Chrome can not open Settings

### ISSUE THREAD

**Issue by Berndinox** [tagspaces/tagspaces#383]
When clicking the Settins icon, bottom left nothing happens.

Console says:
![image](https://cloud.githubusercontent.com/assets/1122698/12554653/d478e298-c37d-11e5-86e8-917f1a2a30e3.png)

![image](https://cloud.githubusercontent.com/assets/1122698/12554659/e6b3b690-c37d-11e5-9123-de3c3b401b42.png)

require.js:8
RegExp)?(b[g]||(b[g]={}),U(b[g],c,d,e)):b[g]=c});return b}function u(b,c){return function(){return c.apply(b,arguments)}}function ca(b){throw b;}function da(b){if(!b)return b;var c=ba;v(b.split("."),function(b){c=c[b]});return c}function C(b,c,d,e){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=e;d&&(c.originalError=d);return c}function ga(b){function c(a,k,b){var f,l,c,d,e,g,i,p,k=k&&k.split("/"),h=j.map,n=h&&h["*"];if(a){a=a.split("/");l=a.length-1;j.nodeIdCompat&&

**Comment by uggrock** [comment]
Can you share the version of TagSpaces you are using?

**Comment by Berndinox** [comment]
2.0.4

**Comment by Berndinox** [comment]
Solution See #384 - Please close
