### ISSUE TITLE
Firefox not able to open "Connect" Window

### ISSUE THREAD

**Issue by Berndinox** [tagspaces/tagspaces#384]
![image](https://cloud.githubusercontent.com/assets/1122698/12575969/e9143408-c410-11e5-82b2-ee0e85ee14fc.png)

Firefox: 43.0.1
Tagspaces: 2.0.4 Webdav Edition

**Comment by uggrock** [comment]
This issue looks very similar to #383. Can you try to load in your browser http://yourserver/templates/LocationCreationDialog.html? Perhaps you have some deployment issue...

**Comment by Berndinox** [comment]
Hy, thanks for your answer, indeed it was an config issue within nginx.

I installed Tagspaces in a subfolder of owncloud. The recommand Nginx config includes the following lines:

  location ~ ^/(build|tests|config|lib|3rdparty|templates|data)/ {
    deny all;
  }

You can see "templates", is the bad guy here. Removed and now it does work.
Please close. BR
