### ISSUE TITLE
Moving tags from one group to another is limited by monitor resolution.

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#385]
V 2.1.0 - Win8.1 64bit

This is reference to closed enhancement #196 

Transitioning to bug since there is no way to move tags from one group to another unless they happen to fit on monitor at the same time.

**Comment by uggrock** [comment]
As a workaround you can move a given tag group up or down to make it closer to another tag group and then you can use d&d of tags...

**Comment by binarybum** [comment]
Yes, but unless it was a really long tag name, it's much easier to just delete and manually re-enter the tag in another group.  
  Scrolling to accommodate a drag and drop is universal behavior across operating systems and is an expected behavior.
   I love tagspaces - but so many actions feel very foreign to the way I navigate nearly every other piece of software.

**Comment by uggrock** [comment]
this issue will be further tracked in our trello board for new ideas and suggestion https://trello.com/b/TGeG5bi9
