### ISSUE TITLE
Problems with file previews

### ISSUE THREAD

**Issue by bolfovanegas** [tagspaces/tagspaces#388]
Hi, I am starting today with tagspaces, which looks really good, 
however, while trying to start using it, I can not see any file preview.

How can I solve that?

thanks

JuanCarlos Vanegas

![screen shot 2016-02-04 at 17 37 38](https://cloud.githubusercontent.com/assets/17069133/12821979/100b78b2-cb66-11e5-9847-e7512b9825fc.png)

**Comment by bolfovanegas** [comment]
push

**Comment by bolfovanegas** [comment]
pls

**Comment by uggrock** [comment]
Hi,

sorry for my late response. The problem here is the '#' character in the name of one of your folders. If you remove it, everything should work.

kind regards,
Ilian

**Comment by bolfovanegas** [comment]
Many many many thanks for your reply!! issue is solved!!!
We will test the app for some couple of weeks and if its what we were searching for I will push my colleges to do a group donation :)

Thanks!

**Comment by bolfovanegas** [comment]
So then I continue with the learning and testing of the application, but now we are facing a new problem.
When putting a tag on files we get the error (as seen in the attached screenshot)

Is important to mention that the location of our files is our server.

Is there any way we can solve this?

thanks!

Juan Carlos Vanegas

![screen shot 2016-02-16 at 16 08 52 2](https://cloud.githubusercontent.com/assets/17069133/13080208/fb0e156c-d4c7-11e5-8f3b-d2667c0d6fd7.png)

**Comment by uggrock** [comment]
So if you are tagging files locally it works without issues ?

Can you make sure you have write access to the files in this server directory ?

**Comment by bolfovanegas** [comment]
Yes, if the files are located on my computer, it works,

But when trying with files located on a server, it present the mentioned error. 

And I have check with the ID department of my company, and yes I have the rights to manipulate that folder.

Any ideas?

many thanks for the support

**Comment by bolfovanegas** [comment]
push push bitte :)

**Comment by bolfovanegas** [comment]
After showing the problem in detail to our IT specialist, this is the question they sent for you:

Is the system capable to handle windows network share (samba share) ?

If yes, can also an Apple computer also access?

Looking forward to hearing from you

**Comment by uggrock** [comment]
Yes, TagSpaces works with windows network share. And recently we tested it successfully on Apple connected with a Samba share.

**Comment by bolfovanegas** [comment]
Hi again,

we tried to connect to the sbm share with a domain admin account and also we tried to grant read/write/delete for all users on the files on the share - still we cant tag files, tagspaces gives us the message "Alert: renaming xyz failed".

Do you have any clue?

**Comment by bolfovanegas** [comment]
PS: We just tried to connect to a afp share and tag a file with tagspaces, same problem...

**Comment by uggrock** [comment]
Please try the new 2.1.4 release, If the problem with shares still exists please open a new issue.
