### ISSUE TITLE
Program crashes when clicking files

### ISSUE THREAD

**Issue by SydneyNS** [tagspaces/tagspaces#389]
So I've been using this program with no problem so far and there haven't been any changes made to the program when this started happening. I was using version 2.0.4. I thought today I should upgrade to the latest version and thought that maybe my old version was the cause, but it keeps happening with the newest version too.

I am running this on windows 7 32 bit. Perspective during crash was grid. Every time I go and click a file in the same directory I've been working in for a long time now, it causes the program to crash. So now, I can't tag my photos anymore because clicking them to view them in the side panel causes the program to crash. I'm going to restart my computer, clear cache, etc. and see if that fixes anything.

**Comment by XzK** [comment]
Hello @SydneyNS,

We did several tests with TagSpaces on Windows 7 32-bit and did not find such a problem.

> I'm going to restart my computer, clear cache, etc. and see if that fixes anything.

Do things changed after that?

**Comment by SydneyNS** [comment]
Yes that solved things. The program wasn't updating itself either, so I downloaded the newest version. Between those 2 things I did, the problem has gone away.
