### ISSUE TITLE
Dragging files from tagspaces to other apps

### ISSUE THREAD

**Issue by jmm** [tagspaces/tagspaces#39]
Is there a way to drag files from the TagSpaces list to other apps? For example, drag a URL shortcut into a web browser window? I just found out about TagSpaces today and I'm intrigued, but this is one of the first things I want to do and it doesn't seem possible. There doesn't seem to be any part of the list item for a file that I can grab to drag into another window. This is with the native app in Windows 7.

**Comment by sunjam** [comment]
+1 on drag and drop, both to and from Tagspaces.

**Comment by uggrock** [comment]
Dragging file to TagSpaces is implemented since  1.8.6 . See this video http://www.tagspaces.org/content/v1.8/tagspaces-drag&drop.mp4 . I think dragging files from tagspaces is with the current state of the web technologies not possible.

**Comment by jmm** [comment]
Too bad :( Thanks @uggrock.
