### ISSUE TITLE
Android app shows no text

### ISSUE THREAD

**Issue by miho87** [tagspaces/tagspaces#390]
Hello!
I installed tagspaces with Android x86 on my Acer W500 tablet. In principle, tagspaces seems to work, but there is no text. I see the grey background on the right panel and some colored boxes (which should contain some tags) on white background in the left panel - but the text is completely missing. I know that Android x86 is a bit experimental, but everything else is working so far. I hope you can fix this problem :-) Does the app use any special fonts or something like that?
I was not able to create a screenshot so far, but I could provide a picture if it helps.

Thanks in advance for any help!

**Comment by XzK** [comment]
Hello @miho87,

Yes, please. Everything you can provide is welcome.

Make sure you are using the latest version of TagSpaces, which is 2.1.1

**Comment by uggrock** [comment]
Can you please confirm if this issue exist in the new 2.1.4 release?
