### ISSUE TITLE
Android App.  On screen keyboard closes automatically after deleting each word instead of continuously deleting.

### ISSUE THREAD

**Issue by klundry** [tagspaces/tagspaces#391]
If I want to delete a whole line or multiple words and hold down the backspace key, it will stop deleting after each word and the keyboard will close.  I then have to tap in the document again to reopen the keyboard and continue deleting the next word.

**Comment by uggrock** [comment]
The issue was reproduced ...

**Comment by uggrock** [comment]
Issue could not be reproduced anymore in version 2.7.
