### ISSUE TITLE
Chrome extension downloads text file instead of saving in the current location.

### ISSUE THREAD

**Issue by klundry** [tagspaces/tagspaces#392]
When editing a text file through tagspaces chrome extension, if I click save the file is downloaded as a new file to my downloads directory.  The expected function of saving an existing file that I am editing is for it to save the file over the original file in the original location that I opened it from.

This is somewhat similar I think to issue [#190](https://github.com/tagspaces/tagspaces/issues/190) but that is saving a new file, where as I am just trying to edit and save an existing file.

Platform: Chrome OS

**Comment by XzK** [comment]
Hello @klundry,

Because of the security measures that Google took for Chrome much of the functionality associated with the management of files, it is not possible. We keep everything possible.

**Comment by uggrock** [comment]
Due to changes in Chrome/Chrome OS  the TagSpaces extension offers meanwhile almost only read only functionality. For file saving we found a workaround which is exactly the functionality what you describe. That's why the extension in Chrome is named "TagSpaces Lite"
