### ISSUE TITLE
MacOS X permissions not executable

### ISSUE THREAD

**Issue by mneilly** [tagspaces/tagspaces#393]
On the latest Mac OS X 64 bit 2.1.1 version I had to chmod +x on both TagSpaces.app/Contents/Frameworks/nwjs\ Helper.app/Contents/MacOS/nwjs\ Helper and TagSpaces.app/Contents/MacOS/nwjs for it to run.

I see there was a past issue indicating that this was resolved but it appears to be an issue again...

**Comment by XzK** [comment]
Hello @mneilly, 

Please try the suggestion here for solving this problem: [Doesn't work on OS X yosemite. #220](https://github.com/tagspaces/tagspaces/issues/220).

Let us know if works for you.

**Comment by mneilly** [comment]
Ah, okay. That's strange. If I double click the zip file in downloads which uses the archive utility all is fine. I had run unzip on the command line which is what appears to not work. I guess there is special processing going on since it is an app and not just an archive? Anyway, thanks for the response.

**Comment by mneilly** [comment]
FWIW - It might be worth updating the OS X section on installation instructions page to indicate "you must double click the downloaded zip file in finder to install properly" or something along those lines. That would have saved me some time...

**Comment by uggrock** [comment]
Thank your for your hint, we just updated our website http://www.tagspaces.org/documentation/installation/#OSX
