### ISSUE TITLE
tagspace on andriod can't see synced owncloud subfolders

### ISSUE THREAD

**Issue by offerlam** [tagspaces/tagspaces#394]
Hi.

in my andriod one+ phone i have both tagspace and owncloud installed. I don't know why but for some reason when i brows my phone from tagspace to find a new target folder. I don't see the synced folders from owncloud? I can with other apps but not tagspace.

am i just "holding it wrong"?

**Comment by offerlam** [comment]
Any reason no one answers? am i not making since? or missing some information?

**Comment by uggrock** [comment]
Hi,

sorry for the delayed answer. I am not sure how exactly the owncloud app works, but I think it does not sync automatically your folder and files. That's why we recommend to use apps such as [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite) for creating local copies of your remote folders, which can be later displayer within TagSpaces.

kind regards,
Ilian

**Comment by offerlam** [comment]
Hi Llian,

In my original post i wrote that i could see subfolders with OTHER apps. like ES file explorer. Now if you were right i shouldn't be able to see subfolders with any app after the owncloud app syncs. 

so i don't thats the case here..

**Comment by offerlam** [comment]
please reopen the case.. i can't do that apparently

**Comment by paapereira** [comment]
I also have the same problem (Nexcloud in my case).
In the Nextcloud app I download a specific folder, but in Tagspaces I cannot see the folders or files I downloaded. The files and folders are visible to other apps (file explorers, via FTP, etc.).
Very strange.
Android 7.1.1, Nexus 6P, but in versions 6.1.1 and 7.0 the same problem was occurring.
Can I get you some more info to help you?

**Comment by uggrock** [comment]
Can you please try to restart your phone and try again to connect the folder from nextcloud in tagspaces?

**Comment by paapereira** [comment]
Already tried several times, but just tried again with no luck.

In the Location Path I tried the following combinations:
- storage/emulated/0/Android/data/com.nextcloud.client
- sdcard/Android/data/com.nextcloud.client
- /sdcard/Android/data/com.nextcloud.client

In the default SDCard location, if i navigate to the nextcloud directory I cannot see any files either.
: (

Really like your app.

I'm thinking about going pro.

My current setbacks:
- Android app not working for me (this issue)
- Tag searches like "+Tag*"
- Some visual/design optimizations

I added my suggestions some time ago in uservoice:
https://tagspaces.uservoice.com/users/285802223-paulo-pereira

**Comment by johjeff** [comment]
Using OwnCloud, and likewise was not able to see the files in the "sync'd" folder. Through the OwnCloud app, I 'downloaded' each file and was able to see them in Tagspaces then. Apparently the OwnCloud app doesn't actually sync the files locally to the Android device unless you download the file. I imagine NextCloud works in a similar fashion.

That sucked, so I switched to FolderSync Lite on my Android phone and sync the folder/files 2-ways between Android and OwnCloud. Seems to be working OK.

**Comment by uggrock** [comment]
A third part app such as FolderSync is also our recommendation for this use case.
