### ISSUE TITLE
thumbnail script?

### ISSUE THREAD

**Issue by laru** [tagspaces/tagspaces#397]
Thanks for the excellent software. I am a qualitative researcher, and I think this will be really useful for coding and managing data across platforms.

I saw on the changelog that there should be a thumbnail generating script included. I am not seeing thumbnails for any file types, and particularly need to for jpg.
Is there a way to see if this script is running?

best, laru

**Comment by uggrock** [comment]
Hi Laru,

in a recent blog post I described the current status of the thumbnails support in the application. Please check it out here: http://www.tagspaces.org/blog/tagspaces-2-1-released/#thumbnails

regards,
Ilian

**Comment by laru** [comment]
thanks for the reply.
sorry for the basic question, but does this mean I can only run the script
on a linux machine? I'm currently working on a mac.

regards,
laru

**Comment by uggrock** [comment]
the script is made for Linux, but it can be easily transformed to run
under OS X.

regards,
Ilian

On 25.02.2016 18:20, laru wrote:
> thanks for the reply.
> sorry for the basic question, but does this mean I can only run the script
> on a linux machine? I'm currently working on a mac.
>
> regards,
> laru
>
> On Wed, Feb 24, 2016 at 6:55 PM, Ilian <notifications@github.com> wrote:
>
> > Closed #397 <https://github.com/tagspaces/tagspaces/issues/397>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tagspaces/tagspaces/issues/397#event-564046669>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tagspaces/tagspaces/issues/397#issuecomment-188887579>.
>


-- 
------------------------------------
Ilian Sapundshiev (Dipl. Inf.)
TagSpaces Founder
------------------------------------
email: ilian@tagspaces.org
web: tagspaces.org
twitter: @tagspaces
------------------------------------
