### ISSUE TITLE
Upgrading to 2.1.2 loses all tag data

### ISSUE THREAD

**Issue by riazarbi** [tagspaces/tagspaces#399]
Hi, I've been using tagspaces since 1.12. Usually, when you release a new version, I delete everything in my tagspaces folder except for the data subfolder and then drag all the new files in. This keeps my tag groups, tags and tag colours all persistent across versions. 

With 2.1.2 and the move to Electron this method does not preserve tag data in the app. 

Please could you give me a method to keep all my tags appearing in the left hand pane, organised in their tag groups with their tag colours while upgrading to 2.1.2?

**Comment by hybridview** [comment]
In my case (NOT in portable mode), I traced File System IO and found that my 2.1.1 version is using ../AppData/Local
and 2.1.2 is using  ../AppData/Roaming

When I copied 
"%USERPROFILE%\AppData\Local\TagSpaces\Local Storage"

to

"%USERPROFILE%\AppData\Roaming\TagSpaces\Local Storage"

all of my tags came back. I don't have much knowledge about how APPDATA folders are chosen, so think of this as a temp fix.

**Comment by riazarbi** [comment]
Thanks, that worked.

**Comment by uggrock** [comment]
solution described on https://github.com/tagspaces/tagspaces/releases/tag/v2.2.1
