### ISSUE TITLE
No menu, just background on WIN

### ISSUE THREAD

**Issue by zhoubinx** [tagspaces/tagspaces#400]
I donwloaded the latest 2.1.1, 32  of WIN. And tried the 32 ver on my WIN7 and WIN10 computer. But I only got a background page, no menu, no button, no nothing. And waited for 10 mins nothing happens.

Can anyone give some help! many many thanks in advance!

**Comment by uggrock** [comment]
Hi,

can you post a screenshot of the application? You have probably a similar issue like #396 .

regards,
Ilian

**Comment by zhoubinx** [comment]
![44](https://cloud.githubusercontent.com/assets/17607309/13546526/70d484da-e2eb-11e5-8c2f-21e33c0c3f46.jpg)

**Comment by zhoubinx** [comment]
Hi, Ilian, sorry for the late answer. Here it is screen shoot of what I got...
It seems like a blank webpage. I guess. Tagspace is loading something from internet, but can't success...
Wait 10 mins nothing happen...

**Comment by uggrock** [comment]
This looks like something went wrong with the configuration of TagSpaces. You can try to start it again after cleaning the cache of the app by just removing this folder c:\user\your_user_name\AppData\Roaming_or_Local\tagspaces. TagSpaces is running completely offline so it is not loading anything from internet. The only call it makes is for checking if a new version is available, which can be disabled in the settings.

**Comment by claell** [comment]
@uggrock I would propose to only close issues after they have been confirmed to be fixed. Also it is rather uncommon to close all issues marked as enhancement. How do you keep track of those then? I would expect to close them after they have been implemented.

**Comment by uggrock** [comment]
@claell for enhancement requests we are using https://tagspaces.uservoice.com/ . This way we are trying to separate the real issues from the ideas coming from the users.

**Comment by claell** [comment]
Alright. Although tags on Github can used for separation as well.

**Comment by zhoubinx** [comment]
Thanks, @uggrock, I downloaded the zip file file again. Than it works now. I don't know what different between this download and previous download. Thanks! I love your project!
