### ISSUE TITLE
Thumbnails in WebDAV version 2.1.1 missing iPad

### ISSUE THREAD

**Issue by petkos01** [tagspaces/tagspaces#402]
I can't see thumbnails in Grid and ImageSwiper view of WebDAV version. And I cant see pictures while 
full screen in ImageSwiper mode. All other viewers and editors working. Browsing on iPad Safari. In iPad Chrome, thumnails in Grid mode are visible but ImageSwiper is still not working. When browsing from Windows Desktop ImageSwiper is without thumbnails but allows full screen mode swiping through images.

![image](https://cloud.githubusercontent.com/assets/17671414/13547217/5ed26678-e2c1-11e5-952b-e5ef630734dd.png)
![image](https://cloud.githubusercontent.com/assets/17671414/13547218/5ef7ce2c-e2c1-11e5-8530-08283b71c092.png)
![image](https://cloud.githubusercontent.com/assets/17671414/13547222/820ee9ae-e2c1-11e5-9c6c-91a165877871.png)

**Comment by uggrock** [comment]
a double to #450
