### ISSUE TITLE
Unable to rename file with comma in filename. WebDAV, OwnCloud.

### ISSUE THREAD

**Issue by petkos01** [tagspaces/tagspaces#403]
In my case on my OwnCloud one pdf filename was with comma. I wasn't able to rename it in WebDAV Tagspaces but I was able to add tag, which is renaming of original file in fact.

**Comment by uggrock** [comment]
On http://demo.tagspaces.org which is running owncloud as backend, renaming and tagging files with comma works. Can you please provide more specific information?

**Comment by petkos01** [comment]
I've tried it on demo, the same problem. Insrted comma to file, refreshed and it has changed to %2c and after that it's impossible to change it, only in Owncloud. 
![image](https://cloud.githubusercontent.com/assets/17671414/13553771/a4f4a484-e38b-11e5-82e5-f02b078e0018.png)

![image](https://cloud.githubusercontent.com/assets/17671414/13553755/37f55b3a-e38b-11e5-8289-b2efd1ac8b9a.png)
![image](https://cloud.githubusercontent.com/assets/17671414/13553756/3818fd6a-e38b-11e5-83e3-8c486226260b.png)
![image](https://cloud.githubusercontent.com/assets/17671414/13553757/38196c6e-e38b-11e5-9e1c-4f092412e185.png)
![image](https://cloud.githubusercontent.com/assets/17671414/13553758/381ab45c-e38b-11e5-91ea-b10d86797961.png)
![image](https://cloud.githubusercontent.com/assets/17671414/13553759/381ba06a-e38b-11e5-9c22-fa63c65794bd.png)

**Comment by uggrock** [comment]
could not be reproduced on version 3.x with webdav
