### ISSUE TITLE
When I sort files by Last Modified in PerspectiveList and swap to PerspectiveGRID, files are sorted by filename.

### ISSUE THREAD

**Issue by petkos01** [tagspaces/tagspaces#404]
Selected sorting is not preserved in PerspectiveGRID and there is no way how to change it in this view.
TagSpaces v 2.1.1

**Comment by uggrock** [comment]
Perspectives are kind of sub apps for TagSpaces, with own logic and functionality. Things like file sorting are not persisted across perspective and have to be implemented in every one. So what we miss here is the ability to sort file in grid perspective which is a enhancement request.
