### ISSUE TITLE
Issue running app on mac osx

### ISSUE THREAD

**Issue by qbektrix** [tagspaces/tagspaces#407]
I am new to the app and I am running it on Os X 10.11.3. I unzipped the file and ran it. I selected the folder, but I am unable to create new files in the folder. I have attached the screenshot of the app along. Do I have to install any prerequisite for the app to run? Like electron or nodejs?  
![screen shot 2016-03-12 at 11 53 30 pm](https://cloud.githubusercontent.com/assets/3854350/13724929/12106270-e8ae-11e5-8084-6188bdce4b05.png)

**Comment by XzK** [comment]
Hello @qbektrix, please follow the instructions [here](http://www.tagspaces.org/documentation/installation/#OSX).

**Comment by uggrock** [comment]
It appears that you are also facing this issue #396 . We are currently working to fix this issue. In the meanwhile you can try an older version of TagSpaces from https://github.com/tagspaces/tagspaces/releases/tag/v2.1.0
