### ISSUE TITLE
nginx webdav list folder as a file

### ISSUE THREAD

**Issue by niphor** [tagspaces/tagspaces#409]
[web.api.js#L162](https://github.com/tagspaces/tagspaces/blob/master/data/web/web.api.js#L162)

using arut's nginx-dav-ext-module
folder has`<D:resourcetype><D:collection/></D:resourcetype>` element and `contentlength >0`

```
if (typeof dirList[entry]._namespaces["DAV:"].getcontentlength === 'undefined' ||
              dirList[entry]._namespaces["DAV:"].getcontentlength._xmlvalue.length === 0 ||
             (dirList[entry]._namespaces["DAV:"].resourcetype._xmlvalue.length === 1 && dirList[entry]._namespaces["DAV:"].resourcetype._xmlvalue[0].localName === 'collection')
            ) 
```
should work

**Comment by uggrock** [comment]
We never tested TagSpaces with nginx, but we are accepting pull requests.
