### ISSUE TITLE
nginx webdav PROPFIND returns code 207 multistatus, but real status is in D:propstat

### ISSUE THREAD

**Issue by niphor** [tagspaces/tagspaces#410]
[webdavlib.js](https://github.com/tagspaces/tagspaces/blob/master/data/web/webdavlib/webdavlib.js)

when create a file , tagspaces send a propfind request to detect whether file is exsit or not

but using arut's nginx-dav-ext-module
it returns 207,and real `404 Not Found` is in `D:propstat`

i use `Object.defineProperty` to rewrite the value  in ajaxHandler

and get the right http code in Multistatus class

**Comment by uggrock** [comment]
We never tested TagSpaces with nginx, but we are accepting pull requests in this direction.

**Comment by Offerel** [comment]
@niphor could you please make a Pull Request? I have the same problem, but i dont know, what i should change, to get it to work.

**Comment by niphor** [comment]
@Offerel 

sorry
besides i had deleted tagspaces long time ago...
it is just an ugly patch

becasue tagspaces only check if status==404 and `webdavjs` can't set right status to response body

i do some check at 
[client.js#L731](https://github.com/sara-nl/js-webdav-client/blob/7106484faadc26fb817b032365f015d9b8b9409f/src/client.js#L731)

if it is nginx's 404 xml

i use `Object.defineProperty` to overwrite `ajax.status`

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing
