### ISSUE TITLE
No display of local image in MarkDown file

### ISSUE THREAD

**Issue by fxshpac** [tagspaces/tagspaces#415]
Just to report an issue with Android version 2.1.1 (doesn't have this issue with Windows version 2.1.1).

Firstly here is the file structure where I saw the issue
```
/sdcard/Documents/1.md
/sdcard/Documents/1.jpg
```

Inside `1.md` I have one single line below to link to the jpg file
`![](1.jpg)`

When I exit out of editing mode and re-open 1.md file, tagspaces doesn't display the image as expected and simply shows blank screen. For testing purpose, I open the same file using Windows version, it displays the image successfully.

Please confirm it's a bug and whether it will be fixed in the next release. Thx

**Comment by uggrock** [comment]
This issue is already fixed in the new release coming next week.

**Comment by fxshpac** [comment]
@uggrock thx a lot for the quick response. Look forward to test it again once new version is available.

**Comment by uggrock** [comment]
@fxshpac  v2.1.4 was released yesterday, so I will close the issue.

**Comment by fxshpac** [comment]
I have confirmed the new version has it fixed. Thx
