### ISSUE TITLE
Having signature of the deb file

### ISSUE THREAD

**Issue by bobo-romania** [tagspaces/tagspaces#417]
Hi,
Your application seems to be really interesting.
Following the linuxmint event (http://blog.linuxmint.com/?p=2994)
Is there a signature available on your last release, at least for linux ? 
In the best case, an .asc signature of the file linked to your public pgp key. or 
a sha256/512sum of your version of the file.

Thanks anyway 
See you

Bobolica

**Comment by jgriessen** [comment]
I would like to help test new code also -- so, later when, "Signing will be mandatory with no override, in Firefox 46 beta and release versions", How do we help you get the add-on signed?

For now, I will work around it and disable signing..but that will go away soon.

**Comment by uggrock** [comment]
Signing deb packages is great(almost mandatory) feature, any contribution or technical advice is welcome.

**Comment by bobo-romania** [comment]
Hi, 
In order to  make an .asc signature of your deb file, you will need a pgp key. It is based on the private / public key concept. 
You can find a good ressource on the subject and advices about how to create one here.
https://emailselfdefense.fsf.org/en/

Basicaly, This guide explain how to create a pgp key for an email adress but you'll be able to use it to sign deb files.
You'll need to use thunderbird email client and enigmail extension (or you could do this in a more geeky way, it's also explain in the adavanced part)

Then you can sign your deb file with this 
`gpg -b mydebfile.deb`

It will produce a .asc file which is the signature
You should afterwat send you public key to a server in order to allows people to get your public key (and be sure that you are the original maker.

If you want to spend your weekend generating you pgp key (i mean assuring you're doing it in a "trustable situation", here is two guides:

- Best practices https://help.riseup.net/en/gpg-best-practices
- Very carefully best practices https://github.com/flamsmark/documentation/blob/master/gpg/smartcard-keygen.md

I hope it will help you.
See you



There is also a more geeky way that 
http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/

**Comment by uggrock** [comment]
fixed with this release https://github.com/tagspaces/tagspaces/releases/tag/v2.2.5
