### ISSUE TITLE
Linux portable mode script

### ISSUE THREAD

**Issue by Nebucatnetzer** [tagspaces/tagspaces#418]
I've created a little bash script to make it easier to launch Tagspaces in portable mode.
I don't know if it's the correct way to do it but it works quite well.
It changes into the directory of the tagspaces binary and executes it from there.
So that it saves the files every time in the same place.
 
**tagspaces.sh**
```
#!/bin/bash
filepath=$(find ~/ -type f -name tagspaces)
folder=$(dirname $filepath)
(cd $folder && exec $filepath -p)
```

**Comment by uggrock** [comment]
Thank you for the contribution.
