### ISSUE TITLE
Embedded images in html are not showing in preview anymore

### ISSUE THREAD

**Issue by rancidfrog** [tagspaces/tagspaces#419]
In previous versions images embedded in html file were showing, but latest version shows:
![empty image](http://s7.postimg.org/jft1p9p9n/Screenshot_from_2016_03_27_03_26_40.png)

**Comment by XzK** [comment]
Hello @rancidfrog,

I tried with my HTML document and everything is just fine.

Please make sure you are using the latest version of [TagSpaces](https://github.com/tagspaces/tagspaces/releases) and verify that the path to the image is correct. For this purpose, you can use devleoper tools (F12 keyboard button) to debug.

**Comment by uggrock** [comment]
Hi,

I can reproduce this issue in 2.2.0, a fix will be provider in the next pre-release coming next week.

kind regards,
Ilian

**Comment by uggrock** [comment]
fixed in v2.2.1
