### ISSUE TITLE
Use of a "sidecar" file for tags vs files

### ISSUE THREAD

**Issue by plinioseniore** [tagspaces/tagspaces#420]
Hi, as listed in your FAQ looks that is yet in the queue an option to save the relation between tags and files into an external file instead of use the filename itself. Is there any planning for this feature?

**Comment by plinioseniore** [comment]
Having some experiments, at least on Windows the use of shortcut links looks a good option to have files tagges without have to add the tag inside the filename itself, as it will be included into the shortcut filename.

This can be considered a "cheap" alternative, with the only drawback that it doesn't preview the document inside TagSpaces.

**Comment by uggrock** [comment]
The sidecar file functionality is implemented and will be release in the next two weeks.

**Comment by plinioseniore** [comment]
That's great!
