### ISSUE TITLE
Error: Cannot Rename Files on Server

### ISSUE THREAD

**Issue by mikaeleemiller** [tagspaces/tagspaces#425]
Started using tagspaces at work to tag a huge image library and it works great with all our files stored on a dropbox. However, when we try to tag/rename a file on our internal smb server it comes up with an error.

Anyone know how to solve this? Is it something to do with permissions or...?

Any help would be greatly appreciated!

**Comment by asbachb** [comment]
perhaps same issue as #358

**Comment by asbachb** [comment]
Could you test latest develop branch and check if the problem still persists?

**Comment by uggrock** [comment]
the fix can tested here https://github.com/tagspaces/tagspaces/releases/tag/v2.2.4

**Comment by uggrock** [comment]
fixed in prerelease

**Comment by mikaeleemiller** [comment]
Issue fixed with the latest release thanks everyone!
