### ISSUE TITLE
Norton removes tagspace.exe

### ISSUE THREAD

**Issue by lyckade** [tagspaces/tagspaces#428]
Norton removes the tagspace.exe file, because of following issue: 
http://us.norton.com/security_response/writeup.jsp?docid=2010-051308-1854-99

In times of encryption viruses it is a high risk to add general exceptions.

tagsspace version: 2.2.1 win64
Norton does not provide a version nr. But norton is up to date (9.4.2016)

To solve that issue norton provides the possibility to add the software on a white list:
https://submit.symantec.com/whitelist/

I know it is not really an issue of tagspace, but adding the software to antivirus whitelists should be also included to the build/publishing process.

**Comment by uggrock** [comment]
Current version of the application was send recently for whitelisting. Thank you for your hint.
