### ISSUE TITLE
Unable to install Linux 32 bit (tgz)

### ISSUE THREAD

**Issue by daj63** [tagspaces/tagspaces#429]
Hi,
Just been trying to install tagspaces for linux (as above).  During the install there is an error which is preventing the install.  Seems it is to do with an out of date 'electron'  - see attached screenshot from the AUR.  Is there any way around this isssue?
Thanks.

![electron](https://cloud.githubusercontent.com/assets/18384903/14413397/92cfbf2c-ff70-11e5-9c99-6503f3731532.png)

**Comment by XzK** [comment]
Hello @daj63,

Would you be so kind to provide a screenshot and more information about this error?

**Comment by daj63** [comment]
Hi

I am using Manjaro which is based on Arch Linux.  I run it on a 32bit system.

I attach two screenshots.  One shows the start of the installation and the second shows where the failure to install occurs.  Seems to be related to an out of date electron package in the Arch repository.

![start of installation](https://cloud.githubusercontent.com/assets/18384903/14424189/a462cdb2-ffd7-11e5-96a9-c14e988f7332.png)

![where failure to install starts](https://cloud.githubusercontent.com/assets/18384903/14424207/b5e843b4-ffd7-11e5-9c50-9b8b4ebdaa05.png)

If you need any more information let me know.

David

**Comment by uggrock** [comment]
Hi David,

we are officially not supporting Arch Linux. The arch package is maintained by volunteers. I think you can contact them here https://aur.archlinux.org/packages/tagspaces/

kind regards,
Ilian
