### ISSUE TITLE
Character ! in directory name makes folder view blank due to JS error.

### ISSUE THREAD

**Issue by hybridview** [tagspaces/tagspaces#432]
I added this comment to an existing bug report, but that bug report stated to make a more significant change to the architecture, while fixing this issue simply requires a few lines of code. The title of this issue report describes what triggers the error, but feel free to change the title to something like below if you want it to explain technical details.
_"Folder names must be escaped to prevent javascript errors due to bad jquery selector."_

Since in TagSpaces, the directory name is used as a jquery identifier, you just need to make sure you escape characters that are not allowed as a jquery selector. I had this problem due to "!" at the start of my directory name (To keep it at the top when sorting in the OS). Every time I update to newest version of TagSpaces, I just edit this file to escape those characters before performing the query. My code is below. 

**In resources/app/js/directories.ui.js**

function jq( myid ) {
    return myid.replace( /(!)/g, "" ); // Simple fix that cured my issue only.
    // return myid.replace( /(:|.|[|]|,)/g, "\$1" ); // Untested, but thorough escape regex for all bad chars.
}

function generateFolderTags(tags, element, menuItem) {
var $tagsElement = null;
if (element) {
var tagId = element.attr('key').split(TSCORE.dirSeparator).pop();
**$tagsElement = $('#' + jq(tagId));**
if ($tagsElement.length === 0) {
$tagsElement = $('

');
$tagsElement.attr('id', tagId);
var $el = element.parent().find('.accordion-body');
if ($el.length > 0) {
$el.prepend($tagsElement);

}
} else {
$tagsElement.empty();
}
}

**Comment by uggrock** [comment]
Thank you for the proposal!
The problem I see here is the case where i have a file tagged with "some!tag" and "sometag". In this case the produced selector is not unique. I was thinking about using base64 on the tag name, but there are issues apperantly with unicode characters ...

**Comment by hybridview** [comment]
Very good point. I did some more research and found a method that properly escapes instead of just removing the character. See my fiddle link below for code and demo:
[https://jsfiddle.net/ydq9fmj5/](https://jsfiddle.net/ydq9fmj5/)

**Comment by uggrock** [comment]
fixed for the next release (2.7)
