### ISSUE TITLE
Relative icon in Linux

### ISSUE THREAD

**Issue by rhoconlinux** [tagspaces/tagspaces#434]
Hi there, 
I've just noticed that the **icon** referred on the .`desktop` for linux is directed to
`icon=/usr/share/pixmaps/tagspaces/tagspaces.svg`
Instead, in order to let different icon themes override  the icon of the app, it should be at:
`icon=/usr/share/pixmaps/tagspaces.svg`

Cheers!

PS. I had to modify the desktop file in order to change the icon, which is extremely not convenient :)

**Comment by uggrock** [comment]
For building the deb packages we are relying on the project [electron-builder](github.com/electron-userland/electron-builder), so please address this issue there.
