### ISSUE TITLE
Improved Login Screen

### ISSUE THREAD

**Issue by c0fe** [tagspaces/tagspaces#436]
I have tried the demo program and find the login screen to be a bit dated, I would like to request a feature to improve the design of the login screen from being a popup window message to a page.

**Comment by joephein** [comment]
Yes this will also be much easier with those password managers around. It is much more difficult to get this working with these pop-up authentication dialogs.

**Comment by Buena-Vista** [comment]
is this related to the pro version?  i'm seriously considering the permanent license but won't buy software that requires internet access to a specific server (after 1 time license validation and registration).  Do you have to logon regularly to the pro version?  There's no logon for the free one unless I'm missing something.
Thanks.

**Comment by uggrock** [comment]
The login screen is related only for the webdav version of the application. This is version which you can host at your own. The free and the pro desktop versions of the application are running completely offline and serverless.

**Comment by uggrock** [comment]
this issue will be further tracked in our Trello board for new ideas: https://trello.com/b/TGeG5bi9
