### ISSUE TITLE
How can you download images back from the rich text note?

### ISSUE THREAD

**Issue by NoTalentGeek** [tagspaces/tagspaces#437]
I am talking about feature in Evernote that you can just right click image, then "Download", and then you finally choose the directory where the image will be saved.

How can I do this in TagSpaces?

**Comment by uggrock** [comment]
Hi,

In HTML viewing mode, you can just drag the image you want and drop it on your desktop for example. Currently there is no dedicated download button.

kind regards,
Ilian
