### ISSUE TITLE
"Open file natively" doesn't work on search results

### ISSUE THREAD

**Issue by mihao** [tagspaces/tagspaces#438]
On Android, when I type something in the search box, and try to open a pdf file natively, the pdf viewer is launched, but it cannot display the file (irrespective of which app is used as a pdf viewer). Everything works fine again when the search is cleared (after clicking on the rubber icon). The problem doesn't occur on Windows.

**Comment by mihao** [comment]
I looked at the intent sent from the app:

Data:
/sdcard/pdf/test.pdf#Intent;action=android.intent.action.VIEW;type=application/pdf;launchFlags=0x3000000;component=uk.co.ashtonbrsc.android.intentintercept/uk.co.ashtonbrsc.intentexplode.Explode;end

URI:
/sdcard/pdf/test.pdf#Intent;action=android.intent.action.VIEW;type=application/pdf;launchFlags=0x3000000;component=uk.co.ashtonbrsc.android.intentintercept/uk.co.ashtonbrsc.intentexplode.Explode;end#Intent;action=android.intent.action.VIEW;end

It doesn't look correct...

**Comment by uggrock** [comment]
Thank you for reporting, we were able to reproduce the issue.

**Comment by uggrock** [comment]
fixed in the next release
