### ISSUE TITLE
"Search in sub-folders by default" doesn't always work

### ISSUE THREAD

**Issue by mihao** [tagspaces/tagspaces#439]
Even when I check "Search in sub-folders by default", after choosing "Show Files With This Tag" for a particular tag I get only results from the current folder, without subfolders.

**Comment by AntonYarchuk** [comment]
Same here.
Even with "Search in sub-folders" checked I got search expression with "~" (like "~+tagname").
To get sub-folders results I should manually remove "~" from the search expression. 
(ver. 2.3.0)

**Comment by uggrock** [comment]
fixed in version 3. We have a file index for the whole location there....
