### ISSUE TITLE
Cannot write to an external SD card on Android

### ISSUE THREAD

**Issue by mihao** [tagspaces/tagspaces#440]
The Android app can't perform any operations that involve writing to an external SD card, e.g. adding or removing tags. The issue is present on Android 5 (Lollipop).

**Comment by mihao** [comment]
Perhaps this API needs to be used: http://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop

**Comment by uggrock** [comment]
Reproduced, but not easy to fix ...

**Comment by sonjav5** [comment]
I have the same problem. I payed for my version. I would be nice if i could use it.
 Can this be fixed?

**Comment by uggrock** [comment]
@sonjav5  the solution for this issue requires a major redesign of our android/cordova api, so a bugfix probably will not come soon.

**Comment by sonjav5** [comment]
Thanks for your answer!

**Comment by rancidfrog** [comment]
Connect to new location should launch default file picker to select location.
After selecting it using default file picker, it should work.
That is what SMS Backup & Restore and FX file explorer does and it works.
The only change is either launch default file picker when selecting to Connect New Location or when clicking on the folder icon in the view that is currently used when selecting to connect to new location.
I do not think that requires any major redesign.

**Comment by gdude2002** [comment]
This still appears to be an issue - My phone is one of many that has a "fake" sdcard for storing user data, and TagSpaces is entirely unable to function. If I try to add my location using the built in browser, absolutely zero subfolders are found. I can manually add, eg, `/storage/emulated/0/Sync` but I can only work at the root level - TagSpaces will think all my subfolders are completely empty.

Is the Android app still being maintained? I also note that there are a lot of rendering issues when running the app in "full screen mode" on my mate 10 pro, which is taller than some other phones (especially with the navigation bar disabled). I also don't see an option to use subfolders for tags as I can on the desktop.

**Comment by uggrock** [comment]
this should be fixed in our last Android version: https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk
