### ISSUE TITLE
Tag search does not work with meta data in folder

### ISSUE THREAD

**Issue by joshuaavalon** [tagspaces/tagspaces#441]
I used "Show Files With This Tag" and nothing show up. It seems to it uses a search queue which search to search the file name instead of search the tags

**Comment by uggrock** [comment]
Issue is reproducible and will be fixed.

**Comment by joephein** [comment]
This is quite a major issue for me. I am not a programmer but how can I support this to be fixed? I already bought the Pro version yesterday. Is there any milestone / date know for this to be fixed?

**Comment by uggrock** [comment]
We are working on this issue, a fix will come in the next few weeks.

**Comment by uggrock** [comment]
fixed for the next release

**Comment by joephein** [comment]
When can I expect this next release? I am current using TagSpaces Pro 2.3.0 - BuildID: 2.3.0.20160429112036

**Comment by uggrock** [comment]
Version 2.4.0 including the PRO version was released some weeks ago, please check you mailbox for an email from Sendowl announcing the new version.

**Comment by joephein** [comment]
I have checked my mail including the spam folder but I have not received an announcement for the latest version.

**Comment by uggrock** [comment]
I just sended you an email with the download link.

On 07.07.2016 15:03, joephein wrote:
>
> I have checked my mail including the spam folder but I have not
> received an announcement for the latest version.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/tagspaces/tagspaces/issues/441#issuecomment-231071041>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABMR8STWSjM1YLw3gU-yL6IdVQwkTsuyks5qTPkngaJpZM4IevpV>.
>


-- 
------------------------------------
Ilian Sapundshiev (Dipl. Inf.)
Founder TagSpaces
------------------------------------
email: ilian@tagspaces.org
web: tagspaces.org
twitter: @tagspaces
------------------------------------
TagSpaces UG (haftungsbeschraenkt)
Sitz der Gesellschaft: München
HRB 219816 Amtsgericht München
Geschäftsführer: Ilian Sapundshiev
------------------------------------

**Comment by joephein** [comment]
I got the mail now. It ended up in my junk mail folder. I also confirm the tag search using the sidecar .ts files is working now. I am really happy with this!
