### ISSUE TITLE
Transfer of tags to new PC

### ISSUE THREAD

**Issue by jonnyyyl** [tagspaces/tagspaces#443]
Hi there.
I plan to move to a new workstation. A file which contains most working pdfs and docs which are all tagged using Tagspaces will be transferred from one PC (Win 7 X 64) to another (likely Win 10).

The directory under the said file will not be changed (ie. C:\\File\PDF1 is still intact). The file will only be transferred from one drive to another. (from above to D:\\File\PDF1)

Is there a way to keep the tags when making the migration? 

Thanks.

**Comment by uggrock** [comment]
Hi,
since TagSpaces is saving all the tags in the filenames or in sidecar files, you just have to reconnect your original folder with the new installation of TagSapaces in your fresh installed Windows.

regards,
Ilian
