### ISSUE TITLE
Menu - About tagspaces gives javascript error

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#445]
Windows 8.1 64bit, Version 2.3.0

F1 or Help from top menu select about tagspaces throws following javascript error.  Works as intended from setting menu, about tagspaces.

![image](https://cloud.githubusercontent.com/assets/10375234/15637182/f25f0c68-25e0-11e6-9e9b-d049fc4d0c70.png)

**Comment by uggrock** [comment]
We were unable to reproduce this issue on windows 8.1 and windows 10. Can you tell us please, if you still get this issue after a restart of the application?

**Comment by uggrock** [comment]
Please reopen if you can reproduce it again.
