### ISSUE TITLE
Cannot copy text without editing a note

### ISSUE THREAD

**Issue by rhoconlinux** [tagspaces/tagspaces#446]
Hi there, 

I am finding problems with a very basic feature, probably easy to implement. Tagspaces doesn't allow to copy text from a note in the _view_ mode. So, basically, I search for a note, I find it and read what I wanted, but I cannot copy the content. 

It would be nice to have the copy feature in the view mode since it is quite annoying to go and edit the note in order just to copy what it says, with the chance of accidentally change the content of the note in the process. 

So, hope this suggestion result also a need for other users, and expect that its implementation not to be complicated. 

Cheers!

PS. I don't know if that is an issue only for the linux version. I'm running tagspaces in Ubuntu 14.04 and 16.04 X64.

**Comment by uggrock** [comment]
In which version of TagSpaces you are experience this issue? Usually you can just select the text in the viewer with mouse and press ctrl+c to copy the selection.

**Comment by uggrock** [comment]
I am closing this issue since the described way in the previous comment works.

**Comment by rhoconlinux** [comment]
Latest version of Tagspaces built on Ubuntu, and the problem still persists.
I figured that changing the view mode to textreader in txt files fixes the problem, but that mode only allows to see a part of a long note. Without doing that manual change in the preferences the copy function doesn't work unless you edit the note.  
(obviously, right click copy / ctrl+c is what's not working, that is what i mean by copy...)
