### ISSUE TITLE
sidecar files support for Hosted edition

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#447]
I very much like the idea of tagspaces and bought the pro version yesterday so I can use the sidecar (.ts) feature. Would it be possible to add this support as well to the Hosted edition so I can use this online in ownCloud?

**Comment by uggrock** [comment]
The reading of sidecars is currently supported in the webdav version, so if you have tagged files with the PRO version, and synced them with ownCloud, you will be able to see the tags. We are currently not planing to release a PRO webdav version, with writting support for sidecar files, but this can change in the future.

**Comment by joephein** [comment]
This is great. I have verified that it is working. Tags are both loaded from the sidecar files and the filename. There is however no detection of duplicate tags if they both exist in the filename + sidecar file:

![capture_tagspaces_duplicated_tags](https://cloud.githubusercontent.com/assets/12627719/15885220/fa822ec6-2d55-11e6-84e0-0e8a1a3f2e71.PNG)

**Comment by madorian** [comment]
how about the inline tags? I don't really care about sidecar, because it's not portable to all the different systems
