### ISSUE TITLE
add Exif Orientation Tag support to ImageSwiper/viewer

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#448]
Exif Orientation is currently not supported and the Exif information is lost in the thumbnail creation. Can support for this be added to the tagspaces (Pro) edition?

**Comment by uggrock** [comment]
Yes, this could be a valuable addition to the PRO version, I will put it to our backlog. The application can try to create thumbnails with the correct orientation, but the information itself will not be saved because the thumbs are in PNG format, which does not support exif data.
