### ISSUE TITLE
tagspaces Hosted Edition: ns.dialogs:errorOpeningPathAlert

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#449]
I have an issue getting the hosted version working.
I have owncloud in the www root folder of Apache (so /var/www and not in a seperate owncloud folder)

I verified that https://dummy.com/remote.php/webdav works. I do see: "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client."

I added tagspaces in /var/www/tagspaces but when adding a new location with the following path "remote.php/webdav" or "/remote.php/webdav" I get error messages like:

0 ns.perspectiveList.FilesFound
ns.dialogs:titleAlert
ns.dialogs:errorOpeningPathAlert

What could I be doing wrong or might there be an issue with my web hosting?

**Comment by uggrock** [comment]
Try this "/remote.php/webdav/" without the quotes as locations path.

**Comment by joephein** [comment]
Thanks for your help. I got it working now. There was an issue in the .htaccess file
Adding `RewriteRule ^(tagspaces)($|/) - [L]` helped to fix it.

**Comment by uggrock** [comment]
Ok, then I will close this issue.
