### ISSUE TITLE
Can thumbnails be named *.ts?

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#451]
When synchronizing the .ts folder to owncloud I do not want to Gallery app to show the thumbnails and have duplicated images. I believe the same would be valid for any other image viewer in Windows that is indexing images on your pc. The thumbnails can be just regular png files but giving them another (unknown) extension (<org filename+ext>.ts  or .bin?) could do the trick.

**Comment by uggrock** [comment]
No, this is not possible because thumbs with .ts or .bin extension won't be recognized as images from the browser.

**Comment by joephein** [comment]
OK in this case the only solution is that the .ts folder including the sidecar files are hidden. I have opened a separate issue for that.
