### ISSUE TITLE
.ts folder is not hidden in Windows

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#452]
The .ts folder is not hidden using tagspaces Pro 2.3.0. on Windows 8.1 enterprise. I read on https://www.tagspaces.org/products/pro/ that TagSpaces PRO offers saving this kind of meta information in a sidecar files located in a **hidden** .ts folder.

**Comment by uggrock** [comment]
We updated the information for the hidden files in Windows on our webpage (https://www.tagspaces.org/products/pro/#tagSidecarSaving) In general it is not easy possible to make the folders hidden under Windows, but probably we will find a solution for this. Nevertheless, this will not solve your problem with .ts folder under ownCloud, for this you have a feature request in this project.

**Comment by joephein** [comment]
I have made a small batch script to recursive hide all those .ts folders and files:
It can be placed in the root of the folder that you need to be processed and it will hide all folders with the name ".ts" and all subsequent files inside these folders:

```
@echo off

for /R /D %%d in (*) do (
    cd %%d
    if "%%~nxd"==".ts" echo %%d
    if "%%~nxd"==".ts" attrib +h "%%d"
    if "%%~nxd"==".ts" attrib +h "%%d"/*.*
    cd ..
)

cd "%~dp0"

exit /b
```

**Comment by uggrock** [comment]
Great contribute, thank a lot for the script!

**Comment by joephein** [comment]
I have also made a batch script to unhide these folders/files:
Unfortunately this is not so straightforward on Windows due to the issue described here: http://superuser.com/questions/475881/for-command-cannot-see-hidden-files

```
@echo off

for /f "tokens=* delims=" %%d in ('dir /b/s/a   *') do (
    cd %%d
    if "%%~nxd"==".ts" echo un-hiding: %%d
    if "%%~nxd"==".ts" attrib -h -s "%%d"
    if "%%~nxd"==".ts" attrib -h -s "%%d"\*.*
    cd ..
)

cd "%~dp0"

exit /b 
```

**Comment by joephein** [comment]
I found out that tagspaces on Windows is not able to update tags in hidden json files so I updated the batch script above to only make the folder hidden.

**Comment by uggrock** [comment]
Ok, so for now we can conclude that TagSpaces is not able to edit files in hidden folders, so it better for that the .ts folder stays as it is now.
