### ISSUE TITLE
Keyboard bindings for select / bulk edits

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#453]
I found out that spacebar = page down. On Windows shift+mouse-click does not work. How can is easily select multiple files but not all (ctrl+a) in a given folder?

**Comment by uggrock** [comment]
You can use the checkbox in front/over the file extension to select single files.

**Comment by joephein** [comment]
Thanks, I know how to do that but that needs a lot of mouse-clicks. I want to do this faster, so 1 left-mouse-click + scroll + 2nd shift-left-mouse-click to select 20 files or by pressing spacebar + down-key for 20 times on the keyboard which is much faster as well then 20 individual mouse-clicks.
