### ISSUE TITLE
Bug: Shortcut for "Select-All" in Textbox bubbles up to the ListView

### ISSUE THREAD

**Issue by larsborn** [tagspaces/tagspaces#454]
In the following Dialog-Box (and probably also in more)

![clipboard01](https://cloud.githubusercontent.com/assets/1826897/15991934/f2a43604-30c0-11e6-86d1-4f46cb18b563.png)

hitting "Ctrl+A" (under windows) also toggles the "Select-All" in the ListView of all the files in the background.

**Comment by uggrock** [comment]
Reproduced, thanks for reporting!

**Comment by uggrock** [comment]
fixed for 2.7 (testable in 2.6.4 or later)
