### ISSUE TITLE
Config option on whether to keep image links as URLs or as base64 array of image

### ISSUE THREAD

**Issue by MochaPenguin** [tagspaces/tagspaces#456]
When copy/pasting a selection from a web page into a note (an HTML file ina directory), the default appears to be to download and keep a base64 array of the images in that selection.

While this gives the flexibility of offline use, it is loading each note with that binary data - particularly a problem where there are a lot of images in a note.

Perhaps a good way would be to have a setting in preferences to allow the user whether 
a) to save base64 arrays for images in the note
b) keep them as < img src > links

with option b, Tagspaces could download the images into a subfolder and rewrite the links into local references (for offline use) or (as I have done) one can write a script to do that for all img src references in files contained in a folder.

PS: I am using the Linux 64 version of the app on Fedora 21, 23 machines.

**Comment by uggrock** [comment]
Making the saving in base64 format configurable is a good suggestion and we can consider implementing this in future releases of the [editorHTML](https://github.com/tagspaces/editorHTML/) extension. We are accepting also pull requests...
