### ISSUE TITLE
Tag order cannot be changed via drag&drop

### ISSUE THREAD

**Issue by larsborn** [tagspaces/tagspaces#457]
The order of tags, that are already attached to a file,  can only be changed by a quite long sequence of clicks (through the context menu). The possibility to move them with drag and drop would be perfect.

**Comment by larsborn** [comment]
or am I missing any existing feature again? :)

**Comment by uggrock** [comment]
Changing the order of the tags is currently only possible with the context menu. We will consider this issue as a enhancement request.

**Comment by larsborn** [comment]
all right, thank you very much! :)
