### ISSUE TITLE
Problem with keyboard shortcuts in French

### ISSUE THREAD

**Issue by mjerem34** [tagspaces/tagspaces#459]
Hi,
I am a French guy and I use AZERTY/Tagspaces every day, but in html editor, keyboard shortcuts `Ctrl + ]` or `Ctrl + [` for indent and outdent.
I have tested others and it seems they work well.

How can I active these keyboard shortcuts ?

Thank you !

**Comment by scith** [comment]
+1 I can't make it work on AZERTY layout

**Comment by uggrock** [comment]
For the HTML editor we use the great [summernote.js](https://github.com/summernote/summernote/) library, and the described issue appears to be reproducible also on their demo site. Please report the issue there and as soon it is fixed we will update our extension.

**Comment by uggrock** [comment]
We found an workaround, issue is fixed in the upcoming 2.7 version. The new shortcut for indent is CTRL+TAB and CTRL+SHIFT+TAB for outdent.
