### ISSUE TITLE
Autosetup OwnCloud path?

### ISSUE THREAD

**Issue by scith** [tagspaces/tagspaces#460]
Hello,
Is there a possibility to have some folders setup by default please?

I would like to install TagSpaces self-hosted edition with a link to _/owncloud/remote.php/webdav_ already added for every user by default so that they don't have to add it themselves

Thanks

**Comment by uggrock** [comment]
Hello, 

this is possible, just take a look in the comments on the following lines in the settings.default.js:

https://github.com/tagspaces/tagspaces/blob/master/data/js/settings.default.js#L20

https://github.com/tagspaces/tagspaces/blob/master/data/js/settings.default.js#L32

cheers,
Ilian
