### ISSUE TITLE
Can't figure out how to sync

### ISSUE THREAD

**Issue by mblock1** [tagspaces/tagspaces#462]
I can't figure out how to sync tagspaces on my laptop with tagspaces on my iphone using dropbox, because I don't know how to link tagspaces to my dropbox folder on my iphone through the "location path" connect a new location option.  Please help!

**Comment by uggrock** [comment]
Syncing files from TagSpaces on an iPhone with Dropbox (or any other service) is not possible, due to restrictions on iOS. On Android this is possible....
