### ISSUE TITLE
Issue with file count - maxes out at 400.

### ISSUE THREAD

**Issue by megankstrait** [tagspaces/tagspaces#463]
When I load/reload a directory, the file count seems to be maxing out at 400.

I've reproduced this on several directories which I know to contain more than 400 files each. I've tried restarting the application/my machine, but TagSpaces still reports just up to 400 files for these directories.

**Comment by uggrock** [comment]
The maximum files shown/found in the current directory is set to 400. This value can be customized in the settings, tab general.
