### ISSUE TITLE
Upgrading to TagSpaces Pro 2.4.0 deletes the tag library

### ISSUE THREAD

**Issue by gerdzhikov** [tagspaces/tagspaces#465]
I've just upgraded to the 2.4.0 version on OSX and the whole tag library is gone

**Comment by uggrock** [comment]
This is very strange, do you have still you locations or are they also gone?

**Comment by gerdzhikov** [comment]
The locations are there. I think, as I installed it (copied to the Applications folder), something was broken, because I couldn't start the application. The message was that the application is corrupted or not installed correctly. I've installed it again and it starts, but with the problem described above

**Comment by uggrock** [comment]
We were not able to reproduce the issue, if someone is experiencing this problem, please reopen the issue.
