### ISSUE TITLE
No  dialog to enter webdav credentials appears

### ISSUE THREAD

**Issue by mfransen** [tagspaces/tagspaces#467]
Hi,
I just installed tagspaces 2.4.0 webdav edition.
When entering a new location with path to /owncloud/remote.php/webdav 
a dialog to enter the webdav credetials should appear, according to
https://www.tagspaces.org/blog/webdav-edition/

However, this dialog does not appear. Is there a way to trigger the appearance
of this dialog?

**Comment by uggrock** [comment]
Sorry for my late response, but I think that your TagSpaces webdav installation is not correct. On http://demo.tagspaces.org we are using the 2.4.0 and there the dialog appears.
