### ISSUE TITLE
feature request to tag photos in imageswiper fullscreen mode

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#468]
I have a feature request to be able to add/edit/remove tags in the imageswiper fullscreen mode. I tried the shortcut Ctrl+T but it opens the add/remove tags window below the imageswiper window and it only becomes visible once the imageswiper fullscreen mode is closed. I would like an easy way to update tags on individual photo's while viewing them in full screen.

**Comment by uggrock** [comment]
This is on our todo list, but if somebody wants to help us the MIT licensed sourcecode of this extension can be found here https://github.com/tagspaces/perspectiveImageSwiper

**Comment by uggrock** [comment]
This will be part of the next release. I will close it since it is enhancement request.
