### ISSUE TITLE
Adding tags in widows properties

### ISSUE THREAD

**Issue by danglies007** [tagspaces/tagspaces#470]
Hi,

I have been using Tagspaces (great product !!!).  

I would like to know if it is possible to add Tags to files directly from the details tab in windows properties.  If I do tag files in this way how do I make Tagspaces recognize the new tag ?

**Comment by uggrock** [comment]
Hi,

this is unfortunately not possible, but as an alternative you can tag files outside TagSpaces by just renaming them with F2 in Windows Explorer and adding [tag1 tag2] to the name of the file, so file1.txt will became file1[tag1 tag2].txt after tagging/renaming.

cheers,
Ilian
