### ISSUE TITLE
please mention "Zim" in related projects

### ISSUE THREAD

**Issue by Osndok** [tagspaces/tagspaces#472]
I recently ran across tagspaces, and this FAQ in particular:
https://www.tagspaces.org/documentation/faq/

I think it would be great if you can add 'Zim' to the list of similar projects/products.

I have already added the reverse link on their user-wiki:
https://github.com/jaap-karssenberg/zim-wiki/wiki/Similar-projects

Thanks.

**Comment by uggrock** [comment]
In the next update of our webpage Zim-Wiki will be mentioned in the FAQ page.
