### ISSUE TITLE
Naming / renaming note in web edition

### ISSUE THREAD

**Issue by lvv1227** [tagspaces/tagspaces#475]
Does not work at all. Thus only automatic tag is present

**Comment by uggrock** [comment]
Hi,
I just test this functionality on http://demo.tagspaces.org/ where the last official webdav version is deployed, and everything works fine. Perhaps you have some server configuration issues, with folder/file read/write rights.
kind regards,
Ilian

**Comment by uggrock** [comment]
issue will be closed due to lack of activity.
