### ISSUE TITLE
Can thumbnails be in jpg format instead of png?

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#478]
Is there a reason to use png format? For photo's jpg are about 30% the size of the png files. Can both formats be possibly supported?

**Comment by uggrock** [comment]
We are working already on this. I will close the issue since it is enhancement request.

**Comment by uggrock** [comment]
in the current PRO version the thumbnail format can be switched to JPG, the size of the thumbnails can also be changed.

**Comment by joephein** [comment]
I confirm it is working on the pro version. However there is still a small issue. Files are still saved using the .png extension. In Irfanview you get this error when opening the file:
![170104_jpg_with_png_extension](https://cloud.githubusercontent.com/assets/12627719/21636438/0931a570-d263-11e6-9742-86890c847838.JPG)
