### ISSUE TITLE
Index subfolders and run index independently

### ISSUE THREAD

**Issue by sprig** [tagspaces/tagspaces#480]
Hello,

It appears that tagspaces pro does not index subfolders of a given folder, even when subfolder view is enabled. I'm not sure whether it is something on my end alone or whether it is just not implemented, but it would be very helpful.

In addition, it would be useful to run the helper independently of when TS itself runs, so that indexing would happen not when I need my computer to respond smoothly and  quickly, but rather e.g. at night.

**Comment by uggrock** [comment]
this issue will be further tracked in our trello board for new ideas and suggestion: https://trello.com/b/TGeG5bi9
