### ISSUE TITLE
Pro Features on Android

### ISSUE THREAD

**Issue by TB1234** [tagspaces/tagspaces#481]
I use the Pro Version on Windows and Linux and it works fine. I also use the feature with hidden folders and sidecar files. It would be nice if I can use this also on my Android mobile.

**Comment by uggrock** [comment]
We have plans to release a limited pro version on android, but currently this is not on our short term focus. By the way, the current Android version, recognizes tags saved in sidecar files.

**Comment by TB1234** [comment]
> By the way, the current Android version, recognizes tags saved in sidecar files.

But not, if you use the Pro feature to save the sidecare files in the .ts folder...

**Comment by uggrock** [comment]
If you manage to sync the .ts folder from the desktop files, to your android device, TagSpaces will show the tags from it, but you won't be able to change them.

**Comment by TB1234** [comment]
No, not realy. the .ts Folder is on my Phone. I checked this and I can also view this folder in TagSpaces when I check the option to view hidden folders. But it does not view my tags.

I use the latest stable 2.4.0 on my android mobile and also the latest 2.4.0 Pro...

**Comment by cablop** [comment]
Well... the last community version has support for sidecar files. I then decided to give Tagspaces a try. But seeing that Android is missing that feature then it is not that interesting. I am really looking for an organizer and ir seemed to me for a moment that TagSpaces was the solution, cause i would be able to edit the things right from the phone wherever i am... sadly, that's not the case.
