### ISSUE TITLE
Crash after save in MD editor on Android

### ISSUE THREAD

**Issue by SaintDI** [tagspaces/tagspaces#483]
How to reproduce:
- Begin to create list
- Go to next line

```
* sample text

```
- Click **Save** button
- Crash

Sometimes it crashing before saving when I start typing on a next line after list.

---

TagSpaces 2.4.0
Lenovo TB3-850M; Android 6.0

**Comment by uggrock** [comment]
Thanks for reporting, we were able to reproduce this issue and will try to fix it for the next release.

**Comment by uggrock** [comment]
This issue appears to be fixed in the current version.
