### ISSUE TITLE
no collected tags group generated or displayed

### ISSUE THREAD

**Issue by Buena-Vista** [tagspaces/tagspaces#485]
running 2.4.0 in portable mode.  do not get the "collected tags" group or the "tags in this folder" group which I've seen listed here as experimental.  Right now, the only way for me to get all of the tags I put in the file names into the tag panel is to manually copy them from the files and hope and pray that I don't miss one.  (I'm almost done migrating from evernote and put my evernote tags into each file name as I exported the note/file/html etc).

Please let me know how to force the collected tags generation.
Thanks!

note:  I remembered seeing the collected tags group sometime in the past and indeed, if I directly execute the exe rather than the batch file, I do get a collected tags group, but it's empty.  I'm not running from an installed version in either case, just an unzipped copy, which is how I need to do this since I'm running it from my dropbox on files in my dropbox.

**Comment by Buena-Vista** [comment]
just tried beta 2.5.  same problem.  i tried clicking on "import tags" but that looks like it wants a json file rather than scanning my location for existing tags and adding them to "collected tags"  still hoping for a fix.  thanks.

**Comment by Buena-Vista** [comment]
hey, i don't even know how to close one of these.  don't know why it shows that I did, but I would still like some help, please. 
Thanks.

**Comment by Buena-Vista** [comment]
aha - i just found out that "collected tags" does get updated when I add a new tag manually inside the tagspaced program.  So I guess this must really be a feature enhancement request to add the capability to scan a set of folders recursively and generate a list of tags for tags which exist.  I still think I must be making a mistake as this seems like such a logical thing for it do do when you start it, that I must be missing something.  I think I'll get around it for now by manually generating one of those tsm.json files for all of my tags.  please let me know if there's a way to force this to be generated automatically.  I'll wait a few days before tediously generating the json file.  Thanks.

**Comment by Buena-Vista** [comment]
Feel free to make this a very low priority.  I just manually "collected" my tags into groups and it only took about 15 minutes so was hardly a calamity.  But I do think that an option to do this seems almost like a mandatory feature.

I also discovered that the tag groups are stored in the personal profile in the portable version, so don't really need to use the tsm.json files, either.

Thanks!

**Comment by Buena-Vista** [comment]
I just discovered that you DO have an option to scan folders for tags in the pro version, called "calculate tags from the current search results".  which works great except for one thing, it seems to be defeating the --portable and using profile info from the appdata/roaming instead of the tsprofile in the portable exe's directory.  I discovered this because it picked up and showed some of my preliminary tag testing groups I had created before I discovered I was supposed to use the cmd file to start in portable mode.  i'll report this as a bug and close this item since the feature does exist after all.
thanks!

**Comment by PEscortellBH** [comment]
It's a shame that feature is not in the open version

**Comment by uggrock** [comment]
this will be in the free version of TagSpaces v3

**Comment by endlessracingz** [comment]
I've started using v3.5.2 and this feature wasn't made free. 

For some reason only the 3 tags I put on the 1st file I tagged appeared in the "Collected Tags" group. No other tags are populating there and as I stated above the "Collect Tags From Current Location" is a PRO only feature.

**Comment by kupietools** [comment]
I have it set to collect tags in the settings, but tags I create on the fly saving web pages using the clipper aren't collected, even though the document shows as correctly tagged when I navigated to it in tagspaces.

**Comment by uggrock** [comment]
Thank for reporting this, but the browser extension is not directly connected with your TagSpaces installation. The only connection happens with the create files. We have a separate functionality which can collect tags from tagged files, which you can trigger in the app.

**Comment by kupietools** [comment]
Thanks for your reply! I thought there must be something like that, but I did hunt through the app and the docs and couldn't find anything like that. Can you tell me where it is?

**Comment by uggrock** [comment]
It is in the context menu of every tag group:

![Screenshot from 2021-09-30 10-34-16](https://user-images.githubusercontent.com/1249777/135417510-86d95a78-1d59-45fe-a469-95be6ff88679.png)

**Comment by kupietools** [comment]
Ahhhhhhh it's a pro feature. Thanks.
