### ISSUE TITLE
feature suggestion:  tag cloud

### ISSUE THREAD

**Issue by Buena-Vista** [tagspaces/tagspaces#486]
in addition to the existing "Perspectives" views, I'd love to see a "tag cloud" as shown and implemented in javascript here:
https://github.com/jasondavies/d3-cloud

**Comment by uggrock** [comment]
I will close this since it is an enhancement request. By the way we are accepting pull request.

**Comment by Buena-Vista** [comment]
Thanks for the offer, but I know far too little to actually add anything myself even if I do know how to search for existing modules. Maybe some day, though!  I've definitely decided to stick with this cool tool instead of evernote or onenote for my notebooks.  Thanks!
