### ISSUE TITLE
no portable zip for pro version.   pro version installer is downlevel.

### ISSUE THREAD

**Issue by Buena-Vista** [tagspaces/tagspaces#487]
just bought the permanent pro license but the download link is to an installer rather than a portable version, and it did, indeed, put a bunch of stuff into my registry.  It does, however, seem to run as a portable if started with the --portable command line argument if I copy it to where I want it to be.  (there's also no portable .cmd starter, but I am using a link rather than a cmd file anyway.) It used the info in my tsprofile which I copied over from my free version.  Most folks using portable apps, including me, would prefer not to have it in the registry at all.

also, I don't see any way to make my free 2.5.0 portable version into a pro version.  how do i get the pro 2.5.0 (which I think is released, not beta, now).

Thanks!

**Comment by uggrock** [comment]
The PRO 2.5.0 version will be released by the end of this week, you will receive a notification email with a new download link.

**Comment by uggrock** [comment]
As for the portable PRO version, you already figured out that it behaves exactly the same way as the free version. Just go to the installation folder in Windows and you will find an unzipped PRO version, with which you can do whatever you want (e.g. copy it on a USB stick and run it in portable mode).
