### ISSUE TITLE
Mac version starts up with 1-psn-092834 as default startup location

### ISSUE THREAD

**Issue by notklaatu** [tagspaces/tagspaces#489]
On Mac OS X El Capitan, when first launched, the location is 1-psn-[some random integer]. Skips intro, tour, or prompt. 

The workaround is to remove this location with the X on the right, and then add a new location manually. We only figured this out from the tutorial video, which showed us what the app was supposed to look like.

Version: 2.5.0

**Comment by uggrock** [comment]
We were not able to reproduce this issue, with a fresh installation on a Mac. It appears to me as some specific local issue.

**Comment by LBBarney** [comment]
I had this issue as well, when I downloaded the program and installed it today.

**Comment by notklaatu** [comment]
I don't know how to re-open an issue in github, but I think it ought to be re-opened.

**Comment by uggrock** [comment]
fixing for 2.7 release
