### ISSUE TITLE
Feature Request: "Close" to System Tray

### ISSUE THREAD

**Issue by notklaatu** [tagspaces/tagspaces#490]
To be a file manager replacement, it would be nice if Tagspace reduced or "closed" to the system tray, the way VLC, Amarok, or Steam (on Linux, anyway) do. That way when user wants to re-open it, they can access it from their tray.

I think this would be useful on all platforms.

**Comment by uggrock** [comment]
This is already on our project plan. I will close this issue since it is enhancement request.

**Comment by Riajyuu** [comment]
@uggrock May I ask when this will be introduced? I can't find this until 2.9.X

**Comment by uggrock** [comment]
We have already a tray entry, from where you can open TagSpaces if it is not visible. Do you still need a real minimization to system tray ?

**Comment by Riajyuu** [comment]
@uggrock sure. the point of tray feature is to keep task bar clean.

**Comment by s0m3f00l** [comment]
I use VLC as a frontend for our media server. 

This would be a great addition
