### ISSUE TITLE
mht files missing images

### ISSUE THREAD

**Issue by emschi** [tagspaces/tagspaces#491]
My MHT files dont have any images in tagspaces (windows or selfhosted) preview. Only a broken/missing image icon. When i open these mht files with firefox/internet explorer and chrome all is fine. 

Windows
TagSpaces 2.5.0 - BuildID: 2.5.0.20160905130746

**Comment by uggrock** [comment]
When you open a MHT file in TagSpaces, you see a kind of preview of this document, the format is usually broken and all the images are loaded from Internet. So if you don't have Internet connection your images will not be loaded in the preview. But you can use a build in function call Open in windows, which will open the original file, with all build in images, css and real formatting.
![github-issue](https://cloud.githubusercontent.com/assets/1249777/18797963/9e74b976-81d0-11e6-83ed-638d2a1596ca.png)
