### ISSUE TITLE
"Check for new version on startup" not working

### ISSUE THREAD

**Issue by ellipticview** [tagspaces/tagspaces#492]
I am running 2.4.0 on Windows (portable mode). 2.5.0 is available. In the options I have checked "Check for new version on startup". This seems to have no effect.

**Comment by uggrock** [comment]
It should work now, thank you for your hint!

**Comment by ellipticview** [comment]
OK, now the application shows an icon when a new version is available. Clicking on the icon invokes a browser window to https://www.tagspaces.org/whatsnew/
But nowhere can I see instructions how to upgrade.
https://www.tagspaces.org/search/ also gives no hits for upgrade.
