### ISSUE TITLE
Lose Tags if you move a file 

### ISSUE THREAD

**Issue by TB1234** [tagspaces/tagspaces#493]
If you move a file in TagSpaces with the function to copy or move it directly in the program you lose all tags if you use sidecar files and hidden folders. The sidecars should also moved to the new location.

**Comment by uggrock** [comment]
Hi,
thank you for the report. Can you please share with us, which operating system and version of the PRO application you are using.

**Comment by TB1234** [comment]
Hi,

I can reproduce it on Windows 10 (x64) and Linux (x64). I use the 2.5.0 Pro version on all systems but I had the problem also with the 2.4.0.

**Comment by gitdocke** [comment]
Same issue here. Version 2.5 Pro and Linux 64 bits.

**Comment by Seanny123** [comment]
Confirmed on Linux Mint 18 (which is a fork of Ubuntu 16.04) x64, Version 2.5.0 Pro. Can I get access to the Pro-code to fix this problem, I noticed that the code that is supposed to execute this is not in this repository.

**Comment by uggrock** [comment]
Issue is fixed for the 2.6 release

**Comment by uggrock** [comment]
As workaround for now, we are suggesting moving the files with drag and drop, this way the sidecars  are moved correctly.

**Comment by uggrock** [comment]
fixed in v2.6
