### ISSUE TITLE
Windows: Can't right-click on program in taskbar 

### ISSUE THREAD

**Issue by neomodern** [tagspaces/tagspaces#499]
Right-click doesn't do anything, worked on previous versions.

When I've got multiple instances of TagSpaces open I have to close them manually rather than right-click > close them all.

**Comment by uggrock** [comment]
We are not able to reproduce this issue on a Window 10. On which Windows version you experiencing the issue?

**Comment by neomodern** [comment]
Windows 7, but testing it out again now it seems to work normally. Looks like a PC restart was all that was needed, thanks!
