### ISSUE TITLE
Deletion of tagged files on remote PCs when synced with full dropbox account

### ISSUE THREAD

**Issue by deptmoon** [tagspaces/tagspaces#501]
**Issue**:
Potential to have files deleted on remote computers during tagging process when synced to a full dropbox account

**Replication**
1. Tag a file on a full dropbox share that has pending uploads blocked through lack of space
2. During the tagging process the file is deleted for a short space of time???
3. Dropbox grabs the newly free space, marks the file as deleted and deletes from any other sync'd folders 
4. The file is written back to the local dropbox directory successfully, now renamed with the tags (but is not uploaded again to the dropbox server as there is now no space for this file, and it is deleted on all synced folders on remote PCs)

**System**
Yosemite 10.10.5
Tagspaces version 2.5.0 (2.5.0)

**Comment by uggrock** [comment]
Hi,

for me this is a clear Dropbox issue, which can reproduced without TagSpaces, so I will close it. Thanks for reporting and for the warning although!

kind regards,
Ilian

**Comment by deptmoon** [comment]
Agreed!
