### ISSUE TITLE
Tags directory in new pc

### ISSUE THREAD

**Issue by jonnyyyl** [tagspaces/tagspaces#502]
Hi there, files have been moved to a new workstation. 
Original files were in a dropbox account, which helped preserved tags in the individual files when opening tagspaces. However, the tags directory (tag 1, tag 2, tag 3...(the area where by default shows Common Tags, Getting Things done)) is gone. 

How do I recover the old directory to the new pc, so that I don't have to create new tags to add to new incoming files? 

Thanks in advance.

**Comment by uggrock** [comment]
Hi,
so basically you want to recover your tag library. For this you need access to your old installation of TagSpaces in order to export it. Please see this article for more details: https://www.tagspaces.org/documentation/sharing-tags/

cheers,
Ilian
