### ISSUE TITLE
Adding tags from search screen results in invalid file links

### ISSUE THREAD

**Issue by JustSid** [tagspaces/tagspaces#503]
This is for the latest Pro version with sidecarding of tags enabled: Let's say I'm looking at everything tagged `Textures` and now I select a subset of the found files and add the tag `Normal-Maps`. If I now go out and try to find files tagged as `Normal-Maps`, it will show me the files that I tagged, but it seems to think that these files are relative to the folder I was in when I did the `Textures` search (ie the root folder).

Does my description make sense?

**Comment by JustSid** [comment]
In other words, I have to navigate to all the files separately again and apply the tags, which is really really annoying. I just want to start by adding coarse tags and then narrow things down from there!

**Comment by uggrock** [comment]
Issue was reproduced and will be fixed for next release.

**Comment by uggrock** [comment]
fixed in 2.6 release
