### ISSUE TITLE
Uncaught exception when clicking About TagSpaces in Help menu

### ISSUE THREAD

**Issue by ingorichter** [tagspaces/tagspaces#507]
Steps to repro
- Click on Help menu
- Click About TagSpaces menu entry

Expected behavior: Show About Dialog

Current behavior: Uncaught Exception
![image](https://cloud.githubusercontent.com/assets/86214/19397049/fde18aee-91fa-11e6-9526-f78feecf0ad4.png)

**Comment by uggrock** [comment]
Hi,
thanks for reporting! Do you experience this issue and issue #506 after restarting the application?

kind regards,
Ilian

**Comment by ingorichter** [comment]
Yes, after a restart this issue doesn't happen anymore. It seems that something cut off the communication between main and render process, since Quitting the app didn't work and throw that exception. After force quitting and restarting it's working now. We can close this issue for now and hope that this was a fluke.

**Comment by ingorichter** [comment]
Close for now.
