### ISSUE TITLE
Syncing tags between devices issue

### ISSUE THREAD

**Issue by deptmoon** [tagspaces/tagspaces#508]
Hi!
I have tagged files in dropbox using 2.5.0 on Yosemite and then exported the tag file and imported onto my client on Windows 10. The import didn't seem to work as not all of the tags are showing.
I can send the JSON on request (rather not post due to privacy of my tags).

=> Have I understood correctly that even with files synced with dropbox (or whatever) you need to export and import tags to have them available on multiple PCs? Would it not be possible to run the tag file from a shared location - i.e. dropbox

**Comment by uggrock** [comment]
Hi,
in this article we have described several for sharing tags between TagSpaces installations. https://www.tagspaces.org/documentation/sharing-tags/

Not importing all tags is strange, you can send your JSON-file for analysis on the tagspaces contact email.

Please write here if you have further questions, regarding you topic.

**Comment by uggrock** [comment]
Closing because of missing feedback.
