### ISSUE TITLE
Is there a way to set the default pdf viewer to something else?

### ISSUE THREAD

**Issue by jonnyyyl** [tagspaces/tagspaces#509]
If possible, rather than the viewer supplied by tagspaces, I'd like to use say foxitreader or adobe to review the document. How do I achieve that?

Thanks in advance.

**Comment by uggrock** [comment]
Hi,
this is not possible, but you can use the "Open File Natively" functionality to open PDFs in the default PDF-viewer of you operating system. It is also possible to create a new PDF-viewer extension integrating some other pdf-library, then the currently integrated PDF.js from mozilla.
regards
