### ISSUE TITLE
Program Crash after using a Network location

### ISSUE THREAD

**Issue by gynet** [tagspaces/tagspaces#511]
Tagspaces crashed after adding a Network location. 
I am using add cryptomator to load a vault, and when I added the location of the network drive, tagspaces will crash with the UI turn into black and freeze.

**Comment by gynet** [comment]
I am using windows 10

**Comment by uggrock** [comment]
Thanks for reporting. We have never tested TagSpaces with Cryptomator. On network devices TagSpaces usually performs  well, also under Windows. Please tell us if you experience the issue without Cryptomator.

**Comment by antehwyl** [comment]
Yes, I'm having the same problem. I can open the network drive via windows explorer fine, but crashes in TagSpaces. The error message ->"Renderer process crashed".
