### ISSUE TITLE
Save Selected fails to work with fx Nightly.

### ISSUE THREAD

**Issue by Radagast** [tagspaces/tagspaces#512]
Hi, I've just started testing Tagspaces and so far, so good. However, with the firefox web scraper, the 'Save Selected' doesn't work with firefox Nightly. Basically, select some text, click the toolbar icon, select the option and a text box appears asking me to 'Please select text'.

I guess this may simply be an incomparability between the web scraper and firefox nightly (53.0a1) as it works with the current release version of firefox (50.0) This is with version 2.5 of the scraper.

**Comment by uggrock** [comment]
Thank for reporting, we will have to take look on this issue. I only hope that there is no API change in Firefox ...

**Comment by uggrock** [comment]
In the current FF53, the issue is not reproducible.
