### ISSUE TITLE
Read-only view on folders

### ISSUE THREAD

**Issue by bruce2004x** [tagspaces/tagspaces#513]
Hi, I just known this app and it works amazingly. Have a question, I gave a laptop to a user. I need that that dude doesnt have the ability to delete, rename or change any of the files in a path. How can I restrict some option in teh GUI? I mean, e.g., hide some of those options or gray the out.

That way, the man can only visualize (open) the files.

Best!

**Comment by uggrock** [comment]
Hi, thank for your feedback! Regarding your question, how about making the folder(s) where you plan to use TagSpaces readonly?

**Comment by bruce2004x** [comment]
Mr. Uggrock, thanks for your quick replay. The thing is that I need to sync some file from Box within, from time to time. So if it is readonly, Boxsync couldnt sync.

**Comment by bruce2004x** [comment]
Dont know if you need more information to this..let me know!

**Comment by uggrock** [comment]
this issue will be tracked on our ideas trello board: https://trello.com/c/HGI3bQZS
