### ISSUE TITLE
When tagging document <tagname>undefined is used

### ISSUE THREAD

**Issue by martingwb** [tagspaces/tagspaces#518]
Using 2.6 for windows 64.
How to reproduce:
- Install
- Connect a new location
- Select a document
- Add an existing tag 
The tag added is displayed as "<tagname>undifined" at the same time to the name of the file "undefined" is added.
![capture](https://cloud.githubusercontent.com/assets/13892083/21093813/1b716610-c054-11e6-8197-19d8eded28ce.JPG)

This also is pretty strange and maybe is related to the behavior described:
![capture2](https://cloud.githubusercontent.com/assets/13892083/21093942/d30bf628-c054-11e6-9868-805e3f09b7b8.JPG)

**Comment by uggrock** [comment]
do the first problem persist after a restart of the application?

the second one with the edit tag is fixed for the next release.

**Comment by uggrock** [comment]
these issues are both fixed in 2.7
