### ISSUE TITLE
Tagspaces assumes widescreen monitor

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#519]
I'm using tagspaces on a 19" monitor.
Its a minor issue, but it seems that Tagspaces assumes I have a widescreen monitor.
When I open it, it fits to width rather than to both width and height - annoying but not a showstopper.

**Comment by uggrock** [comment]
Starting with the next release TagSpaces will remember the application position and size for the next start. So will have to adjust the windows size only once.
