### ISSUE TITLE
Sync with ownCloud

### ISSUE THREAD

**Issue by jancborchardt** [tagspaces/tagspaces#52]
You can access ownCloud through [WebDAV](http://doc.owncloud.org/server/6.0/user_manual/files/files.html).

Then Files can be shared using the above mentioned [Share API](https://github.com/owncloud/documentation/blob/stable6/developer_manual/core/ocs-share-api.rst).

For more info on tagging, see the issue https://github.com/owncloud/core/issues/3812

Also cc @tanghus who is very interested in getting more tagging into ownCloud. :)

**Comment by uggrock** [comment]
tagspaces works with owncloud, so I will close this issue.
