### ISSUE TITLE
Slowdown issues

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#520]
I'm running Tagspaces on Mint 18
Athlon x64 5000+
4GB RAM
256GB SSD with 560/360 R/W speed

I'm experiencing slow performance generally after I have switched directories a few times and tagged or changed tags on a few files. I can still use it, but it seems to get progressively slower over time. If I end task and restart Tagspaces it runs faster again for a while.

**Comment by uggrock** [comment]
The issue is could not be reproduced with the current 2.8.2 version on a similar configuration.
