### ISSUE TITLE
Update to Version 2.6 - "mod+r" Keybinding Reloads Entire TagSpaces Interface

### ISSUE THREAD

**Issue by cdmatter** [tagspaces/tagspaces#521]
I recently updated from version 2.1.1 to 2.6.0 and noticed that using the keybinding (mod+r) to reload the document now reloads the entire TagSpaces interface.  This function worked perfectly in version 2.1.1 and would only reload the document so that I could see how my edits looked (particularly markdown files).

Edit: I think I know what is happening.  First, my computer had mod+r as the same as ctrl+r and TagSpaces has ctrl+r mapped as "Reload Application" (as can be seen in the menu under "View").  Second, it looks like TagSpaces can no longer reload the document when it is in edit mode.  This used to work in version 2.1.1 where I could edit a markdown file, hit ctrl+s to save the changes, and then ctrl+r to reload the file to see a preview.  I would be nice to have this type of functionality back.

**Comment by uggrock** [comment]
the key for reloading the entire interface was exchange for the next version to F5, so mod+r will reload as expected only the current document.
