### ISSUE TITLE
Version 2.6 - Default Location Sorted Alphabetically

### ISSUE THREAD

**Issue by cdmatter** [tagspaces/tagspaces#522]
I wanted to know if there was a way to have the default location sorted by "Date Modified" at start up rather than the current alphabetical sorting of the "Title".  The previous version I was on, 2.1.1, would start up with the most recently modified files at the top and I would really like to have that configuration again.

**Comment by uggrock** [comment]
This is a regression and will be fixed for the next release. In the previous releases the last sorting was saved in the settings of the list perspective, and applied automatically on listing of a new directory.

**Comment by uggrock** [comment]
fixed in version 2.6.3
