### ISSUE TITLE
Can tagspaces recognise math formula?

### ISSUE THREAD

**Issue by Infinemen** [tagspaces/tagspaces#523]
Hello, I use markdown to write notes everyday. There are some math formulas in it. And these formulas have been written in Latex. So I want to know are there any ways to make tagspaces show these formulas normally when I preview these notes in it??

**Comment by uggrock** [comment]
No currently not, we will consider this as feature request, please track it further on our trello board for ideas https://trello.com/c/lVFUCZyN
