### ISSUE TITLE
Mobile app accessing remote location

### ISSUE THREAD

**Issue by steupit** [tagspaces/tagspaces#525]
This is more of a question rather than an issue.

I'm running the WebDAV version on my NAS. Accessing it works great when I'm using my laptop, whether I'm in the LAN or remote.
Question is how do I access my NAS from the Tagspaces mobile app?

**Comment by uggrock** [comment]
This is not possible the current implementation of TagSpaces mobile app, can access only local files. You can use third party sync app for syncing remote folders locally to your android and the open this folder in TagSpaces.
