### ISSUE TITLE
why cannot edit or view emacs org-mode file using the text-editer

### ISSUE THREAD

**Issue by chxp** [tagspaces/tagspaces#526]
I add a new file type with org extension.

but the application cannot view and edit the org-mode file, it show blank.
The emacs org-mode file is just a txt, why it cannot recongnize it?

Do tagspaces cannot add new file extension? 

Besides, wish to add new highlight style of emacs org-mode..  It may be change from markdown mode?

**Comment by uggrock** [comment]
You should select editorText as file viewer and file opener, if the org-files are really plain text files, there is no reason, why they should not open.

**Comment by jordila** [comment]
> NOTE : Orgmode smoother (full : outlines rendering... e.g.) integration would be plus. From free to premium ?

![image](https://user-images.githubusercontent.com/1966068/108591842-1111b480-736b-11eb-8db5-e8751fa0f7bb.png)


ThX beforehand ;-)
