### ISSUE TITLE
Wrong sorting by tag

### ISSUE THREAD

**Issue by lvv1227** [tagspaces/tagspaces#528]
Usually tag represents a date and time. But sorting by tag does not put notes in right order. You may first have June, then December, then November etc

**Comment by lvv1227** [comment]
Just tested different versions. This bug appeared since 2.6.0 version, was absent before

**Comment by lvv1227** [comment]
The issue remains in version 2.7 unfortunately. Returning back to 2.5.0 (((

**Comment by kristiyandd** [comment]
Hi lvv1227,
What do you mean by 'tag represents a date and time' ? Can you give us more details.
If you want to sort by date and time you should use Date Modified else sorting by tags represent sorting by count tags.
Regards.

**Comment by lvv1227** [comment]
When I make a new note the app automatically assigns the tag. It is something like 20170127~160903. In the version 2.5 when pressing on "Tags" title the list was sorted by data and time incorporated in the tag. Now the behaviour is different, I could not even say how the sorting is performed. I do not understand what count tag is. Could you please explain. Also sorting by the tag as it was implemented before was very convenient - you could modify the content of the notes but could also sort by the note creation date (represented by date/time tag)

**Comment by uggrock** [comment]
we have restored the previous sorting algorithm from 2.5, it will be available in the next release.

**Comment by lvv1227** [comment]
Ilian,


I checked 2.8 version. The issue remains... The previous sorting 
algorithm is not restored
