### ISSUE TITLE
Grid view does not show photo preview when filtering for a tag

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#529]
When filtering for a tag the grid view does not show the photo preview thumbnails. It is working in the ImageSwiper view. See attached screenshots for more details.

![000711_2017-01-03 10_40_39](https://cloud.githubusercontent.com/assets/12627719/21604174/f24d6838-d1a1-11e6-82fe-1b2e6327aadd.png)

Compared with the same filtered view using ImageSwiper:

![000712_2017-01-03 10_40_51](https://cloud.githubusercontent.com/assets/12627719/21604175/f24d7e54-d1a1-11e6-9ad5-c9774e14675e.png)

**Comment by uggrock** [comment]
This appear not to be anymore the case in v2.7. The issue will be reopened as soon as someone can reproduce it again.
