### ISSUE TITLE
Open links in browser

### ISSUE THREAD

**Issue by Terrance** [tagspaces/tagspaces#53]
For the Windows build (and presumably other desktop builds), hyperlinks open in the same window, or a new TagSpaces window - neither of which have any browser abilities (back, refresh and so on).

![image](https://cloud.githubusercontent.com/assets/4025899/2724409/ecaa76a6-c5a0-11e3-9c93-ad7311b30ecf.png)

These should instead be opened in the default browser.

**Comment by laike9m** [comment]
Just found this issue. I'm having link opening problem with Version 3.1.4 on Mac. I'm not able to open a browser or navigate to the webpage when clicking on a URL, nothing happens. Is this the expected behavior for latest version?
