### ISSUE TITLE
Date Modified Sort don´t work in the WebDAV edition

### ISSUE THREAD

**Issue by edelrost** [tagspaces/tagspaces#530]
When I click on Date Modified, Entrys won´t sort in Correct Order.

2007.12.21 
2007.12.15
2007.12.18
2012.11.14
2008.02.07
2016.06.08

Is there any way to fix that?

**Comment by mladensap** [comment]
I could not reproduce the issue on Windows 10 with version 2.6.0. Please try the latest version.

**Comment by edelrost** [comment]
I use Tagspaces 2.6.1 self hosted connecting to Nextcloud via Webdav.

**Comment by Offerel** [comment]
same here with 2.6.4 WebDAV

**Comment by litspeed** [comment]
2.7.0 the issue remains.

**Comment by Offerel** [comment]
Sorting by Date seems to work now with Android 2.7.3 Version, however, the Tag Labels have the Issue #559 on Android also.

**Comment by disaster123** [comment]
This issue still remains with 2.8.0 webdav edition.

**Comment by disaster123** [comment]
Any chance to fix this? It's driving be nuts not being able to sort the files.

**Comment by tgruenert** [comment]
installed 2.9.0 on webdav and chrome as frontend sorting by last modified is corrupt. fixing it would be a great christmas gift ;-)

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing
