### ISSUE TITLE
Tagspaces Pro Crashes When Viewing Specific Folders

### ISSUE THREAD

**Issue by junkbrands** [tagspaces/tagspaces#531]
Hi, certain folders are causing Tagspaces to white-out the application screen. The menu is still clickable and the OS functions fine, but Tagspaces doesn't respond until I've quit out of the application and relaunched it.

We are running Tagspaces PRO, version 2.5.0. Attached are two of the crash reports generated by OS X for Tagspaces. Can you see what might be causing this?

Thanks!

[tagspaces Helper_2017-01-03-115448_dsnow.txt](https://github.com/tagspaces/tagspaces/files/683124/tagspaces.Helper_2017-01-03-115448_dsnow.txt)
[tagspaces Helper_2017-01-03-135153_dsnow.txt](https://github.com/tagspaces/tagspaces/files/683125/tagspaces.Helper_2017-01-03-135153_dsnow.txt)

**Comment by uggrock** [comment]
Hi,
is this behavior related to search activities or opening a folder with many images?

thanks for your response in advance!

**Comment by junkbrands** [comment]
Hi uggrock, it's not due to search activities, and I suspected that it could be with opening too many images, but I'm able to open folders with 3x as many images perfectly fine.

**Comment by uggrock** [comment]
This should not be the case anymore in version 3.0.8
