### ISSUE TITLE
Change default file separator

### ISSUE THREAD

**Issue by tomchor** [tagspaces/tagspaces#533]
I just started using tagspace and I think it has great potential. However, as a Linux user that makes use of filenames a lot, the fact that the default separator is a space makes it more difficult to do things on the CLI.

Is there a way to change that? I've seen some figures in some [older posts](http://cdn.makeuseof.com/wp-content/uploads/2015/10/tagspaces-options.png?9be635) that make me believe that older versions had this feature as experimental, but I can't find it on my version (2.6.0).

If this feature was indeed available before and then it was removed, I'd like to propose that it returns (very useful for Linux users). And I'd like to ask what was the last version that had this feature, so I can downgrade :)

Thanks

**Comment by uggrock** [comment]
we have reanabled these options in the tag general of the settings in version 2.6.4. Please retest if still interested.
