### ISSUE TITLE
Not able to edit tag in Pro version

### ISSUE THREAD

**Issue by bch6179** [tagspaces/tagspaces#534]

**Comment by uggrock** [comment]
can you please share some more details about your issue like version of TagSpaces, operating system and  how exactly we can reproduce the issue.

**Comment by bch6179** [comment]
2.6.0 on win10. right click a tag and edit it. Not able to change name or create a shortcut.

**Comment by uggrock** [comment]
This issue is already fixed in version 2.6.3

Am 14. Januar 2017 05:13:28 MEZ schrieb bch6179 <notifications@github.com>:
>2.6.0 on win10. right click a tag and edit it. Not able to change name
>or create a shortcut.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tagspaces/tagspaces/issues/534#issuecomment-272600440

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by uggrock** [comment]
The fix will appear in version 2.7 of the PRO application.

**Comment by bch6179** [comment]
What's the plan for 2.7 release? Thanks.

**Comment by uggrock** [comment]
The 2.7 release of the PRO version is planned for the beginning of February.
