### ISSUE TITLE
Ability to change modified date

### ISSUE THREAD

**Issue by edelrost** [tagspaces/tagspaces#535]
Hello

I use webdav Tagspaces with nextcloud for my note taking and diary needs. I migrated from Evernote to Tagspaces, and i really miss the ability to change a files modified date. When I revisit a entry from 2007 to add some information and I save the file, the file appear at the top of my sorting order when I sort for date modified. I know this works by design, by I would need the ability to change the date modified back to 2007 so that the entry is sorted where it belongs to.

Is there any way to do that inside tagspaces? The only way I could think of by now is to download all my entrys, change the date modified tags in windows and reupload it into my webdav. 

Regards, 
Edelrost

**Comment by uggrock** [comment]
This is currently not possible in TagSpaces, but you can asks the folks from nextcloud if they can implement such a feature there. I will close this issue and move it to our trello board with ideas: https://trello.com/c/8y2DDRMr
