### ISSUE TITLE
Deleting text in the android version does not work.

### ISSUE THREAD

**Issue by hoeltgman** [tagspaces/tagspaces#54]
I cannot delete text in the Android app on my Nexus 7. Writing text is perfectly possible.

**Comment by oozaru-hunter** [comment]
Hi there, is there still hope for some workaround?

**Comment by uggrock** [comment]
Yes, there is hope ....

**Comment by mladensap** [comment]
Issue fixed for the upcoming 1.10.4 release

**Comment by uggrock** [comment]
1.10.4 published to the app store
