### ISSUE TITLE
Cannot edit a second tag

### ISSUE THREAD

**Issue by materathemad** [tagspaces/tagspaces#540]
I can edit one tag (....e.g. change font color to improve contrast, readablilty) but when I try to edit another tag, as soon as I click on the font color, the edit screen becomes useless, complaining about the tag name: "Tags should have a minimum length of 2 characters" etc. etc. I have tried changing the name to see what happens, but nothing changes.
![2017-01-16cant-edit-another-tag-c](https://cloud.githubusercontent.com/assets/25162207/22002253/16b0be3c-dc10-11e6-94d5-43f9fc3990b6.jpg)

This happens EVERY time. In order to edit a second tag. I have to close and re-open TagSpaces for each tag I want to change.

Desktop, Linux Mint 17.3 64-bit with 64-bit TS installed from deb package.

**Comment by uggrock** [comment]
This is a known issue, already fixed in version 2.6.3, which can be downloaded from the [releases section](https://github.com/tagspaces/tagspaces/releases)
