### ISSUE TITLE
No sharing to Tagspaces in Android

### ISSUE THREAD

**Issue by cloo** [tagspaces/tagspaces#543]
This is self explanatory and essential.

**Comment by Offerel** [comment]
+1

**Comment by uggrock** [comment]
What do you mean by sharing, can you please elaborate a little on this use case?

**Comment by cloo** [comment]
When you have content opened in any app (e.g. photo gallery or browser), you can share it to most apps (gmail, fb, pocket, etc) - but not to tagspaces. 
This is a big problem, because tagspaces is meant for collecting content.

**Comment by Offerel** [comment]
I don't know what cloo thinks, but on Android, in most of the Apps a Share Feature is available. This brings up a Menu, where all Apps are listed, which could get the shared Content from the "Source"-App. For Instance in Firefox, this is the current URL, in a Textapp, this could be some selected Text, in another App this could be a Bitmap. If the Target App support this Content-Type and you call the Share Menu, this Target-App is listed as Target. If you select/choose the Target, the Content is transferred to the selected App. I'm not a Android Programmer, so i didn't know exactly if this uses the Clipboard or any other Method for transferring.

For TagSpaces, this means: Please accept this App as a Target-App for supported Content. According to the Content, TagSpaces should be create a new file either as a new Text-Note, ore HTML/MHT, or Markdown or Image and save this new file in the Repository. In future, i could think there could be a Submenu from TagSpaces, where the User could select between a "Cretea New File" and "Add to a existing File" Function. Firefox does this, if you Share Content with Firefox. You can send the URL either to a other Device (with Firefox Sync) or add the URL as Bookmark.

@cloo : sorry for taking your issue over, i hope i get it right.

**Comment by uggrock** [comment]
thank you for the explanation, I have created a card on our Ideas trello boards here https://trello.com/c/6gVO02vR and will close this issue since it a enhancement request.

**Comment by cloo** [comment]
Thanks for brilliant explanation @Offerel !
