### ISSUE TITLE
Unclear differences between two android apps

### ISSUE THREAD

**Issue by cloo** [tagspaces/tagspaces#544]
There are two android apps. Listed features suggest they are almost the same. 
The only differences in description is that [TagSpaces](https://play.google.com/store/apps/details?id=org.tagspaces.androidapp) is "based on codemirror", and [TagSpaces Lite ](https://play.google.com/store/apps/details?id=org.tagspaces.androidle)has keyboard issues on some devices. This is confusing, because functionality or usability is not addressed.

![tagspapps](https://cloud.githubusercontent.com/assets/651760/22215353/b30ee89c-e1a3-11e6-98ad-722028f44540.png)

**Comment by uggrock** [comment]
The TagSpaces Android app is not anymore available on the Play Store for now. We are planning to release a new version of it, containing some of the Pro features this year.
