### ISSUE TITLE
Embedded image in Markdown Subfolder isnt displayed in Viewer (WebDAV)

### ISSUE THREAD

**Issue by Offerel** [tagspaces/tagspaces#545]
I have installed TagSpaces 2.6.4 under Nginx (Web Version) and use Nginx as WebDAV. WebDAV lives under https://subdomain.domain/webdav/ and Tagspaces at https://subdomain.domain/tagspaces/. As Location in TagSpaces i have setup /webdav/Notes/ (since the Notes folders all my Notes are saved). In the Notes folder, there is a Subfolder "media" with the Images. If there is now in Markdown the following Text:

`[![media-xN2256](/media/21365.png)`

the Image isn't displayed in Markdown Preview and i get in Nginx error log: `[error] 1851#0: *14070 open() "/var/www/tagspaces/webdav/Notes/media/21365.png" failed (2: No such file or directory)`

I think open() should open instead ../media/21365.png, but im not sure. Notes is the name i have given the Location. I don't know, if this apply's also to the Desktop App, i haven't tested this so far.

Update: Have tested the same in Windows Desktop App. If i use the Markdown 
`[![media-xN2256](media/21365.png)` (without leading slash), the image is displayed in preview.

**Comment by uggrock** [comment]
without the slash the image should be displayed also in the webdav version.

**Comment by Offerel** [comment]
I have changed the Tag also online, but i get in nginx error.log:

```
2017/01/25 13:26:45 [error] 1853#0: *14702 open() "/var/www/tagspaces/webdav/Notes/media/21365.png" failed (2: No such file or directory), client: 83.169.152.176, server: test.myserver.com.com, re
quest: "GET /tagspaces//webdav/Notes/media/21365.png HTTP/1.1", host: "test.myserver.com.com", referrer: "https://test.myserver.com.com/tagspaces/ext/viewerMD/index.html?&locale=de_DE"
```

**Comment by Offerel** [comment]
I have thinked again about my install after reading https://www.tagspaces.org/blog/webdav-edition/. In my case, i could see the Notes in the Notes Folder, so i think, Folder Setup should be correct. But something makes me wonder a little bit -> the setup process does not ask for WebDAV Credentials. Maybe thats OK, since i use the same Http Basic Auth and Realm for both directorys (WebDAV and TagSpaces). Meanwhile, i have installed also the Android App and the Markdown Viewer displays there also the Image. SO wonder why this seems to be a Problem with the WebDAV Version.
