### ISSUE TITLE
Feature Request: Please make the Listview resizable

### ISSUE THREAD

**Issue by Offerel** [tagspaces/tagspaces#546]
It would be great, if there could be a way that the user can resize the Listview, so that there is more space for the Editor/Viewer. Maybe the Listview could be a sort of Sidepanel.

**Comment by uggrock** [comment]
![image](https://cloud.githubusercontent.com/assets/1249777/22287725/3035dc44-e2f4-11e6-8429-0ef5f31efef1.png)

Are you aware if this button, which will open the current document on the full application width. Making the right panel resizable with drag and drop is on our todo list. https://trello.com/c/0M2YKOuC
