### ISSUE TITLE
Special Characters in Filename on the WebDAV version

### ISSUE THREAD

**Issue by Offerel** [tagspaces/tagspaces#547]
There seems to be Problems with Special Characters in the Filename. Im starting right now with TagSpaces, to look, if it is the right Notes Tool for me. I have used some other Tools before, so i could start with a Folder full of some Notes. Some of them have Specialcharacters in their names. I have seen this in a Example, where the Name had a "&"-Sign in the Name, but maybe other Characters have the same Behavior.

This Sign was translated to the html Sign"%26". If i now try to rename this Note from within TagSpaces 2.6.4, i get a 404 Error, since the WebDAV - MOVE was tried with the converted Name, which failed in this case. 

So i think, it would be a good idea, to either not translate the Name, or translate it back for Fileoperations or present the User a small Message with all the Files, which could not be imported, because of Specialchars in the Filename and a hint, how to rename the File first.

This was with TagSpaces WebDAV Edition 2.6.4 on Nginx. The Desktop App on Windows has not this Problem.

**Comment by roxfanuk** [comment]
Tagspaces on Linux also has issues with certain characters in filenames. When these characters exist, I can't move the files to another folder.
I have to rename them first in a file manager, then its fine.
