### ISSUE TITLE
cant create new File or Upload with Webdav

### ISSUE THREAD

**Issue by Offerel** [tagspaces/tagspaces#548]
I could rename a File and add Tags to the Filename with the WebDAV Edition, but if I try to create a new File, this isnt possible. Server ist Nginx with extra Headers for OPTIONS and PROPFIND.

Filerights are OK, since I could Upload Fles with WebDAV Clients.

**Comment by Offerel** [comment]
I have now installed additionally SabreDAV 3.2.0. With this, its no problem to create a new Note. It seems that WebDAV Implementation requires LOCK and UNLOCK Feature to create a new File/Note, which unfortunately Nginx doesn't provide. So i think, i will stick with SabreDAV until Nginx has no Support for the above Functions.

**Comment by uggrock** [comment]
Unfortunatelly we are not really testing TagSpaces with Nginx. Please check also this issue #410 , which may be related.

**Comment by Offerel** [comment]
Is the fix mentioned in #410 merged in to the current release?

**Comment by uggrock** [comment]
no, but you can make a pull-request if you wish.
