### ISSUE TITLE
Fileformat Questions ODT / HTML / epub

### ISSUE THREAD

**Issue by Offerel** [tagspaces/tagspaces#549]
I try now since some days to convert my Evernote Files to a usable Format with Tagspaces. I tried first the Tagspaces Firefox WebClipper, but this does not embed the Images to File, they look broken in the Tagspaces Viewer. Then i tried several Ways to save the Evernote Note as MHT. This produces a bigger file, so i hoped that the images are included, but it failed again. The Images was viewable in the Desktop Version, but not in the Android App. But it seems that ODT Format is working. I could see the Images in the Desktop App and on Android, i hope that the WebDAV Version will also support this. But according to https://www.tagspaces.org/documentation/supported-file-formats/ Tagspaces does not support ODT with Android. So im a little bit clueless, if it is only a lucky hit, that it works with Android or if it works as a Standard.

Additionally, i would like to ask, if you could extend the WebClipper for Firefox, to either support writing the File as ODT or embed the Images as Base64 encoded String in to the resulting HTML File, since, if i create a new HTML File in the App, the images seems to be embedded also in the HTML File. In the End, i need a Tip for a Fileformat, which is support a) by the WebClipper, b) Images are embedded, c) this format should be working on Android, WebDAV and Desktop App and d) as a nice thing to have to be editable by TagSpaces. 

Please don't see this as critic at your App. But i didn't would like to make the mistake and invest this much time in a new App and Workflow without to know, if it will work in all my Environments.

**Comment by uggrock** [comment]
I think, that the MHT should be the format of your choice. I can be easily exported from Evernote's Desktop app (or at least one year ago this was working). MHT files can be then viewed in all TagSpaces desktop versions, in the Android App and in the webdav edition. Editing MHT file is currently not supported, but you can try to convert MHT files to HTML and then edit them in TagSpaces. MHT as format is not meant for editing, but for archiving (similar usecase as PDF). ODT is interesting, but then you are handling your notes "word" documents. And yes the ODT support is not consistent in the TagSpaces applications. As of for saving of HTML pages and snippets, we are planning to improve our extensions to support embedding of the included images as data urls. 

regards,
Ilian

**Comment by Offerel** [comment]
Sorry for add some comment in the closed issue. If i use MHT for archiving, as i understand this format correctly, images are included as "Multipart Attachment", like in a E-Mail. But if im not connected to the Internet, i didn't see the Images from within Android App and sometimes the WebDAV Version (not connected means here in the local LAN only), since the embedded Images Links also to some Online Version. I don't know why.

For now, i have made some workaround. I have created new and empty HTML Files within Tagspaces, edited them and pasted the Content from Evernote. If is save the Note now, the Images are embedded as Base64, which is what i want. I really hope that you could extend the Firefox Extension as soon as possible to do the same, so that Images are embedded automatically as base64. If you need Testers, i could help, since im a ISTQB certified Softwaretester here in Germany.

Additionally, editing ODT Files would be really cool. I think webodf.js does support this, but im not sure.

**Comment by uggrock** [comment]
There is no problem, writing in a closed issue, I wanted it closed because it is not specific problem with software.

The MHT viewer in TagSpaces is showing a preview of the MHT file by default, which does not extracts the embedded images, but just tries to open the original images. If you want to see the original file you have to press "Open in new window" menu entry.

You are welcome if you want to support the testing of TagSpaces. You can contact us per email. Do you have any experience with automatic testing?
