### ISSUE TITLE
Invalid regular expression error while editing tags

### ISSUE THREAD

**Issue by umid** [tagspaces/tagspaces#550]
Hello,

Thanks a lot for a great product, very useful!

I started using TagSpaces several days ago (on Ubuntu 16.04, version 2.6.0 - BuildID: 2.6.0.20161123203226) and came across an error, which prevented editing existing tags (no spaces in the input field below):

![image](https://cloud.githubusercontent.com/assets/3854318/22585830/aa55b5cc-e9f1-11e6-9c1b-f1139622a86a.png)

Following this discussion [here](https://github.com/PolymerElements/paper-input/issues/395), I removed the escape character before space in the relevant pattern attribute in `index.html` (on line 806, for `tagInTreeName` input element) and the error stopped appearing. This is the current pattern `^([^ #/\\]){1,}$`, while it used to be `^([^\ #/\\]){1,}$`. Just flagging this in case it may be helpful.

I just noticed that input patterns have been modified in a recent commit, so I assume this will not be an issue in future releases.

Thanks,
Umid

**Comment by uggrock** [comment]
Thanks for reporting, the issue already fixed in the current pre-release 2.6.6.
