### ISSUE TITLE
tsm.json file not loading

### ISSUE THREAD

**Issue by CatDee** [tagspaces/tagspaces#551]
Hi, We are trying to sync tag groups between networked devices. I have created the .ts subfolder in the location folder (on our network drive), exported the .json file from one device and saved as tsm.json in the .ts subfolder, then I selected the checkbox "Load Location Meta Data" and restarted the copmuter and the application. Unfortunately, Tagspaces still does not load the tag groups automatically. Am I missing a step? Thanks!

**Comment by uggrock** [comment]
If you try to import the same tagspaces standard tag group, it won't work because they probably already exist in your settings. Please try to edit the tsm.json (e.g. in TagSpaces) and change the key and name of the tag group, then just reopen the folder where the .ts folder is located. You should not restart your computer.

**Comment by CatDee** [comment]
Hi Illian,

Thank you. Changing the key and name of the folders worked.

Catherine

**Comment by uggrock** [comment]
I am happy to hear, that you have managed to solve your issue. We have changed the export functionality to add a new unique key to every tag group on export, so this will be not a problem in the future. Thanks for your input!

**Comment by PEscortellBH** [comment]
Hi, I am having difficulties to load the tsm.json file. Just to clarify, my understanding is that the '.ts' folder is a '.ts' folder that the user creates in the root of the repository of documents, what is called "location" in TagSpaces. The name of this folder can be anything, like "example.ts". 

I have changed the title and key of each of the tag groups, but still it is not loading. To try loading the tsm.json file I go the setting window and click save&restart, with the option of "Load metadata..." ticked. 

Am I doing something wrong?
