### ISSUE TITLE
Android on Chromebook

### ISSUE THREAD

**Issue by sttrebo** [tagspaces/tagspaces#552]
Hi-
Now that my Chromebook can run Android apps I was hoping to install it and get rid of the R/O Chrome extension.  Unfortunately, according to Google Play Store, TagSpaces is not compatible with my device.  Can this be fixed in the Android app or is it a limitation of the Chromebooks Android implementation?

thanks

**Comment by doogalbear** [comment]
Hi. I'm using an Acer R11 and I had the same problem. I found a solution at GitHub. Choose tagspaces-le-2.8.0-x86.apk , the one on Google Play is for Arm7 devices, you are most likely using an Intel based chromebook and need the x86 version. Here is a direct link for it: [tagspaces-le-2.8.0-x86.apk](The apk you need)

**Comment by uggrock** [comment]
Since it appears that TagSpaces is running as Android App on a Chromebook, I will close this issue and update our documentation and website.
