### ISSUE TITLE
Mardown matching brackets in external links

### ISSUE THREAD

**Issue by adrienhenry** [tagspaces/tagspaces#553]
Hi there,

I got a little bug with the mardown renderer when using a link containing brackets:

```markdown
[Wikipedia](https://en.wikipedia.org/wiki/Modularity_(networks))
```
It seems the tag-space renderer matches the first opening bracket with the first closing bracket which breaks the link. By the way, I tried the same link with *Markdown here* and it worked as I expected.

It is not a big problem for me but I wanted to know if you are aware of this bug.

Cheers

**Comment by uggrock** [comment]
For the markdown rendering we use the [marked](https://github.com/chjj/marked) library. So please open an issue there for this problem.
