### ISSUE TITLE
Directory .ts and Cryptomater hang tagspaces

### ISSUE THREAD

**Issue by rikardo48** [tagspaces/tagspaces#554]
After upgrading to version 2.7.0 and converting a large directory of tagged files to Cryptomater, external tagging with a large subdirectory of files locks up the application and renders the Cryptomater volume as non-ejectable. A reboot is required to fix the issue. The only way to get Tagspaces to work again is to delete the .ts folder(s) and turn off 'enabling the use of hidden folders (.ts) ...'  option for storing metatdata. A byproduct of this is that all tags on external media are lost.

**Comment by uggrock** [comment]
On which operating system you have experienced this issue?

**Comment by rikardo48** [comment]
Linux Mint 18 64-bit

**Comment by uggrock** [comment]
double to #581
