### ISSUE TITLE
Tables is not working in markdown

### ISSUE THREAD

**Issue by shureek** [tagspaces/tagspaces#555]
Tables is not working in markdown. I tried this:
```
This is my table:
| Column 1 | Column 2 |
| --- | --- |
| Value 1 | Value 2 |
| Value 3 | Value 4 |
```

**Comment by uggrock** [comment]
In 2.7 tables are working as expected:
![image](https://cloud.githubusercontent.com/assets/1249777/23013458/f1400a44-f42a-11e6-8c03-85421503cd6a.png)
Please give us more details about how to reproduce the issue

**Comment by shureek** [comment]
Here is my example:
![Tables don't work](https://cloud.githubusercontent.com/assets/2562878/23013979/19191b88-f43e-11e6-9c3d-98c9c2c3b75a.png)
What am I doing wrong?

**Comment by shureek** [comment]
I'm using TagSpaces 2.7.0 - BuildID: 2.7.0.20170203223208 64 bit
OS Windows 10 x64

**Comment by uggrock** [comment]
You should a have an empty line between the text and and table:

```
This is my table:

| Column 1 | Column 2 |
| --- | --- |
| Value 1 | Value 2 |
| Value 3 | Value 4 |
```

Here at github is the same: 

This is my table:
| Column 1 | Column 2 |
| --- | --- |
| Value 1 | Value 2 |
| Value 3 | Value 4 |

This is my table:

| Column 1 | Column 2 |
| --- | --- |
| Value 1 | Value 2 |
| Value 3 | Value 4 |

**Comment by shureek** [comment]
Thanks a lot!
