### ISSUE TITLE
Wadsworth Constant, video thumbnails

### ISSUE THREAD

**Issue by ghost** [tagspaces/tagspaces#557]
Would it be possible for an option to turn on the wadsworth constant for video thumbnails? ffmpeg supports seeking X amount of seconds into the video to take a capture. Just set that to Math.round(video_length * 0.3).

There are other video formats that ffmpeg now supports as well that are not included (avi, flv).

Also what about SSD caching? It'd be nice to have an option to keep the thumbnails and metadata in the electron folder while indexing a platter.

I would contribute these myself but I'm not sure how to contribute to the Pro branch.

**Comment by Pandafuchs** [comment]
ffmpeg integration sounds awesome! No support for thumbnails for files like .avi is a dealbreaker for me sadly...

**Comment by uggrock** [comment]
Integrating ffmpeg is not really possible in current setup of the application. But you can actually assign a thumbnail to every file type, so TagSpaces can display it. Just place a JPG file in the .ts folder called yourfilaname.avi.jpg. This can be done of course automatically with an external script using for example ffmpeg.
