### ISSUE TITLE
Tag Group Missing On Shared

### ISSUE THREAD

**Issue by gmow1** [tagspaces/tagspaces#558]
Created .ts and exported .json file to the subfolder per instructions. When the other user views the tags one taggroup is missing. Tried on 2 different installs. Attached is the .json and the manufacturer group is not visible. File needs to be renamed to .json
![tsm](https://cloud.githubusercontent.com/assets/25987745/23273108/fde6bcee-f9ba-11e6-9a30-733c2e9b5cb6.png)

**Comment by uggrock** [comment]
could not be reproduced
