### ISSUE TITLE
Resorting by Date in 2.7.2 displays wrong Tag Labels

### ISSUE THREAD

**Issue by Offerel** [tagspaces/tagspaces#559]
If you click on sort by Date with TagSpaces 2.7.2 in TagSpaces WebDAV. All Tag Labels does Display [object Object]. Additionally sorting by date, does not really sort by date, but this was reported with a earlier issue #530 
![screens_001](https://cloud.githubusercontent.com/assets/14041522/23303418/59d0d010-fa94-11e6-94d5-dd0a8c441df0.jpg)

**Comment by uggrock** [comment]
This should be fixed in 2.7.4, please retest.

**Comment by Offerel** [comment]
Tested with Firefox, Edge and Internet Explorer 11: If i click on Sorting by Date > Nothing happens. Its not resorted or loaded new. If i reload the whole page however it indicates that its now sorted by the clicked column. I see this, as there is a small arrow, next to the sorted column. The [object Object] behavior does not occur.

Also if the small arrow is next Sort by Date, it isn't sorted by Date in the Web.

I dont know if we should reopen this Issue or we should make a new one. I let this up to yours.

**Comment by Offerel** [comment]
Its fixed now in 2.7.5, but only for the Listview. If i switch after changing Sort Order to another View, like Grid or any other, [object Object] appears again in this new View. Do i switch back to the Listview, all is OK.
