### ISSUE TITLE
TagSpaces crashed

### ISSUE THREAD

**Issue by JerzyPa** [tagspaces/tagspaces#560]
Tagspaces pro is crashed during using. Now I am not able to start ist. It crashes each time during the start.

My system is Windows 10

**Comment by JerzyPa** [comment]
![2017-02-24 tagspaces](https://cloud.githubusercontent.com/assets/20687888/23315086/0294008e-fac5-11e6-8b49-bc6d87ebab53.png)

**Comment by uggrock** [comment]
Hello,

please try to rename the last folder or the last location you have used with TagSpaces to something else with Windows Explorer and start the application. This way the application will not find the folder which may have caused the issue. 

Another suggestion is to start the application in portable mode, with a clean profile. This can be done with the tagspaces.cmd located in the installation folder of the application.

kind regards,
Ilian

**Comment by JerzyPa** [comment]
Thank you! I have managed it. I have changed the folder with free TagSpaces. The reason was activated text extraction.

**Comment by JerzyPa** [comment]
I can't find the file tagspaces.cmd in the installation folder.
