### ISSUE TITLE
Add theme support

### ISSUE THREAD

**Issue by j6s** [tagspaces/tagspaces#562]
This is a proposal for a new feature: Theme support.

A theme could either be an additional CSS file, that overrides default styles or a complete replacement of the default styles alltogether (not sure, which makes more sense).

This would also provide a solution to #91 which seems to be a very long standing issue.

I will have a swing at implementing this feature, but I cannot promise anything as I am not familiar with the source.

**Comment by uggrock** [comment]
Yes, indeed theming is a very long awaited feature, which will be welcomed by the community. Feel free to implement it and don't hesitate to contact us if you need some help. You don't have to promise anything :)

As for the implementation, I thing that a single css which overwrites some css classes will be enough, a completely replacement of the current css is too much work.

**Comment by j6s** [comment]
Initial implementation has been done - though I am not sure how and if this will work on mobile platforms.

This implementation searches for ccs files in the `TagSpaces/themes` config directory ( will be under `~/.config/` on Linux, `~/.Library/Application Support/` on Linux and somewhere in Appdata on Windows).

Before continuing, I would like someone that is more familiar with the source to have an eye on the implementation.
https://github.com/j6s/tagspaces/tree/develop

**Comment by uggrock** [comment]
Hi @j6s ,

I just reviewed your code and it looks good, you are definitively on the right path. The only thing is that I will prefer to load the theme from the applications assets folder and not from some config folder. This will imply that the theme custom css or css-s have to be delivered with the application.

regards,
Ilian

**Comment by j6s** [comment]
Not sure, if that will benefit the cause though, as having it in a config directory will allow for easier theme creation by third parties and developers who would like to tinker with the app just a little bit.

Maybe we could do both, load default themes from the app directory while allowing for third party themes  from a more easily accessible folder.

**Comment by uggrock** [comment]
Sure, allowing both folders is also a possibility. In fact, if you use TagSpaces as portable application and even if it is installed, you can alter files in the installation folder, including adding and changing css files. So this is an easy way to try something on the application.

**Comment by uggrock** [comment]
Implemented in version 3

**Comment by montemartin** [comment]
@uggrock I'm confused about how you implemented theming. If I want to load a custom style sheet for my install how do I go about it? 

I'm on MacOS 10.13. It looks like the css is loaded from `~Applications/TagSpaces.app/Contents/Resources/app.asar/dist/style.css`. Am I expected to go into the Applications folder to customize the CSS?
