### ISSUE TITLE
Pull Request? Added "bookmark" to firefox web clipper

### ISSUE THREAD

**Issue by asciiascetic** [tagspaces/tagspaces#564]
Hello there.  I'm recently rather in love with tagspaces and have been attempting to integrate it more completely into my daily grind.

I noticed that in the firefox web clipper there is no way to easily bookmark a page, so I added a button the the extension and have tested it out on FF Nightly with extension signatures disabled. I'd very much like to see this, or a similar feature, available from addons.mozilla.org.  

I'd create a pull request, but thought I should just bring it up here first.  You can view the relevant branch at: https://github.com/asciiascetic/tagspaces/tree/bookmark-button-in-ff-extension  

If my effort so far is inadequate, please let me know how I can improve upon it and I will endeavour to do so.  

Thanks again, tagspaces is a real dream.

**Comment by uggrock** [comment]
Sure, please create a pull request for your changes. I reviewed your contribution and it looks very promising. The only problem I see is that the generated file is not of some standard format for bookmarking, but just a HTML file containing a link.... Which I find personally very practical. Did you have had the chance to use our viewerURL extension https://github.com/tagspaces/viewerURL ? It can parse the bookmark formats .url, .desktop and .website.

**Comment by uggrock** [comment]
PR is part of 2.8.0 FF extension.
