### ISSUE TITLE
ToDo / Checkbox Doesn't Continue

### ISSUE THREAD

**Issue by johjeff** [tagspaces/tagspaces#567]
So, If I am making a list with checkboxes, the expected behavior is that it acts like a list - type a line and hit enter and another checkbox is added before the cursor. When you hit 'Enter' twice in a row, the checkboxes should stop. It is more than a bit tedious to manually add a checkbox for each line. Plus, you cant select multiple lines and then apply the checkbox, because it deletes the highlighted content. 

**_Checkboxes should behave like bullets._**

This is a pretty neat app overall.

Using portable 32-bit version 2.7.0 - BuildID: 2.7.0.20170203223208 on Windows 7 on Intel.

Thanks.

Jeff

**Comment by uggrock** [comment]
Hi Jeff,

thank you for your feedback, we are managing ideas and suggestion for improvements on trello, that's why I have create this card https://trello.com/c/L96X6elP and will close this issue here.

regards,
Ilian
