### ISSUE TITLE
Why are tags added by editing file name?

### ISSUE THREAD

**Issue by eorroe** [tagspaces/tagspaces#568]
I would love to use this if it wasn't tagging by editing file names, this is annoying when working on code or anything really. Could you please explain the reasoning behind this?

**Comment by uggrock** [comment]
Hi @eorroe ,
renaming the file is the simplest way to add tags to any kind of file in a cross platform way. Ensuring the tags are transferred correctly after syncing or copying on any other platform. By the way, our PRO version has an optional functionality to add tags in a so called sidecar files, which does not rename the original file.
cheers,
Ilian
