### ISSUE TITLE
Can't View Files

### ISSUE THREAD

**Issue by samehmeh** [tagspaces/tagspaces#569]
I'm running version 2.7.0 and I'm only seeing 399 files in a folder. If I had additional files, I can't see them. They live on a NAS. I can see the files via my windows 7 machine and also via my Mac. I can't see the files with tagspaces for Mac nor with tagspaces for windows. Is there a limit on the number of files per folder that the free version will show?

**Comment by uggrock** [comment]
You can increase the max. number of files which can be displayed in a single directory in the settings of the application as displayed in the following screenshot.

![image](https://cloud.githubusercontent.com/assets/1249777/23836163/4c0d3daa-0774-11e7-9816-9d3a0f2c0ed1.png)

**Comment by uggrock** [comment]
The limit of files which can be displayed in the community and the pro version is 2000 files.

**Comment by samehmeh** [comment]
that is very helpful. thank you
