### ISSUE TITLE
How To Backup?

### ISSUE THREAD

**Issue by jrwolney** [tagspaces/tagspaces#572]
Hi.

I noticed that Tagspaces does not save the metadata in the files, but in a database of its own, am I correct?

What is the solution if I format my computer, or reinstall my operating system? Is there a way I can preserve my database of tags?

Thank you.

PS: I searched the documentation and did not find information on this issue.

**Comment by uggrock** [comment]
Hi,

the community version of TagSpaces is not using a database to store the meta information, but the name of the file you are tagging. So for example if you tag KW2016-RW.pdf with the tags conference and ux, it will be renamed to KW2016-RW [conference ux].pdf . The paid PRO version is using a sidecar file for storing this information, so your files are not renamed. In both cased no database is involved, so you have to backup only your files and tranfer them on the computer with the new installation.

Ilian
