### ISSUE TITLE
Disabling or modifying global keybindings

### ISSUE THREAD

**Issue by juanmalunatic** [tagspaces/tagspaces#574]
Part of my normal workflow involves using the _control + alt + n_ key combination. This, however, is a global shortcut for Tagspaces (https://docs.tagspaces.org/keybindings) and clutters my notes folder with empty notes (or forces me to keep the program closed).

Is it possible to disable or modify the global keybindings?
(TagSpaces 2.7.0 Community)

**Comment by uggrock** [comment]
This is a very good suggestion, we will try to add an option for disabling the shortcuts in the next release. In a long-term we will provide an ability to change these shortcuts... Thank you for the feedback!

**Comment by uggrock** [comment]
A checkbox for disabling the global shortcuts was added to the Key Bindings tab of the setting in version 2.8.2.
