### ISSUE TITLE
new feature: saved tag searches

### ISSUE THREAD

**Issue by spock** [tagspaces/tagspaces#575]
Thanks a lot for a great tool!

I'm trying to migrate to TagSpaces from the Evernote+GTD-based [The Secret Weapon](http://www.thesecretweapon.org/) approach to planning, and it looks like it may work.

However, there is one GTD/TSW-specific feature, which I'm missing after one day of use: saved tag searches.

TagSpaces can already search by multiple tags (with `+` and also with `-` - great feature!), but I do not see a way to somehow save/store/bookmark frequent searches to quickly reuse them.

Example: the "when" context is a group of about 6 tags like "now", "next", "later", etc.
When adding new tasks/notes/ideas, I do not always assign a time context.
To find these elements later, I can use the search "-now -next -later ...".
It would be great if I could save this search, name it as "w/o When", and make a button/link appear somewhere in the interface (bottom of the left tags panel? top of the window?) to quickly get to the results of this search.

I have just discovered a possible work-around: use the Grid perspective, group by the When tags, and look for *not grouped*. This may work, will test tomorrow.

**Comment by Burningfeetman** [comment]
I like this idea, make sure you post it here; 

https://trello.com/b/TGeG5bi9/tagspaces-ideas

**Comment by spock** [comment]
Just sent an email to the board, hopefully it makes it through soon.

**Comment by uggrock** [comment]
The PRO version offers a basic support for saving search queries. It just saves your last searches and make them available for future search queries. https://docs.tagspaces.org/search.html#prosearch-history

**Comment by uggrock** [comment]
The request was accepted in the trello board.
