### ISSUE TITLE
Right click for context menu changes multiple selection to one item

### ISSUE THREAD

**Issue by Marxsal** [tagspaces/tagspaces#577]
Windows 7 Home Premium
TagSpaces 2.7.0 - BuildID: 2.7.0.20170203223208

You select a set of multiple items. Then right click. Behind the pop-up menu you can see that it is now only selecting one file item. When you try to apply or remove multiple tags, only the one file item is affected.

**Comment by uggrock** [comment]
This is currently the intended behaviour of the context menu. If you want to tags multiple files you can use the CTRL+T key combination or use the perspective menu from the yellow round button in the bottom right part of the perspective.
