### ISSUE TITLE
Tagspaces crashes when using Cryptomator

### ISSUE THREAD

**Issue by timns** [tagspaces/tagspaces#581]
I have assigned a new location using cryptomator and the moment I try to access it via Tagpsaces, I get a crash.

TagSpaces Pro 2.8.0 - BuildID: 2.8.0.20170414113700

![image](https://cloud.githubusercontent.com/assets/24736792/25316906/b8f25ff2-2823-11e7-836a-a2b315d41d3f.png)

**Comment by uggrock** [comment]
Hi,

can you please try to use some other Cryptomator folder with TagSpaces, just to tell us if the problem still persist. Some user are also complaining to have that problem on some kind of folder hierarchy. Another suggestion from our side is to try some newer version of Cryptomator.

regards,
Ilian

**Comment by timns** [comment]
I have the latest version of Cryptomator, and it crashes no matter where I try to create the folder: I tried top-level on C: and D: and then a subfolder as well. Always the same issue which is the render process error as shown in my first message.

**Comment by uggrock** [comment]
Which is exactly your version of Cryptomator? The project gets these day a major redesign, I hope that with new [1.3.0](]https://github.com/cryptomator/cryptomator/releases/tag/1.3.0-rc1) version, many of these sporadic issue will be gone...

**Comment by timns** [comment]
Version 1.2.3. I’ll be happy to try again with 1.3 when it’s available for Windows, and report back.

 

Thanks,

Tim

**Comment by SaintDI** [comment]
Just tried to repeat the bug.

`I've created a new folder in Cryptomator, opened it in TS. Created there a .md file in TS, and opened it.`

Works well, the bug didn't appear.

TS: 2.8.0 Community
Cryptomator: 1.2.3
Win10, x64

**Comment by timns** [comment]
Lucky you. My spec is same as yours, but still the same problem here. I will give it one more try if TS or Cryptomator gets an update.

**Comment by SaintDI** [comment]
Try **Community** edition, because [here](https://github.com/tagspaces/tagspaces/issues/554) @rikardo48 also has problems with Cryptomator. Probably because of the tags in the .ts files from the Pro version.

**Comment by timns** [comment]
I've pretty much lost confidence in the software by now

**Comment by uggrock** [comment]
should not be the case anymore in v3
