### ISSUE TITLE
File Description - Lost, is not always saved

### ISSUE THREAD

**Issue by Burningfeetman** [tagspaces/tagspaces#583]
Hi Tagspace devs! 

I am playing with the new "Description" feature, this is so awesome, thanks for adding it! 

I have a bug that I think is limited to files with an already created .json file within the TS hidden folder. For some reason, if I add a "Description" to these files, it's cached in a sense that the Tagspaces app recognises the newly added description, but the description itself is not committed successfully to the existing .json file, resulting in the users description being completely lost after clicking about & moving on.

Files with a newly created .json file seem to work OK though. 

Further to this; more of a feature request;

 - Is it possible to channel the "Description" text into the img files properties, as "Comment" data? 
 - If detected, can either "Description" text or "Comment" text appear under the photo automatically, or with setting toggle to be shown automatically?
[Win7 -Dataset.zip](https://github.com/tagspaces/tagspaces/files/956827/Win7.-Dataset.zip)
![feature request](https://cloud.githubusercontent.com/assets/5137574/25412421/ef34aa7c-2a65-11e7-9778-32cc17d29f8f.jpg)

**Comment by uggrock** [comment]
@Burningfeetman thanks for your suggestion and bug report! 

I was trying to reproduce your issue without success under Linux, but on Windows I was having more luck. The problem was the file you have sended to me were flagged hidden or read only, can you please check and confirm this. TagSpaces was not able to rewrite them, but also notepad was not able. On the same Windows installation I was able to add tags and descriptions without issues to file in other folders.

**Comment by Burningfeetman** [comment]
Good morning uggrock, thanks for looking into this! 

As Tagspaces propagated .TS folders throughout my dataset, I decided to change .all created .TS folders to "Hidden". In making this change, it appears that all previously created sub-files were also marked as hidden.

In testing, I can keep the .TS folder as hidden, but if the .json files are hidden themselves, then they don't seem to be writeable. From a programming perspective, should be a tiny change to make this work.

However, I am curious if there's a broader concern here, and if there's a reason why hidden .JSON files are not updating? 

Either way, problem solved.
