### ISSUE TITLE
HTML in Markdown file

### ISSUE THREAD

**Issue by bouncydot** [tagspaces/tagspaces#585]
Hi,

found your great product last week, thank you very much!

Could you please tell me if your preview of markdown files really cannot parse html? Because it doesn't work on my device. If I write for example `<h1>great product</h1>` it literally show this exact words in the preview.  It would be really sad if you would not fix it because I am sure I am not the only one who need html in markdown sometimes.

**Comment by uggrock** [comment]
Hi,

The current implementation of the preview functionality for text files such as txt adn markdown, just loads the text content and renders it as an image. We are not planning for now to have a real md preview, due to performance concerns.

Ilian
