### ISSUE TITLE
Too sensitive to Alt key ;)

### ISSUE THREAD

**Issue by yazdan** [tagspaces/tagspaces#587]
Hi

I use alt+shift to change my keyboard layout and every time I do that the application will open the file menu that is a little annoying. Is there anything that I can do to resolve this issue.

Thanks.

**Comment by uggrock** [comment]
Hi,

alt+shift is not a specific key combination for TagSpaces. Can you specify on which operating system you are using TagSpaces ?

Ilian

**Comment by yazdan** [comment]
I'm using Fedora Linux 25 64bit and tagspaces version is 2.8.0

**Comment by uggrock** [comment]
I will close this issue since it appears to be a general electron feature.
