### ISSUE TITLE
Tags info NOT in filename

### ISSUE THREAD

**Issue by nikkolasg** [tagspaces/tagspaces#588]
Hi all,

First, I want to say Tagspaces looks real neat, sounds like a really good project. 
BUT...
As many others (from what I see), the fact that the free version of tagspaces only stores tags in the filename is just a show stopper for me. It's directly a NOGO.
My reasons are like many others: we have tons of applications on unix systems that depends on filenames (just git for example).

I feel it's a very bad marketing move to put the feature to store tags informations in a separate file as a Pro version, as tagspaces just looses a *lot* of visibility / reputation / users just because that feature is missing by default. It's a bad marketing move to play the "carrot and the stick" method, I just don't want that and I don't think I'm the only one thinking like that in the open source community.

While looking at the open sourced js code, it does not seem too complex to change that, but I won't be able to use the addons etc that easily. 

I'm merely writing it so "one more voice" is showing up for this feature to be included by default.

Best

**Comment by mediapathic** [comment]
+1. Tagspaces looks like an _incredibly_ useful tool which I cannot use because changing filenames breaks everything I would ever want to use it for. At the very least, giving a preview of what you mean by "sidecar file" would allow me to consider whether I want to pay money for something that may break everything in some new exciting way. 

Oh and btw all of your download links on your site for the community version are broken. I had to come to github to download it. (Opera 45.0)

**Comment by holocronweaver** [comment]
I would go one step further. Sidecar files should not be a 'premium' feature, they should be default behavior. I will not use this app until the open source version can function without touching filenames. If nothing else, we can create a fork and implement it. It's a simple feature, if the tagspaces code base is reasonable it shouldn't take much work.

**Comment by proxycyber** [comment]
I agree with all of you, this is a no-go. It's a shame, because I really loved TagSpaces when it was completely free. Making sidecar files should not be a premium feature - and neither should simple things like **editing a note description.**

Agree with @mediapathic: It's an incredibly useful tool which I can't use because of that exact issue.

**Comment by holocronweaver** [comment]
Had a quick look at the code base in `data/js`. The code is only somewhat modular. There is no clear separation of data storage backends, instead you have branches like [this in `tagutils.js`](https://github.com/tagspaces/tagspaces/blob/436d43a304795c27ad76ebeffa8c4c0a011372b3/data/js/tagutils.js#L361) which depend on PRO and `WriteMetaToSidecarFile` being enabled. All the sidecar code is there in `meta.js`, it is just being held back by the PRO flag. I tried manually flipping the PRO flag in code and sidecar tagging worked as intended.

Despite getting the feature I wanted, I have decided against using tagspaces for now. The price is too high for what it currently is (certainly not worth only a year of updates for alpha quality software!) and the UI is very clunky. These problems can be fixed. Will probably check back in a year or so to see if they have.

**Comment by proxycyber** [comment]
> Despite getting the feature I wanted, I have decided against using tagspaces for now. The price is too high for what it currently is (certainly not worth only a year of updates for alpha quality software!) and the UI is very clunky. These problems can be fixed. Will probably check back in a year or so to see if they have.

I definitely agree with you. The price is way too high for what it is and for the quality its currently in. Hopefully within a year, they will get their act together and realize that this is a text editor and not some special software. I'm hoping for the best, but you never know.

**Comment by uggrock** [comment]
Hi all,
we started recently a complete rewrite of the applications in react with a completely new software architecture, once we are ready we expect a significant performance boost. 

About the tags in meta files, this will probably not be a PRO feature, once we release the react version.

About the paid pro version and its price, all of the income is used for keeping the product as a whole alive...

Thanks for your interest so far.
Ilian

**Comment by nikkolasg** [comment]
> About the tags in meta files, this will probably not be a PRO feature, once we release the react version.

I'd be happy to use tagspace *now* if it were already free ... ;)
Looking forward to the next iteration !

**Comment by github-account1111** [comment]
Doesn't using anything but the filename make it not portable whatsoever and thus a total PITA to use?
What if you decide to move to macOS or Windows in the future?
Or switch your file management tool?
Or even just sync some files to your phone?
Unless you tag using filenames, it will all be lost.
