### ISSUE TITLE
no print option in Android

### ISSUE THREAD

**Issue by doogalbear** [tagspaces/tagspaces#591]
I love using tagspaces. This program keeps me organized. After using if for a few months and organizing myself I noticed there is no print option for the android platform. Am I missing this or is it not available? I currently use the WebDav edition and have all my files synced with Linux and Android devices. Also, can someone point out the pros and cons of using WebDav vs say Pro. WebDav isn't listed on the comparison chart. 
Edit: Printing from PDF is available, but no other format. 
Thank you, 
Douglas

**Comment by uggrock** [comment]
Thanks for the suggestion! It will be tracked on our trello board here: https://trello.com/c/SP1AnhQ1
