### ISSUE TITLE
"Show all files" does not work properly + memory leak

### ISSUE THREAD

**Issue by Lukastos** [tagspaces/tagspaces#593]
On 2.8.0 with lubuntu 16.04

When clicking "Show all files" in the list view, it freezes for a minute or so (obviously trying to load the list, since it's using quite much CPU) but in the end doesn't display anything. It also seems that it creates some memory leak. After trying to show all the files a few times, tagspaces used few GB of RAM

Same result in grid view.

The folder isn't that huge, 80%  of my files are already displayed. 

If I use a filter/search, no problem to get all the files

**Comment by uggrock** [comment]
issue is obsolete since there is no such functionality anymore -> closing
