### ISSUE TITLE
Empty Menues (Webdav Version)

### ISSUE THREAD

**Issue by steve-s-71** [tagspaces/tagspaces#596]
See screenshot. I face this issue with Firefox and Chrome under Win 10
![empty menues](https://cloud.githubusercontent.com/assets/17343515/26789581/07857488-4a11-11e7-8d69-99e24277d8f8.jpg)

**Comment by uggrock** [comment]
Hi Steve, does this happen every time you open the application, or sporadically? If happens everytime it should be some kind of misconfiguration.

**Comment by steve-s-71** [comment]
Hi Ilian,

It happens every time.

I have just unzip tagspaces-2.8.0-web.zip and copies the files to the server. What might be the misconfiguration? 

To avoid misunderstanding: Apart from the missing letters (words) the menus are working and even the icons are displayed in each line (see screenshot above). So if one knows where to click, the menus can be used. Also everything else on the application works normal.

**Comment by steve-s-71** [comment]
@uggrock @all 

Do you have any hint for me, what might be misconfigurated?

**Comment by uggrock** [comment]
Hi Steve,

we were not able to reproduce the issue, have you checked the access right for the language files in the locales folder ?
