### ISSUE TITLE
No Webdav access if another brower session is logged-in to Nextcloud

### ISSUE THREAD

**Issue by steve-s-71** [tagspaces/tagspaces#597]
This seems to be a known issue in the Webdav version, as it is mentioned in the manual – at least for the initial setup of the webdav link. As workaround it is suggested to logout the Nextcloud session. 

As the problem occur also during normal operation, it is very an annoying issue. Is it at all possible to fix this issue?

**Comment by ptah-alexs** [comment]
Same problem. Owncloud 9.1.6, tagspaces 2.8.0, debian sid.

**Comment by steve-s-71** [comment]
Any comment from dev team?

**Comment by sunjam** [comment]
Hi, please comment on this issue as it breaks any real integration with both Nextcloud and Owncloud.  Are there any plans to resolve? 
    
The description of this release literally states **WebDAV Edition Working on top of a WebDAV servers such as ownCloud or Nextcloud.**    
    
I truly hope we can see this issue finally fixed.

**Comment by uggrock** [comment]
Hi,
this is an actual issue, which we are currently not able to fix. It requires a deeper integration with owncloud/nextcloud software.

**Comment by sunjam** [comment]
Thanks so much for the update!  Well, it would be fantastic if there were deeper integration between the different projects and tagging, [as discussed in this thread](https://help.nextcloud.com/t/tagspaces-for-owncloud/452).  I see related open issues for the Nextcloud Notes App @LukasReschke that could benefit [Issue #8](https://github.com/nextcloud/notes/issues/8) and [Issue #45](https://github.com/nextcloud/notes/issues/45), Gallery App [Issue #153](https://github.com/nextcloud/gallery/issues/153) and [Issue #61](https://github.com/nextcloud/gallery/issues/61).  Perhaps @jancborchardt or @jospoortvliet from the Nextcloud project can help advise.  @uggrock What kind of integration do you feel is needed?    
    
For me, I find tagspaces to be most similar to the Nextcloud Files app, just greatly expanded by many additional benefits of media playback, markdown editor, gallery features.

**Comment by jancborchardt** [comment]
cc @rullzer and @schiessle from Nextcloud for WebDAV help. :)

**Comment by rullzer** [comment]
I don't really know this project. But how are you managing the credentials when connecting to nextcloud?

Do you enter a username&password?

**Comment by sunjam** [comment]
@rullzer The credentials are an issue since they will not display if logged into Nextcloud, [as shown in the Tagspaces manual here](https://docs.tagspaces.org/selfhosting.html).  Tagspaces users are recommended to logout of a selfhosted Nextcloud instance, then they will be able to add login credentials.

**Comment by rullzer** [comment]
@sunjam we have a new endpoint that provides a token (our mobile clients use it and our clients soon as well).

However this requires you to be able to catch a certain url scheme (nc://). Is that possible for you?

**Comment by sunjam** [comment]
@uggrock Hey Illian, please step in and share your thoughts.

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing
