### ISSUE TITLE
Tagspaces Pro problems in subdirectories of tsm.json file location

### ISSUE THREAD

**Issue by chogendorn** [tagspaces/tagspaces#598]
I am using Tagspaces Pro 2.8.0 on Mac OS X 10.12.5 ,and I am syncing the tag groups tsm.json file across two computers.

I can use Tagspaces Pro to add and edit tags normally in the directory foo that contains the .ts/tsm.json file. But in subdirectories of that directory, Tagspaces Pro will not edit or add tags properly. I can only get one tag per file, and it only appears after restart.

In other directories this behavior does not occur.

**Comment by uggrock** [comment]
this is fixes since a long time -> clsoing
