### ISSUE TITLE
incorrect tagging when dragging tags between adjacent files in list view

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#599]
I have a list of files, some are tagged some not.
I want to drag a tag from one file to another.

I'm using 2.8.0 on Linux Mint 18.2, and this feature used to work in earlier versions (at least 2 releases back i think). It was a useful feature for quick tagging, but now its broken...

If the source file has multiple tags already I find that dragging one of those tags to an adjacent file applies one of the other tags to that file, not the one I dragged. There seems to be no logic to it, it picks a random tag from the file where I dragged from.

**Comment by dermojoo** [comment]
Can confirm this with windows 10 64 bit on TagSpaces 2.8.0 - BuildID: 2.8.0.20170414113700.

**Comment by uggrock** [comment]
This appears to be a bug, but I could not reproduce it every time ...

**Comment by uggrock** [comment]
could not be reproduced in version 3.x
