### ISSUE TITLE
Brackets in filenames

### ISSUE THREAD

**Issue by ontheway16** [tagspaces/tagspaces#602]
Hello, thanks for this nice piece of software. I am having problems with brackets. I am using ImageJ software and it can open the image file with brackets in name, no problem, but when I try to save, it says brackets not allowed. I can rename and same of course, but this time, tagspaces will fail to read tags I guess. Is it the only char possible, to seperate tags?
Regards,

Alp

**Comment by uggrock** [comment]
Hi,
currently changing the brackets with other characters is not possible. We are thinking of making this configurable in the future.

regards,
Ilian

**Comment by xstable** [comment]
Would be really nice, because if you use ScanBot on Android, it is impossible to use [ ] for tags.
