### ISSUE TITLE
tagspaces loads slow

### ISSUE THREAD

**Issue by doogalbear** [tagspaces/tagspaces#603]
Love the program. 
However, I have a lot of information stored on my phone in tagspaces and I use it a lot. When I need it, I want it now not later. My issue is: Tagspaces loads slow. What can I do to make it load faster? 
I use this mainly on Android phone and tablet. 

Thank you for any input, 
Douglas

**Comment by uggrock** [comment]
The current implementation of the mobile version of TagSpaces can have performance issue, if you try to load folders with many files (>300) . As a tip you can try to distribute your files in sub folders so the navigation through the folders will be smoothly. We are working on other performance optimizations but I can not name you a date when they will be released.

**Comment by ShurikMur** [comment]
Feels like the program was never tested on real use cases. Esp. on photos with preview: just as the count hits above 400 it becomes very slow and irresponsive to controls (i7 4 GHz quad core, 16 gigs and so on...).
As the list of photos is scrolled down, the program slows up until become completely unusable!
Yes, JS is not fast by any means, but why not perform very simple optimization like NOT processing content outside of visible zone? Or f.e. just split the whole content in chunks to only show manageable amount of photos at a time.
