### ISSUE TITLE
newly added tags aren't displayed

### ISSUE THREAD

**Issue by aejolene** [tagspaces/tagspaces#604]
TagSpaces Pro 2.8.0
sidecar files mode
Windows 10

When I add a new tag to a file the JSON sidecar file updates, but the tag does not display unless I restart TagSpaces
![image](https://user-images.githubusercontent.com/13810938/27643760-f1623556-5bef-11e7-8927-21dd228800f3.png)

`{"tags":[{"title":"plan-view","type":"sidecar","style":"color: #ffffff !important; background-color: #42d692 !important;"}],"description":"","appVersionCreated":"2.8.0","appName":"tagspaces","appVersionUpdated":"2.8.0","lastUpdated":"2017-06-28T14:50:06.700Z"}`

After restart: 
![image](https://user-images.githubusercontent.com/13810938/27643843-3087dd26-5bf0-11e7-8a55-040c183b0e85.png)

**Comment by uggrock** [comment]
How about just reloading the directory where the tagged file is located ?

**Comment by aejolene** [comment]
Reloading the directory does cause the tags to refresh.

**Comment by uggrock** [comment]
duplicate to #582 , fixed for 2.8.3 and 2.9
