### ISSUE TITLE
Why is there no font size or spell check options?

### ISSUE THREAD

**Issue by proxycyber** [tagspaces/tagspaces#605]
I love Tagspaces, and I don't mean this in a rude way, but why are such simple features missing? Spell check, font size, etc. In the rich text editor. Are there plans to implement these? Default font is way too small.

**Comment by uggrock** [comment]
TagSpaces is a open source project with with open source extensions, so anybody with basic javascript skills could be able to add such features. We do not have currently the capacity to develop the core of the application and all the extensions. Our hope is to get some support from the community.

**Comment by uggrock** [comment]
Font size was reintroduced in the HTML editor.

**Comment by proxycyber** [comment]
Awesome! Any updates on spell check, by any chance?
