### ISSUE TITLE
portable mode only works when launched from application directory on windows

### ISSUE THREAD

**Issue by CTrauma** [tagspaces/tagspaces#606]
Launching tagspaces with the --portable switch from any directory other than the application directory using full path to the executable tagspaces will not find the user data store

I'm guessing it is this bit here:

https://github.com/tagspaces/tagspaces/blob/1f7940261bf40d7c714e7cc47e27f3966652776b/data/electron/main.js#L29

Should the code be using ```__dirname``` instead of ```process.cwd()```?

**Comment by uggrock** [comment]
The idea is to place the tsprofile in the same directory where the executable is located, not from where it is called.
