### ISSUE TITLE
[Android App 2.8.0] Problem with path handover to internal and external editor

### ISSUE THREAD

**Issue by Pr0blemF1nder** [tagspaces/tagspaces#610]
Hi,

I have/found a problem when using the android app (v.2.8.0) on my LG G5 (Android 6.0.1)

I sync my notes to the Android path **/storage/emulated/0/notes**. I can see every file in the app, and can create new notes, but I am not able to open them through the app with the internal and external file viewer (see screenshots)

For example, I want to open **/storage/emulated/0/notes/placeholder.txt**, but the internal and external editor gets the path file:///s/placeholder.txt (which is not correct), and the opening of the file failed.

I have to use the path  **/storage/emulated/0/...**, I changed the foldername (now: 'notes'), but I had the same problem. I tried to open different types of files in the folder, but I had the same problem

Is this a bug in the android app, or what can I do to open and edit the notes?

![capture _2017-07-15-22-13-17-2](https://user-images.githubusercontent.com/30241689/28281930-f6bcc744-6b28-11e7-8c25-04598241fd05.png)

Already wrong path in "File(s) to proceed":
![capture _2017-07-15-22-16-18](https://user-images.githubusercontent.com/30241689/28281934-f6e271ec-6b28-11e7-8838-78a6ef2a8280.png)

Opening a textfile with the internal editor:
![capture _2017-07-15-22-13-27](https://user-images.githubusercontent.com/30241689/28281933-f6dfb236-6b28-11e7-9cfb-f0918c646337.png)

Wrong path was given to an external text editor;
![capture _2017-07-15-22-14-04](https://user-images.githubusercontent.com/30241689/28281932-f6def882-6b28-11e7-9e92-4f53ed029ee7.png)

**Comment by uggrock** [comment]
this should be fixed in our last Android version: https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk
