### ISSUE TITLE
No thumbnails for mp4

### ISSUE THREAD

**Issue by Eusorph** [tagspaces/tagspaces#613]
Tagspaces 2.9.0 win 64. 
![sketch](https://user-images.githubusercontent.com/30339709/28458083-b349f3be-6e08-11e7-9582-3402b3aa0041.png)
Thumbnails are not generated for MP4 videos on Surface 4 Pro with Windows 10 Creators Update. Jpgs, Pngs work.

**Comment by uggrock** [comment]
The screenshot is not from the PRO version. In the PRO version there is the suffix Pro after TagSpaces in the upper left corner. 
![image](https://user-images.githubusercontent.com/1249777/28459486-f5fb027a-6e0d-11e7-935f-5735e70d656d.png)

**Comment by uggrock** [comment]
Thumbnails of MP4 files is a PRO feature.
