### ISSUE TITLE
How EML files works

### ISSUE THREAD

**Issue by remydev** [tagspaces/tagspaces#614]
Hello

As mentioned at this [link](https://docs.tagspaces.org/extensions/viewerMHTML.html#features) 

> Viewing of EML files - EML is file format for saving emails. It is the default export email format of the Thunderbird email client. The show original email functionality in Gmail™ also exports the email in this format.

I wish know how use or create easily a EML file from a mail to store it.
I tried a drag and drop from thunderbird, but it doesn't work

Thanks

**Comment by mrnejc** [comment]
Select the emails you wish to save and press CTRL+C or go to File->Save As->File ...

**Comment by tgruenert** [comment]
drag&drop works fine for me with thinderbird and current chrome

**Comment by uggrock** [comment]
EML files can be opened with the integrated MHTML viewer. This feature is supported also in version 3.0
