### ISSUE TITLE
Client writes sidecar files but does not read after refresh

### ISSUE THREAD

**Issue by Agent3122** [tagspaces/tagspaces#616]
Problem Recreation Procedure

1. Enable Sidecar function
2. Create tag on any file
3. Open Settings
4. Restore Initial Settings
5. Reload application
6. Re-enable sidecar feature

Problem: Client will continue to write sidecar files in the .ts folder but will no longer read after refresh

Attempt:
Reinstall 
Reinstall and deleting C:\Users\#\AppData\Roaming\tagspaces

Please solve this issue. Thank you

**Comment by Agent3122** [comment]
Expand Information:
Windows 10 Pro [Clean]
Windows Tagspaces 2.9.0 Client

**Comment by Agent3122** [comment]
![image](https://user-images.githubusercontent.com/30540811/28741377-bcb0ea5e-73c9-11e7-81d3-eb9b4fc147a2.png)

**Comment by uggrock** [comment]
Hi, 
and thanks for reporting this issue. I have just tested the exact steps you have described and was not able to reproduce the issue. Do you have some more hints about the issue?

**Comment by uggrock** [comment]
You can try to create a file in the .ts folder of your location in order to see if it is for some reason read only ...

**Comment by uggrock** [comment]
Closing the issue due to inactivity, please reopen if needed.
