### ISSUE TITLE
HTML content with img are using external link for both Clip board & web clipper

### ISSUE THREAD

**Issue by gynet** [tagspaces/tagspaces#617]
Current copy and paste HTML content having imgs will be saving as external link instead of base64 string. 

It has the same issue as web clipper.

**Comment by gynet** [comment]
using Mac OS 10.10 + Chrome

**Comment by gynet** [comment]
Using tagspaces 2.9.0

**Comment by uggrock** [comment]
this should be fixed in the current versions of the product -> closing
