### ISSUE TITLE
Document preview cropped under IOS

### ISSUE THREAD

**Issue by schadan** [tagspaces/tagspaces#619]
Hi, under IOS abd Mac OS X the document preview is cut & not completely visible. Is there already a solution for that?

This concerns the WebDav version of TagSpaces.

Thanks, Daniel
![img_0265](https://user-images.githubusercontent.com/30724497/28967324-e6b94a16-791a-11e7-9063-7b0fc36da25d.PNG)

**Comment by uggrock** [comment]
Please try to use the Chrome Browser on Mac OS X, the problem should not appear there.

**Comment by schadan** [comment]
Hi, unfortunately that didn't helped. What I've tested so far:

IOS - Safari, Chrome, Firefox - the same problem (very likely because of the same browser engine in the background, correct?)
Mac OS X - Safari, Chrome - the same problem, only in Firefox the pdf viewer showed the complete page.

Thanks, Daniel

**Comment by schadan** [comment]
One more detail - it seems that this problem is related to the file opener and not to the pdf viewer - the same problem occurrs when opening other file types like jpg.

**Comment by uggrock** [comment]
This issue should be fixed in version 3.
