### ISSUE TITLE
Chaotic Typing in Tagspaces Lite (Android) with Default Google Keyboard

### ISSUE THREAD

**Issue by necopinus** [tagspaces/tagspaces#621]
**TagSpaces Lite version:** 2.8  
**Android device:** Nexus 6P  
**Android version:** 7.1.2

Typing in TagSpaces Lite is unpredictable when using the stock Google keyboard ([Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)). The first word of a line is typed with one letter per line until the first space, and is then consolidated into one line. Spaces and punctuation disappear.

The problem is somewhat better when using a different keyboard (I have [1Password](https://play.google.com/store/apps/details?id=com.agilebits.onepassword), which includes a keyboard for password entry), but still sometimes inserts an extra space after the first character in a line.

Both problems are illustrated in the attached video (zipped up so that GitHub would allow the upload). Perhaps related to #232? Note that I also am experiencing the same issue described in #391, though this isn't demonstrated in the video. 

No obvious changed to Gboard's setting appear to change the observed behavior, and there are no problems with Gboard in other applications.

[20170805_135557.zip](https://github.com/tagspaces/tagspaces/files/1202640/20170805_135557.zip)

**Comment by Zireael07** [comment]
I confirm it's slightly better with SwiftKey but still loves inserting spaces in weird spots.

**Comment by mateidavid** [comment]
I'm also affected by this. I come back occasionally to check on it, but I haven't seen any progress.

**Comment by magowiz** [comment]
I'm also facing the same issue, do you know if there are some keyboards that doesn't make the input chaotic?

**Comment by necopinus** [comment]
I just re-tested this with the current version of TagSpaces Lite on Android (2.8.0), and the default Google keyboard (Gboard) remains unusable. Given @Zireael07's comment, I also tested out SwiftKey, which seems to have improved _a lot_ in the last year; I get occasional weird behavior, but overall the experience is more "occasionally annoying" than "utterly broken".

So "use SwiftKey" is kind of a work-around, but really a user shouldn't have to install a special keyboard just to use TagSpaces on Android...

**Comment by uggrock** [comment]
not reproducible -> closing
