### ISSUE TITLE
No images displayed with number sign '#' in file name

### ISSUE THREAD

**Issue by jothanne** [tagspaces/tagspaces#622]
I found out, that all images with a file name containing the nuber sign '#' are not displayed. You only get the selected background colour and with larger images the loading indicator. I tested this reproducible with *.jpg and *.png files in the windows and android client of TagSpaces.

**Comment by uggrock** [comment]
could not be reproduced in version 3.x

**Comment by IHappyDayI** [comment]
I can reproduce this. Any image with a # in the file name will neither generate a thumbnail, nor show the thumbnail if there exists one, nor show anything when opened in the media player.

This can apparently be fixed when replacing the # with the matching unicode.
> replace(/#/g, '%23')

I have tested this for the thumbPathUrl in renderCellContent in `app\perspectives\grid-perspective\src\index.js` but I have not spend the time to check how to fix the thumbnail generation or display in the media player.

Any of the other common special characters `@€äüöß{[]},.-;_+~!§$%&()=` seem to work fine in the file name on windows
