### ISSUE TITLE
Inserting link with 'Open in new window' checkbox always scrolls document view to the top

### ISSUE THREAD

**Issue by jothanne** [tagspaces/tagspaces#623]
When activating the 'Open in new window' checkbox in the 'InsertLink' dialog while inserting a link in a HTML text document via the 'Link' button or 'CRTL+K' shortcut, the document view beneath always scrolls to the first line of the document though the cursor remains at the position of the inserted link.
This really annoying behaviour occurs reproducible in the windows and android client of TagSpaces.

**Comment by uggrock** [comment]
this should not be the case anymore
