### ISSUE TITLE
Installing/Enabling Extensions

### ISSUE THREAD

**Issue by BuhtigAdmin** [tagspaces/tagspaces#624]
Where is it documented how to install and enable the various types of extensions? (I am not referring to the Google Chrome and Firefox browser extensions).  It is also unclear what this really means since I can't figure out how to enable any extensions: "This extension is packaged with any new version of TagSpaces".

**Comment by uggrock** [comment]
Hi,

please refer to this guide https://docs.tagspaces.org/dev/extension-development-guide.html about installing and developing custom extensions.

kind regards,
Ilian

**Comment by BuhtigAdmin** [comment]
You misunderstood me uggrock. I meant documentation/instructions for ordinary users rather than developers or extremely sophisticated superusers. The Developers Extension Guide is clearly not written for normal users. Does that exists yet?

**Comment by uggrock** [comment]
The app has no build-in functionality for managing extensions during the run-time. The only way to install extensions is the one described in the document. All the officially available extensions are distributed with the app and enabled by default.

**Comment by BuhtigAdmin** [comment]
Thank you very much for taking the time for your responses uggrock. I understand. I guess the home page of the website and at www.tagspaces.org/extensions should probably make it clear upfront that adding additional extensions is really just for developers. Because right now it certainly gives the impression that a normal user has access to these additional extensions when you look at those pages.  Anyway, thanks again.
