### ISSUE TITLE
moving more than one file at a time

### ISSUE THREAD

**Issue by KIRINPUTRA** [tagspaces/tagspaces#628]
Hi, I'm trying out the Pro version on OSX. I can't figure out how to move files (from one folder to another) in bulk. Is this supported?

If I did it natively in OSX, the sidecar tags would be left behind, so that's no good. So it has to be done in Tagspaces. And there will be a lot of files to move, since the Tagspaces paradigm enables (and to some extent calls for) a different kind of directory structure.

Thanks.

**Comment by uggrock** [comment]
Sure, this feature is already implemented. Just select some files with checkbox in front of them and then open the perspective context menu with the yellow round button. In this menu you will find a Copy / Move Files entry.
