### ISSUE TITLE
Use hashtags as alternative

### ISSUE THREAD

**Issue by Brixy** [tagspaces/tagspaces#630]
Hi all!

Really like the tagging concept and the editor of TagSpaces.

What I would like to suggest is the option to use hashtags instead of square brackets. (I have been manually using hashtags for years and never experienced problems changing OSs), so that a tag as `#php` can be found in any OS and piece of software.

If that is not wanted/possible/fully compatible, I would like to be able to convert tags like `#tag` or `@tag` into the TagSpaces format.

Thank you!

**Comment by uggrock** [comment]
Hi and thanks for your suggestion,

Using the hash symbol in the file name is not a good idea the hash symbol can be used in URLs for deep linking. This could be problematic if you host your file online.

cheers,
Ilian
