### ISSUE TITLE
folder tagging in Pro is erratic

### ISSUE THREAD

**Issue by KIRINPUTRA** [tagspaces/tagspaces#633]
In Pro, you can tag a directory by going into it.

When I try to tag a directory w/o going into it — by selecting it and pressing the keyboard shortcut to tag — I get "Tagging not possible! Please select a file first".  

However, if I select multiple folders and press the shortcut, it becomes possible to tag.

But if I then go into one of the directories, the tags will not be shown as having applied. But if I go back up a level, the tags will be there again.

I really hope this can be fixed.

**Comment by uggrock** [comment]
The correct way for tagging folder is to go in it, open it's properties and add tags. Selecting multiple folders and then tagging with shortcut is a bug, which should be fixed. In this case in handles the folder as a file, which is not correct.

**Comment by KIRINPUTRA** [comment]
Thanks.

**Comment by uggrock** [comment]
The file and folder tagging was redesigned in version 3 of the application. This behavior should not be the case anymore.
