### ISSUE TITLE
User session

### ISSUE THREAD

**Issue by bigpietro** [tagspaces/tagspaces#636]
Sorry, but maybe I misunderstood TagSpace ...
TagSpace work fine but only for only PC (one browser session) all of another connection to TagSpace show as new (first) connect, I see only help wizard and I must setup all folders and tags again for each connection (session).

What is wrong or is this normal ?

**Comment by uggrock** [comment]
We do not support user session in TagSpaces webedition. But you can still have many tabs pointing to the same webdav instance.
