### ISSUE TITLE
No documentation for adding webdav shares 

### ISSUE THREAD

**Issue by schvabodka-man** [tagspaces/tagspaces#638]
Hi, i've dockerized machine with tagspaces self hosted version on port 5632, and lightppd with webdav on some other port. How the hell i do add share from it? I obliviosly can't use the way it's done in official tutorial because webdav and tagspaces are running on different ports. I was trying localhost:port http://localhost:port ip:localhost and stuff like that but nothing of this worked.

**Comment by cesalo** [comment]
You could use owncloud (docker) and from there you could share any mount point, directory, etc and then use it in tagspaces.

**Comment by uggrock** [comment]
Adding webdav shares is not possible in TagSpaces ....
