### ISSUE TITLE
self hosted on synology

### ISSUE THREAD

**Issue by it4offices** [tagspaces/tagspaces#640]
Hi I'm having an issue setting up the self hosted version on a synology nas.
I've got the site running but when i add a location it gives the following error

![tagspaces](https://user-images.githubusercontent.com/32513405/31174478-8c742d5a-a903-11e7-86c3-1367db397b7e.GIF)

I've tried a folder on the nas as well as my local machine.  
thanks in advance.

**Comment by tgruenert** [comment]
Tagspaces 2.7.0 and 2.9.0 running fine on my synology. 
Check that path has to be absolute, i.e /documents/archiv/

**Comment by elevenyao** [comment]
@tgruenert could u please tell me how to set it?

**Comment by uggrock** [comment]
A kind of short tutorial will be really interesting also for me, I have a Synology but never have the time to try TagSpaces there...

**Comment by Sojourneer** [comment]
I've just started using TagSpaces today with my Synology as store, and am also thinking of self-hosting on the Synology.  A short tutorial would be great.

**Comment by uggrock** [comment]
this issues goes out of the scope of the project
