### ISSUE TITLE
Date tag edition loses current date

### ISSUE THREAD

**Issue by hectorcanto** [tagspaces/tagspaces#641]
When editing a date type tag, If I change between data types (or even general) I expect to maintain the date.

Case 1:
Say that automatic tag sets datetime 20171018-120000, if I choose Date I would expect 20171018 but I get 20160101. 
Case 2:
I set date 20171018, I change to datetime and I get  19900101~000000. I'll expected 20171018-120000 or 20171018-000000

**Comment by uggrock** [comment]
this should not be anymore the case -> closing
