### ISSUE TITLE
Preselect only the filename without extension when renaming a file

### ISSUE THREAD

**Issue by lanwin** [tagspaces/tagspaces#643]
I mostly rename all my files within Tagspaces. But at 100% of all cases I want to keep the extension as it is. So I always need to select only the filename part and then I can change to filename to whatever I want.

It would be a huge timesaver if Tagspaces could preselect the filename parts without extension in the rename dialog so I could directly start editing the filename without selecting the parts for myself before.

**Comment by steff517** [comment]
+1

**Comment by uggrock** [comment]
Implemented for TagSpaces V3 RC4

**Comment by lanwin** [comment]
Sadly this didnt work in 3 pro. 

The rename file dialog input box has not the focus when the dialog appears. If I use tab to get focus to the box, the full content of the input box gets selected. If I click to the input box, I can see that only the filename is selected, but one second later, the full content of the box is selected again.

OS: Win10

**Comment by uggrock** [comment]
You are right, it does not work from the context menu, but if you select a file and press F2 for rename, it works. I am reopening the issue.

**Comment by uggrock** [comment]
this is implemented in the current version of the app -> closing
