### ISSUE TITLE
Firefox 57 extension support

### ISSUE THREAD

**Issue by paapereira** [tagspaces/tagspaces#644]
With the new Firefox 57 release some "legacy" extensions stopped working and tagspaces is one of them.

**Comment by uggrock** [comment]
Hi, 
we know this, but currently we did not have free resource to rewrite the extension for the new [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) standard. 

So any help is welcome.

**Comment by uggrock** [comment]
The Firefox extension was migrated to WebExtensions recently, so I will close this issue.
