### ISSUE TITLE
Disable auto-creation of tags

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#646]
I'd like a simple option or flag to disable the auto-creation of tags when creating files within Tagspaces, since they are always automatiically added to file names based on date and time.
![tagspaces-new-file-tag](https://user-images.githubusercontent.com/1787238/33302258-b31240c4-d3af-11e7-8f7a-7dad14c33f53.png)
![tagspaces-new-file-no-tag](https://user-images.githubusercontent.com/1787238/33302261-b68e6aca-d3af-11e7-81b5-68a9f71bf47a.png)

**Comment by ookimi** [comment]
I think this should be an option - and users should be able to choose the default tag to be set automatically, or none at all. For instance, I would use the date, but I don't need the seconds.

**Comment by uggrock** [comment]
This functionality was redesigned in TagSpaces. Now the user sees the actual filename before create, so she can adjust it.
![screenshot from 2019-01-01 22-39-23](https://user-images.githubusercontent.com/1249777/50576634-369f7500-0e16-11e9-9653-69e48a82422c.png)
