### ISSUE TITLE
tsm.json Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by abunavas** [tagspaces/tagspaces#647]
When I am opening markdown file a have this errors

`file:///D:/My%20Documents/Gdrive/!!!!CLIPPINGS/.ts/tsm.json Failed to load resource: net::ERR_FILE_NOT_FOUND

i18next.min.js:5 currentLng set to: en_US

i18next.min.js:5 loaded: locales/en_US/ns.editorText.json`

Any help. please?

**Comment by uggrock** [comment]
These errors are not related to markdown. The first error comes on every directory which does not contains a tsm.json file in the hidden .ts folder. This is currently the most performanced way to find out if the tsm.json file exists. The second error is related to the translation library we are using.
