### ISSUE TITLE
SpellCheck

### ISSUE THREAD

**Issue by Provoo** [tagspaces/tagspaces#648]
TagSpaces, is one of my favourite apps for ubuntu and keep my information and notes save without using evernote, but I can't set up a spellchecker in the text area in Ubunut 16.04, I think is very important to have this feature or let us know how to active.

**Comment by Provoo** [comment]
Hi, I still waiting somebody can help me, In my phone I use a Keyboard that help me with this because also in the mobile app, you don't have a spellchecker. Please let me know if it is away probably I can help with the solution.

**Comment by uggrock** [comment]
spellcheck is available since 3.7.8 in some parts of the application -> closing
