### ISSUE TITLE
Save as File buttons do nothing in Vivaldi Browser (Chrome Extension)

### ISSUE THREAD

**Issue by lairdchris** [tagspaces/tagspaces#649]
I'm using **Vivaldi** as my main browser on my Ubuntu 17.10 machine. I've installed the Tagspaces Chrome Extension and allowed access to file-URLs.
I can open Tagspaces from the webclipper dialog, but I can't clip anything from there. Pressing any of the three buttons (save whole page, save selected, screenshot) simply does nothing.
In **Chromium Browser** it's working as expected.

**Comment by rg-software** [comment]
May I suggest changing saveAs() into chrome.downloads.download()? It works in both Chrome and Vivaldi.
[popup.zip](https://github.com/tagspaces/tagspaces/files/1771868/popup.zip)

**Comment by uggrock** [comment]
@rg-software Thank you for the hint, we will try to integrate your suggestion.

**Comment by rg-software** [comment]
It works, just use the file attached :) Thanks for a useful tool!

**Comment by uggrock** [comment]
The main idea was integrated in version 2.12.0 of the extension. But in the Vivaldi browser for some file types we loose the original file name while saving ....

**Comment by rg-software** [comment]
Yes, it is a known bug is Vivaldi, I think, and recently I reported it to the Vivaldi team, just in case.

**Comment by uggrock** [comment]
could not be reproduced in version 3.0.1 of the extension

**Comment by zengels** [comment]
Hi ! I am in front of the same problem while using webclipper with a pro version of Tagspaces an Vivaldi. I tried to "add" the "popup.zip" to "save as"...i certainly does not understand how to do that...would it be possible to help me understand how it could make the webclipper work ? Thanks !

**Comment by uggrock** [comment]
Unfortunately we do not support or test the extension in Vivaldi. The extension is actually not connected to the desktop apps such as TagSpaces Pro, it just generates files, which can be opened there. We are open for changes in the browser extension. The source code is located: https://github.com/tagspaces/browser-extensions/ And the popup.js is in /src/ui .

**Comment by uggrock** [comment]
Have you tried to configure Vivaldi to ask you every time where to save the downloaded files?
