### ISSUE TITLE
WebDAV incorrectly process soft-link pointing at non-exist location

### ISSUE THREAD

**Issue by SilverBut** [tagspaces/tagspaces#650]
If a soft link is pointed at a non-exist location, webdav version of tagspaces will throw a exception:
```
web.api.js:208 Uncaught TypeError: Cannot read property 'getcontentlength' of undefined
    at davSuccess (web.api.js:208)
    at Function.nl.sara.webdav.Client.ajaxHandler (webdavlib.js:5)
    at XMLHttpRequest.ajax.onreadystatechange (web.api.js:78)
```

Related code:
```
//...
            filesize = undefined;
            lmdt = undefined;
            //console.log(dirList[entry]._namespaces["DAV:"]);
            if (typeof dirList[entry]._namespaces["DAV:"].getcontentlength === 'undefined' ||
              dirList[entry]._namespaces["DAV:"].getcontentlength._xmlvalue.length === 0 ||
              (dirList[entry]._namespaces["DAV:"].resourcetype._xmlvalue.length === 1 &&
              //...
```

You can reproduce it on the latest version of tagspaces, with nginx 1.10.3

**Comment by SilverBut** [comment]
Though WebDAV may not showing if the file is a soft-link or a real file (correct me if i wrong), we can still assume that a file exists in autoindex but got 404 is either removed between two requests, or a soft-link. What about just mark them with red color and modify it?

However currently I just use a empty try-catch to avoid this.

**Comment by SilverBut** [comment]
Nope. The problem seems exists in js-webdav-client. This seems caused the same bug in #410 and #548.
The right solution is to make changes in js-webdav-client, which seems not a elegant way...

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing
