### ISSUE TITLE
Tags in the ListView disappear after switching from List view->Grid view->List view

### ISSUE THREAD

**Issue by ikelaiah** [tagspaces/tagspaces#651]
Using TagSpaces 2.9.0 on macOS 10.12.6.

Tags in the ListView disappear after switching from List view->Grid view->List view. The actual tags are still there but do not display on the ListView.

I could only bring back the Tags in the ListView by clicking `Refresh` on the Folder Navigator.

Thanks for the app a good Evernote alternative for managing project files and my MarkDown notes. Will be purchasing soon.

-ikel

**Comment by uggrock** [comment]
Could not be reproduced in version 3.
