### ISSUE TITLE
Local image and file links are not working on Mac

### ISSUE THREAD

**Issue by Ecartman84** [tagspaces/tagspaces#654]
With TagSpaces 2.9.0 on MacOS 10.13 it seems that when you create a link to a local image or file the link does not work.

Steps to reproduce:
1. Create a test.txt file
2. Create a md file in the same folder and add the following link
[This is a Link](test.txt)
3. Click on the link and nothing happens
4. Now if you open up the Windows version of TagSpaces 2.9.0 and click on the link it will open the txt file without issue

**Comment by uggrock** [comment]
issue is fixed in > v3 -> closing
