### ISSUE TITLE
Firefox addon died again :(

### ISSUE THREAD

**Issue by ookimi** [tagspaces/tagspaces#655]
This version is no longer working: https://github.com/tagspaces/tagspaces/releases/tag/v2.2.5 - too old and incompatible with Firefox 57.0.1 on 64-bit Ubuntu.
And the version downloadable from tagspaces website won't install at all, because it is unsigned.

**Comment by uggrock** [comment]
The Firefox Addon was updated recently supporting the last Firefox versions. It can be downloaded from https://addons.mozilla.org/en-US/firefox/addon/tagspaces/

**Comment by VirtualW** [comment]
Excellent. Thank you.
