### ISSUE TITLE
Only displaying certain number of files

### ISSUE THREAD

**Issue by BPLAAO** [tagspaces/tagspaces#656]
Hello there!

I have 480 files in the tagspaces folder, and only 398 are being displayed in the main view of tagspaces. When I search them or press "show all files", they exist; but I won't be able to see them if I don't do one of these previous things. Tagspaces is always displaying these 398 files, even if I add more files to the folder.

My problem is the way that the software deal with these "extra" files. As the ones that I cannot see are (for example) all the files starting with u to z. When adding new files to the tagspaces folder, if named "wood bench", the file won't show in tagspaces. Only as said before when searching or pressing show all files.

Thanks for this amazing software!

**Comment by uggrock** [comment]
You can increase this limit in the setting as displayed in this screenshot:
![image](https://user-images.githubusercontent.com/1249777/34254595-13aa070a-e64d-11e7-8e0d-e95bd2145ace.png)
Please be carefull increasing it too much, since tagspaces may have performance issues....
