### ISSUE TITLE
when ordered by title, files will go from 1 to 10 rather than 1 to 2

### ISSUE THREAD

**Issue by sirtriangle** [tagspaces/tagspaces#660]
![pic](https://user-images.githubusercontent.com/35554620/35082716-611cfd1a-fbe9-11e7-9628-5ead42fa30e7.PNG)

Windows recognizes that files should be ordered numerically but tagspaces will have a file named "10" come directly after a file named "1" instead of after a file named "9"

**Comment by uggrock** [comment]
this will be corrected in the upcoming major update of the application.

**Comment by uggrock** [comment]
Fixed in version 3.0
