### ISSUE TITLE
select multiple files and open in external directory

### ISSUE THREAD

**Issue by jozefbaar** [tagspaces/tagspaces#661]
Hi 
I would like to select few files from certain tag and open it in external window to right click and share it by google drive. Is it possible ?
thanks

**Comment by uggrock** [comment]
Hi,
no, this is not possible. But since the tags are saved in the names of the files you search in google drive for the tag and share from there.
cheers

**Comment by jozefbaar** [comment]
Hi @uggrock 
Thanks for prompt reply. Please write me how to do search in google drive by tags ?

**Comment by uggrock** [comment]
just search in gdrive for the name of the tag...

**Comment by jozefbaar** [comment]
not satisfied at all about this workaround. but your solution seems to work!
thanks.
