### ISSUE TITLE
TagSpaces with NextCloud 12

### ISSUE THREAD

**Issue by catalyst1987** [tagspaces/tagspaces#662]
Hello,
   I'm using TagSpaces 2.9 with NextCloud 12 and couldn't get tagspaces to open if I placed it in /var/www/tagspaces.  So instead I placed it in /var/www/nextcloud/web/tagspaces and then it opened.  I tried creating a location pointed towards /remote.php/webdav/ but unfortunately I get the following errors:

webdavlib.js:5 PROPFIND https://mycloud/remote.php/webdav/.ts/ 401 (Unauthorized)
nl.sara.webdav.Client.propfind @ webdavlib.js:5
(anonymous) @ web.api.js:236
listDirectoryPromise @ web.api.js:186
getDirectoryMetaInformation @ meta.js:20
navigateToDirectory @ directories.ui.js:487
openLocation @ directories.ui.js:167
editLocation @ directories.ui.js:727
(anonymous) @ directories.ui.js:762
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
web.api.js:309 GET https://mycloud/remote.php/webdav/.ts/tsm.json 401 (Unauthorized)
(anonymous) @ web.api.js:309
getFileContentPromise @ web.api.js:295
(anonymous) @ meta.js:421
loadFolderMetaDataPromise @ meta.js:415
initFolderProperties @ directories.ui.js:616
navigateToDirectory @ directories.ui.js:485
openLocation @ directories.ui.js:167
editLocation @ directories.ui.js:727
(anonymous) @ directories.ui.js:762
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
webdavlib.js:5 PROPFIND https://mycloud/remote.php/webdav/ 401 (Unauthorized)

Any tips would be great on getting this to work.

Many Thanks.

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing
