### ISSUE TITLE
Change Markdown rendering options

### ISSUE THREAD

**Issue by xordspar0** [tagspaces/tagspaces#664]
It would be nice to let the Markdown options that marked supports be configurable by the user. For example, GFM, tables, breaks, and smartypants could be turned on or off in the settings of TagSpaces. Personally, I would like to be able to turn off the "preserve line breaks" option.

**Comment by uggrock** [comment]
Thanks for the suggestion. We are accepting pull-requests....  https://github.com/tagspaces/viewerMD

**Comment by xordspar0** [comment]
Since the markdown rendering is done in core (in data/js/utils.js), won't the work have to be done in this repo?
