### ISSUE TITLE
Change tag order (sidecar)

### ISSUE THREAD

**Issue by paapereira** [tagspaces/tagspaces#666]
Tagspaces 2.9.0, Linux.
Cannot change the tag order when using the sidecar option. It shows a warning saying that's because it is not part of the file name.
Probably a limitation at this time, but can you consider allow this operation to work?

**Comment by uggrock** [comment]
Hi,
yes this sounds like an useful feature, we will consider it feature releases.
cheers,
Ilian

**Comment by uggrock** [comment]
We added this request to our trello board with ideas and suggestion: https://trello.com/c/AwGuWfIS
