### ISSUE TITLE
[Android] When trying to give a new note a title first, file is split in two

### ISSUE THREAD

**Issue by calvadosxo** [tagspaces/tagspaces#669]
Using lastest Tagspaces version on latest Android

When creating a new note txt or HTML (didn't try the other format), if I try to give a title to the file before entering text content in the new note, upon saving the title and the content, the file will be split in two: 1 note will have only the title and blank content, and 1 other file will not have title but will have the content.

The work around is to first enter some content in a new file, then save that content and then add a title and save that. This is less intuitive, so I keep making split files.

**Comment by uggrock** [comment]
not reproducible anymore -> closing
