### ISSUE TITLE
Firefox web clipper not installable

### ISSUE THREAD

**Issue by cloo** [tagspaces/tagspaces#670]
Unverified (or unsigned?) plugin:
![error](https://i.imgur.com/ggCmp4g.png)

Firefox [suggests ](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct)using dev/nightly builds, where you can disable requirement to be signed. 
Awkward, and still doesn't work, as plugin is incompatible with the current dev build..

**Comment by uggrock** [comment]
Sorry for that, the link in the blog page is wrong, it should lead to the addon page on mozilla. Please try uinstalling the last version from here: https://addons.mozilla.org/en-US/firefox/addon/tagspaces/

**Comment by uggrock** [comment]
we will correct the link as soon as possible...
