### ISSUE TITLE
CSV File Support

### ISSUE THREAD

**Issue by mbakstars** [tagspaces/tagspaces#671]
I cannot tag a CSV file due the following error. I suspect it is due the structure of CSV files themselves.  Sorry for the fuzzy image...not sure why it displays that way.

![image](https://user-images.githubusercontent.com/31328113/36563568-01cca988-17c7-11e8-9758-2741aedf89ec.png)

**Comment by uggrock** [comment]
in the community version TagSpaces renames the file in order to tag it, so tagging is completely independent from the file format. In your case it appears that the app for some reason was not able to rename this file.... The fact that the file was in onedrive folder, could be also the reason ....
