### ISSUE TITLE
Sorting by tag broken

### ISSUE THREAD

**Issue by jbhatami** [tagspaces/tagspaces#673]
If you click on the tag column to sort ascending/descending order, the label icons disappear (and the order they are sorted in is not apparent).

If you create a new empty folder in the main directory, attempting to sort by tag works (I assume) as intended, which is to say it sorts by the timestamp from the auto smart tag.

If you are trying to search by last modified, basically you need a dummy folder to have this functionality work.

**Comment by jbhatami** [comment]
sorry, sort by date created is what I meant, not modified.

**Comment by uggrock** [comment]
This should not be the case in version 3.0
