### ISSUE TITLE
Request:  Release Tagspaces WebDav Edition as a Nextcloud App

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#674]
Request:  please release [Tagspaces WebDav Self-hosted Edition](https://github.com/tagspaces/tagspaces/releases/) as [an official Nextcloud App](https://docs.nextcloud.com/server/13/developer_manual/app/startapp.html).   Fyi, I will totally pay for this as a **Pro Edition**, fully open source app.  This would optionally require:

- Tags not created automatically issue #646 since Nextcloud does not yet support such behaviour in file names by default.
- Fix webdav authentication issue #597 .  Nextcloud webdav team mentioned on the issue page that they are ready to assist you!
- Consider syncing with [Nextcloud Activity app ](https://github.com/nextcloud/activity)so Tagspaces can compliment or replace default Files app.
- Consider syncing with [Nextcloud Gallery app](https://github.com/nextcloud/gallery) so Tagspaces can compliment or replace default Files app.
- Consider syncing with [Nextcloud Markdown Editor ](https://github.com/icewind1991/files_markdown)so Tagspaces can compliment or replace it.
- Consider syncing sidecar files with [Nextcloud Collaborative Tags for integration and automated workflows.](https://docs.nextcloud.com/server/12/admin_manual/file_workflows/automated_tagging.html)
- Consider syncing with [Nextcloud Comments on files](https://nextcloud.com/sharing/) + [Share API](https://docs.nextcloud.com/server/13/developer_manual/core/ocs-share-api.html)
- Consider saving web clipper app bookmarks to [Nextcloud Bookmarks REST API](https://github.com/nextcloud/bookmarks)
- Consider syncing todo task checkboxes with [Nextcloud Tasks Caldav, ](https://github.com/nextcloud/tasks)which already supports every major desktop platform, including iOS and Android reminders.

**Comment by uggrock** [comment]
Hi Sunjam,
thank you for the meaningful suggestions. As you may already know, we are currently rewriting the core of TagSpaces in react.js . This will probably keeping us busy for the next 1-2 months. After releasing a stable react based TS we will consider release also an webdav version as usual. Once we have this version, we will be happy to support somebody to make the Nextcloud integration. 

kind regard,
Ilian

**Comment by Spass1966** [comment]
Can we keep this issue open to track? Tagspaces has not yet been released as a Nextcloud app so it makes sense to keep it open until it has.
