### ISSUE TITLE
Windows Client 64bit - Right click on several selected files, deselects all but the clicked one.

### ISSUE THREAD

**Issue by ascheucher** [tagspaces/tagspaces#677]
To test the external sidecar file tagging, I wanted to move some files to another folder.

But right clicking over some selected files (in list view), deselects all but the one below the cursor.
In the moment only one file can be moved at once.

As every move action are at least 6 clicks, it's becoming very cumbersome.

**Comment by uggrock** [comment]
It is clear, that we have a usability issue here. As a workaround for actions on multiple files, please use the perspective menu, available by clicking on the round yellow button.

**Comment by ascheucher** [comment]
Ahh! :)
Thanks for the fast response and the suggestion! 
This improves users live enormously ;)

**Comment by uggrock** [comment]
not reproducible anymore -> closing
