### ISSUE TITLE
Resizable panes?

### ISSUE THREAD

**Issue by rg-software** [tagspaces/tagspaces#679]
I am trying to customize TagSpaces a bit. First, I wanted to move the preview pane downwards, which was relatively easy to do (see my screen below). Next, I thought it would be useful is to make the border between the list pane and the preview pane resizable. I tried to make use of [jquery-resizable](https://github.com/RickStrahl/jquery-resizable), but it didn't work for now. I managed to display a splitter, but it doesn't move at all.

So, I wanted to ask whether (1) this approach should work in theory and I have to try harder; (2) there is a plan to implement something similar anyway in a proper way, and I can just wait a bit :)

![clipboard01](https://user-images.githubusercontent.com/13718460/37252864-5b83972c-256c-11e8-93f6-c47d2db3e347.jpg)

**Comment by uggrock** [comment]
We are working on a complete rewrite of the app in react.js and we are not planing to support the old user interface anymore, so please don't invest your time extending it...

In the new UI the panels are already resizable...
