### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by xstable** [tagspaces/tagspaces#681]
**Steps to reproduce:** 

1) Create A File
2) Click "Add Tags" and enter some (don't hit save)
3) Click "Tags bereinigen" ("Clean Tags") ![auswahl_565](https://user-images.githubusercontent.com/1778068/37400875-9b2af07a-2786-11e8-9c9c-948ea672ab11.jpg)

**What happend:** 

If you press "Tags bereinigen" (clean Tags  in English?), you got a dialoge with a last request if you wan't remove all Tags of the filename.
If you click cancel, all Tags you've entered before in the textfield are disappeard
.

**Comment by uggrock** [comment]
In the English version of the application "Tags bereinigen" is called "Clean all tags". The button makes exactly this, it removes all the tags from the selected files.
