### ISSUE TITLE
thumbnail gets eaten by tag

### ISSUE THREAD

**Issue by notklaatu** [tagspaces/tagspaces#682]
Using ``TagSpaces 2.9.0 - BuildID: 2.9.0.20170715161933`` on Linux:

0. No thumbnails in grid view. Internet search reveals that this feature is disabled [for now?], so I generate PNG thumbnails in ``.ts`` directory manually.
1. Go to grid vew, see thunbnails.
2. Apply tag to a file in grid view.
3. Thumbnail disappears.

**Comment by uggrock** [comment]
this is fixed in the upcoming major rewrite of TagSpaces with react.js
