### ISSUE TITLE
filenames are not tags

### ISSUE THREAD

**Issue by notklaatu** [tagspaces/tagspaces#683]
If I have a file with trailing brackets in the filename, the contents of the brackets are detected as tags.

Is there a way to opt out of using file names as tags, and instead use metadata or a localised SQLite database?

**Comment by notklaatu** [comment]
Also, warning users that tagspaces will permanently change the names of their files would be useful. Trying out tagspaces shouldn't mean that your filesystem is altered forever (or at least until you go back through, with tagspaces, to remove all tags applied). It was not clear from initial documentation that tagspaces was not creating metadata, but changing the names of files.

**Comment by uggrock** [comment]
A link to our documentation from the homepage of the project, explains extensively how tagging is implemented in TagSpaces -> https://docs.tagspaces.org/tagging#file-tagging-based-on-filename
