### ISSUE TITLE
Preview Window Offset with Videos+ Thoughs.

### ISSUE THREAD

**Issue by daephx** [tagspaces/tagspaces#685]
When viewing a video file from a full screen preview window, a portion of the bottom of the video is cut off.

Definitely like the software, after looking into many alternatives this is the one I settled on.
I very much like the idea of a minimalist/contained method of managing media/files without the 'requirement' of calling things like InfanView and MPC.
Sadly my ability to program is extremely weak otherwise id be delving into figuring out some of these things myself but here are a couple of notes I wanted to throw in for potential feature additions, such as. 

A: Custom Themes.
• I spent a couple hours just editing the CSS files. It looks pretty nice with my dark theme.

B: The ability to Hit the delete key while browsing with the preview window, for quick file removal.
• Ideally with "Ctrl+z" or "Undo" in case the action was accidental.

C: Setting to allow the user to change the default video playback to endless loop  in the Preview window, as well as an option of the player or in the "bottom right menu".

D: Finally, The ability to have another layer of "Tag Groups" or Folders in groups, Personally I Only foresee needing three layers deep but having that sort of organization of tags seems terrific.

**Comment by uggrock** [comment]
the video player was redesigned in the recent versions, dark theme is also available since v3 -> closing
