### ISSUE TITLE
Slow UI after prolonged use.

### ISSUE THREAD

**Issue by johnbturnip** [tagspaces/tagspaces#688]
After about 16 minutes of use, (searching, tagging images, etc.), the UI starts to become unresponsive.  After clicking the three dots next to a tag group, it takes 1.48 seconds just to open the context menu.  The wait times get longer as you continue to use the program.  After enough time, it can get up to 5.84 seconds.  It probably gets even longer than that as you keep going.

This really makes using the program a pain.  Thankfully, restarting the program fixes the issue, but it's obviously not a permanent solution.

Since we're talking about performance, here are my specs:
* OS: Windows 10
* CPU: Intel Core i5-4430 @ 3.00Ghz.
* RAM: 8 GB
* Windows 10 is running off of an SSD, but TagSpaces is installed on an HDD, along with  
* The folder I'm managing with TagSpaces is also on an HDD

Some more details about my workspace, just in case they're relevant:
* I have over 53 user-defined tags in the left panel
* There are 398 image files in the folder I am managing.  Almost all of them have at least one tag.

Alright, that should be enough information to reproduce the issue.  If you're still having trouble reproducing the issue, let me know and I'll see if I can help.

**Comment by arcandio** [comment]
I've got this problem too, but for some reason it was more pronounced when I first started the app, perhaps because of the default tag groups that I removed?

**Comment by uggrock** [comment]
This should be fixed in version 3.x
