### ISSUE TITLE
Is it there a better way to multi-select files?

### ISSUE THREAD

**Issue by EfronC** [tagspaces/tagspaces#689]
I just downloaded and tested this program, and at this point, the first problem I encountered is the multiple selecting of files, because the program is very sensible to movement of the mouse, and while selecting, it easily detects a tiny movement over an image as if you are trying to move that image, and deselect all the previous image. Let's say i'm selecting 23 images from a group of 100 images, and at the image 20, because it's together with another, I pass the mouse very fast between 19 and 20, causing that the mouse keep 19 clicked while moving for a little moment, this causes images from 1 to 18 to be deselected, and only left selected 19, even when that's not what i was trying to do, and is pretty annoying since this is very common due to the sensibility of the program. Is it there a better way to multi-select files where you can't move the images so this doesn't happen? Or a way to disable the "Drag image" function, or just make the checkbox area of the image not draggable? I have tried multi-select with the checkbox and with ctrl button, and the problem still happens, and I don't see another way to do this.

**Comment by arcandio** [comment]
It seems like what *should* be happening is that the drag behavior shouldn't interfere with the selection at all.

When I try this in windows explorer, I select 2 files holding `control`, then drag on a third file, and the tooltip says "2 files", having not actually selected the third. When I do this without holding `control`, the last file is dragged, having changed the selection completely.

**Comment by uggrock** [comment]
fixed in version 3.0.7
