### ISSUE TITLE
Synchronizing the "tags library" across multiple TagSpaces Pro users

### ISSUE THREAD

**Issue by Krellan** [tagspaces/tagspaces#691]
Hi, I'm using TagSpaces Pro on Mac. Couldn't find a "Contact Us" page on the https://www.tagspaces.org/ website, so using this instead. Hope it's the right place.

I'm using Tagspaces Pro with a local directory on my Mac that is under the control of Google Drive. Google Drive has its own sync process, that works. I see my shared documents, and the tags show up correctly in TagSpaces.

Multiple people have access to this Google Drive directory. We're using TagSpaces to keep collaborative work organized. For this, it works great. Unfortunately, we can't find a way to keep the "tags library" in sync, even though the files and tags themselves are good at remaining in sync.

The problem is with the "tags library" in TagSpaces. Where is the backing storage for this feature? I can't find a way to keep that in sync. Each person seems to have their own view of the "tags library", and when somebody adds a new tag, it doesn't show up as available for others to also use. Is the "tags library" stored as a file anywhere? I wish I could also put that file in Google Drive, then it would show up the same for all users.

The workaround is to use Settings/General/Export Tag Groups As JSON to make a JSON file, and save that to Google Drive. Then, in the "tags library" panel, scroll all the way down to Import Tags, then select that JSON file. Sometimes it works, and sometimes it doesn't. It doesn't seem to merge changes in tag groups. It either ignores changes entirely, or it doubles-up the tag group, creating a second copy.

I really like how I can point Tagspaces Pro at a certain directory, and it will read that directory. I wish I could do this for a tags library file as well. I would love to point Tagspaces Pro at a shared file representing our tags library, then it could sync from it, and stay in sync for all users. Is there any way to do this? Thanks!

Josh

**Comment by uggrock** [comment]
This will be a great addition to the PRO version...

**Comment by uggrock** [comment]
feature request -> closing 
some information about having a common read-only library can be found here: https://docs.tagspaces.org/dev/external-config#configuring-custom-tag-library

**Comment by Krellan** [comment]
I think this feature request was misunderstood. I do not want a common read-only tag library. I want multiple users to be allowed to read and write tags as well, and not fall out of sync with each other.

It seems that each user has their own personal view of the "tags library" and this isn't shared. This is unfortunate. The backing store must evidently be local. I wish the backing store for the "tags library" were in a configurable file location. If it were, then I could have the backing store on the shared drive also, along with the files I wish to tag. That way, everything would stay in sync.

Unfortunately, it does not seem possible to do this now. It greatly diminishes the effectiveness of tags if they can't be shared and coordinated amongst multiple users. Sharing a common read-only library isn't a full solution, as it means that users can't make any new tags or edit existing tags.
