### ISSUE TITLE
Web Clipper embedding screenshot won't work.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#693]
Web Clipper has an option in Firefox to embed a screenshot. But it will not work.
I am using Firefox ESR 52.7.3 (64 bit) in Linux.

**Comment by uggrock** [comment]
Enabling this feature will save a screenshot as dataurl in HTML and URL files. It is unfortunately still not usable, because we haven't released yet the version of TagSpaces, where these screenshots will be utilized.
