### ISSUE TITLE
Cannot open/show PDF on Windows network location

### ISSUE THREAD

**Issue by rdoila** [tagspaces/tagspaces#694]
Tagspace pro 2.9.0/2.9.8
Windows 10
See path

PDF.js v1.2.109 (build: 875588d)
Message: Missing PDF "file:///C:/Program%20Files/TagSpaces/resources/app/libs/pdfjs/web/\\nas\docs\afile.pdf".

**Comment by uggrock** [comment]
issue is fixed in version > 3 of the app -> closing
