### ISSUE TITLE
TagSpaces doesn't work

### ISSUE THREAD

**Issue by smsdavis** [tagspaces/tagspaces#695]
I just found this product today. Downloaded, unzipped.  Clicked EXE and it opens up a window with a tag that says TagSpaces...but that's it.

No menu bar or anything else ever happens.  Just this big window with a pretty background.  

Umm...shouldn't there be a MENU or something!  All I can do is close this window.

**Comment by uggrock** [comment]
Please try to run the 32bit or 64bit version respectively.

**Comment by smsdavis** [comment]
The only EXE I have is TagSpaces.exe

**Comment by uggrock** [comment]
there are different downloads available

**Comment by smsdavis** [comment]
I downloaded the 2.9 version for Windows 64 bit which is what my machine runs.  Any other suggestions?

**Comment by smsdavis** [comment]
Ok.  SO I downloaded it again and re-unzipped it and now it seems ok.
