### ISSUE TITLE
PDF files won't view

### ISSUE THREAD

**Issue by smsdavis** [tagspaces/tagspaces#696]
I have a lot of PDF files.  Some of them it views fine others it generates error saying "missing PDF file".  The PDF file is there and all my other PDF viewing programs have no problems viewing them.

**Comment by smsdavis** [comment]
Yes and no.  On a NAS drive in the same directory I can see some PDFs fine and others give the error.  Same directory, files created in the same manner.  Very odd behavior.

**Comment by uggrock** [comment]
this should be fixed meanwhile -> closing
