### ISSUE TITLE
single click opening files (feature request)

### ISSUE THREAD

**Issue by naringas** [tagspaces/tagspaces#697]
>It takes 2 clicks to open files in TS which is maybe expected like most file managers but I think that single click option should be offered since we are not really double clicking to open a file in another app.

dupe of #111 which is closed :'(

**Comment by naringas** [comment]
i want this enough to try to hack it in on my fork.

but api docs are gone?

**Comment by uggrock** [comment]
this is implemented as a option in the default perspective of version 3.0.7
