### ISSUE TITLE
Latest ViewerImage version is not included

### ISSUE THREAD

**Issue by florin-postolache** [tagspaces/tagspaces#699]
I implemented the web version of tagspaces and discovered that psd files can't be previewed.
On the ViewerImage repository it says that it's included in tagspaces v. 2.9.0, but it's not up to date.
I tried to manually include the latest ViewerImage but can't find the global function initI18N.
Will main tagspaces repository be updated with the latest extensions or should I continue trying implementing manually?
Thank you for your great work!

**Comment by uggrock** [comment]
It is now included in the beta releases of TagSpaces V3.
