### ISSUE TITLE
Essential usability improvements

### ISSUE THREAD

**Issue by coubass** [tagspaces/tagspaces#700]
Hi all,

I' glad that I've found Tagspaces: it's something I've been dreaming of for quite a while. However, there are several things that seriously hinder the user experience, and, perhaps, can be rather easily amended.

First, scaleability. For some people the fonts are too small, for me they are too big. The most basic Ctrl++/Ctrl+- zooming for all views would suffice (obviously this should involve not just text, but icons and spacing as well, and the left panel). Font options in the preferences and Gmail-like comfort-cozy-compact spacing regulation might also be considered (too much unused space between list items in the present design, as for me).

Second, one-action tagging operations. There are too many things that should be done with just one action (click, double click or keyboard shortcut), while they require two or three actions in Tagspaces.

The most essential is tagging: it's really annoying to click on a tag and then click on 'Tag Selected Files' in the context menu, especially if you have thousands of files to tag. Drag&drop doesn't work for multiple selected files, and even for individual files it's inconvenient and time-consuming.

It can be better done with a check-box-like interface. This might be a little circle next to the tag name, still on tag's background. It may have three looks: checked, unchecked and half-checked (gray or alike if some, but not all multiple selected files are tagged with it). Clicking on the circle would tag or untag selected file(s).

Clicking on the tag itself may send us to the list of files tagged with it. And the context menu with the remaining least frequent operations ('Edit tag', 'Delete tag') can be assigned to right-click only (three-dot icon may be removed).

Tags within the file field can be shown without check-box. Clicking on a tag may send the user to all files tagged with it; context menu assigned to right-click.

D&d tagging can be either deprecated or preserved.

Third, one-action external file opening. At least in my experience the most frequent action after I find a file is to open it 'natively'. Sadly, this requires two actions in Tagspaces. I'm not sure to which action this should be assigned (double-click on file name?), but it seems essential to me to be able to open files with just one action.

Fourth, tag and group order operations.
- Add 'Move tag to the last position' in file field tag context menu.
- Add 'Move tag group to the top' and '...to the bottom' in tag group context menu.
- Add user-defined tag order operations within tag groups, just like it is done for file's tags (currently, there are two options: by time of adding and by alphabet; and once you arrange them by alphabet, there is no coming back).
- All these are better implemented with drag&drop: in my humble opinion, this is where d&d is more useful. If d&d order operations are introduced for groups, tags within groups, file's tags, order options may be removed from the context menus.

Fifth, basic file management operations. It is annoying to go to a file manager to perform an action you contemplated in Tagspaces. Deleting non-empty folders, drag&drop copying and moving file(s). To me, it would be best to have a standard tree-view folder left panel with d&d functionality.

Sixth, search. Not essential, but anyway: it would be useful to search in all favourited locations and to use OR and () operands.

**Comment by coubass** [comment]
PS As for 'Third, one-action external file opening', this can be done this way:
- Click on extension icon opens file internally;
- Double-click opens it natively;
- Right-click opens context menu;
- The three-dot icon may be removed.
Not sure how it can be done on other systems, but on PC this would be ideal. For me, at least.

**Comment by uggrock** [comment]
Thank you for your suggestion. Actually some of them like the ctrl++ for zooming are already implemented in the current beta of TagSpaces v3. You can check if out here: https://github.com/tagspaces/tagspaces/releases/tag/v3.0.0-beta.12

**Comment by uggrock** [comment]
the tagging experience was improved a lot in the latest version -> closing
