### ISSUE TITLE
Translation Error, German translation 

### ISSUE THREAD

**Issue by MikeUniformCharlie** [tagspaces/tagspaces#701]
TagSpaces 2.9.0 - BuildID: 2.9.0.20170715161933

Hi everyone!

This is my first time ever posting on GitHub and on a minor issue with a software. I am currently evaluating "tagspaces" and found a typo in the german translation. Under "Help" (ge: Hilfe) > "License Agreement" (ge: Lizenzvereinbarung) the word "Lizenzvereinbahrung" should read "Lizenzvereinbarung". 

I am not sure if this is the right forum (or wether you even call it that). 

Cheers,

Peter

**Comment by uggrock** [comment]
Thank you for the hint, we will change this. The right forum would be our Translation page at Transifex, which can be found here: https://www.transifex.com/tagspaces/tagspaces/dashboard/
