### ISSUE TITLE
Tags are unresponsive and slow when dragged

### ISSUE THREAD

**Issue by dominictwlee** [tagspaces/tagspaces#702]
Version: TagSpaces 2.9.0 - BuildID: 2.9.0.20170715161933
OS: Ubuntu 16.04

![peek 2018-06-09 11-18](https://user-images.githubusercontent.com/34794189/41190471-0bc8f428-6bd7-11e8-9b9c-3067a82f5369.gif)

Whenever the tags get dragged around, they seem to be slow and delayed when following the mouse cursor. I'm not sure whether this is intentional or not but I'm happy to take a look into this and make a pull request if it is indeed a bug?

**Comment by arcandio** [comment]
I'm experiencing this as well. 2.9.0 on windows 10

**Comment by 3d73a4a412** [comment]
This is an issue for me as well, Win10 v2.9.0

**Comment by uggrock** [comment]
not reproducible anymore in the last versions
