### ISSUE TITLE
Tagging on SD card

### ISSUE THREAD

**Issue by Eusorph** [tagspaces/tagspaces#704]
I have a large video collection that I had tagged on my Surface Pro. I recently bought an Honor 9 Premium phone and transfered the SD card with the videos on it. TagSpaces doesn't see what I did on my PC, but more importantly won't put tags on the files. I get an "important" message and then it fails to add tags. Do files have to be on the internal memory of the phone to work?

**Comment by uggrock** [comment]
Some users are experiencing issues with tagging files on sd-cards. We are not sure if this is a device dependent issue. Tagging files on virtual sd-cards, which are available for example on Nexus devices, works. Can you try to tag files located on your phone memory ?

**Comment by uggrock** [comment]
this should be fixed with our last version: https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk
