### ISSUE TITLE
Feature Request: Negate Tag in Search

### ISSUE THREAD

**Issue by arcandio** [tagspaces/tagspaces#705]
I'd really find it handy to be able to *exclude* files with a tag from a search, say `anatomy arm !+NSFW` or `+anatomy +arm not +NSFW` something similar. With that, I could build very useful and complex searches for what I'm looking for in my art reference folders.

**Comment by arcandio** [comment]
In addition to this, it be nice to a whole robust tag search system, NOT, OR, AND, XOR (not sure if that one would find any use)

**Comment by uggrock** [comment]
We have discontinued the + and - shortcuts for the tag search in version 3 of the application. Now you can select the tags from a dropdown menu.

**Comment by arcandio** [comment]
Are the dropdowns purely inclusive, or can I exclude things with them as well?
