### ISSUE TITLE
Document version 3 build process

### ISSUE THREAD

**Issue by swalladge** [tagspaces/tagspaces#706]
It would be nice to have documentation for how to reproduce the prebuilt binaries available on the releases for version 3, and basically info on how to build/test the application for various platforms. This would help package maintainers maintain packages for the latest versions as well as helping would-be contributors. :)

**Comment by uggrock** [comment]
Hi,
we have updated the README for the changes with comming with version 3 of TagSpaces. For now you can find it here: https://github.com/tagspaces/tagspaces/tree/develop

**Comment by uggrock** [comment]
Please don't hesitate to ask here further questions. In the scripts section of the package.json you will find additional commands with which you can build the packages for Windows, Linux and Mac OS.
