### ISSUE TITLE
Feature Request: Drag Images to Other Programs

### ISSUE THREAD

**Issue by arcandio** [tagspaces/tagspaces#707]
I use TagSpaces to organize a large library of reference images for making artwork. I'd like the ability to drag images out of TagSpaces and into something like PureRef, where I can make a board of several images I like for a given piece. My workflow would go something like this:

1. Open TagSpaces and PureRef
2. Search for appropriate reference (`+female +face +hair`)
3. Drag 1 or more images from the TagSpaces Grid perspective into PureRef
4. Arrange/pack images in PureRef & save

**Comment by arcandio** [comment]
As it stands, I can't use tagspaces to browse for reference, I've got to do it in an explorer window so that I can drag them into PureRef, which sort of defeats the purpose of having a complex file browser built into TagSpaces for me a lot of the time.

**Comment by uggrock** [comment]
Unfortunately I think that dragging from TagSpaces or any other Electron based program is technically not possible. On the other hand dragging files info TagSpaces is supported in v2 and soon in v3 of the application.

**Comment by arcandio** [comment]
I've not attempted to build anything using the code, but [this issue](https://github.com/electron/electron/issues/11691) suggests that `webContents.startDrag()` should be the route to this kind of functionality.
