### ISSUE TITLE
WebDav Release for tagspaces v3?

### ISSUE THREAD

**Issue by flo82** [tagspaces/tagspaces#709]
hello,

thank you for your great work. I like tagspaces very much.
Is there a webdav-package (like in 2.9) planned?

Best,

Florian

**Comment by uggrock** [comment]
Yes we are planing such package. For now you can try it the webdav version following these steps: https://github.com/tagspaces/tagspaces#how-to-start-the-webdav-edition-for-testing
Any feedback and bug-reports are welcome....
