### ISSUE TITLE
Finding Untagged Files

### ISSUE THREAD

**Issue by ewa-ny** [tagspaces/tagspaces#715]
I just found TagSpaces and am testing it for a project. The one drawback I see is that I will be adding files to the TagSpaces directory directly from other applications as I work. I was hoping that TagSpaces would have a "Select Untagged Files" option so that I could quickly call up those files and tag them.

Obviously I can manually save the files with [untagged] in the name, but I was planning to sync this folder with another user who is not quite as careful about file names. So finding files without any tags would be useful to me.

**Comment by uggrock** [comment]
Implemented, will be part of v3 beta.22

**Comment by Salamimonster** [comment]
How do I search for untagged files today?

**Comment by uggrock** [comment]
You can find more on the topic in the advanced search area of documentation: https://docs.tagspaces.org/search/#search-by-type

**Comment by Salamimonster** [comment]
Thank you for the answer @uggrock
