### ISSUE TITLE
Is there a way to build v3 and target Pro version?

### ISSUE THREAD

**Issue by CTrauma** [tagspaces/tagspaces#716]
I bought a license but would like to use v3 Pro features, but can't build without the pro node module. Are there v3 Pro beta binaries available? v3 community is working great

**Comment by uggrock** [comment]
The PRO version of TagSpaces v3 is still in development. Which features do you miss most in the current v3 version?

**Comment by CTrauma** [comment]
Well I was more interested in what pro offered, but what got me interested was the folder description in markdown that is PRO only. If there is not current PRO build I'll just wait. Thanks for giving me a heads up.
