### ISSUE TITLE
Select “Show files with this tag” crashes TagSpaces

### ISSUE THREAD

**Issue by Agent-Sesame** [tagspaces/tagspaces#717]
The following function select operation worked reliably in past. 

- Select Tags view
- Right click a tag
- Select “Show files with this tag” from pop up menu
- Message box “TagSpaces is busy - TagSpaces is indexing the current directory with subdirectories”
- (This process never was particularly speedy)
- Message box “This process has crashed”

macOS High Sierra version 10.13.6
Processor 1.7 GHz Intel Core I7
Memory 8 GB 1600 MHz DDR3
TagSpaces version 2.9.0

**Comment by uggrock** [comment]
This feature is much more reliable now in v3 of TagSpaces.
