### ISSUE TITLE
Hidden setting in linux

### ISSUE THREAD

**Issue by EfronC** [tagspaces/tagspaces#718]
Hi, in Ubuntu Linux (Tested in 16.04) there is an option that is being hidden by the close button section.

![problem](https://user-images.githubusercontent.com/5926318/43967004-fc5a5580-9c88-11e8-9ac5-75e26e6df647.png)

PS: It can't be scrolled down more.

**Comment by uggrock** [comment]
Thanks for reporting this issue. It will be fixed in the next version.

**Comment by uggrock** [comment]
fixed in v3
