### ISSUE TITLE
Show hidden files/folder setting not working

### ISSUE THREAD

**Issue by joephein** [tagspaces/tagspaces#719]
Tested with the latest tagspaces-pro-win-3.0.0-beta.14.exe on Windows 10 64 bit.

The "Show files/directories with a dot (.) in front of the name (e.g. Unix, Linux, OS X hidden files)" is not working in Windows. Despite the setting turned off hidden files and folders (even when a dot is added in front of the name are shown. This function only has effect on the .ts folder created by TagSpaces.

![180815_tagspaces_hidden_files_in_windows](https://user-images.githubusercontent.com/12627719/44154107-39476cb0-a0aa-11e8-8427-ae50162f9021.PNG)

**Comment by uggrock** [comment]
It appears that the current implementation considers only the folders. This should be changed in the next versions.

**Comment by uggrock** [comment]
fixed for 3.0.4
