### ISSUE TITLE
How many Tags can I add to a file?

### ISSUE THREAD

**Issue by scorobo79** [tagspaces/tagspaces#728]
Hi,

I have just bought the payed version of Tagspaces exepcting to be able to apply many tags to a single file but after a certain number of adding tags an error occurs saying the file naming process has failed just like the free version. I am really unhappy with this and can't find the issue addressed anywhere. Is there a way of adding multiple (like mre than the ten of twelve I'm allowed)? I will be asking for a refund if this is not possible. Thanks

**Comment by uggrock** [comment]
In version 3 of TagSpaces you can use sidecar file for saving the tags. This makes the amount of tags theoretically unlimited.
