### ISSUE TITLE
ok button on 'connect a location' window does not work mac 10.13.2

### ISSUE THREAD

**Issue by Rogerhersey** [tagspaces/tagspaces#730]
Dear Reader

I have just downloaded the MacOS version of TagSpaces.
On opening the App I was shown a help box pointing to the Choose Location button.
I filled in the required fields and received no error messages.
The OK button does not activate.

My first attempt was for a Dropbox folder location.
I tried it also for a Desktop folder location but neither worked.

<img width="606" alt="screenshot 2018-09-03 14 13 17" src="https://user-images.githubusercontent.com/42924458/44967482-e78b2580-af84-11e8-8822-257426784e8f.png">

**Comment by uggrock** [comment]
Can you please try to reproduce this issue on our current beta for version 3 of TagSpaces. It is available here https://github.com/tagspaces/tagspaces/releases

**Comment by uggrock** [comment]
closed due to inactivity
