### ISSUE TITLE
Name of the file is changed while using tags

### ISSUE THREAD

**Issue by SaratBushan** [tagspaces/tagspaces#731]
Hi

I have subscribed from Pro version .

When tagging the name of the file is changed by adding tags to file name. Is there any way I can use Tagspaces without changing the name of the file?

**Comment by uggrock** [comment]
Hello, 
you can activate the feature for renaming the files by tagging, in the Pro tab of the application settings. There you have to activate the following to checkboxes:
![image](https://user-images.githubusercontent.com/1249777/45162527-823a6d00-b1ee-11e8-97f0-3747fef61b3d.png)
