### ISSUE TITLE
Brand new Tagspace 2.9.0 instalation is not working with MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by ranaur** [tagspaces/tagspaces#732]
Just download the zipfile tagspaces-2.9.0-osx64.zip from https://www.tagspaces.org/downloads/,, extracted and tried to open. I got the following error message.

It could be some problem with the new version os the OS.

Process:               TagSpaces [92150]
Path:                  /Users/USER/Downloads/*/TagSpaces.app/Contents/MacOS/TagSpaces
Identifier:            tagspaces
Version:               2.9.0 (2.9.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TagSpaces [92150]
User ID:               501

Date/Time:             2018-09-23 16:51:46.111 -0300
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        B734F156-DA5E-8F52-16D0-D64F2E0B88AF

Sleep/Wake UUID:       E9BD3CC2-EACB-4B4F-94C9-A6388F9625ED

Time Awake Since Boot: 830000 seconds
Time Since Wake:       2000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Downloads/*/TagSpaces.app/Contents/MacOS/TagSpaces
  Reason: no suitable image found.  Did find:
	/Users/ranaur/Downloads/tagspaces-2.9.0-osx64 (1)/TagSpaces.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Users/ranaur/Downloads/tagspaces-2.9.0-osx64 (1)/TagSpaces.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10a777000 -        0x10a777ff7 +tagspaces (2.9.0 - 2.9.0) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Users/USER/Downloads/*/TagSpaces.app/Contents/MacOS/TagSpaces
       0x10a8cd000 -        0x10a917acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld

**Comment by uggrock** [comment]
Hello,
can you please try our last beta available here https://github.com/tagspaces/tagspaces/releases
Thanks in advance!
