### ISSUE TITLE
-TAG search is not working

### ISSUE THREAD

**Issue by yoteamoa** [tagspaces/tagspaces#733]
In the previous version +TAG, -TAG2(without TAG2) search is perfectly worked But, In 3.0.0 Beta 14 that fuction is not working any longer

One more thing, in previous version (+TAG +TAG2) search is showing me only the files which have TAG & TAG2 but In 3.0.0 Beta 14 is not

Please check the function

Anyway I`m very pleased using your apps thanks

**Comment by whisllayjr** [comment]
I'm having the issue

**Comment by uggrock** [comment]
+ and - are not supported anymore for the tagsearch, please use the provided dropdown for selecting the tags for the tag search

**Comment by rabitag** [comment]
Even when selecting from drop down: no results

![image](https://user-images.githubusercontent.com/46843094/51427088-b2116c80-1bf3-11e9-9dd6-22d4414170f2.png)

![image](https://user-images.githubusercontent.com/46843094/51427091-bdfd2e80-1bf3-11e9-966d-0b5bc663a697.png)
