### ISSUE TITLE
Feature request: Cleanup button to delete all local stored/cached tag groups (webdav edition)

### ISSUE THREAD

**Issue by schadan** [tagspaces/tagspaces#735]
In the webdav edition it would help to have a cleanup/delete button available to delete all local stored/cached tag groups to be able to make a clean download of centralized tag groups from the tsm.json file in .ts directory without having local duplicates available.

**Comment by schadan** [comment]
see #712

**Comment by uggrock** [comment]
webdav is not supported anymore -> closing
