### ISSUE TITLE
Dark Theme for Linux Fedora

### ISSUE THREAD

**Issue by whisllayjr** [tagspaces/tagspaces#737]
I saw that there is Dark Theme for the version for Ubuntu. But I don't see this option on the version for Fedora.

**Comment by uggrock** [comment]
The theming implementation is the same for the all platforms Linux, Windows and Mac OS, but is available only on our beta releases for now. Please make sure you are using this version: https://github.com/tagspaces/tagspaces/releases/tag/v3.0.0-beta.14
I know there is now Fedora package, but you can try the tar.gz download.
