### ISSUE TITLE
Is there already a pro version for new v3.0.0-beta.14 available?

### ISSUE THREAD

**Issue by marcus-tmamtv** [tagspaces/tagspaces#739]
Hi guys,

Is there already a pro version for new v3.0.0-beta.14 release available?

thanks
marcus

**Comment by uggrock** [comment]
Hi Marcus,
no, the PRO version is still in development, but some of the old PRO features, like tagging in sidecars instead of file renaming are in the current beta release. Which PRO features do you miss at most ?
kind regards,
Ilian
