### ISSUE TITLE
Need option "Open with.."

### ISSUE THREAD

**Issue by johan0013** [tagspaces/tagspaces#74]
I can't open some files in internal viewer, for example such as *.html, *.html.maff, *.fb2.zip and others. And I can't select required application for this mime types, therefore need option "Open with external app".

**Comment by palica** [comment]
would it be possible to display such files as .maff or .fb2. Those are zipped files along with resource files. It would be perfect for maff (https://en.wikipedia.org/wiki/Mozilla_Archive_Format) since these web-page containers take up less amount of space as compared to .mht

Thank you 
palica
