### ISSUE TITLE
left-click function of the Tag

### ISSUE THREAD

**Issue by RtwChina** [tagspaces/tagspaces#741]
Why left-click and right-click of a Tag have the same function？？？

I think We can set the left-click function of the label to show files of this Tag.

In  Mac 2.9 and 3.0.

**Comment by RtwChina** [comment]
[picture](![](http://pgbppx8oi.bkt.clouddn.com/2018-10-24-TagFunction.png))

**Comment by RtwChina** [comment]
![picture](http://pgbppx8oi.bkt.clouddn.com/2018-10-24-TagFunction.png)

**Comment by uggrock** [comment]
The idea behind this is to support touch screen interactions.
