### ISSUE TITLE
Portable stable version not showing files when used from inside the external HDD that has all the files

### ISSUE THREAD

**Issue by GregariousJB** [tagspaces/tagspaces#742]
The beta version does, but likely because it's not portable - it's getting installed.

I volunteer for a animal shelter and they have over 2,000 videos that need organizing/tagging, but the external HDD they use gets moved around to different computers frequently to offload footage. Is there any way I can get this program to work by putting it on an external HDD and leaving it there?

**Comment by uggrock** [comment]
For this use case you have to create a location with relative location path such as ./ 
The portable mode works also on the v3 of TagSpaces, which is currently in beta. You have just to run in from the command prompt with the --portable parameter.
