### ISSUE TITLE
Syncing tag groups between devices

### ISSUE THREAD

**Issue by PEscortellBH** [tagspaces/tagspaces#745]
This is issue is related to issue #551 , although the solution provided here is not working for me.

Hi, I am trying to sync tag groups between networked devices, but I am having difficulties to load the tsm.json file. Just to clarify, my understanding is that the '.ts' folder is created by the user in the root of the documents repository, called "location" in TagSpaces. The name of this folder can be anything, like "example.ts".

I have changed the title and key of each of the tag groups editing with TagSpaces, but still it is not loading. When trying to load the tsm.json, file I go the setting window and click save&restart, with the option of "Load metadata..." ticked.

Am I doing something wrong?

**Comment by uggrock** [comment]
this will be possible with version 3.11.2

**Comment by jaepil-choi** [comment]
Is it possible yet? Doesn't seem like it's working.
