### ISSUE TITLE
No PDF preview on self hosted, WebDAV service

### ISSUE THREAD

**Issue by nasichassoulas** [tagspaces/tagspaces#747]
Hi everyone,

Stumbled across Tagspaces recently, it fits my needs perfectly. I have Tagspaces running on an Ubuntu 16.04 WebDAV server. The application runs perfectly over a remote connection in Chromium, I can login and browse all files and folders, but PDF preview just stays blank. An HTML test file previewed correctly.

The issue persists in Firefox and Chrome.

Thanks for your help in advance, I would really like to test Tagspaces further.

Regards,
Nasi

**Comment by uggrock** [comment]
In our last release candidate for version 3 of TagSpaces the preview works correctly again.
