### ISSUE TITLE
No evident way to install Beta to different drive than C: on Windows 10

### ISSUE THREAD

**Issue by tinkicker** [tagspaces/tagspaces#750]
I'd like to install to a storage drive I have rather than my C: drive. Is there a way to do this, because all I see is the acceptance tick box at the very beginning of the install process, and then away it goes onto my C: drive.

**Comment by uggrock** [comment]
Fixed for RC5 with https://github.com/tagspaces/tagspaces/commit/1c75e22dcb0c2f5314d3451cabf6cf5b605ab0cb
