### ISSUE TITLE
What is the process for migrating all of my notes from OneNote to Tagspaces?

### ISSUE THREAD

**Issue by tinkicker** [tagspaces/tagspaces#751]
In light of Microsoft's decision to deprecate the OneNote desktop program, I'm very interested in moving to something more future-proof. I've examined OneNote's file export selections, but I'm at a loss as to which format is best for importing into Tagspaces. Most important to me is preserving the deep notebook structures I've built there, since that is a critical part of novel planning for me.

**Comment by uggrock** [comment]
We do not have a migration guide from OneNote. If somebody can provide such, we can publish it on our blog.
