### ISSUE TITLE
Beta - ODT preview broken on Ubuntu 

### ISSUE THREAD

**Issue by Stele77** [tagspaces/tagspaces#752]
Hi!
With latest beta ODT preview is broken. Images and PDF work though.
Other than that, it looks good. Nice to see TS getting a serious upgrade!
When this is fixed, i will try TS as a document manager (once again), even though in app editing of ODT and RTF is not possible, and subscribe for pro if all goes well.
The dark theme option is godsend, this i can say so far.. :)

**Comment by uggrock** [comment]
Unfortunately we can not support anymore ODF formats...
