### ISSUE TITLE
Problem selecting multiple ficles

### ISSUE THREAD

**Issue by LAPUYADE** [tagspaces/tagspaces#753]
Hello, 
when selecting different files there is a bug : can not copy or move correctly all files : it reinitializes at just one file... 
thank you for correcting, it is a probleme for me !

**Comment by uggrock** [comment]
Thanks for reporting. On which TagSpaces version occurs this issue?

**Comment by LAPUYADE** [comment]
The last one. But did not had understand files were copied on a specific folder !

Frédéric LAPUYADE
Expert ressource en eau et digital / Pôle services

Tél. 05 57 57 28 89 / Mob. 06 33 26 15 66
91 rue Paulin – CS 71706
33050 Bordeaux Cedex - France

[cid:image001.jpg@01D3001B.967BF760]

De : Ilian <notifications@github.com>
Envoyé : lundi 12 novembre 2018 22:45
À : tagspaces/tagspaces <tagspaces@noreply.github.com>
Cc : Frederic LAPUYADE <f.lapuyade@sondalp.fr>; Author <author@noreply.github.com>
Objet : Re: [tagspaces/tagspaces] Problem selecting multiple ficles (#753)


Thanks for reporting. On which TagSpaces version occurs this issue?

**Comment by uggrock** [comment]
Please try our last beta release 3.0.0-rc.2 from here: https://github.com/tagspaces/tagspaces/releases/tag/v3.0.0-rc.2

The issue should be fixed there. Please reopen, if this is not the case.
