### ISSUE TITLE
Dragging tags onto files fails

### ISSUE THREAD

**Issue by kwa11ace** [tagspaces/tagspaces#758]
Hi, 

I  am sure I am missing something here but I cannot drag tags onto files, it shows the NA icon when trying to do so, this has been the case with all the betas I have used.  I am also a pro user, is this a pro feature or can any version do it?

I was trying this on a Dropbox folder but other local folders do the same.

**Comment by uggrock** [comment]
Hello,
no dragging on file is not a PRO feature and should work on all TS versions. Can you please try this on our last version RC3? Currently dragging on some Linux distributions with enabled graphic acceleration is not working. This is fixed for the next RC.

**Comment by mcmahonsport** [comment]
Hi there,
I have the same issue with Pro 3.0.0.0 rc-3
I installed it and encountered problems with Tagging.
- dragging a tag to a file did not work (circle with a cross through it)
- dragging tags to 'drop tags here' in the viewed file, does not work
- clicking 'Add' in Tags in the viewer--works
- removing Tags from the above dialogue also works
- Using multiple tags doesn't work
- Cleaning Tags from above works
![image](https://user-images.githubusercontent.com/43268308/48623377-5d5a3700-e9a1-11e8-9ff3-817f40f0957b.png)

**Comment by uggrock** [comment]
We were able to reproduce the issue.

**Comment by uggrock** [comment]
Partly fixed in RC4. Full fix will be available in RC5.
