### ISSUE TITLE
TagSpaces freezes when adding 

### ISSUE THREAD

**Issue by xephon2** [tagspaces/tagspaces#76]
TagSpaces freezes on my System when I try to scan my *Documents* folder including its subfolders. The *Documents* folder currently contains 86758 files (6.8 GB).

![tagspacesissue](https://cloud.githubusercontent.com/assets/3266567/3065016/0f003308-e25c-11e3-88ad-b923f4394680.png)

*top* shows 100% CPU usage of the *nw* process.

![tagspacesissue2](https://cloud.githubusercontent.com/assets/3266567/3065023/26bd663c-e25c-11e3-9c27-821c18dc02bb.png)

The CPU is quite fast:

```
Version: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
External Clock: 100 MHz
Max Speed: 3000 MHz
Current Speed: 3000 MHz
```

**Comment by uggrock** [comment]
The folders listing performance was improved in the last year, we implement on to a limit of 400 file pro folder, so I will close this issue.
