### ISSUE TITLE
Tag underscore (_) delimiter in 3.0.0 RC1

### ISSUE THREAD

**Issue by elkazer** [tagspaces/tagspaces#761]
To whom it may concern,

I'm missing the underscore delimiter in new version, so it is impossible to "import" tags from previous 2.9.0 Version.
Will this implemnted in the future for 3.x Version?

Thank you and best regards you will find a new customer
Daniel

**Comment by uggrock** [comment]
_ will not be supported for now as a delimiter -> closing
