### ISSUE TITLE
Preview pdf files after search broken in RC3 pro

### ISSUE THREAD

**Issue by perhamsen** [tagspaces/tagspaces#771]
When searching for tags, preview of files from search result result in error "Missing PDF file". See attached image. Indexing of files for text search does not work either apparently.

<img width="1280" alt="skjermbilde_search-tagspaces-rc3pro" src="https://user-images.githubusercontent.com/44965895/48945439-a0308780-ef2a-11e8-86b0-337dbdaddc51.PNG">

**Comment by uggrock** [comment]
this should be working now
