### ISSUE TITLE
Textsearch / TAGSearch not working in PRO RC4

### ISSUE THREAD

**Issue by perhamsen** [tagspaces/tagspaces#772]
After upgrading to RC4, textsearch doesn't work (didn't work in RC3 either). Searching for filenames works fine, and documents opens when I click on a file in search result.
Searching for TAGS doesn't work.

Best Regards,
PH

**Comment by hansdev123** [comment]
Yes i can confirm this issue -> issue also in RC5
Please prioritize the implementation of this feature

----

Beside of this, i wanna thank you for this great app and also for the intensiv development in the last weeks ;-) (i have purchase the pro version twice to support you ...)

**Comment by uggrock** [comment]
We can't reproduce this issue. Can you please provide exact steps for the reproduction, including the operation system? Have you clicked the search button after selecting a tag?

@hansdev123 Thank you for the positive feedback and for supporting us!

**Comment by uggrock** [comment]
possible duplicate to #818
