### ISSUE TITLE
HTML Note Buttons Not Working

### ISSUE THREAD

**Issue by kwa11ace** [tagspaces/tagspaces#773]
Just tried the RC 4 with a new HMTL note and found that some of the formatting buttons are not working.  Tried on 2 Win10 computers.

![html-not-working](https://user-images.githubusercontent.com/28090400/48991132-94cc9e80-f16c-11e8-97fb-b315be45b3be.png)

**Comment by uggrock** [comment]
Hello and thanks for reporting!
This issue is already fixed for the next RC. See this commit: https://github.com/tagspaces/editorHTML/commit/7e523aa736583ac0f5bfc9c7f53be91b16dd8cac
