### ISSUE TITLE
Issue - UI: ICON Size in mac Status bar -> v3.0.0-rc.5

### ISSUE THREAD

**Issue by hansdev123** [tagspaces/tagspaces#781]
## Summary:
AppIcon isn't fit in mac status bar

<img width="197" alt="image" src="https://user-images.githubusercontent.com/15907791/49345104-7ab92180-f680-11e8-89f7-2ec999b2b457.png">

## System Infos

Type | Value
------------ | -------------
Process:    |    TagSpaces 
Path:          |     /Applications/TagSpaces.app/Contents/MacOS/TagSpaces
Identifier:    |        org.tagspaces.desktopapp
Version:      |         **3.0.0-rc.5 (3.0.0-rc.5)**
Code Type:  |           X86-64 (Native)
Date/Time:    |         【date:yyyy-MM-dd】 【time:"HH:mm:ss"】
OS Version:   |         **Mac OS X 10.13.6 (17G3025)**

**Comment by uggrock** [comment]
Thanks for reporting this!

**Comment by uggrock** [comment]
Fixed for the next RC release
