### ISSUE TITLE
FeatureReq: thumbnail for documents for 3.0.0-rc.5

### ISSUE THREAD

**Issue by hansdev123** [tagspaces/tagspaces#782]
Please add the thumbnail feature for documents like pdf, md, txt, docx, and so on ...

Thanks hans

**Comment by uggrock** [comment]
This is already on our todo list!

**Comment by elkazer** [comment]
> This is already on our todo list!

Perfect, also for "Free" version or only for "Pro"?

**Comment by uggrock** [comment]
Generating and persisting thumbs will stay a PRO feature. New for free v3 is that the thumbs of JPGs and PNGsn are now persisted.
PDF generation will be available in the next RC.

**Comment by hansdev123** [comment]
Hi uggrock,

thanks for feedback, perfect
![image](https://user-images.githubusercontent.com/15907791/49524186-948a7c80-f8ab-11e8-8e7a-fbd061a4e23e.png)

is a pro version for rc build already available?

thanks
Hans

**Comment by hansdev123** [comment]
Hi,

that would be great ;-)
what is your email adress?

thanks

**Comment by uggrock** [comment]
info@tagsp...
