### ISSUE TITLE
Issue: Search file type can't be choosen in 3.0.0-rc.5

### ISSUE THREAD

**Issue by hansdev123** [tagspaces/tagspaces#783]
## Summary

Search file type can't be choosen and is always deactivated

<img width="301" alt="image" src="https://user-images.githubusercontent.com/15907791/49345536-9a534880-f686-11e8-9064-9c6b8af096b9.png">

## System Infos

Type | Value
------------ | -------------
Process:    |    TagSpaces 
Path:          |     /Applications/TagSpaces.app/Contents/MacOS/TagSpaces
Identifier:    |        org.tagspaces.desktopapp
Version:      |         **3.0.0-rc.5 (3.0.0-rc.5)**
Code Type:  |           X86-64 (Native)
Date/Time:    |         2018-12-02 23:02:35
OS Version:   |         **Mac OS X 10.13.6 (17G3025)**

**Comment by uggrock** [comment]
Searching for file types, the type of the tag search and some more search options not currently visible are planned to be part of the PRO version, that's way they are disabled in the Github version.
