### ISSUE TITLE
Ampersand '&' in a pdf file name causes tagspaces to not find that pdf

### ISSUE THREAD

**Issue by chylee** [tagspaces/tagspaces#792]
If there is an ampersand in the title of the pdf tagspaces can not find the pdf. An error message 'Missing PDF file 
'PDF.js v1.9.430 (build: 60225003)
Message: Missing PDF' 

then it show the path and filename up to but not including the ampersand &

**Comment by uggrock** [comment]
Fixed in 3.0.4
