### ISSUE TITLE
CJK font look ugly

### ISSUE THREAD

**Issue by Riajyuu** [tagspaces/tagspaces#796]
![image](https://user-images.githubusercontent.com/16912240/50039245-9d2c4100-0069-11e9-83a6-79e6d6e03101.png)

It seems you guys didn't define it so it just falls back to `Sim Sum` as Election defined. Here I suggest `Segoe UI`.

You can learn how to define CJK font and Latin font simultaneously from Visual Studio Code.

**Comment by uggrock** [comment]
enhancement -> closing
