### ISSUE TITLE
Optionally Store Preferences with the Exectuable 

### ISSUE THREAD

**Issue by Riajyuu** [tagspaces/tagspaces#797]
Now it is in %user%/AppData/Roaming, this makes portable mode kinda useless.

**Comment by uggrock** [comment]
In order start the app in portable mode you have to run it with --portable argument. Once started with this parameter a folder called tsprofile is created in the folder where the tagspaces.exe is located. In this folder are store all the settings of the application.

**Comment by Riajyuu** [comment]
@uggrock @sytolk 
but I was running the portable zip release?
why not make this default in those releases？

**Comment by RoyiAvital** [comment]
@uggrock , What about Registry keys?
Does tagspaces uses those in Windows even in the ZIP flavor?

I agree with @Riajyuu , The ZIP file should be portable by default.
An elegant solution by others is that the EXE looks for local settings folder. If it exist it runs in portable mode.
Then all needed is to ship the ZIP file with this folder included.
