### ISSUE TITLE
PDF file are not displayed any more

### ISSUE THREAD

**Issue by stefan38** [tagspaces/tagspaces#803]
I cannot view the content of PDF files in v3 on windows 10. I try to open a PDF, very few times its content is displayed, the most time not. I tried with other PDFs, nothing. This problem is not related with the size of the PDFs.

**Comment by uggrock** [comment]
Can you please send us one the PDFs which you can not open (if they are of course not confidential).

**Comment by stefan38** [comment]
Sure. This is one of many PDFs that are not displayed.
[This is a basic test.pdf](https://github.com/tagspaces/tagspaces/files/2706340/This.is.a.basic.test.pdf)

**Comment by uggrock** [comment]
Probably fixed with https://github.com/tagspaces/viewerPDF/commit/8e3b7dfdedbfd5be227fde8f3f1af632d03bb275
The fix will be part of version 3.0.3

**Comment by stefan38** [comment]
I use Tagspaces version 3.5. The problem still appears.

**Comment by uggrock** [comment]
issue is fixed in the recent versions -> closing
