### ISSUE TITLE
WebDAV Edition 3.0.0: Tag Library import doesn't work with older tsm.json file

### ISSUE THREAD

**Issue by schadan** [tagspaces/tagspaces#804]
When opening dialog for importing tag library in new webdav edition, I can't select a directory where my latest tsm.json (2.9.0 format) has been stored. How must the file be named in v3.0.0 to be able to place/use a centralized tag library on my web server? Btw, in 2.9.0 the tsm.json was automatically loaded in the browser - is this still working the same way in 3.0.0?

**Comment by uggrock** [comment]
fixed for the next release (3.0.1)
