### ISSUE TITLE
Existing tags no longer available after update to v3

### ISSUE THREAD

**Issue by hugopeek** [tagspaces/tagspaces#809]
Hi guys, congrats on the 3.0 release!

Eager to unwrap that long awaited present icon in 2.9.0, I just installed v3 (Pro, Linux AMD64), but now all my previous tags are gone! They are still assigned to the files (through sidecar files), but no longer show up under Tag Groups..

I tried looking in my backups for old config files to import, but couldn't find anything. Any ideas on how to get them back?

**Comment by uggrock** [comment]
We have a short migration manual published on our blog: https://www.tagspaces.org/blog/tagspaces-3-0/#migrationFrom2x

**Comment by hugopeek** [comment]
Thanks, that did the trick :+1:
