### ISSUE TITLE
[Linux] Key binding conflict

### ISSUE THREAD

**Issue by shiningdracon** [tagspaces/tagspaces#810]
When enable global keyboard shortcuts, some shortcuts of other applications stops working.
Example:
Ctrl + Shift + N is "open new window" in Firefox, but now it triggers "Create File" in TagSpace, even it is not the current focus window.

**Comment by preflight** [comment]
The same issue is occurring on Mac. Is there a setting to disable this key binding and/or all global key bindings?

**Comment by uggrock** [comment]
Ok, here is a screenshot for this setting.

![screenshot from 2019-01-10 21-42-35](https://user-images.githubusercontent.com/1249777/50995872-b3220a00-1520-11e9-9a32-4207ef7e67f6.png)

**Comment by korbendallaskoop** [comment]
same issue here (Budgie Desktop) and some of the key bindings isn't binding inside TagSpaces either. If you consider it a bug? 
Sadly makes the otherwise great app and concept unusable in my setup.

**Comment by uggrock** [comment]
You can disable the global keybinding with the checkbox from the screenshot above.

**Comment by korbendallaskoop** [comment]
Will do, thanks. Looking into tools llike AutoKey to macro into tagspaces instead for now :)
