### ISSUE TITLE
Epub format crashes the program 

### ISSUE THREAD

**Issue by NikosGre** [tagspaces/tagspaces#811]
When you try to open files in epub format they are not displayed (black screen) and just after that if you try to open another file, the program immediately crashes. 
(Linux Ubuntu 18.04, never noticed something similar in the previous version of the app)

**Comment by uggrock** [comment]
Unfortunately we do not have currently the capacity to support the epub viewer in v3 of TagSpaces. 
We will be very happy if somebody can take the lead in the development of this TagSpaces extensions. The final integration in TagSpaces will be made of course by us ...

The repository for the epub viewer can be found here: https://github.com/tagspaces/viewerEPUB

**Comment by NikosGre** [comment]
I see, I wish I could help, I'm not a developer I'm just someone who likes very much and uses a lot Tagspaces so that's how I I came here. ;-)

**Comment by uggrock** [comment]
Hi @NikosGre 
the comment was not meant not only for you but for anybody who is interested to have a epub support in TagSpaces.

**Comment by NikosGre** [comment]
Yes, I know that was not meant for me only. But why did you already close  the issue? Perhaps someone could help.

**Comment by uggrock** [comment]
The issue was closed because we disabled the epub support in 3.0.1 and and the crash does not happen anymore on new installations.
