### ISSUE TITLE
Feature request: more compact list view

### ISSUE THREAD

**Issue by Lukastos** [tagspaces/tagspaces#813]
Hi,

The list view in the v3.0.1 is not very compact and doesn't allow to see many files as it was the case in the 2.9.0. That would be nice to have a much more compact view.

For now I will stick with the 2.9 version.

By the way, the interface is much less responsive than the v2.9 when many files are displayed.

**Comment by uggrock** [comment]
This is on our todo list.

**Comment by uggrock** [comment]
Implemented in version 3.0.4
