### ISSUE TITLE
<br> line break does not work

### ISSUE THREAD

**Issue by chylee** [tagspaces/tagspaces#815]
As 3.0.1 \<br\> or \</br\> no longer line break text. if <br> no longer line breaks how do I line break text in a table.

**Comment by uggrock** [comment]
I am not able to reproduce this issue. Can you please share some more details ?

**Comment by jasonguthrieUnitas** [comment]
Actually, that didn't work in 2.9 either.  Essentially, if one inserts a <br> line break in a markdown .md file, it should render a line break as the markdown specification allows for using that and other html tags.

**Comment by uggrock** [comment]
I think empty lines are rendered once we have two regular line breaks in the md files.

**Comment by chylee** [comment]
I have done a test file to show how the page in rendered on my system. I am on a linux system using version 3.0.4 tagspaces

![screenshot_20190115_000909](https://user-images.githubusercontent.com/893425/51149568-922c2280-185a-11e9-817b-77cea0db294f.png)

[test.md.txt](https://github.com/tagspaces/tagspaces/files/2757557/test.md.txt)
