### ISSUE TITLE
Description in file name does not persist

### ISSUE THREAD

**Issue by mcmahonsport** [tagspaces/tagspaces#817]
Similar to issue #583 the description does not persist if the file is renamed after the description is saved or if a tag is added.

A subsequent description cannot be saved--the save button is greyed out.

If you move to another file and then move back, the description is there.

I am using Tagspaces Pro 3.0.0 db 592fb44c7

**Comment by uggrock** [comment]
Hi and thanks for reporting this. I was able to reproduce it. If you hit the reload button, then the description is also there .... This should be fixed.

**Comment by uggrock** [comment]
issue is fixed in the recent versions -> closing
