### ISSUE TITLE
Return from "full width view"  opens the location manager area

### ISSUE THREAD

**Issue by NikosGre** [tagspaces/tagspaces#819]
Steps to reproduce:
1 launch tagspaces, open a file and close "location manager"
2. Press "full width view" button and then press again to return back to regular view.
3. You'll see on the left a void dark column which is the space for the location manager when it's opened.
4. Press location manager shortcut and then the contents of the location manager column will appear inside the space. 
(Ubuntu 18.04, dark theme view)

**Comment by uggrock** [comment]
Thanks for reporting! I was able to reproduce the issue, it should be fixed soon.

**Comment by uggrock** [comment]
not reproducible in version 3.2.5 -> closing

**Comment by NikosGre** [comment]
Thank you, but I must inform you that something is going wrong with the
newest .deb 3-2-5 file for linux, it does not install on the system
although it appears to do so.

Στις Δευ, 21 Οκτ 2019 στις 7:16 μ.μ., ο/η Ilian <notifications@github.com>
έγραψε:

**Comment by NikosGre** [comment]
Sorry, this was wrong, the problem was on the system not the .deb file, I
fixed it and installed 3.2.5 just fine!

Στις Σάβ, 26 Οκτ 2019 στις 11:57 π.μ., ο/η Nikos Zaronakis <
nikoszr@gmail.com> έγραψε:
