### ISSUE TITLE
Sort order not persisting in 3.0.0

### ISSUE THREAD

**Issue by hugopeek** [tagspaces/tagspaces#820]
Whenever I navigate to a new folder, the sort order falls back to default again (alphabetic). This worked fine in 2.9, where setting the sort order once would apply to all subsequent folders visited.

A system setting for changing the default order would be icing on the cake!

**Comment by uggrock** [comment]
Thanks for reporting this! We will consider it for the next releases.

**Comment by uggrock** [comment]
fixed for 3.0.4
