### ISSUE TITLE
file and folder description enters into the list panel area when sized to minimum width

### ISSUE THREAD

**Issue by NikosGre** [tagspaces/tagspaces#821]
In the picture below you see the last part of the file description circled in red (the folder named "AB")
![img_20190103_124445](https://user-images.githubusercontent.com/46260059/50634341-fa276280-0f56-11e9-91bc-15649e6e08b8.png)
When I drag the list panel to minimize it this description enters into the area of the files list -again circled in red in the photo below:
![img_20190103_124558](https://user-images.githubusercontent.com/46260059/50634499-8b96d480-0f57-11e9-8a52-372a97d79614.png)

Idea: Why not have the file/folder path description displaying on the file panel (which is actually the panel most likely to be used in the fullest width?) Also when the file panel is opened in "full width view" it's the only way to see the full path to the file opened. 

(Linux Ubuntu 18.04 )

**Comment by uggrock** [comment]
This should be fixed soon.
