### ISSUE TITLE
Negative tag search not working  in version 3.0.1 anymore?!?

### ISSUE THREAD

**Issue by versus167** [tagspaces/tagspaces#822]
In previous versions this work with search for: -tagname 

But now I find no way to search for files without tags...

**Comment by uggrock** [comment]
In version 3 the search functionality was reimplemented from scratch and the support for + and - in front of the tags is for now not supported.

**Comment by versus167** [comment]
Oh, that's bad for me. Where can I get the previous version?

**Comment by uggrock** [comment]
This is the last release supporting the "negative tag search" https://github.com/tagspaces/tagspaces/releases/tag/v2.9.0

**Comment by versus167** [comment]
Okay. Thank you!

**Comment by uggrock** [comment]
Negative tags search is available in version 3.0.9
