### ISSUE TITLE
Feature Request: Recursive Search

### ISSUE THREAD

**Issue by julianseeger** [tagspaces/tagspaces#823]
In TagSpaces 2 there was an option to search recursively, thus allowing to find files within tagged folders. I would like to have that again as it was pretty useful (at least for me). It could also be described as virtual transitive/recursive tagging when thinking the other way around.

Simplified usecase:  
Imagine you collect music files...

- top-level folder: release year (tag name equals folder name; example: "2019")
- subfolder: genre (tag name equals folder name; example: "Jazz")
- files are dropped into that subfolder after buying (tag name is for example the artist like "Camila_Meza")

You could, of course, tag every file with the artist, the genre and the year, but that would be pretty redundant as it's already placed in the corresponding folder.

Now imagine you want to find all Jazz songs by Camila_Meza, so you enter the search, type Tags=`Jazz`,`Camila_Meza`, activate "all tags" and "recursive" and as a result, you find all Jazz songs of her from all release years.

**Comment by uggrock** [comment]
The search in TagSpaces 3 is always recursive. By opening of a location the application index all files and subfolders in it. Later, the search shows results from this index.

**Comment by julianseeger** [comment]
@uggrock seriously, it just doesn't work. Neither with 3.0.1, or with 3.1.1.

Example:
root/folder1/file1

Tag folder1=tag1 and file1=tag2.
Now search in root for tags "tag1" and "tag2".

**Actual behavior:** No file or filder found
**Expected behavior:** file1 found
