### ISSUE TITLE
Cannot paste images directly from clipboard.

### ISSUE THREAD

**Issue by jbhatami** [tagspaces/tagspaces#824]
In version 2.x you could paste directly into the body from the clipboard. This is much faster.

In version 3.0.1 it appears to not be working. Seems the only way is to click the insert image button, and specify the image location.

This is obviously a huge step backwards.

**Comment by jbhatami** [comment]
Hi, please see attachment showing 3 separate methods of pasting from clipboard on v2.9.


Used with hotkeys for the screen capture, this feature really increases productivity when using images heavily (bug reports, how-tos, etc.).

![2019-01-07_14-46-58](https://user-images.githubusercontent.com/36491644/50869601-98596500-1369-11e9-81dc-e31126a3b61c.gif)

**Comment by uggrock** [comment]
Hi and thanks a lot for the clarification video!
For the html editor extension we use the [summernote](https://summernote.org/) library where in its current version this functionality appears to be brocken. TagSpaces is designed to support many editor extensions, so if somebody wants to implement a html editor with a modern editor like [slate](https://www.slatejs.org/#/images) for example is welcome! We will support him/her and will integrate the new editor in the application.

**Comment by uggrock** [comment]
The code for the current editor can be found here: https://github.com/tagspaces/editorHTML

**Comment by ymjonline** [comment]
Hi,
pasting images does not work in a Markdown file either.  

This is really a limitation, especially for an app that claims to be a replacement for Evernote.

I end up editing my MD files in an external editor (Typora or Marktext - that do that superbly)
but that would be great and essential to be able to paste pictures directly from within Tagspaces, especially on the mobile apps (to create quick notes on the go)

**Comment by jbhatami** [comment]
FYI looks like it is working on Summernote's site.
![2019-01-14_10-16-18](https://user-images.githubusercontent.com/36491644/51131862-b13c9d00-17e5-11e9-9db3-005f756d651d.gif)

**Comment by LaRoccaD2** [comment]
Has there been any updates on this issue, I attempted to paste a screenshot from clipboard on 3.2.4 and  3.2.5 but no luck
Thanks!

**Comment by uggrock** [comment]
Fixed in version 5.0 in the markdown editor

**Comment by WGandy** [comment]
It seems that pasting an image from clipboard put the images inline the md file (rather than creating an image file and linking to it). Is this correct? 
If so, this is unfortunate because it breaks readability for the md files in a regular text editor.

**Comment by WGandy** [comment]
I want to test further but I've run into a problem. TagSpaces opens a plain white window when I try to view a document. I need to somehow reset the application. This is on macos apple silicon.

**Comment by sytolk** [comment]
![Screenshot 2023-10-11 094915](https://github.com/tagspaces/tagspaces/assets/1415463/9eb7cb29-5261-4425-8af2-839fad59032e)
