### ISSUE TITLE
Markdown does not render checkboxes.

### ISSUE THREAD

**Issue by hasues** [tagspaces/tagspaces#826]
In Markdown, I believe the "[ ]" would render a checkbox.  Putting an x in the [ ] would create a checkbox that has been filled.  This does not appear to work in 2.9.0 or 3.0.0.

**Comment by uggrock** [comment]
The [] brackets are not part of the markdown specification. So we do not support such functionality for now. But it can be added by in [viewerMD](https://github.com/tagspaces/viewerMD) extensions. We use there the [marked](https://github.com/markedjs/marked) javascript library, which I believe can be easily  extended with such functionality.
