### ISSUE TITLE
Microsoft Excel files tagged by TagSpaces cannot use Excel's pivot table functionality

### ISSUE THREAD

**Issue by suhailtandel** [tagspaces/tagspaces#827]
The pivot table functionality of Microsoft Excel does not work if the square brackets [] are used in the file name. ( Ref _https://support.microsoft.com/en-in/help/2862807/excel-pivottable-error-data-source-reference-is-not-valid_ ). This issue prevents the use of tagspaces for adding tags on Microsoft Excel files.

**Comment by uggrock** [comment]
Hello,
we can't do much about this issue. You can use the sidecar tagging by default, if you have Excel with pivot tables. Sidecar tagging is meanwhile available in the free version.
Ilian
