### ISSUE TITLE
Change task status from Markdown viewer

### ISSUE THREAD

**Issue by ymjonline** [tagspaces/tagspaces#829]
** Issue
to make it a true replacement from e.g. Evernote and the likes, the ability to manage tasks/ToDo is crucial.
For now the only way is to create a note with a bunch of checkboxes (would be great to have a "file" which is a task in itself and that can be "checked" so that we can put more info about that task in the file itself - but that's another story)

The problem is that checkboxes cannot be checked from within the interface (aka MD viewer)
Having to get into the code first is not user-friendly at all.

** Screenshots
![tagspaces_checkbox](https://user-images.githubusercontent.com/46528969/50970549-fa3cda80-14e1-11e9-80ac-fe8313f9b0d6.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.1

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy 8]
 - OS: [e.g. Android 7.0.1]

**Additional context**

**Comment by uggrock** [comment]
enhancement request -> closing
