### ISSUE TITLE
Show files with Tag, directly

### ISSUE THREAD

**Issue by ymjonline** [tagspaces/tagspaces#830]
** Problem 
In a note taking context, the ability to quickly find what you're looking for is crucial.

** Expectation
I'd expect that upon clicking a Tag, I would immediatly see the associated notes/files.
Instead, I have to choose and click "Show files with tag". It feels very heavy, cumbersome and not user-friendly.

** Solution
Why not make the "tag editing" menu visible only upon clicking on the 3-dot menu ? and clicking the tag itself would show associated files immediatly ?

** Screenshot
![tagspaces_show_tag](https://user-images.githubusercontent.com/46528969/50971749-18f0a080-14e5-11e9-8ab8-e0ea2515756e.gif)

** Context
Especially in the context where I would put all the notes in one flat single directory (as opposed to one Folder per "Notebook") and would use Tag as "Notebooks" instead, this becomes super frustrating.

** Associated bug
As I was testing this, I realized that it does not actually show *all* files with the Tag. Some are missing. Will try to make a separate issue out of it, but can't figure the discriminative factor for now.

(thanks for this awesome tool !  - I'm dreaming of turning it into the multi-platform note-taking app, getting there...)

**Comment by uggrock** [comment]
feature request -> closing
