### ISSUE TITLE
New tags create by a tag rename are not collected

### ISSUE THREAD

**Issue by ymjonline** [tagspaces/tagspaces#832]
**Describe the bug**
The collected tag features does not seem to actually collect "orphan" tags.

For instance, if I edit a tag from a file a rename it then
-  the tag does not appear anywhere in the Tag list
- I cannot search for this Tag
- I cannot apply it to another file 

**Screenshots**
![tagspaces_orphan_tag](https://user-images.githubusercontent.com/46528969/50973578-8b637f80-14e9-11e9-9a4b-659fc21c9cbc.gif)

**Desktop** 
 - OS: Windows 10
 - Version 3.0.1

**Comment by ymjonline** [comment]
> BTW, which tool do you use to create this great animated gif ?

[ScreenToGif](https://github.com/NickeManarin/ScreenToGif) Pretty neat, but that's on Windows

**Comment by uggrock** [comment]
Thanks!

**Comment by uggrock** [comment]
fixed for 3.0.4
