### ISSUE TITLE
Full text search not available

### ISSUE THREAD

**Issue by ymjonline** [tagspaces/tagspaces#833]
**Describe the bug**
Upon search for keyword, the result should return files that also _contain_ the keyword.
This should be true for text-based files such as Markdown

However it does not find anything.

This is obviously an *essential* feature.

**Desktop**
 - OS: Windows 10
 - Version 3.0.1

**Screenshots**
![tagspaces_search_empty](https://user-images.githubusercontent.com/46528969/50974823-67ee0400-14ec-11e9-9e18-957f3c8f1ce3.gif)

**Comment by uggrock** [comment]
TagSpaces does not currently have a full-text search, but we are planning to implement such at least for text, markdown and html files.

**Comment by 7c** [comment]
This feature will make this app more useable for sure, right now this app is nice to tag but thats all. Fulltext search is a must

**Comment by uggrock** [comment]
An experimental fulltext search is available in TagSpaces PRO for MD, TXT and HTML files, starting from version 3.0.9 .
