### ISSUE TITLE
RPM suport

### ISSUE THREAD

**Issue by TJProgrammer** [tagspaces/tagspaces#834]
A rpm package for redhat, centos, fedora and other rpm OS.

**Comment by uggrock** [comment]
How about using the AppImage package for these distributions?

**Comment by TJProgrammer** [comment]
Or Flatpak....
And update the documentation.

**Comment by Hillside502** [comment]
Appimage is good --- but unavailable for TagSpaces Pro!

**Comment by uggrock** [comment]
enhancement -> closing
