### ISSUE TITLE
[Request] Supprot Reading keyword from XMP standard

### ISSUE THREAD

**Issue by woc2006** [tagspaces/tagspaces#837]
Adobe Bridge/ Illustrator/ InDesign/ Photoshop use XMP to store keywords. It could be a great help for people like me using Bridge to manage photos before.

https://helpx.adobe.com/bridge/using/metadata-adobe-bridge.html
https://en.wikipedia.org/wiki/Extensible_Metadata_Platform

**Comment by uggrock** [comment]
This will be a good addition to TagSpaces...

**Comment by uggrock** [comment]
feature request -> closing
