### ISSUE TITLE
Update 'Directory Properties' when selecting a different folder

### ISSUE THREAD

**Issue by Jhsmit** [tagspaces/tagspaces#838]
First of all, great product and I'm very happy with the v3.0 release.
I'm using Tagspaces Pro v3.0.1.

I want to add tags and description for a large number of folders in one subfolder. I'm currently adding tags and descriptions by right clicking and selecting 'Directory Properties', which opens up another panel on the right while the folders i'm going through are now in the middle panel. 

For me, my workflow would be faster if the Directory Properties would update on the right if I selected a different folder in the middle. At the moment I have to right click and select Directory Properties every time which slows the process down. This would also speed up scanning though several folder descriptions.

**Comment by uggrock** [comment]
Thanks for the positive feedback!
The idea behind this feature is that now you able to navigate in some sub folder, without closing the currently opened file. Regarding the scanning of the descriptions, the first few words of every descriptions is visible in the grid and list view.

**Comment by Jhsmit** [comment]
That makes sense. Is there a possibility of assigning a hotkey to opening directory properties of selected folder?

**Comment by uggrock** [comment]
ALT+Enter can be used for opening the properties of the current entry.
