### ISSUE TITLE
[Request]: Advanced search, include sub-string...

### ISSUE THREAD

**Issue by Nealix58** [tagspaces/tagspaces#841]
When working on version 3.x advanced search, please consider
the following;    If a user is going to tag thousands of files, it still
makes sense to have a smaller number of tags so that the user
interface is not too huge while tagging files and doing drag and drop.

Therefore, I would propose that in addition to being able to search
by file size and date, please also add;
Search by filename substring;  In example;  
<Filename includes sub-string(s):  1975 .AND. Mustang>
.AND.
Tags =  Cars, Ford
.AND.
File Type = PDF

In other words, I will still need a reasonable number of tags while tagging,
but I don't want to scroll through tags for every year from 1900 to 2019.
And I don't want to scroll through tags for every model name under
each car manufacturer name.  So it seems logical to have tags like car, Ford,
GM, Toyota, but then to also be able to search where the filename also includes
some substrings.   In this example above, it might look like this;

Filename:  "A history of the 1967 Mustang.PDF"
Tags:  Cars, Ford, Reference, Articles

Thanks for considering.

Neal Pollack

**Comment by uggrock** [comment]
the file name is considered by the search in recent version of the app -> closing
