### ISSUE TITLE
Markdown Tables do not render correctly when using table operators in a string or quote.

### ISSUE THREAD

**Issue by hasues** [tagspaces/tagspaces#844]
If I create a quoted string in a markdown table block that contains the table item delimiter "|", it will interpret that as the end of the entry for a table grid item and put the rest of the contents in the next grid.

**To Reproduce**
Create a table in markdown.  in one of the cells, make a comment string using the ``` operators and insert the | character.  It will interpret this as the end of the table item definition.

**Expected behavior**
This should be automatically escaped as it is part of a string due to the end delimiter of string type has not been reached.

**Screenshots**
This occurs in 2.7-3.0:
Put this in an md file and save it:

|Function | Command |
|-----|-----|
|Example | `awk` |
|Example2 | `awk | grep`|
|Example3 | "awk | grep" |
|Example4 | ```awk | grep```|

Code:
```|Function | Command |
|-----|-----|
|Example | `awk` |
|Example2 | `awk | grep`|
|Example3 | "awk | grep" |
|Example4 | \```awk | grep\```|```


**Desktop (please complete the following information):**
 - Linux
 - Browser Firefox
 - Version 52

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by hasues** [comment]
Hm, it seems that Git's Markdown has the same issue.  Oh well, I guess it is expected behavior.  Whatever markdown renderer Laverna used worked really well based on these gotchas I'm finding.  Starting to really dislike Markdown.

**Comment by hasues** [comment]
Since this happens on Github as well, i'm going to consider this normal.  I'm too spoiled on the previous editor I used.

**Comment by hasues** [comment]
| Requisites | Command |
|------------|---------|
|CMDB Computer System Domain Name| ```PATH=/bin:/usr/bin:/usr/sbin;LANG=C;nslookup $(hostname) 2>/dev/null |awk '/Name:/ {print $2}' |cut -d. -f2-6 -s``` |
|CMDB_hostName|```PATH=/bin:/usr/bin:/usr/sbin;LANG=C;nslookup `hostname` 2>/dev/null \|awk '/Name:/ {print $2}' |cut -d. -f1```|
|CMDB_tokenId|```uname -s```|

**Comment by hasues** [comment]
The above can not render correctly in Markdown in TagSpaces.  It really goes back to the original issue I stated, which may fall on the flavor of Markdown being used which expects escaping characters, regardless if they are in existing strings of sorts.  However, it appears that the angle bracket ">" beings to break the rendering.  I tried escaping it with "\" as well as "`` ", but it doesn't render it.

**Comment by hasues** [comment]
![image](https://user-images.githubusercontent.com/3744096/51286283-527f4b00-19c0-11e9-98dc-8c72a4e444e2.png)

This is how it is rendered.

**Comment by hasues** [comment]
> | Requisites | Command |
|------------|---------|
|CMDB Computer System Domain Name| ```PATH=/bin:/usr/bin:/usr/sbin;LANG=C;nslookup $(hostname) 2>/dev/null \|awk '/Name:/ {print $2}' \|cut -d. -f2-6 -s``` |
|CMDB_hostName|```PATH=/bin:/usr/bin:/usr/sbin;LANG=C;nslookup `hostname` 2>/dev/null \|awk '/Name:/ {print $2}' \|cut -d. -f1```|
|CMDB_tokenId|```uname -s```|

**Comment by uggrock** [comment]
Hey @hasues , and thanks for reporting this! For the markdown rendering we relay on the [marker](https://github.com/markedjs/marked) library. Can you please check you could reproduce this issue there? They have a nice [playground](https://marked.js.org/demo/).

**Comment by hasues** [comment]
I can't get the playground to work.  Is it working for you?  When I go there, I see the source on the left but nothing renders on the right.  What do you do to get anything to render?

**Comment by uggrock** [comment]
Yes it is working for me on Chromium, I see the result immediately in the right panel.

**Comment by hasues** [comment]
I don't see it unless I press the "Permalink" button.  It appears to not render tables at all for me.  Still playing.  Markdown headers work as does code statements.  Tables don't work.

**Comment by uggrock** [comment]
There is a dropdown after the clear button, there you select the rendering options and experiment with them.

**Comment by uggrock** [comment]
Here are our current options: https://github.com/tagspaces/viewerMD/blob/master/main.js#L18

**Comment by hasues** [comment]
![image](https://user-images.githubusercontent.com/3744096/51305801-d90c4a80-1a09-11e9-9009-2e4d3816e6b9.png)

**Comment by hasues** [comment]
Looks like it renders the code blocks correctly, but until I can get that demo to recognize table code, I can't test how it handles escaping the pipe character |.

**Comment by uggrock** [comment]
Can you then copy and paste here the last working configuration, so we can integrate it in the markdown viewer. Or you can also create a PR in the viewerMD repo...

**Comment by jasonguthrieUnitas** [comment]
Oh, but I should add that it does not work in TagSpaces 2.9 on MacOS; it just works on the site you sent me.

**Comment by uggrock** [comment]
fixed in the latest 4.x releases
