### ISSUE TITLE
<br> line break does not work

### ISSUE THREAD

**Issue by chylee** [tagspaces/tagspaces#845]
As 3.0.1 \<br> or \</br> no longer line break text. It no longer line breaks. I have done a test file to show how the page in rendered on my system. I am on a Linux system using version 3.0.4 tagspaces. kubuntu 18.10

![screenshot_20190115_000909](https://user-images.githubusercontent.com/893425/51386326-f03a5d80-1b19-11e9-871e-8c658339b7f1.png)

[test.md.txt](https://github.com/tagspaces/tagspaces/files/2772855/test.md.txt)

**Comment by uggrock** [comment]
<br> is a HTML-tag and HTML tags are not supported in the md-viewer -> closing
