### ISSUE TITLE
Delete hidden files, when uninstalling

### ISSUE THREAD

**Issue by rabitag** [tagspaces/tagspaces#846]
When Tagspaces is uninstalled, thge hidden files in the folders should be also deleted (or wherever they are).

Steps to reproduce:
1. delete all tags
2. uninstalled tagspaces
3. install tagspaces again
4. check tags: tags that were deleted are visible again

**Comment by uggrock** [comment]
Some users are uninstalling the old version before installing a new one, in such case, removing of all .ts folders on uninstalling will not make sense.
You can always delete the .ts folders, just search for them in Windows Explorer and delete them.
