### ISSUE TITLE
"Search in Document" not working

### ISSUE THREAD

**Issue by jvmachados** [tagspaces/tagspaces#847]
Even if the tagging function is great, being able to search for text inside notes is still an indispensable feature. 

I know that Tagspaces doesn't support full text search for all notes just yet (I'm waiting anxiously for that feature to be included). Still, while we're waiting for that to be released, the "Find in Document" feature that already exists for .md files should be improved.

When I search for a word using that option it highlights it, but doesn't scroll the reader automatically to find it. I have to scroll manually until I find the highlighted word. It also doesn't give me the option to "show next" or "show previous". Needless to say, that isn't very practical.

I'm really liking Tagspaces and I would like to continue using it without having to use third party applications all the time. Please fix this.

(Sorry for my quirky English)

**Comment by uggrock** [comment]
Search in the content of TXT, MD and HTML files was added to the PRO version starting from version 3.0.9 .
