### ISSUE TITLE
TAG search is not working

### ISSUE THREAD

**Issue by rabitag** [tagspaces/tagspaces#848]
Even when selecting from drop down: no results

![image](https://user-images.githubusercontent.com/46843094/51427178-ffdaa480-1bf4-11e9-81a0-df2ad11b04ba.png)

![image](https://user-images.githubusercontent.com/46843094/51427179-0701b280-1bf5-11e9-8bdc-c57c7a6b83df.png)

**Comment by stefan38** [comment]
I saw it works if I reload the open directory and close the open tagged file.

**Comment by uggrock** [comment]
could not be reproduced in the last versions -> closing
