### ISSUE TITLE
Folder view not updating when selecting next or prev file in the file viewer

### ISSUE THREAD

**Issue by IHappyDayI** [tagspaces/tagspaces#859]
The lastSelectedEntry updates, but the array of selectedEntries doesn't. That's why the highlight on the entry doesn't update either.

![folderviewnotupdating_01](https://user-images.githubusercontent.com/1915778/51781026-1791bb80-2114-11e9-8fcc-53632a6c0b58.gif)

**Comment by uggrock** [comment]
This should be working now, please try it in the current 3.0.9 version and reopen if not.
