### ISSUE TITLE
image zoom reset display problem

### ISSUE THREAD

**Issue by stefan38** [tagspaces/tagspaces#861]
**Describe the bug**
After resetting the image zooming (>500%), the huge black area is displayed and it requires to zoom out to 3% the image could be visible on the screen again. Note: the used image has: 640px X 4071px size, it is a screenshot of an article. I use to create screenshots of my articles.

**To Reproduce**
1. Select the image file
2. In the preview area zoom in >500%
3. Click to zoom reset
4. See the display problem
5. Zoom out to aprox 3% till the image appear in the preview in very small size.

**Expected behavior**
After resetting the image zooming, the selected image should be centered and displayed on the screen as before zooming.

**Desktop (please complete the following information):**
 - OS: Windows 10 latest version 64-bit
 - Version Tagspaces 3.0.5

**Comment by uggrock** [comment]
this should be meanwhile fixed -> closing
