### ISSUE TITLE
monthly subscription

### ISSUE THREAD

**Issue by stefan38** [tagspaces/tagspaces#864]
**Describe the solution you'd like**
Is there any plan to make an option for monthly subscription?

**Comment by uggrock** [comment]
Actually not. It will be difficult to setup such a thing. We can not and do not want to track your TagSpaces usage. Buying a PRO license, will give you the right to get updates for one year, which is kind of yearly subscription, with one difference, after this one year you can continue to use the old version TagSpaces.
