### ISSUE TITLE
Unable to browse any directories.

### ISSUE THREAD

**Issue by angrierhorse** [tagspaces/tagspaces#87]
Tagspaces on my android is completely non functional.  I cannot add any directories via the dialog.  I can manage to add paths by typing them manually but I cannot navigate to any directories.  All I get is the following message:
 
"Error occurred while opening a path! Currently opened location will be closed."

logcat is filled with these errors:

06-06 11:19:11.350 D/CordovaLog(18267): file:///android_asset/www/cordova/fastclick.min.js: Line 9 : Uncaught TypeError: Cannot call method 'apply' of undefined
06-06 11:19:11.350 E/Web Console(18267): Uncaught TypeError: Cannot call method 'apply' of undefined at file:///android_asset/www/cordova/fastclick.min.js:9

Pastebin dump of logcat, verbose level:

http://pastebin.com/mF0h0U3t

I have tried wiping the cache and reinstalling.  There is not really much else I can do to make this work.

This is really p******** me off.  The program is completely non functional.  The phone is a Lenovo P780, android 4.2.

**Comment by allyalla** [comment]
What is closed? Nothng closed there. App probably just do not have and do not even aims to reserve rw permission during installation - permission to write to the External SdCard. It should be able to be places to the external sdcard - then it will qet from the official system personal folder in /storage/extSdCard/Android/data/org.tagspaces.androidapp  and then it will be able to work in these folder on extSdCard. What is closed here man?

**Comment by uggrock** [comment]
issue should be fixed in the current 1.12.0 release
