### ISSUE TITLE
Feature - Auto-hide the media player progress bar

### ISSUE THREAD

**Issue by IHappyDayI** [tagspaces/tagspaces#878]
When the mouse cursor is not in the media player, or the media player received no input for a short duration, it would be nice to hide the play/progress bar. The bar is covering the bottom part of a video being played. I guess a different solution would be to move the bar below the video.

**Comment by uggrock** [comment]
The source code for the audio video player extension is located here: https://github.com/tagspaces/viewerAudioVideo

**Comment by uggrock** [comment]
The implementation will not be easy, since this feature is not supported in the [plyr](https://github.com/sampotts/plyr) library, which is used in the player.
