### ISSUE TITLE
Optimize performance by virtualizing

### ISSUE THREAD

**Issue by IHappyDayI** [tagspaces/tagspaces#888]
To optimize performance and memory usage when loading folders with lots of files the list and grid views should use virtualized lists.

React-Virtualized (https://github.com/bvaughn/react-virtualized) seems to support both lists, and grids.
https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md
https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md

**Comment by EnvarionX** [comment]
This is very needed! Anything to improve performance. I need this program to be much more capable of handling >30,000 images in one directory without a NASA computer.

**Comment by uggrock** [comment]
We are accepting PRs, if somebody want to integrate virtualization in the application...
