### ISSUE TITLE
The oportunity to set a fixed order of tag by group

### ISSUE THREAD

**Issue by therearegods** [tagspaces/tagspaces#895]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by roxfanuk** [comment]
Yep - I'd like this too, just keeping the tag group sorted alphanumerically would be a great start

**Comment by uggrock** [comment]
you can now change the order of file in the tag groups with drag and drop -> closing
