### ISSUE TITLE
Internal links to local files (HTML editor)

### ISSUE THREAD

**Issue by Victor239** [tagspaces/tagspaces#896]
**Is your feature request related to a problem? Please describe.**
TagSpaces' folder- and tag-based navigation is insufficient for building wiki-like personal knowledge base. Hyperlinks would be far more efficient for this purpose. 

**Describe the solution you'd like**
In HTML files either extend the hyperlink button or create a new button which allows linking to any file in any location in TagSpaces. That way it can work like a wiki page with multiple internal links in paragraphs, all pointing to different relevant files. 

**Describe alternatives you've considered**
The closest is tag-based navigation, but that's much more time-consuming and bad UX.

**Comment by uggrock** [comment]
Implemented in the markdown and html editors
