### ISSUE TITLE
Improve changelog layout

### ISSUE THREAD

**Issue by AWalton** [tagspaces/tagspaces#897]
Not exactly a feature for TagSpaces itself but on the website it would be much more readable if you used several sections e.g. Ongoing / New Features / Improvements / Fixes:
![](http://i.imgur.com/0g3c9DX.png)

My favourite layout I've seen though uses coloured tags to mark each bullet point:
![](http://i.imgur.com/KQcOLon.png)

**Comment by uggrock** [comment]
Thanks for the suggestion, will try to classify the items in change log for the future releases.
