### ISSUE TITLE
Show a unique URL when previewing each folder/file (cloud version)

### ISSUE THREAD

**Issue by Victor239** [tagspaces/tagspaces#898]
**Is your feature request related to a problem? Please describe.**
I use hyperlinks to travel between the pages and files of various web apps I use such as Google Sheets, Airtable, Asana, etc. Currently I can't link to TagSpaces files because there is no unique URL for each file i.e. http://demo.tagspaces.org never changes no matter what file you open.

I also often use the 'Duplicate Tab' feature in my browser so I can open multiple files at the same level in a hierarchy (folder equivalent in TagSpaces), but using it with TagSpaces just opens the second tab at the root directory, which means I would have to click through all the folders again.

**Describe the solution you'd like**
I imagine URLs like these examples: http://demo.tagspaces.org/file/c8dcde8f5b66 and http://demo.tagspaces.org/folder/105df5d0ac66. This way filename or filetype changes won't affect the unique URL, but you at least know that a file can't change into a folder.

**Describe alternatives you've considered**
There's no real alternative at the moment other than dealing with this UX headache and clicking through all the folders to reach the file I was looking to link to. 

**Additional context**
This is related to #896 (internal links in HTML editor) but only regards the cloud version, and only for hyperlinks from external websites/apps to TagSpaces.

_Note:_ This is NOT regarding sharing files with others (though this feature probably could extended to do so). This is simply related to personal-use hyperlinks so I can access the files quickly and easily.

**Comment by uggrock** [comment]
This will be very useful indeed ....

**Comment by uggrock** [comment]
already implemented -> closing
