### ISSUE TITLE
"Add / Remove tags" thinks i have multiple files selected

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#899]
**Describe the bug**
Tagspaces 3.0.9
Tag editor window has incorrect title when editing tags for a single file

**To Reproduce**

1. Right click a file in the right hand panel
2. hit Add / Remove tags
3. tag editor has title "Tag operation on multiple files" even when only one file is selected

**Expected behavior**
Title should be "Add / Remove Tags"  or something similar

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
installed from .deb

**Comment by uggrock** [comment]
could not be reproduced in the latest versions -> closing
