### ISSUE TITLE
v3 Regression:  can't drag and drop tags from one file to another

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#900]
issue:
In previous versions of TagSpaces we could drag and drop tags from one file to another. We could also drag and drop exisiting tags from files into the tag library.
In version 3.x its not possible. Dragging seems to attempt to drag and drop the entire file record but achieves nothing.

steps to reproduce:
1. open a directory that contains more than one tagged file
2. try dragging a tag from one file to another that doesn't already have that tag
3. the entire file record is dragged, and dropping it does nothing

expected behaviour:
A file's individual tags can be dragged onto another file, or can be dragged into the tag library

OS: Linux Mint 19.1
TagSpaces 3.0.9

**Comment by uggrock** [comment]
This is supported again in version 3.1.1.
