### ISSUE TITLE
no focus when adding tags

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#901]
**Describe the bug**
Previous versions I could just start typing the new tags for a file after right-clicking and selecting Add /Remove tags. In version 3.x I have to also click inside the textbox before typing which adds an extra step to the process.

**Expected behavior**
Right click the file, select Add / Remove tags, start typing your tags.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - TagSpaces 3.0.9

**Comment by uggrock** [comment]
not reproducible anymore -> closing
