### ISSUE TITLE
Missing drag and drop of tags from one file to another

### ISSUE THREAD

**Issue by robozb** [tagspaces/tagspaces#902]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by roxfanuk** [comment]
in v 2.x you could just drag and drop, no need to copy/paste.
in v 3.x you can't  - no idea why not.
I already posted a bug report for it.

FYI - you'll be more likely to have your feature request looked at if you describe it fully in the description box using the prompts provided.

**Comment by uggrock** [comment]
closing -> duplicate to #900
