### ISSUE TITLE
drag and drop tags between groups is moving the tag to the right of the one selected

### ISSUE THREAD

**Issue by Buena-Vista** [tagspaces/tagspaces#905]
new bug in 3.0.9
if you drag the last tag in a group to another group, however, it works.  but otherwise, it's picking up the tag to the right of the selected tag and moving it.

also, the background color on the first tag in a tag group is being reset to black after some attempts to move tags in that group.

THANKS A HUNDRED MILLION FOR THE NEW COLLECT ALL TAGS FEATURE!!!!
Although might be better if it only collected tags for a selected folder rather than the entire location...

**Comment by uggrock** [comment]
The drag and drop issue could not be reproduced in 3.1.0. Please reopen if it does not work for you.
Regarding the tag collection, just create a temp. location to folder from which you want to collect the tags..

**Comment by Buena-Vista** [comment]
moving tags working correctly in 3.1.1, thanks.

creating a temp location to limit collection is an adequate workaround.  i should have thought of that!  ;-)

thanks!
