### ISSUE TITLE
add option to not open files at all on single click

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#906]
**Is your feature request related to a problem? Please describe.**
It bugs me that files are always opening on single click in 3.x. I know its a valuable feature for some people, but when you're trying to tag a whole bunch of files it gets annoying and TagSpaces slows down a lot if its video files you're tagging and its trying to open them [...]

**Describe the solution you'd like**
Add an option to not open file at all on single-click

**Describe alternatives you've considered**
Add new options for double-click to open

**Comment by uggrock** [comment]
implemented in 3.0.10
