### ISSUE TITLE
Move tag positions missing in 3.x

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#907]
**Describe the bug**
In 3.x it seems that the right click "move tag" options are gone. (left, right, first position, last position). This was really useful feature in previous versions. I used it all the time in combination with tag group colours. Makes visual checking of your tags much easier..

**To Reproduce**
Right click a tag on a file
You can only edit it or delete it.

**Expected behavior**
Right click a tag on a file
Options are available for moving the tag left, right, first position, last position

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1

**Comment by uggrock** [comment]
implemented in 3.11.2 -> closing
