### ISSUE TITLE
File preview can't be turned off

### ISSUE THREAD

**Issue by luckywwd** [tagspaces/tagspaces#909]
**Describe the bug**

File preview can't be turned off.  (Tagspaces -version 3.0.9]
When a file is single clicked, it is always open internally or externally.  
There is no way to stop file preview.

![image](https://user-images.githubusercontent.com/47409958/52392844-c3191380-2af7-11e9-99cf-5a036236b7ed.png)

**To Reproduce**
1. Go to ' a PDF shown in Tagspace window'
2. Click on 'Any PDF file'
3. The selected PDF always be opened for preview or opened by an external software

**Expected behavior**
There would be an option to stop file preview.

**Screenshots**

![image](https://user-images.githubusercontent.com/47409958/52392897-f9569300-2af7-11e9-97b1-4e829436df61.png)

**Desktop (please complete the following information):**
 - OS: [Winodws 10]

**Comment by uggrock** [comment]
fixed for 3.0.10

**Comment by roxfanuk** [comment]
thats good news

**Comment by Shwalamazula** [comment]
I am running 3.4.2 on Windows 10 and there is no way to select an item and not have it open a preview pane. It is really frustrating with a type of file that is not supported (like an .stl or .7z).

![image](https://user-images.githubusercontent.com/62410512/77130744-86745700-6a2f-11ea-8c1d-b2375fb8fa15.png)
