### ISSUE TITLE
Dark color scheme

### ISSUE THREAD

**Issue by blurmonk** [tagspaces/tagspaces#91]
The workspace is very nice but it might be too  bright for many uses (including myself). Are there any plans to provide additional skins?

**Comment by enricllagostera** [comment]
Hi, @uggrock, I might be interested in creating the dark version. Are there any pointers on where to start? I saw the .css files on the `data/assets` folder, but I just wanted to know if there are any tips or considerations for doing that without creating a whole alternative build.

**Comment by uggrock** [comment]
Hi, @enricllagostera, 

I will be glad if you can contribute implementing this cool feature. Yes data/assets is the right place to start. I think a good starting step will be the migration of the css files so sass or something similar, this will make creating of various themes very easy.

cheers,
Ilian
