### ISSUE TITLE
Remove tags doesn't work in the dialog for tagging operations on multiple files

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#910]
**Describe the bug**
If I want to remove a tag on multiple files, the tag may get removed on one file if you're lucky.
There is no dialogue regarding the successful or failed removal

**To Reproduce**
1. Search for files with a certain tag
2. in the results select all files
3. Click the tag button
4. type the tag name that you want to remove
5. Click "REMOVE TAGS"
Nothing happens

**Expected behavior**
After clicking "REMOVE TAGS", the tags should be removed and you should get a dialogue box regarding that, and/or any file rename failures

**Desktop (please complete the following information):**
 - OS:Linux Mint 19.1
 - TagSpaces  3.0.9

**Comment by SiriusStarr** [comment]
Can confirm, batch removing tags doesn't work on Linux (Fedora 30) or Windows 10 for me (v3.1.4).

**Comment by uggrock** [comment]
could not be reproduced in the last version -> closing
