### ISSUE TITLE
Search returns results outside the current location

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#912]
**Describe the bug**
I have browsed to a folder, and now i want to search within that folder.
The search returns everything matching the string or tag but from the root of the current location, rather than from the subfolder I am in.

**To Reproduce**
1. drill down a few levels deep in your folder structure
2. enter a search string or tag
3. results returned includes items not in the current folder path

**Expected behavior**
Results should not include anything outside your current path.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Version 3.09 (deb install)

**Comment by uggrock** [comment]
The search in TagSpaces v3 searches in the whole location by default. Since version 3.0.9 you can restrict the search to the current directory only by clicking on this button.
![image](https://user-images.githubusercontent.com/1249777/52538182-d8987280-2d6f-11e9-9a46-ed22a7f77207.png)

**Comment by roxfanuk** [comment]
In that case i would argue that the "Search in current location" wording in your screenshot is ambiguous.
Current location by most people's understanding is exactly that.
Please consider rewording:
The word "location" generally may be better termed "source"

1) Search this source
2) Search in current subfolder

This would make it very clear

**Comment by pixelbrackets** [comment]
This is irritating. I just wondered why the search result is exactly the same for »folder and subfolder« and »current location« in the first and second level, and differs in some deeply nested folder structure. I agree @roxfanuk - this should be worded differently and the suggested phrases are clear to me.

 @uggrock Could you please consider re-opening this issue and give a feedback to the suggested wording?
