### ISSUE TITLE
Incorrect markdown rendering for italics

### ISSUE THREAD

**Issue by crile** [tagspaces/tagspaces#913]
**Describe the bug**
`_` are not handle properly when there are surround by another character.

**To Reproduce**
1. Create a new document
2. Add the following text

        * _correct_
        * "_incorrect example_"
        * ,_incorrect example_,

**Expected behavior**
All sentences should be in italic, but only the first one works.

**Desktop (please complete the following information):**
 - OS: Windows
 - TagSpaces 3.0.9

**Comment by uggrock** [comment]
marked library updated to version 0.6.0 -> issue fixed for the next release
