### ISSUE TITLE
Adding A Tag via File Viewer > Properties > Tag looses focus after Adding Single Tag

### ISSUE THREAD

**Issue by sbenders-c3iot** [tagspaces/tagspaces#917]
**Describe the bug**
When adding a tags via the Preview Window > Properties, adding a tag leaves focus from the field/dropdown.

**To Reproduce**
1. Open File Previewer Properties
2. Click on Tag field
3. Enter New Tag or Select Existing Tag (use enter or tab to accept)
4. See focus has been lost after adding tag
5. Go back to step 2 to add another tag.

**Expected behavior**
1) After adding a tag (with enter or tab), the focus should remain in the tag field so I am able to add more tags quickly.
I expect the same behavior as in the Folder View > Tag Selected Entries modal.

2. If I click on an Existing Tag in the dropdown, the dropdown should remain open, allowing me to select multiple tags to apply.  If I click a selected tag a second time with the dropdown still open, it will be unselected and will not be applied. 
Tags should be applied on modal close or prev/next file being loaded.

**Desktop (please complete the following information):**
* OS: Mac OSX 10.13.6
* Browser: Chrome
* Version: TagSpaces: 3.0.9 / BuildID [4444f22] | Chrome: Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
Similar to https://github.com/tagspaces/tagspaces/issues/312 

I expect the same behavior as in the Folder View > Tag Selected Entries modal.

**Comment by uggrock** [comment]
Could not be reproduced anymore in version 5.1.x -> closing
