### ISSUE TITLE
Regression - Right-click "show files  with this tag" is missing

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#919]
**Describe the bug**
In previous versions you could right-click any file's tag, then select "show files with this tag". In 3.x you can only do this by right clicking the tag from the tag library. If your library is extensive, finding the tag first can take a while. IMO this is a major regression in terms of speed.

**To Reproduce**
1. Go to any tagged file
2. Right-Click on any of its tags
3. There is no "show files  with this tag" option anymore

**Expected behavior**
1. Go to any tagged file
2. Right-Click on any of its tags
3. Select "show files  with this tag"
4. Current list of files changes to show only files i the current path that include that tag

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - TagSpaces 3.0.9

**Comment by uggrock** [comment]
this feature is implemented in version 3.1.1
