### ISSUE TITLE
"Error while renaming file" when attempting to add a tag onto pdf

### ISSUE THREAD

**Issue by inxd** [tagspaces/tagspaces#920]
**Summary of error**
When adding tags to pdfs, error message comes up and tag is not added. This seems to happen randomly, sometimes when the pdf already has one tag on it. I have tagged about 200 pdfs without having this issue, but it now seems to be popping up with increasing frequency.

**To Reproduce**
1. Open a file folder with pdfs
2. Right click on one of the pdfs
3. Select 'Add/remove tags'
4. Type in a tag
5. Click 'Add tags'

**Expected behavior**
The tag should be added to the pdf.

**Screenshots**
![screen shot 2019-02-20 at 11 40 32 am](https://user-images.githubusercontent.com/47828068/53112418-c3a4a780-3504-11e9-9829-4793c17749e1.png)

**Desktop (please complete the following information):**
 - OS: [macOS Mojave]
 - Browser [chrome]
 - Version [10.14.3]

**Comment by uggrock** [comment]
Hey @inxd ,
do you still have the problem with the failed file renaming?
Another question how is the general stability meanwhile on macOS Mojave, which version of TagSpaces are using ?

cheers,
Ilian

**Comment by inxd** [comment]
Hi Ilian,

I did figure it out, thank you for making sure! The general stability is good; although it occasionally shows up with a “tagspaces closed unexpectedly” message, I’ve never had an issue with my tags not being saved. 

Thanks,
@inxd
