### ISSUE TITLE
TagSpaces Pro Desktop Windows 3.1.1 (64bit zip) not available on download portal

### ISSUE THREAD

**Issue by hansdev123** [tagspaces/tagspaces#921]
**Describe the bug**
The current TagSpaces Pro (portable/Zip) version 3.1.1 isn't available on the download portal. 
If you download the TagSpaces Pro version 3.1.1 from the portal https://transactions.sendowl.com you file find in the zip file only the normal tagSpaces version
![capto_capture 2019-02-26_10-41-32_pm](https://user-images.githubusercontent.com/15907791/53448445-b19c9a80-3a17-11e9-9244-e59926a1bbeb.png)

**Comment by uggrock** [comment]
thanks for pointing this out, I just uploaded the correct zip file!
