### ISSUE TITLE
Notification links can't be found

### ISSUE THREAD

**Issue by schroef** [tagspaces/tagspaces#924]
**Describe the bug**
When an new update is available in the bottom right corner a small notification menu is shown. Clicking one of these links results in an error showing "ITEMNAME* can't be found". (* shows item which is clicked)

**To Reproduce**
1. Click one of the items in the notification menu
2. Show error message (see attached image)

**Expected behavior**
It would need to show or open a link from its context. So release notes would go to a page showing all release notes for that version. Get now would go to the release page or download page.

**Screenshots**
<img width="1050" alt="screen shot 2019-03-02 at 11 58 23" src="https://user-images.githubusercontent.com/6923008/53684394-193a3a80-3ce3-11e9-8a85-03e709b4c813.png">

**Desktop (please complete the following information):**
 - OSX 10.11.6
 - Release 3.1.0

**Comment by uggrock** [comment]
Not reproducible anymore -> closing
