### ISSUE TITLE
Random crashes OSX v3.1.1

### ISSUE THREAD

**Issue by schroef** [tagspaces/tagspaces#925]
**Describe the bug**
Open TAGspaces 3.1.1 and do any actions in non-depending order. The app will random crash like this happened in 3.0.9 on OSX.

**To Reproduce**
1. Open TAGspaces 3.1.1
2. Do random interactions like view image and cycle through images (key also work funky btw)
3. App will crash randomly

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OSX 10.11.6
 - v3.1.1

**Additional context**
I had this same experience with v3.0.9 on OSX where it random crash when doing non-relating actions. Happened while app was open in the background or active. While i was selecting or cycling through images.

**Comment by uggrock** [comment]
issue is outdated -> closing
