### ISSUE TITLE
Unicode Search Support

### ISSUE THREAD

**Issue by grefel** [tagspaces/tagspaces#926]
On MacOS and Tagspaces Pro 3.11 the search for german umlauts does not work (ü,ä,ö)

**Comment by uggrock** [comment]
thanks for reporting this, I was able to reproduce the issue for plaint text search. But if the tag contains unlauts, then in works.

**Comment by grefel** [comment]
I don't have tags with umlauts :-) But unfortunately some filenames. Hope you can fix this. Thanks.

**Comment by uggrock** [comment]
this is working now -> closing
