### ISSUE TITLE
Compact and Default modes are the same if you use tags

### ISSUE THREAD

**Issue by Piscean** [tagspaces/tagspaces#927]
In the file list, if you have tags on all your files, the Compact mode is no smaller than the Default mode.

**To Reproduce**
1. Go to a directory where nothing has tags
2. Switch view to Default.
3. Now switch to Compact.  (Notice they are different.)
4. Now Tag one of the items in the list
5. Switch between Compact and Default.  The item with the tag stays the same height, regardless of Compact or Default mode.

**Expected behavior**
I expect the Compact mode to be smaller than the Default, whether items are tagged or not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 3.1.1

**Comment by uggrock** [comment]
this is improved in the latest versions -> closing
