### ISSUE TITLE
Search for specific filetype 

### ISSUE THREAD

**Issue by versus167** [tagspaces/tagspaces#929]
**Is your feature request related to a problem? Please describe.**
I want to search for csv-files with or without specific tags on it. But this is not possible in 3.11. :/ Or if I search for "all files without specific tag" then I get a ton of .ini-files -> Where is the option to exclude hidden files? 

**Describe the solution you'd like**
I would like to specify the filetype for search and to exclude hidden-files in search.

**Comment by uggrock** [comment]
how about searching for ".csv" without the " plus adding the tags you need? 
Excluding of hidden files under Windows is unfortunately currently not possible.

**Comment by versus167** [comment]
Ah, ok. Tank you! I tried it with 'filetypes', but without success... Now I kow how to search ;)
