### ISSUE TITLE
3.1.1 Painfully slow

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#930]
**Describe the bug**
Since updating from 3.0.9 to 3.1.1 TagSpaces has become so slow its almost unusable.
After clicking anything there's typically a 3-4 second delay before anything happens.

**To Reproduce**
1. I guess, install 3.0.9 
2. upgrade to 3.1.1
3. try to do stuff

**Expected behavior**
everything should be snappy

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Version 3.1.1 (.deb installer)

**Comment by uggrock** [comment]
Can you tell us how many files you have in the location you are experience the performance problem?

**Comment by roxfanuk** [comment]
I get similar performance no matter what location i am in.
I have one location which contains 585 files in root directory and a further 66 files in subfolders.
In other locations I have no files in root folder and the subfolder with the most files has 317 files

**Comment by roxfanuk** [comment]
One thing which seems to have a very negative performance hit is if i have any files downloading to the location at the same time as viewing that location. Like tagspaces maybe constantly trying to index and update to accomodate changes to the files. Can this be mitigated against somehow?

**Comment by EnvarionX** [comment]
I have the same problem. 3300 files in one directory, running Surface pro 7,  8gb RAM with i5 processor.

Tested the same on my desktop computer with AMD Ryzen 7 3800X and GTX 1080ti with similar results. this is for the current version v3.4.2

**Comment by uggrock** [comment]
@EnvarionX can you please try the new 3.5.0 version, we improved there the indexing functionality, which should have impact on handling locations with many files.

**Comment by uggrock** [comment]
This should be improved in our last beta release https://github.com/tagspaces/tagspaces/releases/tag/v3.5.1
