### ISSUE TITLE
Renderer Process Crashed

### ISSUE THREAD

**Issue by roxfanuk** [tagspaces/tagspaces#931]
**Describe the bug**
Renderer Process Crash after rename a file and waiting for the view to update

**To Reproduce**
this is the first time i had a crash.
add tags to a file
wait for view to update
crash

**Expected behavior**
no crashes

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Version 3.1.1

**Comment by uggrock** [comment]
Can you reproduce this issue every time you do this operations?

**Comment by roxfanuk** [comment]
No its happened once only so far

**Comment by uggrock** [comment]
ok, then I will close the issue, please reopen if it happen again.
