### ISSUE TITLE
Saving ts file separately from the current folder location

### ISSUE THREAD

**Issue by IlyaBrisbane** [tagspaces/tagspaces#934]
**Is your feature request related to a problem? Please describe.**
I'd like to have an opportunity to store the ts folder separately from the current folder I'm tagging files in. I use tagspaces for managing customized files folder for pretty complex software. I'm afraid that even if it's hidden someone can accidentally delete the ts folder... The customized files folder in my case must have the full access for all users accessing the settings from there. That's where the hidden folder in the current folder is not going to work...

**Describe the solution you'd like**
Have a chance to select the path for ts folder location 

**Describe alternatives you've considered**
 No alternatives in this case

**Additional context**
N/A

**Comment by uggrock** [comment]
This is a very big change of the app, which we probably are not going to implement in the near feature -> closing
