### ISSUE TITLE
OCR Support

### ISSUE THREAD

**Issue by AnalogJ** [tagspaces/tagspaces#936]
**Is your feature request related to a problem? Please describe.**
I want to use Tagspaces to store all my personal documents, and move towards a paperless home filing system. 

**Describe the solution you'd like**
When images & documents are uploaded to tagspaces, they should run though an OCR system like tesseract and the content should be searchable. 

**Describe alternatives you've considered**
Paperless and MayanEDMS.

**Comment by uggrock** [comment]
OCR support will not be provider any soon, except we get external help for the implementation.
