### ISSUE TITLE
extconfig.js - example file WebDAV

### ISSUE THREAD

**Issue by TomTomNavigator** [tagspaces/tagspaces#939]
Obviously you can use extconfig.js to set default settings in WebDAV hosted version. I am missing an example file where I can see the possibly settings I can set. Would be cool if an example extconfig.js could be added.

**Comment by uggrock** [comment]
The support for external config is a brand new feature of TagSpaces which is not finalized and officially announced yet. Currently you can use this sample json for the ext config.
window.ExtLocations = [
  {
    uuid: '10965f09-c7fd-1233-ac22-a75db415b5ba',
    type: '0',
    name: 'ExtLocationName',
    paths: ['/home/username/Downloads'],
    perspective: '',
    isDefault: true,
    isReadOnly: true,
    persistIndex: false,
    fullTextIndex: false,
    watchForChanges: false,
    creationDate: '2019-02-18T09:15:29.024Z'
  }
]
