### ISSUE TITLE
My TagSpaces Pro 3.1.1 screen looks like nothing shown on website and missing features

### ISSUE THREAD

**Issue by barnj** [tagspaces/tagspaces#942]
![tagspaces-pro-3-1-1-1](https://user-images.githubusercontent.com/49206080/55423258-85f75d80-554b-11e9-89fc-ae99893b5952.png)
I started with the free version, 2.9.  Then I upgraded to Pro version 3.1.1.  By and large, I like the new format but there are some things missing.  In 2.9, there was a link to the documentation. There is no such link now. I am trying to learn this system by working with the documentation.  One of the problems is that the screen is totally different, so some things aren't where the docs say they are and some things are missing.
Right now, I am working with the section Browsing Your Files.  It lists four perspectives, but there are only two on my screen, list view and grid view.  Missing are Image/Swiper Perspective, and Folder Viz 
Perspective.  A little later on, it mentions a Floating Action Button in the lower corner, which is nowhere to be found on my screen, nor do any of the existing context menus have the items listed in the docmentation example.

Finally, when I upgraded from 2.9 to 3.1.1, I lost all the tags I created in the tag panel.  The tags were there where I tagged the files, but I had to manually recreate them in the tag categories.  I mention this because if there is any software update I need as a result of the issues I've raised, I'm afraid I am going to lose all my tags again - which would be worse than last time, since I've created quite a few additional tags.

I'm sorry if my issue is annoying because I'm such a newbie, but I'm really trying to make use of this utility.

**Comment by uggrock** [comment]
issue outdated -> closing
