### ISSUE TITLE
Search by TagGroup

### ISSUE THREAD

**Issue by TheClownDE** [tagspaces/tagspaces#944]
**Is your feature request related to a problem? Please describe.**
I create TagGroups by Programming Language, e.g. I have a group Python with plenty of tags in it. If I want to find all Python projects I would have to select all Tags individual.

**Describe the solution you'd like**
Also search for the Tag Group, in above example Python.

**Additional context**
I'm using the Community edition.

**Comment by uggrock** [comment]
This is an interesting feature...

**Comment by uggrock** [comment]
implemented in 3.10 -> closing
