### ISSUE TITLE
Testing v3.1.4 performance issues

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#946]
For purposes of testing I fired up tagspaces-linux-x86_64-3.1.4.AppImage. 
I just deleted the old location with plenty of files and tags and created a new simple location with a few files: 2 directories, 3 subdirectories, and 22 files.
The result is discouraging, the perfomance is going down without hope and it is not suitable to use. I am still working with v3.0.5 for actual production.
I add a couple of animations to show the situation.
Also, in the second animation, a two instances of Tagspaces can be seen, this issue is happening from v3.0.9. The first instance is the actual Tagspaces window but the second one is a phantom window. This non visible windows shows up randomly after a few minutes using the program.
 - OS: Debian 9 64bits.

![Peek 2019-04-07 23-11](https://user-images.githubusercontent.com/22734449/55697488-98c8c280-598f-11e9-89c9-95904d9980fe.gif)
![Peek 2019-04-07 23-24](https://user-images.githubusercontent.com/22734449/55697494-9c5c4980-598f-11e9-9abb-08aa3208f67a.gif)

**Comment by uggrock** [comment]
related to #911

**Comment by uggrock** [comment]
The non visible window is used for the indexing the and for the thumbnail generation. It is basically a second process where these CPU intensive tasks are performed without affecting the main TagSpaces window.
Reasons for the performance issues could be for example:
- trying to open folder with big files, for which TagSpaces can try to create thumbnails
- opening folder located on a network drive
- opening of a locations containing many files

**Comment by uggrock** [comment]
closing as double to #911
