### ISSUE TITLE
Add a viewer for DjVu files

### ISSUE THREAD

**Issue by ChristianSchwarz** [tagspaces/tagspaces#949]
[DjVu](https://en.wikipedia.org/wiki/DjVu) is a document storage format much like PDF, mostly used for scanned documents. It would be cool if this file format would be supported.

Some open source DjVu viewer for JS exists, maybe they can be used:
 * [DjVuJs]( https://djvu.js.org/) -> [demo](https://github.com/RussCoder/djvujs) 
 * [djvu-html](https://github.com/mateusz-matela/djvu-html5) -> [demo](http://mateusz-matela.github.io/djvu-html5/demo.html)

**Comment by uggrock** [comment]
This a great idea for a TagSpaces extension. If somebody wants to take the lead for developing it I will be happy to support him, with the integration in the application.
