### ISSUE TITLE
Location-specific Tag Groups

### ISSUE THREAD

**Issue by SiriusStarr** [tagspaces/tagspaces#955]
A feature I'd love to see (possibly a new Pro feature?) is the ability to associate or otherwise limit Tag Groups by Location (or folder).  For my usecase, I have a good number of tags that are general and get used across all locations as well as a number of tags that are specific to certain locations and would never appear elsewhere.  As it is, it's very inconvenient if I have 10 locations to have to sort through/scroll past 9 extra tag groups I'm not going to use in that location.  Just a thought, but it would be a fantastic feature for me personally.

**Comment by rekypup** [comment]
yers this times 100% It is the only thing holding me back from using it at the moment. Ideally I would like it so that the tag system to show the tags available for a location and if it finds others that are not in your list or are not authorised whilst scanning it will put them at the bottom of the tag list maybe in Italic to show that they are unoffical tags

**Comment by SiriusStarr** [comment]
The latter part seems to sort of happen already (I think they're put in a
group called "Collected Tags?") but agreed would be good to have that
functionality tied in with the location-specific nature.


On Apr 24, 2019 at 03:58, <rekypup <notifications@github.com>> wrote:

yers this times 100% It is the only thing holding me back from using it at
the moment. Ideally I would like it so that the tag system to show the tags
available for a location and if it finds others that are not in your list
or are not authorised whilst scanning it will put them at the bottom of the
tag list maybe in Italic to show that they are unoffical tags

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tagspaces/tagspaces/issues/955#issuecomment-486175143>,
or mute the thread

**Comment by uggrock** [comment]
this is implemented in version 3.11.2 -> closing
