### ISSUE TITLE
Pro version downloads reseted to 10.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#956]
I just downloaded v3.1.4.
My downloads remaining for the DEB version should be 4, but 10 showed up.
Something is wrong with the company handling your interests.
Regards.
![10 downloads reseted](https://user-images.githubusercontent.com/22734449/56419445-42e5fb80-6268-11e9-9cf0-f29e85bf32fd.png)
![9 downloads remaining](https://user-images.githubusercontent.com/22734449/56419449-48dbdc80-6268-11e9-9a7c-955cfdb63579.png)

**Comment by uggrock** [comment]
Thanks for reporting this. We are resetting on a regular basis the download counter. The main motivation for having this limitation at all is to prevent leaking the PRO version, if someone accidentally publishes his download links online.
