### ISSUE TITLE
"Tagspaces Worker" window showing up

### ISSUE THREAD

**Issue by tderevko** [tagspaces/tagspaces#957]
**Describe the bug**
When I open Tagspaces Pro on Mac (Mojave), the first window is my default Location. However, when I click the main folder, a new window called "Tagspaces Worker" is opened fullscreen with the Tagspaces logo in the centre, instead of the main window with my folders. Sometimes I can go back using the Tagspaces symbol on the toolbar and choosing "Show Tagspaces", but there are moments when the TS toolbar is not there, and I have to restart the software. Even when I manage to go back to my folders, the "Tagspaces Worker" window will appear again, fullscreen, when I select a subfolder. Weirdly, that doesn't happen all the time. It seems to me that the "TS Worker" window was supposed to be in the background but for some reason, it is showing fullscreen.

**To Reproduce**
1. Start TagSpaces
2. On Location Manager, click on the main folder (saved)
3. See error (Tagspaces Worker window on fullscreen)

**Expected behavior**
Showing subfolders and documents. (Which happens sometimes, let's say 50% of the time)

**Screenshots**
https://imgur.com/h83QXey
https://imgur.com/3lqPNth

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4

**Comment by theovds** [comment]
If have a similar issue on Windows, although the 'Tagspaces Worker' is not full screen. It is a small square.

**Comment by uggrock** [comment]
the worker window does not show anymore -> closing
