### ISSUE TITLE
Perfomance Issues - v3.1.4  Pro - (Workaround)

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#958]
This post is to report that I found a workaround to bring Tagspaces to work properly while browsing and tagging without any appreciable delay.
Just because of a random Eureka moment, I discovered that if I delete the "Collected Tags" group which contains now around 1400 tags, Tagspaces will behave as expected.
I reproduced this behavior many times by deleting such group and testing Tagspaces in a very pleasant and productive way; and then recreating it with the command "Collect Tags From Current Location" to get Tagspaces to crawl and to be impossible to work with.
The drawback of deleting this group is that while imputing tags, be to tag a file or to search, the list showing the all the existent tags will not be functional.

**Comment by uggrock** [comment]
having over 1000 tags seems like an edge-case, the performance should be meanwhile better though -> closing
