### ISSUE TITLE
Use native Windows tagging

### ISSUE THREAD

**Issue by NicholasJohn16** [tagspaces/tagspaces#96]
Windows has a native tagging ability.  Could support be added to use it instead of changing the file name?

**Comment by joepie91** [comment]
@canpolat Hmm, extended attributes are not implemented identically across operating systems, are tey?

**Comment by canpolat** [comment]
@joepie91 I have no idea :) I saw it in the suggestion thread and it sounded like a good idea to me since it makes keeping the tags attached to a the file. But if it's not practical to implement, well, then it's not practical to implement.

**Comment by dandv** [comment]
[Renaming files](https://github.com/tagspaces/tagspaces/issues/96#issuecomment-49704584 has a certain ick factor for me too. On the other hand, it's compatible with manually renaming files according to the tag scheme, and I found myself doing that before I knew about TagSpace. For example, when I [download a video from YouTube](https://github.com/rg3/youtube-dl/), I add `[YouTube <id>]` to the name.

**Comment by uggrock** [comment]
In future releases tagspaces will support saving meta data in sidecar files

**Comment by HiHitHito** [comment]
Looking forward for it. :)

joepie91 commented on 26 Dec 2014
...("store in local database" and "store in per-file metadata manifests")...


Maybe it can be combined.

All tags are stored in the database, you can export the tag to separate tag file.
When you add a new separate tag file from another computer, you just import the separate tag file into the database.
Mmm. maybe the name is...
rebuild the database based on separate tag files?

I do not know, whether the database has its advantages or not.
(maybe faster processing?)

So the market can choose.
There may be an option.
All tags are stored in the database
All tags are stored in the database + update to separate tag file (with checking before, ideally)

**Comment by fxshpac** [comment]
if sidecar format has been decided i suggest using xmp sidecar since it's a standard format being used widely.
