### ISSUE TITLE
Enhancement - Nested hierarchical tags

### ISSUE THREAD

**Issue by rekypup** [tagspaces/tagspaces#967]
It would be extremely useful to have the option to have nested hierarchical tags

Potentially, you could use pipedeliminators as a reserve character and use it to store the tags correctly in the sidecars.

To do this, you would have to warn the end user that nested heierachical structure only work with side cars and not file names.

**Comment by rekypup** [comment]
I have had a chance to look at how the software works with different tag groups with the same tag name in it. Now that I understand that the tag is what is being recorded in the json file and not the group I don't think that it would be wise to write out the full hierachy to the file  since it would force issues with existing user base and since the concept of the tag should be such that it is generic keywords and combinations of these keywords returns your results (i.e. search engine)

If you could make it so that the end user is able to embed a group within another group in the file manager then that would be a fantastic enhancement as it would allow the end users to easily work with their tags is a very structure manner .


-------------------------------------Thought Experiment---------------------------

Going back to the concept of exporting the entire hierachy structure; at this moment in time, I can't think of why you would want to so I have made this scenario to force a situation. Suppose I have a two tag groups:
Effort In Month - 1,2,3,4,5,6,7,8,9,10
Effort In Days - 1,2,3,4,5,6,7,8,9,10 
This would not work as searchng for 2 would return files marked with 2 Months or 2 Days as such with the current setup you would be forced to have one group called Effort with tags called M1,D1,M2,D2

In this scenario I would imagine the ability to select the two groups in question and mark them both to export out and search upon the entire hierachy. when you then tag a file, it would write out "Effort In Month - 2" to the json file

That was more of a thought experiment more than anything and again it is a strange scenario why I would using a tagging system to record ratings.

**Comment by uggrock** [comment]
enhancement request -> closing
