### ISSUE TITLE
Enhancement - Locking and Setting a Location to password protected

### ISSUE THREAD

**Issue by rekypup** [tagspaces/tagspaces#968]
It would be helpful to allow us to hold a cheap password for particular locations alongside two descriptions, one which is the password protected description and one which is the standard description

So in the location Manager I would like to see a indication for each location whether it is a password protected one and if so it will display the password description e.g. "your first pet"

Upon clicking it, I would enter the password and it will then unlock the location and change the description to the correct name.

It is not important that the password is encrypted (it can be stored as free text in the config files for all I care) mearly so that if you are going over tagspace with a colleague there is a small barrier that prevents them from clicking in a location.

**Comment by uggrock** [comment]
enhancement request -> closing
