### ISSUE TITLE
Drag single tag

### ISSUE THREAD

**Issue by johnnybaida** [tagspaces/tagspaces#969]
**Describe the bug**
When I drag a tag, an incorrect image is shown

**Screenshots**
<img width="786" alt="Schermata 2019-04-24 alle 21 46 33" src="https://user-images.githubusercontent.com/13869348/56689817-48b26580-66dc-11e9-8aa4-63d7fcc7beba.png">

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version 3.1.1

**Comment by uggrock** [comment]
this is fixed -> closing
