### ISSUE TITLE
Tag calendar icon

### ISSUE THREAD

**Issue by johnnybaida** [tagspaces/tagspaces#970]
**Describe the bug**
The calendar icon is shown incorrectly in the tags

**Screenshots**
<img width="351" alt="Schermata 2019-04-24 alle 21 45 04" src="https://user-images.githubusercontent.com/13869348/56689961-94650f00-66dc-11e9-9d2f-b5f4fc332a71.png">

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version 3.1.1

**Comment by uggrock** [comment]
Space are actually not allowed in the names of the tags. The real bug here is probably, how it was possible to create such tag.

**Comment by johnnybaida** [comment]
This is an old TAG. I think the space character should be restored.
I use numeric TAGs to indicate codes, the calendar icon creates confusion.
Thank you.

**Comment by uggrock** [comment]
fixed in 3.2.0
