### ISSUE TITLE
Showing context menu on multiple file selection under Mac OS 

### ISSUE THREAD

**Issue by alomaritrq** [tagspaces/tagspaces#973]
**Describe the bug**
I am still testing TagSpaces to make sure its what I need. Using a Mac, when selecting more than one file I need to use the Ctrl key, but each consecutive selection requires releasing the Control and clicking on the file to close the pop-up menu before I can go to the next file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows 10, Linux, Ubuntu]
 - Browser - only needed if you use the web version [e.g. firefox, chrome]
 - Version [e.g. 3.1.1]

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy 8]
 - OS: [e.g. Android 7.0.1]
 - Version [e.g. 3.1.1]

**Additional context**

**Comment by uggrock** [comment]
Thanks for reporting, I was able to reproduce this issue.

**Comment by uggrock** [comment]
fixed for the next reseale, duplicates the #980
