### ISSUE TITLE
Right Click then Add Tag does not generate ID in json

### ISSUE THREAD

**Issue by Gary00** [tagspaces/tagspaces#975]
**Describe the bug**
When right clicking on a file and selecting "Add / Remove Tags" the JSON generated for a sidecar gives the "id" as the name of the tag rather then a unique ID that is generated from creating the tag in the Tag Library

**To Reproduce**
1. Right Click on file and click "Add / Remove Tags" 
2. Create a new tag
3. Inspect the JSON sidecar file and look for "id" 
4. See that it's the same as the title which is unlike creating it from the Tag Library

**Expected behavior**
I would have expected the ID to be generated like it was when adding it from the Tag Library

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.4
![example](https://user-images.githubusercontent.com/3980690/57360548-c175ef00-71bd-11e9-8c46-5f1bf8ac326c.JPG)

**Comment by uggrock** [comment]
fixed for the next release. Why do you need the id there? Is there any specific reason, use case? We are eventually considering removing them fror the tag's data structure.
