### ISSUE TITLE
TagSpaces not automatically collecting new Tags

### ISSUE THREAD

**Issue by Gary00** [tagspaces/tagspaces#976]
**Describe the bug**
According to the documentation TagSpaces should be collecting tags automatically if the folder has a "tsm.json" file (created from exporting the tag library) in the ".ts" directory. This doesn't appear to be happening. 

**Screenshot**
![Example_TagSpaces](https://user-images.githubusercontent.com/3980690/57432296-cea3e400-7278-11e9-9143-817a789dcff7.JPG)

**To Reproduce**
1. Export the tag library to a location on PC
2. Rename the file to "tsm.json"
3. Move to ".ts" folder 
4. Navigate to that folder (and allow index) in TagSpaces which does not automatically update the tag library.

**Expected behavior**
Tag Library should update with the found tags from the "tsm" file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.4

**Comment by uggrock** [comment]
in version 3.11.2 we offer location specific tags -> closing
