### ISSUE TITLE
Ability to drag tag groups to reorder

### ISSUE THREAD

**Issue by Gary00** [tagspaces/tagspaces#977]
**Is your feature request related to a problem? Please describe.**
Reordering tag groups is slow when working with lots of groups having to select "Move Tag Group Up" or "Move Tag Group Down" on each individual group.

**Describe the solution you'd like**
Having the ability to drag the tag groups to the desired location. 

**Describe alternatives you've considered**
A possible alternative if the drag/drop method is hard to implement would be to sort the groups (A to Z for example)

**Comment by uggrock** [comment]
enhancement request -> closing
