### ISSUE TITLE
Feature suggestion: History

### ISSUE THREAD

**Issue by UhWatchMe** [tagspaces/tagspaces#978]
Hi,

A feature to see history of the following things;

- Label changes
- Folder added/removed
- File added/removed

The layout of history would be with a "daily" view of changes.

As example (maybe with windows username)

15-05-2019
Label test removed from filename - Windows username
Folder name created in parent folder - Windows username

14-05-2019
File name added to folder name
Label ToDo added to filename

Also the ability to "filter", at date, label, action (added, removed for label/folder/filename etc)

**Comment by uggrock** [comment]
History of recently used files and folders was added to version 5.0 -> closing
