### ISSUE TITLE
Enhancement - Smart Tag - Cascade tags

### ISSUE THREAD

**Issue by rekypup** [tagspaces/tagspaces#979]
I have alot of work files and I would like the ability to cascade a tag for all files in a folder and subfolder. IT would be moost useful to have a checkbox with the default set to off that when checked, it would cascade all tags down to the levels below.

**Comment by uggrock** [comment]
This is possible with the search functionality. Just open the search panel and select from the file type dropdown: "Files". This should show all files in your location. Then you can select them all and apply any tag.
