### ISSUE TITLE
Bug - Select multiple files in any order shows submenu & uses wrong key modifier on OSX

### ISSUE THREAD

**Issue by david-nguyen** [tagspaces/tagspaces#980]
**Describe the bug**
Selecting multiple files on OSX requires the control modifier key to be held down, however, there are two issues. 

- a submenu appears preventing you from selecting more files
- the modifier key should be command to mimic the default finder

**To Reproduce**
1. View files
2. Select a file
3. Hold control and select another file

**Expected behavior**
The command key should be used as the modifier to select images in any order. No submenu should appear when selecting images with the modifier key held.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.4
 - Version 3.1.4

**Comment by uggrock** [comment]
fixed for the next release
