### ISSUE TITLE
upgrade to 3 from 2.9.0 - collected tags preservation?

### ISSUE THREAD

**Issue by james-cook** [tagspaces/tagspaces#983]
**Describe the bug**
I'm experimenting with tagspaces (web) and just upgraded to 3.x.x from 2.9.0 ish. Everything looks fine except that existing tags in file names no longer appear as "collected tags" in the tag view on the left. My old 2.9.0 install is now behaving like a fresh install for some reason (context lost- cookies?) so I can't export the tag library from there. So, is there any way to get tagspaces3 to regenerate the "collected tags" from the tags existing in the filenames? A script or a scan or...

**To Reproduce**
1. work with 2.9.x - "collected tags" show all the tags "You" added
2. upgrade to 3.x.x
3. "collected tags" doesn't show/is empty
4. adding new tags does add to "collected tags" - but existing tags do not appear

Apache 2.4.18
Nextcloud 15 latest stable, webdav 

Hopefully I'm just missing something obvious...

**Comment by uggrock** [comment]
webdav version is not supported anymore -> closing

**Comment by santa-klaus** [comment]
@uggrock Sorry, I don't get what this has to do with WebDAV? I wasn't using WebDAV when I experienced the bug.
