### ISSUE TITLE
ODT preview not working

### ISSUE THREAD

**Issue by lucasrodwell** [tagspaces/tagspaces#984]
ODT files are not previewed properly, they are shown as text files :

![Capture du 2019-06-12 16-04-13](https://user-images.githubusercontent.com/51288944/59354762-67bd9300-8d2e-11e9-98b3-cfe7da23b4eb.png)

**Desktop (please complete the following information):**
- Linux Mint 19 updated 12/06/19
 - Version 3.1.4

**Comment by GitFr33** [comment]
I'm having the same issue with LibreOffice .odt and .ods files. 
Ubuntu 16.04, TagSpace v3.1.4

**Comment by uggrock** [comment]
ODF formats like ODT or ODS are officially not supported https://www.tagspaces.org/supported-file-formats/ , so I am closing this issue.
