### ISSUE TITLE
Default folder when saving files

### ISSUE THREAD

**Issue by fabiobianchiwebdev** [tagspaces/tagspaces#985]
I'm always frustrated when saving an article as .html (or any other for that matter), that I have to look for the default tagspace folder.

I think this is more of an issue problem than a feature request.
The webclipper should open my File manager on the default folder assigned on TagSpace. 

I'm not sure if I can set up that behavior within my system. I'm using GNU/Linux Xubuntu 18.04.
If you know a way to do that by the system itself, please help me.

Thanks a lot!
I love the software and I'm saving money to buy the pro version, I'm from Brazil and the dollar is pretty expensive, so I have to save money from my adsense profits from my blog. ;)

**Comment by uggrock** [comment]
Unfortunately this is currently not possible, due to API restrictions in the Chrome and Firefox browsers.
