### ISSUE TITLE
Install fails for mackbook running High Sierra 10.13.6

### ISSUE THREAD

**Issue by HankBrown** [tagspaces/tagspaces#988]
**Describe the bug**

Downloaded ZIP SIZE 65,423,450 bytes to macbook macOS 10.13.6

Unzips without errors. Copy to Application folder.  Click Ctl+Open, click OK.

"TagSpaces cannot be opened because of a problem""
Check with the developer to make sure TagSpaces works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

**Desktop (please complete the following information):**
macOS 10.13.6

**Comment by uggrock** [comment]
This should be fixed in the version 3.1.6, which we have released today.

**Comment by HankBrown** [comment]
v3.1.6 downloaded 65,467,434  same issue.
BUT... I noticed I was double-clicking to open (using RAR Extractor Lite).
Arg. **Opens fine** with Archive Utility 10.10

So I think this may have been my problem. I post this follow up in case others need a reminder.
Sorry for the hassle. Thank you for your time.
