### ISSUE TITLE
Tagspaces v3.1.4 Pro shows duplicated tags.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#989]
**Describe the bug**
After searching for files, the results show all the tags with uppercase letters in lowercase.
This would be of no consequence if this display were just the representation of "unique" tags, which is not the case.
As shown in the following video, when I delete a fake lowercase tag, the real uppercase tag shows up forcing me to repeat the procedure twice to make sure such tag is gone.
![Peek 2019-07-05 01-41](https://user-images.githubusercontent.com/22734449/60700880-7a5b6000-9ec7-11e9-9a84-62009c8f1217.gif)

-----------------------------------------------------

- OS: KDE Neon (Ubuntu 18.04)
- Tagspaces 3.1.4 Pro

**Comment by gitdocke** [comment]
A follow up.
As shown in the below video, when dragging tags Tagspaces is creating, and not just showing, a new lowercase tag into the same file. Therefore it is not honoring the original tag.

![Peek 2019-09-05 02-30](https://user-images.githubusercontent.com/22734449/64317787-a1491780-cf86-11e9-8d80-cde22669dd9d.gif)

In the next video is the same case, but when dragging tags to other files.

![Peek 2019-09-05 02-33](https://user-images.githubusercontent.com/22734449/64317853-c76eb780-cf86-11e9-9be5-d2cf4480865c.gif)

------------
Tagspaces Pro v3.2.1
KDE Neon 5.16 (Ubuntu 18.04 LTS)

**Comment by uggrock** [comment]
Not reproducible in version 5.x -> closing
