### ISSUE TITLE
Scrollbar won't allow to reach the end of the directory

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#990]
When using the scrollbar, it won't allow to see the files located at the button.
Only owning a mouse with a wheel can overcome this inconvenience.
I have noticed this behavior at least from v3.0.1, but perhaps the problem might be tracked to earlier versions.

-----------------------

KDE Neon (Ubuntu 18.04)
Tagspaces V3.1.4 Pro
![Peek 2019-07-05 02-01](https://user-images.githubusercontent.com/22734449/60701480-e6d75e80-9ec9-11e9-930a-f70727aa49f6.gif)

**Comment by gitdocke** [comment]
I discovered how to make to work the keyboard's UP and Down keys to scroll the directory.
By default these keys won't work even if a file is selected to try to force focus. But if a tag is clicked and dragged a little bit, the directory will gain focus and those key will work as intended.
This behavior is still present in v3.1.6 Pro.

![Peek 2019-08-11 03-37](https://user-images.githubusercontent.com/22734449/62831238-dfeaec80-bbe9-11e9-81e1-0545a1212a85.gif)

**Comment by uggrock** [comment]
fixed in 3.2.5 -> closing
