### ISSUE TITLE
The quantity of entries is hidden.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#991]
At the top of the interface there is a field displaying how many entries are present. However in versions 3.x.x this field is hidden and only reveals itself when the pointer hovers over it.

---------------------------

KDE Neon (Ubuntu 18.04)
Tagspaces 3.1.4 Pro

![Peek 2019-07-05 02-30](https://user-images.githubusercontent.com/22734449/60702843-04a6c280-9ece-11e9-9a26-9150dce72122.gif)

**Comment by uggrock** [comment]
implemented for the next release
