### ISSUE TITLE
Numbers and the calendar icon  - Request for improvement -

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#992]
Any number with 4 or 6 digits will be recognized as a date.
There are cases when a number represent legit tags, for example the book "1984", or a part number.
Also the icon is fine as eye candy, but is an inconvenience for a quick look at the tags content.
I request such icon to be deprecated or to change Tagspaces' code to represent a literal "date" tag.

----------------------------------

KDE Neon (Ubuntu 18.04)
Tagspaces v
![Peek 2019-07-05 02-49](https://user-images.githubusercontent.com/22734449/60704149-9b28b300-9ed1-11e9-9242-8d07c59f1db6.gif)
3.1.4 Pro

**Comment by uggrock** [comment]
fixed in 3.2.5 -> closing
