### ISSUE TITLE
Date tags reset to their original value when dragged.

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#993]
As shown in the following video, when date tags are dragged to tag another file, the new applied tag will reset to its original value, not honoring the edited one.
This behavior is not new and it can be found also in older Tagspaces' versions.
Also notice how in the "Collected Tags" group multiple instances of date tags with same values are present; perhaps Tagspaces reads their original value instead of the edited ones.

![Peek 2019-07-07 23-03](https://user-images.githubusercontent.com/22734449/60780742-abc56d00-a10d-11e9-8027-1c1430051a0f.gif)

---------------------------

KDE Neon (Ubuntu 18.04)
Tagspaces v3.1.6 (appimage version)

**Comment by uggrock** [comment]
fixed for the next release -> closing
