### ISSUE TITLE
intent / untent in HTML notes under MacOS

### ISSUE THREAD

**Issue by AH72** [tagspaces/tagspaces#994]
Hi, i am a user of the latest pro version under latest MacOS version. 
I trying to solve three "issues" i have with the build in html editor/viewer. 

1) tab/untab or indent/outdent
I am missing a feature or simply could not find how to solve it regarding indent/outdent under the internal HTML editor. I am writing a lot of HTML notes with the internal html editor, using heavily the feature to structure paragraphs with indent and outdent.

Normally i am using shortcuts to indent / outdent like cmd+tab or cmd+shift+tab. Unfortuneately, this seams not to work on MacOS as this shortcuts are "overrided" by an "system" default shortcut to switch between applications. So i have to use the icon menu bar inside the html editor window to do indent/outdent which is enoying slow from workflow perspective. 

I found so far no way to resolve this under MacOS. It would be a great relief for me if there is a way to tell tagspace to 

a. override this system default shortcut and using instead the typical shortcuts for indent / outdent as long as using the html editor of tagspaces. 
b. second best solution would be a general override over the system shortcuts from MacOs if tagspaces is the active windows and 
c. third idea would be to define other shortcuts for indent/outdent inside the internal html editor (could not find them in the list of shortcuts from tagspace so that i would be abe to modify it).

2) default style format for HTML notes
 Is there a way to change the default html layout like with a css (defining the size and layout of Header 1 ,2 3, etc.) for the internal html editor?

3) How can i change the background color of a html table cell inside the html editor (not the background color of text)?

I would appreciate to get there a solution as i realy like to use tagspaces.

kind regards and many thanks  in advance

André

**Comment by uggrock** [comment]
Could not be reproduced in the last version -> closing
