### ISSUE TITLE
Video Thumbnail Is Captured Too Early

### ISSUE THREAD

**Issue by lots0logs** [tagspaces/tagspaces#996]
**Describe the bug**
AFAICT video thumbnails are currently generated using the frame at 2s. That is not sufficient in all situations. I have many videos where 2s is still too early.

**To Reproduce**
N/A

**Expected behavior**
Video thumbnails would always exclude the intro labels and credits that appear before the actual content.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 3.1.6 Pro

**Comment by gitdocke** [comment]
I have a similar problem but with a video extremely shot, around 1 second, which Tagspaces was unable to create the thumbnail. After some basic research I found "the method" to get the thumbnail I want.

Workaround:
1 - Play the video and take a screenshot of the wanted frame.
2 - Resize such screenshot to no more than 400x400 px. For example: 300x400; 400x250; et cetera.
3 - Rename the resized screenshot exactly as the video and add the ".jpg" extension. For example: if the video is called "Sunny day.webm", the screenshot must be renamed to "Sunny day.webm.jpg".
4 - Paste the screenshot into the .ts folder, located in the same directory than the video. If necessary overwrite the existing and not wanted thumbnail.
5 - Fire up Tagspaces and voila!, the desired thumbnail will show up, permanently.

**Comment by aanatoly** [comment]
Can we use relative position, eg `ffmpegthumbnailer -t 15%` ?

The more cooler thing would be 
-  start playback, got to the "right" frame
- pause a movie
- launch "make this frame a thumbnail" action via a button or menu

`tagspaces` would take current movie position from the player and make a thumbnail from that position

**Comment by uggrock** [comment]
In the current PRO version you can set a custom thumbnail to every file or folder, so I am closing this issue.

**Comment by lots0logs** [comment]
@uggrock Really this issue is only halfway solved. The complete solution is as you mentioned where it would be possible to select a thumbnail directly in the app. No one has time to manually create thumbnails IMO. :thinking:

**Comment by gitdocke** [comment]
@lots0logs 
Allow me to give my 2 cents.
The difference between what you wanted and what everybody is getting is a few more clicks to select the desired thumb.
Granted, it is not the luxury solution, but it gets the job done.
And I am taking into account that there are plenty of priority bugs to iron before to divert time to a non pressing matter.

**Comment by lots0logs** [comment]
Perhaps for you and some others it gets the job done but for me it most certainly does not. The point I was trying to make is that I don't feel this issue is completely resolved and so the issue shouldn't be closed because that guarantees no further work will be done on it.

**Comment by lots0logs** [comment]
@uggrock *bump*

**Comment by gitdocke** [comment]
@lots0logs
My issue in this matter is you are going to piss off the developer.
Your lack of self awareness and whiny behavior is a threat to every user of this project.
Do you realize this circus is ran by a single man? 
Do you realize this man owes nothing to nobody? 
Do you realize that this man can drop the project anytime for any reason? 
Do you realize that the "purchase" is about a license and not a commitment to do what the users want?
If so, then please tone it down a couple of notches.
Still wanna make a fuzz? Then open a request for improvement and pray for to get attention.

**Comment by uggrock** [comment]
@lots0logs 
The code for video thumbnail generation is not closed see: https://github.com/tagspaces/tagspaces/blob/develop/app/services/thumbsgenerator.js#L316

Feel free to contribute and make this feature configurable.

**Comment by lots0logs** [comment]
@gitdocke Really? Who do you think you are talking to? I myself am a developer and have had my own popular projects. The only person in this thread causing any problems is you. I'd appreciate it if you just mind your own business and keep your opinions to yourself.

**Comment by uggrock** [comment]
Guys, please calm down....

**Comment by lots0logs** [comment]
I'm calm. Nothing I have posted in this thread is even remotely close to being a problem. I've been on GitHub contributing to open source for a long time. Not once have I ever had a problem with anyone. 

Furthermore I have to make clear that I find the meme posted  by @gitdocke extremely offensive. Anyone who understands Autism would understand why it's offensive. It should be deleted immediately.

**Comment by gitdocke** [comment]
The meme stays.

**Comment by gitdocke** [comment]
@lots0logs
Congratulations you did censor my speech.
The SJW brigade have just brought the outrage infection here.
Grow up kid, your feelings are irrelevant to the code.
Anyways, the pendulum is coming back, and hard, to the common sense, all that victimhood learned at the university has no future.
Gloat free meanwhile.
